### ISSUE TITLE
Aren't Fonts loaded or are they locally installed

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#100]
<img width="1387" alt="screen shot 2017-12-19 at 20 39 27" src="https://user-images.githubusercontent.com/914443/34175446-bcf1b8c8-e4fc-11e7-969c-5a37f2374ce4.png">

**Comment by AndyOGo** [comment]
Just released on AEM and tested again inside of Citrix VDI. Fonts got loaded over there.
So I guess I just have them locally available, hence Chrome doesn't download anything.

**Comment by LucaMele** [comment]
works 🚀 
<img width="1360" alt="bildschirmfoto 2017-12-21 um 11 22 21" src="https://user-images.githubusercontent.com/275235/34251727-4998cf2e-e641-11e7-9368-f5ca2b6f069f.png">
