### ISSUE TITLE
Button icon not framed inside square

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1005]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

When creating an AXAButton (`<AXAButton variant="secondary" motion icon="phone">Anrufen</AXAButton>`), I expect to see the icon framed inside a square outline.

![button-icon-v1](https://user-images.githubusercontent.com/1171773/57686118-4edf9600-7639-11e9-9000-d0b83357e44d.png)

## Actual Behavior

In the latest version, the icon simply follows the button text, and is not framed inside a square.

![button-icon-v2](https://user-images.githubusercontent.com/1171773/57686119-4edf9600-7639-11e9-9793-fd96b75453a7.png)

## Steps to Reproduce the Problem

Please see above.

## Specifications

 - Browser: Chrome
 - Browser Version: Version 74.0.3729.131 (Official Build) (64-bit)
 - Node Version: v10.15.1
 - NPM Version: 6.4.1
 - Platform: Windows

**Comment by MKaHead** [comment]
<img width="701" alt="Bildschirmfoto 2019-05-14 um 11 31 55" src="https://user-images.githubusercontent.com/11683864/57687779-5bb1b900-763c-11e9-99a8-cad6edbef916.png">

Hello @cge,
- The current buttons in the pattern lib are up-to-date and signed of with designers @kenaxa and @jojackpot 
- Indeed,  you may have received designs which are out of date and the update has not been communicated yet. We are working close with designers and we discussed it. You can refer to the current/newer versions of the current plib. Feel free to ask designers directly (@kenaxa, @jojackpot )

**Comment by cge** [comment]
Perfect @MKaHead , thanks a lot. Good to know the change is intentional and happy to go with the new philosophy.
