### ISSUE TITLE
Checkbox component missing

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1006]
A new checkbox component seems to be missing and a likely branch stale: https://github.com/axa-ch/patterns-library/tree/develop-v2-axa-checkbox

It would be great to know the ETA for the new checkbox component.

**Comment by LucaMele** [comment]
As said in the mail of Manuel, and agreed on ARP, checkbox will be ready today

**Comment by cge** [comment]
Thanks @LucaMele , understood. Simply opened the ticket to track progress, but if delivered today I guess it is not necessary.
