### ISSUE TITLE
update polyfill to support core-js 3.x

### ISSUE THREAD

**Issue by ahoehn** [axa-ch/patterns-library#1011]
core-js@2 entered feature freeze 1.5 years ago; all new features were added only to the core-js@3 branch.
https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

but the https://github.com/axa-ch/patterns-library/blob/develop/src/components/05-utils/polyfill/package.json still refrences "core-js": "^2.6.5"

**Comment by ahoehn** [comment]
package.json
"dependencies": {
    "@webcomponents/webcomponentsjs": "^2.2.7",
    "core-js": "^3.0.1",
    "regenerator-runtime": "^0.13.2",
  }

index.js
import 'core-js/stable/reflect';
import 'core-js/stable/promise';
import 'core-js/stable/array/includes';
import 'core-js/stable/array/from';
import 'core-js/stable/object/assign';
import './index.webcomponents';

**Comment by LucaMele** [comment]
We should fix this asap, thanks adrian

**Comment by MKaHead** [comment]
We are running after upgrade to corejs 3 into dev enviroment problems. (https://github.com/storybooks/storybook/issues/6204 )
For the moment we wait that Storybook fix this problem, if it takes to long we program a workaround in.

**Comment by MKaHead** [comment]
If we update - Midgard, pods and so on crashing.

**Comment by LucaMele** [comment]
Not doable now as too many project depends on v2
