### ISSUE TITLE
Define Test Strategy

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#102]
Lets have a discussion on what can our test strategy be

**Comment by LucaMele** [comment]
Anyone, please add some suggestions

**Comment by AndyOGo** [comment]
I would test in various phases:

1. Linting
2. Unit Tests of global helpers
3. Behaviour Tests of components themself

**Comment by AndyOGo** [comment]
Let's consider Jest as it is:
>Although Jest may be considered a React-specific test runner, in fact it is a universal testing platform, with the ability to adapt to any JavaScript library or framework.
https://jestjs.io/docs/en/testing-frameworks

**Comment by AndyOGo** [comment]
Actually there are other options for testing web components:
- Polymer's Web-Components-Tester: https://github.com/Polymer/tools/tree/master/packages/web-component-tester
- Skate's bore: https://github.com/skatejs/bore

**Comment by AndyOGo** [comment]
## What we want?

- [ ] Unit Tests of:
   - helper functions
   - may only need to be executed browser-less directly within Node
- [ ] Component Tests
   - should test each component separately
   - snapshot testing - shallow render VS full render (excluding/including Webcompoent-child's DOM)
   - behaviour tests
   - visual layout tests
   - best to execute them within multiple browsers
- [ ] Integration tests of the Patterns-Library
   - used natively within other projects
   - used by React, Angular, etc.
- [ ] CI/CD assurance
   - tests should run for Pull-Requests and block merging if they fail

**Comment by AndyOGo** [comment]
Snapshot testing with karma :)
https://github.com/localvoid/karma-snapshot

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
