### ISSUE TITLE
Header: split it down further

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#103]
It turns out it should be beneficial to split the header molecules down into more granular parts.
Especially by abstracting those away to allow for custom arrangement, inclusion or exclusion...
Maybe rethink #80 to use shorter names.

- [x] **Header Meta Navigation** -> `m-header-meta`
   - Navigation -> `m-header-others`
   - Right container (only for arrangement) -> `m-header-meta-right`
   - Languages/Countries -> `m-header-languages`, `m-header-countries`
   - Actions, Buttons, etc ->  -> `m-header-action`, `m-header-button`
- [x] **Header Main Navigation** -> `m-header-main`
   - Logo -> `m-header-logo`
   - Navigation -> `m-header-navigation`
   - Search Form -> `m-header-search`
   - Actions -> `m-header-button`
   - Mobile Burger button -> `m-header-burger`
- [x] **Header Main Navigation Mobile**
   - Analogous to above
      ```html
      <axa-header-mobile>
        <axa-button />
        <axa-header-mobile-navigation />
        <axa-header-mobile-others />
        <axa-header-mobile-languages />
      </axa-header-mobile>
      ```
   - `m-header-others` could be reused and/or extended by `--mobile` modifier
   - `m-header-languages` seems different...

**Comment by LucaMele** [comment]
agree with everything
