### ISSUE TITLE
When running npx lerna bootstrap --hoist classmap brakes

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1030]
Link should be white but is blue.

We need to move all utils into npm package utils

<img width="1114" alt="Bildschirmfoto 2019-05-23 um 09 14 23" src="https://user-images.githubusercontent.com/275235/58233024-4d018b00-7d3b-11e9-9d7f-2b7fcccaba77.png">

**Comment by LucaMele** [comment]
Ok, when i remove manually node_modules, it gets fixed. But still we should move it to a `@axa-ch/patterns-library-utils`

**Comment by raphaellueckl** [comment]
@LucaMele Why should we do that? What advantage do we get when we do it?
