### ISSUE TITLE
Add 'tint' or button variant to support correct color of hover state in top content bar

### ISSUE THREAD

**Issue by TheDadi** [axa-ch/patterns-library#1038]
Currently the design of the top content bar seems a bit off... The font color of the button on hover doesn't match the color of the bar itself.

Current implementation:
![image](https://user-images.githubusercontent.com/7534085/58424722-591d7d80-8098-11e9-9faa-6e87d053e618.png)

**Comment by LucaMele** [comment]
Agree, we need to discuss it with designer but i vote to fix this asap.

@jojackpot or @kenaxa any FB?

**Comment by LucaMele** [comment]
Reproduce:
https://patterns.axa.ch/?path=/story/molecules-top-content-bar--top-content-bar-red-with-button
and hover the button

**Comment by kenaxa** [comment]
Hi @TheDadi We took a look together this morning. It’s not the intention to be displayed like this therefore  this bug will be fixed in the next major release.
