### ISSUE TITLE
AXACheckbox: add onFocus and onBlur handlers

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1041]
Add `onFocus` and `onBlur` handlers to `AXACheckbox` component.

These are needed by form frameworks which evaluate whether a field was touched and so whether to do validation, enable submit button, etc...

**Comment by MKaHead** [comment]
I have already implemented `onBlur` and `onFocus` callbacks in input-text thats coming soon.
It's easy to implement it also in checkbox. Should be viable soon in the next minor release of checkbox.
