### ISSUE TITLE
AXADropdown: add onFocus and onBlur handlers

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1043]
Add `onFocus` and `onBlur` handlers to `AXADropdown` component.

These are needed by form frameworks which evaluate whether a field was touched and so whether to do validation, enable submit button, etc...

(Same as in #1041 for AXACheckbox)

**Comment by MKaHead** [comment]
legit
I have already implemented blur and focus callbacks in input-text thats coming soon.
Should be viable soon in the next minor release of checkbox.

**Comment by markus-walther** [comment]
Fixed in minor release 2.1.0.
