### ISSUE TITLE
AXADropdown: onAXAValueChange cb called on render

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1044]
The `onAXAValueChange` callback on `AXADropdown` component is called on every render with the empty string value "".

This is no good.

(In fact it causes endless loop in our app).

**Comment by jackblackCH** [comment]
Thanks, we will fix it and write a test. A Patch will be delivered asap!

**Comment by markus-walther** [comment]
@MarekLacoAXA The new version will support controlled-component behaviour under React and therefore features a `onChange` callback that can be used just like with native select.

Hence in that version I took the liberty to drop `onAXAValueChange` alltogether. The existing axa-change custom event still fires whenever 'items' is updated, so can be used as replacement if needed.

**Comment by markus-walther** [comment]
Fixed in minor release 2.1.0.
