### ISSUE TITLE
15px padding left right on small footer

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1048]
Accordingly to design.com, v1, www.axa.ch and mandatory guidelines footer should not have a padding lx & rx of 15px.

Question is in clearance with designer as well in case im wrong

<img width="1254" alt="Bildschirmfoto 2019-05-31 um 09 50 06" src="https://user-images.githubusercontent.com/275235/58690456-d6dbd480-8389-11e9-9ef8-c26df7886907.png">

**Comment by raphaellueckl** [comment]
I guess the designers don't need to take a look at that. I just fixed it, because I agree that we should only have the container padding that was added later and not the padding overall. Check #1061, after merge, this issue is resolved.

**Comment by raphaellueckl** [comment]
Fixed
