### ISSUE TITLE
Map "class" property from React

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1056]
## Current behavior:

- The class name "myClass" does not appear in DOM.

Example:
```
import createAXAButton from '@axa-ch/button/lib/index.react';
const Button = createAXAButton(React.createElement);
...
<Button className="myClass">...</Button>
```

Example renders as:
```
<axa-button type="button" style="-webkit-appearance: none;">....</axa-button>
```

## Wished  behavior (in all components where it makes sense):

- The class name "myClass" woud appear in DOM.

Example would render with **class="myClass"** :
```
<axa-button class="myClass" type="button" style="-webkit-appearance: none;">....</axa-button>
```

Thanks! :pray:

**Comment by MKaHead** [comment]
Hi @MarekLacoAXA, thanks for creating the feature request. We will implement it!
