### ISSUE TITLE
Lerna publish somehow does not publish materials

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1057]
<img width="1080" alt="Bildschirmfoto 2019-06-04 um 09 38 36" src="https://user-images.githubusercontent.com/275235/58860505-8bd50080-86ac-11e9-86b1-8898e9dec53f.png">

I just run `npm run release` and after `npx lerna version` to manually choose version and materials got updated according to lerna, but on npm it was still old version

**Comment by LucaMele** [comment]
I had to manually npm publish materials

**Comment by raphaellueckl** [comment]
These issues seem to be connected, please remove one.

#1057 #1080

**Comment by raphaellueckl** [comment]
@LucaMele Is this still an issue? Never heard that we have problems there and we did several global releases in the meantime.
