### ISSUE TITLE
axa-container max-width collides with breakpoint

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1060]
The max width imported into axa-container (from layout.scss) collides with the mobile breakpoint.

max-width: 540px
mobile breakpoints: 576px

This leads to a weird look&feel within that delta. This can be resolved by just removing the import of the max-width in axa-container. It would be best to directly fix it in the layout.scss file.

Pls check for sideeffects when making a change there.

![Screenshot 2019-06-04 at 10 46 07](https://user-images.githubusercontent.com/8248662/58865483-ea06e100-86b6-11e9-872a-80d6e87388c5.png)

Content should also stretch to the horizontal edges.

**Comment by danyball** [comment]
We need that delta to have the margins around. Without them the content do not have any space to the horizontal edges. And what do you mean with "weird look&feel" - the screenshot seems to be good?!

Re-open that issue if there is a need.

**Comment by raphaellueckl** [comment]
I just fixed this issue :D Nice coincidence. I will add you as a reviewer.
