### ISSUE TITLE
<axa-link> forces default spacing

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1063]
In some places we use inline `<axa-link>`s and when they are followed by commas especially, the default spacing they force can be undesired. Please see here:

![axa-link-forces-default-spacing](https://user-images.githubusercontent.com/1171773/58963275-27e63100-87ad-11e9-9d21-201ded2964ab.png)

**Comment by raphaellueckl** [comment]
done

**Comment by cge** [comment]
Thanks for the speedy help!
