### ISSUE TITLE
<axa-link> wrapped label alignment

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1066]
It would be nice if a wrapped `<axa-link>` label could align with the text on the first line when an icon is present. Perhaps similar to `<axa-checkbox>`. Please see the difference below:

**Checkbox**

![checkbox-label-alignment](https://user-images.githubusercontent.com/1171773/59031801-f9c42800-8864-11e9-8264-fe7094c0b498.png)

**Link**

![link-label-alignment](https://user-images.githubusercontent.com/1171773/59031825-0b0d3480-8865-11e9-9f57-c6a41d2b9618.png)

**Comment by raphaellueckl** [comment]
The designers should decide on that.

@kenaxa @jojackpot @TommyHoliday

**Comment by raphaellueckl** [comment]
@kenaxa said, we should change it according to your recommendation @cge.

**Comment by cge** [comment]
That's great @raphaellueckl , thanks for finding out.
