### ISSUE TITLE
Release unstable

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1080]
We need to fix release as its completly unstable. 

How to reproduce: https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#how-to-release-a-component

**Comment by jackblackCH** [comment]
Please always give more description. For instance here what exactly is unstable and how to reproduce and what he have to fix.

**Comment by raphaellueckl** [comment]
I see this more as technical depth than a bug with high prio, because that feature never worked, if I am correct.

**Comment by raphaellueckl** [comment]
@LucaMele Looks outdated to me.

**Comment by danyball** [comment]
What do you mean with "unstable" in this context?

**Comment by LucaMele** [comment]
duplicated to #1422
