### ISSUE TITLE
Refactor Title & Text

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1088]
Title isn a `article` atm. Should be a `h*` instead

**Comment by LucaMele** [comment]
And a `title-section` has been beta released on NPM and we have title primary and secondary in the source code

**Comment by LucaMele** [comment]
Action plan:

* Update Readme on NPM: https://www.npmjs.com/package/@axa-ch/title-section to something like: Deprecated, please check out new repo: https://www.npmjs.com/package/@axa-ch/title

* Refactor title-primary and title-secondary to only title having variant primary and secondary and size in 1,2,3,4,5,6. -> Reason: visible channel should always match with semantic. Big fat title is a h1. If we need to give more importance to a lower heading title than a higher one, we add a readme to explain how to wrap lower, sub section title in `<article>, <section>, <nav>, <aside>, <axa-container>`

REFs:
- https://html.spec.whatwg.org/#headings-and-sections
- https://html.spec.whatwg.org/#sectioning-content-2

**Comment by LucaMele** [comment]
SEO compliance should be given, accessibility should match now with visible channel

**Comment by raphaellueckl** [comment]
@LucaMele Do we wait for this until the new typography is released?

**Comment by LucaMele** [comment]
@raphaellueckl what is missing with typography? Is already released in Materials. This issue can be fixed and should be fixed ASAP
