### ISSUE TITLE
<checkbox> inside square alignment

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1090]
No biggie, but is seems the checkbox square is somewhat misaligned these days:

![checkbox_square_alignment](https://user-images.githubusercontent.com/1171773/59663200-cb244680-91ae-11e9-81f9-4811c2f34d07.png)

**Comment by jackblackCH** [comment]
Please always mention the OS, version and browser you tested with and where to reproduce.

**Comment by cge** [comment]
Sure, will do if it occurs again. Perhaps it would be nice to re-use the issue template of `v1` in the `develop` branch? https://github.com/axa-ch/patterns-library/blob/develop-v1/ISSUE_TEMPLATE.md

**Comment by markus-walther** [comment]
We could not reproduce, the CSS says it's all aligned, plus the screenshots are not misaligned. Feel free to re-open when this potential bug resurfaces.
