### ISSUE TITLE
Datepicker: stretch to full width/height

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1110]
Stretch the Datepicker's internals to full width/height of the parent `<axa-datepicker/>`.

Design need. See attached pictures:

![image](https://user-images.githubusercontent.com/43809369/60257295-792ca080-98d3-11e9-9329-eb59d097d52c.png)

![image](https://user-images.githubusercontent.com/43809369/60257541-ee987100-98d3-11e9-8d42-c30b92c6997e.png)

**Comment by LucaMele** [comment]
yes it make sense to fix this. We will do it

**Comment by markus-walther** [comment]
A flexible solution is to provide new properties `width` and `height` for axa-datepicker.

`width="100%"` would then enable the depicted behaviour. `height=25` would set the height of the input field to 25px.

Defaults for both are `auto`. 

This way, the intrinsic sizing of axa-datepicker is preserved when the new properties are not used.

**Comment by markus-walther** [comment]
Fixed by NPM release 2.3.0.0.

**Comment by MarekLacoAXA** [comment]
Using v 3.1.13:

Effectively the datepicker **is not stretched to 100%** width, as there is a `max-width: 226px` css rule applied, which breaks the attempt to fully stretch the datepicker.

See:

![image](https://user-images.githubusercontent.com/43809369/68933906-ea42f680-0795-11ea-8d9d-9d733a9d69c7.png)

**Comment by LucaMele** [comment]
@markus-walther is this still open?

**Comment by danyball** [comment]
@MarekLacoAXA We have this max-width, because the datepicker do not look good if its wider than this max-length. 
What do you say to this max-length here? @TommyHoliday @kenaxa

**Comment by LucaMele** [comment]
@danyball IMHO, all input fields should be same length on one form for consistency. ergo, if no width is set to the datepicker input field, it should stretch same as `axa-input` and `axa-dropdown`. 

Lets see what the designer thinks is best though

**Comment by TommyHoliday** [comment]
@LucaMele @danyball 
i totally agree with luca. input, dropdown and datepicker should all behave the same - so it should be possible to stretch it to 100%.
