### ISSUE TITLE
Datepicker: unusable in react

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1111]
When using as 'inputfield' variant: 

Datepicker component doesn't behave like 'controlled' which is react standard:

Datepicker doesn't have "value" prop, so it can't display the pre/selected date.

Datepicker doesn't survive re-render. So in practice every click on Date causes dismiss of the opened calendar (*), and the input shows no date selected.

*) onChange event in Datepicker causes react state change which causes parent component rerender which rerenders the Datepicker, which appears as blank ==> buggy behavior

Another problem:
onAXADateChange cb is called on first render (seems that with the "Monday" day of current week)

**Comment by LucaMele** [comment]
This is alomst merged. ATM datepicker is alpha for react. Here follow this PR: https://github.com/axa-ch/patterns-library/pull/1077

**Comment by MarekLacoAXA** [comment]
I think Datepicker is unusable with React.
The only way I was able to "make it work" was misusing the "defaultValue" attribute and pass there the user-formatted date value.

Please provide a react story, where:
- no value is chosen on the beginning
- a date can be chosen
- that chosen date comes to Datepicker as prop with a new re-render of the component (controlled input)

(The current story "'Datepicker with inputfield as React Component" renders just once)

**Comment by markus-walther** [comment]
@MarekLacoAXA Strong allegations require strong proof.

"I think Datepicker is unusable with React." is clearly false given the tests. Such overly general statements are not likely to generate good will.

If on the other hand you mean "For my specific use case and needs I make assumptions A and B and would politely request feature X and Y", then please state A,B,X,Y in sufficient detail and we will certainly listen with interest.

**Comment by MarekLacoAXA** [comment]
Sorry, it is usable in React indeed, just the consumer has to fully understand how it works.
In my specific use case the Datepicker wasn't working:

To avoid confusion - a note for other React developers trying to integrate AXADatepickerReact component **in the `inputfield` mode**:

- The date prop **IS NOT** a controlled prop as you might assume. This means - pushing a new value to `date` prop DOES NOT display that date in the text input. It doesn't work like this.

- If your react app happens to flush a component tree and recreate it new, after each onDateChange, then don't be surprised that the observed behavior would be as if "nothing happens". In reality, the Datepicker will be recreated and rendered again - effectively loose its internal state (the selected date) so will display its `defaultValue` prop again.
