### ISSUE TITLE
Follow up Dropdown issues

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1114]
- Not native has bigger bottom border -> Feedback Jonas: needs to be fixed.
- Dropdown native has different padding with dropdown not native what makes it look broken on screen resize -> Feedback Jonas: needs to be fixed.

- Selected option is not respected, default title is displayed instead on the "enhanced version":
![Bildschirmfoto 2019-07-01 um 09 59 10](https://user-images.githubusercontent.com/275235/60420030-fcf1d000-9be6-11e9-985c-e4dae7b061d2.png)
<img width="442" alt="Bildschirmfoto 2019-07-01 um 09 59 25" src="https://user-images.githubusercontent.com/275235/60420031-fcf1d000-9be6-11e9-8252-1db20ceb62d5.png">

- Imported in a react project as client, following effect found:
<img width="1150" alt="Bildschirmfoto 2019-07-01 um 09 58 09" src="https://user-images.githubusercontent.com/275235/60419958-d2a01280-9be6-11e9-87eb-6c9c896b0881.png">
<img width="1133" alt="Bildschirmfoto 2019-07-01 um 09 58 13" src="https://user-images.githubusercontent.com/275235/60419959-d338a900-9be6-11e9-8b2a-5c980411b9ae.png">
<img width="1199" alt="Bildschirmfoto 2019-07-01 um 09 58 17" src="https://user-images.githubusercontent.com/275235/60419960-d338a900-9be6-11e9-9e2d-83c4a9da25a0.png">

**Comment by markus-walther** [comment]
Fixed in minor release 2.1.0.
