### ISSUE TITLE
<axa-link> erratic icon look

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1115]
## Expected Behavior

When rendering an `<axa-link>`, I expect the look to be something like:

![axa-link-good](https://user-images.githubusercontent.com/1171773/60278007-f28db880-98fe-11e9-9be0-69e0b5cf1322.png)

## Actual Behavior

Sometimes, exactly the same mark-up renders incorrectly, like:

![axa-link-bad](https://user-images.githubusercontent.com/1171773/60278114-17822b80-98ff-11e9-961e-66cc57e06896.png)

With mark-up:

![axa-link-bad-markup](https://user-images.githubusercontent.com/1171773/60278147-2537b100-98ff-11e9-80d4-096db3acdc95.png)

## Steps to Reproduce the Problem

1. Render mark-up above, both locally and deployed on DEV.
2. Right now the issue is local, but sometimes it fails in the same way on DEV.
3. Using same browser - see below.

## Specifications

 - Browser: https://whatsmybrowser.org/b/2HY99SL
 - Node Version: v10.15.3
 - NPM Version: 6.4.1
 - Platform: Windows 10 Enterprise

**Comment by MKaHead** [comment]
Hi @cge thanks for creating the issue. We try to reproduce the contemporary.

**Comment by danyball** [comment]
@cge Is this still an issue?

**Comment by LucaMele** [comment]
seems is fixed
