### ISSUE TITLE
Cleanup breakpoint system

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1120]
related: #1117, #1119

**Comment by raphaellueckl** [comment]
What needs to be done here? The "breakpoint system" is fixed, as I read from the linked issues. Do we have a problem with breakpoints?

**Comment by raphaellueckl** [comment]
@LucaMele Can we close this?

**Comment by LucaMele** [comment]
@raphaellueckl nope still not done

**Comment by LucaMele** [comment]
My fix in the two related issue was temporary. I copy pasted a npm module. As dependency it didn’t work when u import it due to naming.

**Comment by flexbox** [comment]
Almost one year old 😂 

We opened #1811 maybe we can close this one @LucaMele ?
