### ISSUE TITLE
Dropdown with global box-sizing: border-box broken

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1143]
With border box:
<img width="1440" alt="Bildschirmfoto 2019-07-08 um 18 41 02" src="https://user-images.githubusercontent.com/275235/60827205-f697c100-a1af-11e9-93bf-747a38c5396e.png">

Without border-box:
<img width="1440" alt="Bildschirmfoto 2019-07-08 um 18 41 39" src="https://user-images.githubusercontent.com/275235/60827242-0d3e1800-a1b0-11e9-9784-d2f5090c28bc.png">

**Comment by markus-walther** [comment]
axa-datepicker is also broken,  both in its embedded dropdowns, and otherwise.
