### ISSUE TITLE
Dropdown react: onChange called when selecting current option

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1144]
AXADropdown/react:
The onChange is called when the current option is selected again.
Logically, there doesn't happen a "change" so IMO nothing should happen. 
(Native select also doesn't call onChange when selecting current option.)
Thx!

**Comment by markus-walther** [comment]
Thanks for the bug report!

Of course, the bug is due to the more complicated inner structure of axa-dropdown, which cannot rely on its inner select alone to determine change.

Will be fixed!

**Comment by MarekLacoAXA** [comment]
Btw. a side note: the readme documentation could be updated regarding that onFocus and onBlur callbacks do work on this component.
