### ISSUE TITLE
Dropdown / Datepicker: empty error wrapper div takes up vertical space

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1146]
The empty error wrapper div `m-dropdown__error` takes up vertical space and so disorders the page design:

![image](https://user-images.githubusercontent.com/43809369/60872926-d874a400-a235-11e9-9c45-258435de9304.png)

**Comment by LucaMele** [comment]
related #1147

**Comment by markus-walther** [comment]
Yes, that is by design and was discussed with our designers. As a solution, see #1147.

**Comment by LucaMele** [comment]
@markus-walther please also add this feature to Datepicker

**Comment by MarekLacoAXA** [comment]
Was this fix released? If so, in which version?
I am testing version: "2.2.0" under react  width `embedded={true}` and the empty error wrapper div stukk takes up vertical space.

**Comment by MarekLacoAXA** [comment]
I see, the "embedded" prop in react component doesn't make it to the web component. 
So it doesn't work on my react side, but does work on your WC side.

**Comment by MarekLacoAXA** [comment]
The same for axa-datepicker.
