### ISSUE TITLE
All form components must implement a flag that disable any place reservation

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1147]
At the moment, Textarea, Inputs, Dropdown, etc reserve place for checkmark and error messages.

Now this place reservation makes sense only if components are used in sync inside a form. But the plib is more flexible then that and must allow devs to flag this place reservation off.

Some related issues
#1146

**Comment by MarekLacoAXA** [comment]
What about to split each such component into two:
1) a plain version. As a nice-looking replacement of the native component.
2) An enhanced rich version. Which adds the additional form-props like checkmarks, error messages.

The reasoning: it would be easier to integrate the plain version (1.) because developer would naturally assume it behaves like its native counterpart (same API) without any surprises like having to set a special flag to render as normal.
 
(Btw. that enhanced version (2.) could be a wrapper fn / HOC which wrapps/transforms the plain component on input)

**Comment by AndyOGo** [comment]
Isn't that an anti pattern, to reserve place for invisible parts?

All components should automatically know and adjust its view depending upon its state, i.e.:
- if there is an error, show it, if not do reserve any place for it
- if a field is valid, add a valid mark, if not do reserve place for it

**Comment by MKaHead** [comment]
Hey @AndyOGo, @MarekLacoAXA that with invisible parts is because of design reasons, they don't want something popup and shift layout, in the forms. So they force you this UX - the want to unify UX, too.

One Solutions is your Marek, but the question is what the common default behavior.

**Comment by LucaMele** [comment]
I would just add a flag and that one disables the space reservation

**Comment by markus-walther** [comment]
That flag is documented already for axa-dropdown as `embedded`, and used productively inside axa-datepicker.

**Comment by AndyOGo** [comment]
Thanks for your answer @MKaHead 

Sure layout shift upon state change is a common problem, no discussion about that.
Though I doubt this is the right approach, for following reasons:

- it violates separation of concerns
- it may workaround one problem by introducing another one (a good solution does not introduce new problems)
- if just empty space is needed, it should be controlled by CSS, not additional placeholding mark-up (don't use markup for styling)

**Comment by LucaMele** [comment]
They are design rules so no point in discussing it here. Talk to @jojackpot ot @kenaxa.

Anyway you are not a consumer of the patterns library as you refuse for ideological reasons so leave us alone please

**Comment by AndyOGo** [comment]
I understand.

I can't help you, if we can't have an objective and constructive communication about a possible improvement without subjective justification.

**Comment by jojackpot** [comment]
From a design perspective we want to prevent shifting jumping of the form layout as @MKaHead described .
