### ISSUE TITLE
Dropdown: visual enhancement: items right padding too wide

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1148]
The selected option needs right padding because of the expand/collapse arrow icon.
But the dropdown-options do not need this padding -- it takes up space and so the text is unnecessarily truncated, which doesn't look good:

![image](https://user-images.githubusercontent.com/43809369/60875460-34412c00-a23a-11e9-8fd6-1f3b022bac0f.png)

![image](https://user-images.githubusercontent.com/43809369/60875490-458a3880-a23a-11e9-8742-e2e58b3ad5f8.png)

**Comment by markus-walther** [comment]
To be precise, the dropdown items don't need this padding when *dropped down*.

As the screenshot shows, the topmost "Alle (8)" does need the padding.

**Comment by jojackpot** [comment]
The Dropdown Items dont need a padding right :-)
