### ISSUE TITLE
Enhance context

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#115]
The first prototype of an asynchronous context implementation works quite good in production.
Though it isn't feature complete.

- [ ] Multiple contexts
   ```js
   class AXAFoo extends BaseComponentGlobal {
     constructor() {
       super();

       this.enableContext();
     }
   }

   class AXABar extends BaseComponentGlobal {
     constructor() {
       super();

       this.enableContext();
     }
   }

   class AXABaz extends BaseComponentGlobal {
     constructor() {
       super(stylesSticky, templateSticky);

       this.selectContext('axa-foo', 'axa-bar');
     }

     connectedCallback() {
       super.connectedCallback();
     }

     contextCallback(contextNode) {
       // nodeName ist the context's name/key
       const { nodeName } = contextNode;
     }
   }
   ```
- [ ] Share contextual Data (not just a `contextNode`)
- [ ] Contextual Lifecycle methods
   - `contextConnectedCallback` (just a proposed rename of `contextCallback`)
   - `contextChangedCallback`
   - `contextDisconnectedCallback`

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
