### ISSUE TITLE
Datepicker/react: incorrect calendar rendered

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1150]
The day of week is wrong 9. July 2019: Should be Tuesday not Friday. However, it would be nice to have Friday already :-D

![image](https://user-images.githubusercontent.com/43809369/60886222-aa04c200-a251-11e9-81e1-5f11fa5f76d6.png)

```
            <Datepicker
              locale="de-CH"
              year={new Date().getFullYear()}
              month={new Date().getMonth()}
              day={new Date().getDate()}
              onChange={console.log}
              inputfield
              placeholder=""
            />
```

**Comment by MKaHead** [comment]
Hi @MarekLacoAXA, thanks for creating the issue. @markus-walther will fix the bug, soon
