### ISSUE TITLE
Dropdown/styles: ensure proper design in "box-sizing: border-box" env

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1152]
**Quick fix:**
Please add styles:
```
.m-dropdown__list {
  box-sizing: content-box;
}
```

**Long description:**
Please ensure proper design in "box-sizing: border-box" environment. This is btw. the _reboot.scss from PLv1 which we are reusing: 
```
*,
*::before,
*::after {
  box-sizing: border-box; // 1
}
```
Or, maybe the shadowdom would help.

Pictures how it looks currently in "box-sizing: border-box" env without the quickfix applied:

![image](https://user-images.githubusercontent.com/43809369/60956337-eb08df00-a302-11e9-80b7-9709be9e3893.png)

hover:
![image](https://user-images.githubusercontent.com/43809369/60956361-f3f9b080-a302-11e9-95bf-ffc369ea7e50.png)

**Comment by LucaMele** [comment]
@markus-walther is fixing this ATM. Also drop down have same issue

**Comment by markus-walther** [comment]
axa-dropdown is a form component, therefore cannot have ShadowDOM unfortunately.

The sketch of the fix is to apply border-box styling throughout internally, and correct the fallout from that .
