### ISSUE TITLE
<axa-link> alignment regression

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1153]
The icon's vertical alignment with the label seems to have changed from top to middle.

<axa-link> `1.3.10`

![axa-link_1 3 10](https://user-images.githubusercontent.com/1171773/60956950-10e2b380-a304-11e9-8731-72741e015f58.png)

<axa-link> `1.3.13`

![axa-link_1 3 13](https://user-images.githubusercontent.com/1171773/60956940-0de7c300-a304-11e9-9a9d-f42daa6152bd.png)

**Comment by MKaHead** [comment]
Hi @cge should be fixed in the patch.

**Comment by LucaMele** [comment]
stale
