### ISSUE TITLE
Datepicker: use normalized format for onChange return value

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1154]
**Current behavior:**
- when using `locale="de-CH"`, the return value is in format "31.12.2019" which isn't parseable with new Date()
- when editing freetext field, the return value is whatever user types in during typing, which often isn't a date at all (so why is it returned from a *Date*picker?)

**Wished behavior:**

In order to seamless integrate the Datepicker component, it would be much helpful if the Datepicker would:
- return value in a normalized format, which would be parseable with new Date(), regardless of locale
- when editing freetext field, the value would NOT be returned until the value is a valid date (maybe even with some debounce timeout), OR maybe until the field looses focus

**Comment by LucaMele** [comment]
Some applications relay on local formatted formats, some dont. In the v1 datepicker we had a option where we could set the output format to iso. @MKaHead or @markus-walther please verify if we still have such option

**Comment by markus-walther** [comment]
As discussed privately, the fundamental issue is whether we compare axa-datepicker to input type=text or input type=date.

This issue assumes the latter, whereas the current implementation assumes the former.

@LucaMele Currently we don't have an iso option, unlike v1.

**Comment by markus-walther** [comment]
For reference, ` <input id="date" type="date" onchange="console.log(this)" min="2019-01-01" max="2019-12-31">` fires `onchange` events also for invalid dates: e.g. year < 2019, month = 99, etc.

**Comment by MarekLacoAXA** [comment]
Hi @markus-walther! 
In which browser did you test?
My tests in Chrome **never** returned an invalid date. Most of the time it didn't fire the onChange event untill a complete date was entered (month plus day). In worst case it returned **an empty string** instead of invalid date. In such case after bluring the file input, its value jumped back to a valid date.

Are there reasons why the axa-datepicker should behave differently? Like fire onChange with a non-date string value - requiring the consumer to pay special attention to do value validation and parsing?
I would expect this from a *date* picker.

```
<input id="date" type="date" onchange="console.log(this.value)" min="2019-01-01" max="2019-12-31">
```

Thanks.

**Comment by markus-walther** [comment]
This issue is superseded by #1169.
