### ISSUE TITLE
Link/styles: arrow is too much far away

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1159]
The arrow of the axa-link component seems to be very distant from the text, which doesn't look ideal and differs from our design:

Design:
![image](https://user-images.githubusercontent.com/43809369/61116286-6d74d880-a494-11e9-9abf-7c5b10569cef.png)

Actual result:
![image](https://user-images.githubusercontent.com/43809369/61116305-7796d700-a494-11e9-91a0-3960988775bf.png)

**Comment by jojackpot** [comment]
MMhhh the padding should be 12 Pixels. Perhaps the Bounding Boxes add to the padding? Zeplin Design can be found here: https://app.zeplin.io/project/5bed40045544f67ec5c16d69/screen/5d15f824e0c86673cf77cb12

![Bildschirmfoto 2019-07-12 um 11 10 10](https://user-images.githubusercontent.com/17493343/61116905-b5482f80-a495-11e9-8765-c133bb0b53cc.png)

**Comment by danyball** [comment]
no bug any more:
![image](https://user-images.githubusercontent.com/7448004/68485328-6b066d80-023f-11ea-97dd-e04b9d68c0fb.png)
