### ISSUE TITLE
Mobile Navigation Interaction Animation

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#116]
Wau, the mobile navigation's animation here at www.axa.com is stunning.
I'm super keen to implement the burger/cross morph. Though I feel the menu itself takes too long to animate (but is nicely synchronized).

![mobile-navigation-axa-com](https://user-images.githubusercontent.com/914443/34291232-9bcffa5a-e6fb-11e7-84bc-e76faa49124f.gif)

**Comment by LucaMele** [comment]
it looks very fancy this one. But i think for less technical people, it might be too flashy

**Comment by LucaMele** [comment]
plus there is a contrast issue

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
