### ISSUE TITLE
Cookie Disclaimer Demo works only once

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1168]
https://patterns.axa.ch/?path=/story/molecules-cookie-disclaimer-demo--cookie-disclaimer-dynamic-story-is-invisible-after-click-on-ok-button

If you accept the cookie disclaimer, a button will be there to remove the item from the localstorage. But if you do that on the demo page, a white page is shown after the cookie disclaimer was again accepted, instead of the button to remove the localstorage again. :)

If you click 'accept' multiple times on the link above, you will see what I mean. See you in 3 weeks. 🙉

**Comment by LucaMele** [comment]
I know but is wanted so its a feature

**Comment by LucaMele** [comment]
See u soon, we miss u
