### ISSUE TITLE
Datepicker: offer Date-object-driven mode

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#1169]
The current axa-datepicker offers a controlled-component mode designed for React. The underlying mental model for this mode has to be the behaviour of `<input type="text">`, for various technical reasons.

As such, invalid or partial date strings can be returned via the `onChange` callback.

It makes sense to offer a complementary mode that works with `Date` objects instead, bypassing questions of string representations of dates entirely and ensuring valid dates throughout.

A settable `date` property would take a Date object. Its `onDate` callback counterpart would deliver a changed valid Date object whenever user input resolves into a valid date.
Finally, a `defaultValue` property would allow to set the initial displayed date in the input field under React.

This issue asks to implement such a complementary mode.

**Comment by MarekLacoAXA** [comment]
Looking forward to this feature!
- `onDate` cb could be named `onDateChange`

Just wondering, who needs "..invalid or partial date strings..." returned from the original onChange cb?

**Comment by markus-walther** [comment]
Controlled-component behaviour, an original sin committed by the React folks, 'needs' the original strings from the input field, semantic concerns like validity play no role there. Trust me... or try to implement it yourself, then you'll see.

**Comment by markus-walther** [comment]
`onDateChange` has been accepted by the team as a better name - thanks for the feedback!

**Comment by MarekLacoAXA** [comment]
Hi @markus-walther !

My example below is not ideal, but you will get an idea:
The demo Datepicker component is controlled - accepts "date" property.
At the same time it has its own logic - when to adopt the date property and when to propagate the entered date:

https://codepen.io/mareklacoaxa/pen/ageWGp?editors=0011
