### ISSUE TITLE
Remove slotted from footer due to too low specificity 

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1170]
<img width="1440" alt="Bildschirmfoto 2019-07-16 um 16 18 03" src="https://user-images.githubusercontent.com/275235/61302047-6bd54880-a7e5-11e9-8435-4f45cd122750.png">

This is needed for AEM migration v1 to v2

**Comment by danyball** [comment]
Some more infos about the bug:

MY DAILY FOR TOMORROW:
Please lets not use slotted anymore for 3 reasons:
1) IE11 Polyfill is, lets say, limiting
2) Is Working Draft therefore not standard technology yet
3) class selector in css with slotted have LESS spcificity then TAG selector :verwirrt: See: https://github.com/axa-ch/patterns-library/issues/1170
Example on how to achieve the same without slotted: https://github.com/axa-ch/patterns-library/blob/19fda7964c5a21a0deb2481efaac898f576ef27f/src/components/20-molecules/cookie-disclaimer/index.js#L44 (bearbeitet)

**Comment by danyball** [comment]
Found 2 ways to get `::slotted` working:
https://stackoverflow.com/questions/49985269/overriding-externally-defined-styles-in-a-web-component

The easiest way is to use `!important`.
