### ISSUE TITLE
Footer Small in React, onDisclaimerChange not usable

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1189]
The event fires, but the issue is WHAT it fires.

USE CASE (steps):

1. I have a translation tool that shows on the footer the disclaimer "Terms of Use" and "Data Protection" based on current language.
2. Now, you have the flag `dynamic` which enables the React Callback logic. So far so good.
3. I need callback for language switch of course so i can change locale but for disclaimer i simply need to call www.axa.ch. Ideally would be if in the `disclaimerItems={disclaimer}` i could set  something like: `const disclaimer = [{ text: t('term_of_use'), href:'www.axa.ch'}]`. In this way it should NOT call the callback function but instead open a link.
4. What makes it worst, ATM, in the callback function i receive the translated text as a param. This makes it impossible to check & open a link myself when "terms of use" or "data protection" has been pressed due to that the text can be translated. It should at least pass me an object containing the key.

This issue is a blocker for my pod Baugarantie.

Code sample: https://github.com/axa-ch/pod-baugarantie/blob/de5bc72a7bbfb1d19f74c8be39ecb8c60ef633ad/src/pod.js#L38

**Comment by codepleb** [comment]
I can take over here, although I need further explanation.

**Comment by raphaellueckl** [comment]
@LucaMele Is this still an issue?
