### ISSUE TITLE
2 layout bugs on footer v2

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1199]
Facebook icon not aligned to text:
<img width="656" alt="Bildschirmfoto 2019-08-05 um 15 19 02" src="https://user-images.githubusercontent.com/275235/62467661-8d966f80-b794-11e9-9285-879619bf3f64.png">

On Ie in between sm and lg resolution layout broken
<img width="1106" alt="Bildschirmfoto 2019-08-05 um 15 19 20" src="https://user-images.githubusercontent.com/275235/62467662-8e2f0600-b794-11e9-8438-02e6de866ac5.png">

**Comment by raphaellueckl** [comment]
@LucaMele done
