### ISSUE TITLE
add boilerplate code generator scripts

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#12]
It would be comfortable to have special scripts to kick-start component development for `atoms`, `molecules` and `organisms` 🚀

**Comment by AndyOGo** [comment]
@LucaMele 
isn't that fixed?
If so, you could mention this issue in related PRs with keywords like `fix`, `fixes`, `fixed` following by issue hash, like:
fixes #12

**Comment by LucaMele** [comment]
ah yes good point sorry. Is fixed
