### ISSUE TITLE
Dropdown, title property and native collide

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1206]
When forcing native and adding a title as preselected value, it wont show. In the pattern library  demos instead was made a hack to make it work by adding a item that was named same as title. Changing the property native or not native should not change the behaviour of title attribute.

<img width="1438" alt="Bildschirmfoto 2019-08-06 um 09 10 52" src="https://user-images.githubusercontent.com/275235/62518557-25926880-b82a-11e9-9dff-f5ed084124c5.png">

![Bildschirmfoto 2019-08-06 um 09 10 58](https://user-images.githubusercontent.com/275235/62518585-3511b180-b82a-11e9-9c18-818c73262066.png)

IS: Title not showed in combination with `native`
SHOULD: Title show same behavior as without `native`

Maybe same issue as here: #1213

**Comment by markus-walther** [comment]
The desired behaviour is not contingent on `native` being present. Rather, the request is to generally treat `title` as an invisible extra option (disabled, of course), which is preselected initially.
