### ISSUE TITLE
Dropdown, Styling Issue

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1207]
Version installed 2.3.0 -> i thought that embedded was deprecated, so is it not released yet?

![Bildschirmfoto 2019-08-06 um 09 16 05](https://user-images.githubusercontent.com/275235/62519136-4c04d380-b82b-11e9-9819-66082c179403.png)

Issue 1 -> Place reservation of error message and tickbox
<img width="1437" alt="Bildschirmfoto 2019-08-06 um 09 15 50" src="https://user-images.githubusercontent.com/275235/62519199-66d74800-b82b-11e9-9e11-baab07730f85.png">

<img width="774" alt="Bildschirmfoto 2019-08-06 um 09 39 39" src="https://user-images.githubusercontent.com/275235/62520565-262cfe00-b82e-11e9-8ef8-159e66698f00.png">

**Comment by markus-walther** [comment]
This was merged here: https://github.com/axa-ch/patterns-library/commit/cd32b154a357b225940883e8ecf0a499ddef5597.

Will be released soon.

**Comment by LucaMele** [comment]
Ah ok cool.. i thought we already did release it
