### ISSUE TITLE
Radio buttons, alignment in a horizontally instead of vertically.

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1212]
The radio buttons are aligned in a horizontally instead of vertically.

The Zeplin screen is updated accordingly.

Best regards
Ken

**Comment by LucaMele** [comment]
@raphaellueckl IMHO i think it is horizontally styled when using fieldset and horizontal attribute. I tested it myself. Please be more precise where and with what attribute or I will close with "cannot reproduce"
