### ISSUE TITLE
Dropdown, value property does not work at all

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1213]
The value property cannot be used to pre-select something from the dropdown as described here: https://www.npmjs.com/package/@axa-ch/dropdown#value

maybe same issue as here: #1206

<img width="689" alt="Bildschirmfoto 2019-08-08 um 10 01 52" src="https://user-images.githubusercontent.com/275235/62685827-adf84100-b9c3-11e9-874d-a0edf9f2a6ff.png">

<img width="853" alt="Bildschirmfoto 2019-08-08 um 10 02 06" src="https://user-images.githubusercontent.com/275235/62685835-b2bcf500-b9c3-11e9-93f5-63640f2f1330.png">

**Comment by MKaHead** [comment]
Crucially, this behaviour pertains to _uncontrolled_, native mode. The doc forgot to mention that restriction.
