### ISSUE TITLE
Colors differs on axa-dropdown and axa-input-text

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1214]
<img width="1174" alt="Bildschirmfoto 2019-08-08 um 10 54 30" src="https://user-images.githubusercontent.com/275235/62689441-1696ec00-b9cb-11e9-8c9a-f38e4baed4c2.png">

Either text or dropdown has wrong border color. Please @kenaxa tell which color is correct

**Comment by MKaHead** [comment]
I looked at Zeplin, the border color should be #999, so dropdown have to be fixed. Maybe the error comes from the dropdown list because that thing have a border color #ccc.
