### ISSUE TITLE
Datepicker, design of input field differs to dropdown and input text

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1220]
IS: Design is different
SHOULD: design should be the same

Seems obvious, but still double check with @kenaxa 

![Bildschirmfoto 2019-08-10 um 10 08 14](https://user-images.githubusercontent.com/275235/62819540-e9774480-bb56-11e9-89af-739c6e33ac66.png)

**Comment by markus-walther** [comment]
Fixed in release 3.0.0.
