### ISSUE TITLE
Datepicker, manual editing of date breaks error logic

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1221]
IS: After selecting a date and changing the date manually, an error occurs. After reverting it back, error stays even if date is correct
SHOULD: When writing a correct date error message should disappear

![Aug-10-2019 10-15-18](https://user-images.githubusercontent.com/275235/62819631-111adc80-bb58-11e9-989d-fbde875ce605.gif)

**Comment by markus-walther** [comment]
Fixed in release 3.0.0.
