### ISSUE TITLE
Script, that installs and serves a component for testing 

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1227]
After a component has been published, it's kind of messy to test it. We should find a way to more or less automate this process and also get the full HTML spit out after completion.

Process:
- Component has been published to npm
- Dev activates script that asks for component name
- The script sets up a react / pure html environment and starts to serve the component
- The user validates, that it works on native and react
- After validation of the user, the script spits out the current html and js files that are relevant for the readme, so we can copy&paste 1:1 what you've seen running with your own eyes.

**Comment by LucaMele** [comment]
@raphaellueckl is this still relevant?

**Comment by raphaellueckl** [comment]
@LucaMele imho yes, but let's close it and see how big the pain is in the future.
