### ISSUE TITLE
<axa-textarea> value property does not work. 

### ISSUE THREAD

**Issue by romantenger** [axa-ch/patterns-library#1244]
The value property from the axa-textarea does not work in React.js at all.

sample: `<axa-textarea value="test"></axa-textarea>`

![image](https://user-images.githubusercontent.com/28395751/63249272-6f873f80-c269-11e9-8498-49f3c0193409.png)

![image](https://user-images.githubusercontent.com/28395751/63249539-f805e000-c269-11e9-8505-d690071ca03e.png)

**Comment by LucaMele** [comment]
Thank you @romantenger , we will look at it asap and let you know

**Comment by LucaMele** [comment]
@romantenger, did you use the wrapped react component or add the textarea as native WebComponent?  

This:
```
<axa-textarea value="test"></axa-textarea>
```
OR that:

```
import { createElement } from 'react';
import createAXATextareaReact from '@axa-ch/textarea/lib/index.react';
 
const AXATextareaReact = createAXATextareaReact(createElement);
 
<AXATextareaReact value="test" />
```

**Comment by LucaMele** [comment]
Under react, i think what you would like to achieve is done in this way: https://www.npmjs.com/package/@axa-ch/textarea#defaultvalue

@MKaHead please confirm.

**Comment by romantenger** [comment]
I used the wrapped text component

**Comment by MKaHead** [comment]
Hi @romantenger, I can't reproduce the problem, for the moment. Can you give us a snippet or screenshot how you use the textarea under react and the version number, thank you?

**Comment by romantenger** [comment]
I'm using React Version 16.8.6.
I've broken down the code to the minimum:
![image](https://user-images.githubusercontent.com/28395751/63269509-a293f800-c296-11e9-8223-f54faee3fea4.png)
![image](https://user-images.githubusercontent.com/28395751/63269588-cd7e4c00-c296-11e9-85f4-8e825a9b09d0.png)
![image](https://user-images.githubusercontent.com/28395751/63269659-f1419200-c296-11e9-969a-ef2e0b1553c3.png)
![image](https://user-images.githubusercontent.com/28395751/63269775-1504d800-c297-11e9-9620-1822dadba6ef.png)

**Comment by MKaHead** [comment]
Here @romantenger a living example, how you use textarea in react.
https://codesandbox.io/s/little-mountain-ie0kh?fontsize=14

If you can't open, here are screenshots:
![Bildschirmfoto 2019-08-19 um 16 33 12](https://user-images.githubusercontent.com/11683864/63274055-6ca74180-c29f-11e9-9e44-615c926f6177.png)

![Bildschirmfoto 2019-08-19 um 16 38 02](https://user-images.githubusercontent.com/11683864/63274260-c4de4380-c29f-11e9-94ba-84c7c9d62aa3.png)

**Comment by romantenger** [comment]
That worked perfectly. Thank you!

**Comment by MKaHead** [comment]
@romantenger, your welcome :)
