### ISSUE TITLE
Dropdown: in NOT NATIVE MODE: once open, autocomplete should work same as in native mode

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1247]
In NOT NATIVE MODE: once open, autocomplete should work same as in native mode.

Use case: you have a list with all countries and want to look for italy. Under native dropdown you can open it and start typing It.. and it scrolls down to where Italy is.

**Comment by markus-walther** [comment]
The scope of autocomplete/autosuggest behaviour should cover *2 scenarios* to be compatible with native behaviour:

- dropdown is closed but focussed
- dropdown is open and focussed

(the 2nd case has been suggested by @danyball)

**Comment by markus-walther** [comment]
Additional features in scope for this issue:

- scroll to position selected by typing
- ability to key-board-navigate from selected position via up/down arrows

As always, native &lt;select&gt; serves as a model for desired behaviour.
