### ISSUE TITLE
Dropdown should innerscroll according to zeplin

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1256]
<img width="949" alt="Bildschirmfoto 2019-08-21 um 16 00 11" src="https://user-images.githubusercontent.com/275235/63438615-e3257a00-c42c-11e9-83c4-f92f29f52477.png">

This is required for go-live

**Comment by MKaHead** [comment]
it's fixed in dropdown version 3.0.0.
- You have to use the Boolean property maxHeight
- You will find a demo here: [max height with many options](https://patterns.axa.ch/?path=/story/molecules-dropdown-react-demos--many-options-react-ified-dropdown)
