### ISSUE TITLE
policy features: do we have a border-box problem?

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1257]
Luca left a comment on review:
https://github.com/axa-ch/patterns-library/pull/1188#issuecomment-520378770

I cant reproduce this problem. But we must have a closer look at that problem.

**Comment by raphaellueckl** [comment]
Do we need 2 issues here? @danyball

**Comment by danyball** [comment]
Yes, because we do not know if the "centered" problem is caused by a border-box problem. It could be, but we dont know.

**Comment by raphaellueckl** [comment]
I guess that cannot be. Borderbox should not decide if something is centered or not. It could just mess a bit with the borders and I doubt that one of those is several hundred pixels wide. :D

**Comment by LucaMele** [comment]
@raphaellueckl it can be because without border box the width is bigger. If u apply border box, the inner width is smaller and depending how u styled inside, it can happen that stuff get rearranged if they are not all fluid
