### ISSUE TITLE
Input field show id error, even if no id is set

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1259]
When NOT setting a ID in react, a empty string ID is set and therefore show following message in chrome:

![Bildschirmfoto 2019-08-25 um 16 23 11](https://user-images.githubusercontent.com/275235/63651423-db2f4800-c754-11e9-9ee3-df1663044b67.png)

Expected behaviour: no id should be attached if no one is set

**Comment by MKaHead** [comment]
That problem should be fixed #1240. Could you update the version to get newest patch.
