### ISSUE TITLE
Datepicker, box-sizing collision

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1267]
Most liekly there is a issue with box-sizing on the button cancel in datepicker. Had no time for deeper analysys

<img width="371" alt="Bildschirmfoto 2019-08-28 um 18 51 55" src="https://user-images.githubusercontent.com/275235/63876073-1172fe80-c9c5-11e9-9bdb-cd95283fef24.png">

**Comment by markus-walther** [comment]
This is a consequence of embedded axa-button, and has nothing to do with box-sizing.

**Comment by markus-walther** [comment]
Fixed in release 3.0.1.
