### ISSUE TITLE
Disable hover CSS for mobiles and small screens

### ISSUE THREAD

**Issue by jan-capiak** [axa-ch/patterns-library#1283]
The problem is when you touch the screen on top of some component (AxaRadio - type button f.e.) and scroll, then this components stays focused and it looks like it is selected, which is confusing the user.
Thank you

**Comment by 01231** [comment]
@jan-capiak Does this only happens in chrome? Because I cant reproduce it in safari and firefox.

**Comment by raphaellueckl** [comment]
@jan-capiak Isn't this default browser behaviour? Not sure if we should mess with that, because that could lead to a lot of code.

**Comment by marek-polak** [comment]
@NoahLiechti this happens in mobile (touch) devices only. It's super explained here: https://medium.com/@mezoistvan/finally-a-css-only-solution-to-hover-on-touchscreens-c498af39c31c
In short: "The problem arises when the user interacts with this element on a touchscreen: after the tap has been done, the hover effect is stuck on the element."

**Comment by raphaellueckl** [comment]
We decided to go with the default browser behavior. @LucaMele brought evidence, that the behavior is the same with the native buttons.
