### ISSUE TITLE
Dev Rebuild is slow

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#130]
# To Do

- [x] make build **incremental** - only build what has changed (including resolved consumers)
- [ ] add BrowserSync for automatic reloading of changed ressources (Not necessary for patterns library)

**Comment by LucaMele** [comment]
fixed. Wont add browser sync as it would be to much for the moment. With the rework of the dev build now is very quick and with browser reload you always land on the same component. So browser sync is not needed and i close the issue
