### ISSUE TITLE
AXA Datepicker, february leap year not working and on year change february have 30 days

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1303]
AXA Datepicker, february leap year not working and on year change february have 30 days

![february-bug](https://user-images.githubusercontent.com/275235/64353360-ecead800-cffd-11e9-9920-4acc02643c4e.gif)

**Comment by markus-walther** [comment]
"Leap year not working" demonstration is incorrect, since 2019 and 1971 - featured in animated GIF - are both not leap years. I claim that leap year works (e.g. demonstratable with 2020, which has a passing ui.test.js case for Feb. 29).

**Comment by LucaMele** [comment]
I tried 6 different years @markus-walther. 1970, 1971, 1972, 1973, 1974, 1975, 1976. One out of them is deffo a leap year.

The video represets the switching year issue not the leap one.

**Comment by markus-walther** [comment]
As the video demonstrates, there is (has been) an update problem. This can give the illusion that there is a leap year problem when transitioning between years. There is however no leap year problem per se.
