### ISSUE TITLE
AXA Dropdown may fire 🔥 uncaught exception when client side rendered 

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1308]
Proposed solution:

Defensive programming with a IF around the call of `findIndex`

<img width="453" alt="Bildschirmfoto 2019-09-09 um 08 56 35" src="https://user-images.githubusercontent.com/275235/64509436-fb780e80-d2df-11e9-9aa3-6d80e85b3c46.png">

<img width="380" alt="Bildschirmfoto 2019-09-09 um 08 56 42" src="https://user-images.githubusercontent.com/275235/64509423-f5822d80-d2df-11e9-9aaa-ce49a2ab71b8.png">

**Comment by markus-walther** [comment]
Title changed to 'may fire' because axa-dropdown clearly only shows the bug under very specific circumstances.

**Comment by markus-walther** [comment]
The simplest way to reproduce this bug is to *forget* the `items` attribute/property.

**Comment by LucaMele** [comment]
I think AEM forms starts without items and then is set dynamically with JavaScript (needs to be verified)
