### ISSUE TITLE
Add label to dropdown

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1313]
I would like to have a label on top of a dropdown, like other elements have (input-text for example).

See screenshot below. Other elements have a label, the dropdown label has to be set manually.

![Screenshot 2019-09-10 at 10 12 34](https://user-images.githubusercontent.com/8248662/64596095-968de880-d3b3-11e9-9cdd-28ae081137f4.png)

**Comment by markus-walther** [comment]
axa-dropdown has a label property that is documented in its README. It works.
