### ISSUE TITLE
axa-textarea: max-char-entered should put the textarea into an error state

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1320]
When entering too many characters, an error text "Max number of chars is reached"  is shown by &lt;axa-textarea&gt;

The error text below the textarea should be in red and the checkmark should not be shown.

<img width="692" alt="Bildschirmfoto 2019-09-11 um 15 21 32" src="https://user-images.githubusercontent.com/275235/64700852-f5348e80-d4a7-11e9-986b-e6aef112c47d.png">

This feature request is approved by Martin and needed for AEM Forms.

**Comment by markus-walther** [comment]
As discussed today with the designer, for better UX the visual error state should be shown 1 character before the limit is enforced by the native underlying &lt;textarea&gt;:

E..g. for `maxlength="3"` with no characters "2 character(s) left", with 1 character "1 character(s) left", with 2 characters "0 character(s) left", and with 3 characters "Character limit reached" (only then visual error state).

**Comment by markus-walther** [comment]
The issue in the previous commit has been addressed in commit 56e43d89583c96ba4bf041a6be340c08f8579285.
