### ISSUE TITLE
Storybook - some component stories have folder icon

### ISSUE THREAD

**Issue by NoahLiechti** [axa-ch/patterns-library#1325]
The icons in the story-tree of `AXAButtonLink`, `AXAButton` and `AXAInputText` differ from the other components. They should all have the same icon.

<img width="180" alt="Bildschirmfoto 2019-09-12 um 08 33 24" src="https://user-images.githubusercontent.com/38284563/64761038-6a04d880-d53b-11e9-8f9d-e4a2ce045eb6.png">

**Comment by danyball** [comment]
This is because they are folders. They all have subfolders "React" or "Demo".

**Comment by NoahLiechti** [comment]
But so does input file.
<img width="185" alt="Bildschirmfoto 2019-09-19 um 14 52 32" src="https://user-images.githubusercontent.com/38284563/65245623-31da3880-daed-11e9-9dec-b2452b64de20.png">

**Comment by raphaellueckl** [comment]
This should be fixed by a team decision on how deep we want our stories to go.

**Comment by raphaellueckl** [comment]
I asked the storybook devs about this: https://github.com/storybookjs/storybook/issues/8292
