### ISSUE TITLE
Put AXA Logo to icon-component

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1326]
An icon speaks for itself. The axa logo does not fit into this category.

A button with a download icons says "if you click me, you download something".
A button with a axa logo says nothing. It doesn't speak for itself.

The axa logo should be only under /images.

**Comment by danyball** [comment]
For me icons are very simple - and the logo is not. So i would prefer to see it as a image. Is it possible that the axa-icon component imports /images?

**Comment by danyball** [comment]
Folgende Lösung im Daily besprochen:

- das Logo soll nur unter /images liegen
- die icon-Komponente soll das logo (2 dateien) in ihr Katalog aufnehmen
- die icon-Komponente soll ein SVG-string entgegennehmen können (damit können z.b. alle anderen images in pure HTML pages dargestellt werden)

**Comment by raphaellueckl** [comment]
@LucaMele I just looked into it. Those icons are different. One contains a fixed width and height and the other one doesn't (and the viewboxes are different). Maybe it's not worth the effort to unify this special case.
