### ISSUE TITLE
AXA Dropdown prevents form submit on enter

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1332]
Behavior: 
When AXA Dropdown is present in the form user can not submit form by pressing enter key.

Cause:
Dropdown options are buttons without specified type attribute -> this takes precedence over form submit button as their handler is called instead and event propagation is stopped.

Fix:
All buttons must have specified attribute `type="button"`

**Comment by markus-walther** [comment]
This cannot be reproduced without further input.

http://patterns.axa.ch/?path=/story/molecules-dropdown-demos--dropdown-inside-form shows a working form submission using &lt;axa-dropdown&gt; and automated end-to-end tests using this pass correctly.

We would need more details (framework?)  and ideally a reproducible minimal test case.

**Comment by salle18** [comment]
@markus-walther Issue is already reproducible on the link you provided, choose dropdown option using mouse, press enter on the keyboard -> form is not submitted although it should have been.
Clicking on submit button or directly targeting submit button in e2e tests is not the same, form should submit without focus on submit button when user presses enter on input.

Further reading:
https://stackoverflow.com/questions/31644723/what-is-the-default-button-type

Buttons without type:
https://github.com/axa-ch/patterns-library/blob/c02648feb51619c0c6cf37f29808780287a688ae/src/components/20-molecules/dropdown/index.js#L68

e2e test is directly targeting submit button:
https://github.com/axa-ch/patterns-library/blob/c02648feb51619c0c6cf37f29808780287a688ae/src/components/20-molecules/dropdown/ui.test.js#L227

**Comment by markus-walther** [comment]
I think there is a misunderstanding. Axa-dropdown is not specified to have type "submit" (see the defining README), the question of whether internal buttons have which type therefore is not relevant here.

As I understand, you are requesting a new feature, not reporting a bug.

It would be helpful to just state the feature you want and *why* you want it (rather than using a standard submit button, which works now).

Oh, and we would appreciate to not speculate about component internals or possible fixes in issue descriptions, things are most often more complicated than you think.



Thanks a lot.

**Comment by salle18** [comment]
Hi @markus-walther, I will try to argue with you one more. This is reporting a bug and not making a feature request.

Please go back to my initial bug report where I clearly stated what is a buggy behavior:
`When AXA Dropdown is present in the form user can not submit form by pressing enter key.`

Standard submit button works only if you directly click on it or focus it and press enter.
**Implicit form submission using keyboard enter key does not work at the moment.**

**Why is this important?** 
Implicit submission is vital to assistive technologies and impaired users that cannot use a mouse at all.

Please try it here https://codesandbox.io/embed/wonderful-haslett-qqxkc

Steps to reproduce:
- Choose Item B from the dropdown
- Go to the input text field and enter some text
- Press enter on keyboard
- **Dropdown option changed to Item A**
- **Form is not submitted**

Expected behavior:
- Dropdown option is still Item B
- Form is submitted

As for speculating about component internals or possible fixes - I spent some time figuring out why my form would not submit so I figured out you would appreciate if I saved some of your time looking for the same think, I guess I was wrong about that and things are a bit more complicated.

**Comment by LucaMele** [comment]
I agree with @salle18. Is a Issue and needs to be fixed

**Comment by markus-walther** [comment]
After amicably resolving the misunderstandings in bilateral dialogue, a fix has landed in commit 1cc1d07b0650a81877c835772b7f90978ef4d781.
