### ISSUE TITLE
Policy Features: alternative Text for Image

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1373]
If a image isnt load. 

`alt=`

**Comment by danyball** [comment]
Selina gibt noch Feedback wie es aussehen soll, ansonsten neu designen

**Comment by NoahLiechti** [comment]
@danyball the images in pattern-library are `<svg>`so they don't have any `alt` tag. 
I don't think that this should be a use case.

**Comment by danyball** [comment]
Good point @NoahLiechti .

We have 2 ways to show SVG in policy features:

- set icon attribute to a svg-string --> we dont have a real "loading" of the image, so we dont need a alt tag
- set icon attribute to a svg-url --> it is possible to check if the url response with error code != 200. Now it would be possible to show a text.

@selinagahlinger Is it a requirement that screen readers can read the alt text of an image? There are possibilities to set `aria` text for SVGs - not so easy in our use-case because they are set within the svg tag.

**Comment by selinagahlinger** [comment]
@danyball it is not a requirement in agreement with Martin Stüdle

**Comment by danyball** [comment]
Ok, feel free to open a new issue if you need new features.
