### ISSUE TITLE
Policy Features: not centered

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1375]
![image](https://user-images.githubusercontent.com/7448004/65435326-a16b6300-de20-11e9-8ce4-dcfb4bdaa79a.png)

**Comment by NoahLiechti** [comment]
@danyball is there more information about how this was implemented? I can not reproduce this error.

**Comment by danyball** [comment]
I cant reproduce it, too. Please ask @selinagahlinger for more infos. Perhaps because they are using `border-box *` like in this open issue: https://github.com/axa-ch/patterns-library/issues/1257

**Comment by 01231** [comment]
so I tried it with `border-box`and it works perfectly, even on ie11...

![Bildschirmfoto 2019-10-01 um 14 26 50](https://user-images.githubusercontent.com/38284563/65961878-c9c61380-e457-11e9-96a7-19527ec5d335.png)

**Comment by 01231** [comment]
so @selinagahlinger in my opinion this is not the fault of the pattern-library. It would help if we could reproduce this scenario. Otherwise I will close this issue.

**Comment by raphaellueckl** [comment]
@danyball @NoahLiechti  We should override border-box. This is the approach we always take. We should be plug&play.

**Comment by danyball** [comment]
Should override that if necessary. Lets try to find out if this centerd-bug is caused by border-box problems. @NoahLiechti We can do that together with selina.

**Comment by raphaellueckl** [comment]
@selinagahlinger Can we close this issue?

**Comment by selinagahlinger** [comment]
@raphaellueckl yes
