### ISSUE TITLE
Automatic generation of React wrapper for components

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#1380]
Prompted by a discussion with @raphaellueckl: Currently, React wrappers (`index.react.js`) are manually written, and prone to errors of omission. One might forget to include a new property, or one might forget to specify a default value for a property.

But we *have* that information already: the list of properties is declared in the static `properties` getter of the class that defines the component, and the default values are canonically specified in the constructor of that class.

This issue asks to find a way to use said information to automatically generate a React wrapper for a component.

**Comment by LucaMele** [comment]
Comment from a consumer:

hello Luca, i have tried the cusrtom attribute in our React app, but it isnt in the DOM. Can you try to whitelist all custom attributes in the createReactComponent function please?

We need to pass all props down with the `...rest` operator

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues/1443

**Comment by 01231** [comment]
can we close this one and #1443? @LucaMele
