### ISSUE TITLE
export every component class

### ISSUE THREAD

**Issue by zuzana** [axa-ch/patterns-library#139]
**What:** Could you export every component class? 
**Why?** So that I can import and extend it inside application when necessary

e.g. 

    wcdomready(() => {
      window.customElements.define('axa-footer-languages', AXAFooterLanguages);
    });

    export default AXAFooterLanguages;

It would also require change in `stack/tasks/bundle.js` 

    const outputOptions = {
      format: 'umd', // is 'iife' at the moment
      name: 'StyleGuideWebComponent',
    };

**Comment by LucaMele** [comment]
Hello @zuzana, thank you very much. Feel free to do the needed changed to all components and create a PR. If not, i can do it as well.

**Comment by AndyOGo** [comment]
@zuzana I just created a PR for this
