### ISSUE TITLE
Build and Release Pipeline for release Branches

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1390]
I am releasing components. i have to manually run tests, npm i and all that stuff again. Would be cool if we had all these steps on the server. If everything is ready i want to click a release-button in Jenkins. And a build-user commits the components to npm and changes to git.

What do you think about that way?

**Comment by raphaellueckl** [comment]
I don't see the advantage here.

You would still need to say if an update is minor, major, patch and this can already be done with a script.

We fixed the "install" part, so the release script now includes the install step. And we should fix the adapting of the lerna json file. But if you go to a jenkins or whatever and click a button or just manually enter the `npm run release` command, doesn't make that much of a difference. It's just a layer of complexity more with imho no benefits.
