### ISSUE TITLE
Table Row Sortables

### ISSUE THREAD

**Issue by kenaxa** [axa-ch/patterns-library#1396]
Only one arrow at the time should indicate that it has been sorted. 

re-create bug: Sort different rows, now multiple arrows are pointing down. 
Only one arrow at the time, the active sorted one, should be pointing downwards.

**Comment by danyball** [comment]
It is just 1 arrow blue. The others are grey and that indicated that they are not active. Does it matter if a grey arrow points up or down?

**Comment by danyball** [comment]
Talked to Ken: If a column is not active sorted, 2 arrows in grey should be visible. It you click on such a column it changes to 1 arrow in blue.

**Comment by danyball** [comment]
> - Der Header in der gleichen dunkle Farbe wie der Rest der Headers auch bei active & inactive(nicht blau)
> - Denn Doppelpfeil (oben & unten) als default
> - Active sortiert oben oder unten mit Pfeil in Blau (#00008f) (bearbeitet)

**Comment by danyball** [comment]
Verhalten wie https://examples.bootstrap-table.com/
