### ISSUE TITLE
How wil we document those components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#14]
Each component has some intrinsic features and behaviours.
In special cases or in combination with certain other components it's likely that layout, measurements and other stuff may change.

Concrete examples are the [mobile menu](https://design.axa.com/web-guidelines/header#types-of-header) (which triggers an unrelated DOM tree from within another component) or the various variations of the [footer](https://design.axa.com/web-guidelines/footer#types-of-footer).

Those intrinsic features and behaviours are reflected by code, either as `html`, in `css` or through `js`. So I don't think that we need to document the related stuff in all code, but we need to find an easy way to do it and make it parseable.

Regarding **JS** i would use awesome [`@JSdoc` doclets](http://usejsdoc.org/).
And for **SCSS** I would use awesome [`@sassdoc` doclets](http://sassdoc.com/)

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
