### ISSUE TITLE
path to assets

### ISSUE THREAD

**Issue by zuzana** [axa-ch/patterns-library#140]
**What?** When using built components as they are in application, I'm getting following error:

    Module not found: Can't resolve './assets/fonts/PublicoHeadline-Bold-Web.eot'

**How to solve?** Could you adjust path to assets in a way described below?

*src/styles/settings/_fonts.scss*

    $font-base-path: '/assets/fonts/' !default;
    // $font-base-path: './assets/fonts/' !default; // BEFORE

*src/index.html*

     httpObj.open("GET", "/assets/icons/icons.svg", true);
     // httpObj.open("GET", "./assets/icons/icons.svg", true); // BEFORE

**Comment by AndyOGo** [comment]
@zuzana 
Please have a look at the SASS docs regarding `!default` variables:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default

It should answer your question.

**Comment by AndyOGo** [comment]
@zuzana 
Hope above fixes your issue, if so please close.
