### ISSUE TITLE
Textarea Check mark breaks scrollbars

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#1403]
The :heavy_check_mark: breaks the scroll bars in all browsers.

- on **Windows** it always overlays the scrollbar and does not allow the user to `click` the scroll-up arrow button
- on **macOS** it will lose the scrollbars focus, thus abandons scrolling and does not allow the user to `click` the scroll-up arrow button
- it reduces the available space for the user's input

Please see Browsers and OS below, each browser is linked to whatsmybrowser.org for all relevant details.

**Note:** The global design guidelines specify the position of the check mark to the right of the input/textarea field:
https://design.axa.com/web-guidelines/forms#forms-elements

**Windows:**

- [Firefox](https://whatsmybrowser.org/b/3D2VR59)
  ![Textarea-Tick-Firefox-Windows](https://user-images.githubusercontent.com/914443/66120408-11c17380-e5db-11e9-9023-ae8f4ccd0ee0.gif)

- [Chrome](https://whatsmybrowser.org/b/6U97SFQ)
   ![Textarea-Tick-Chrome-Windows](https://user-images.githubusercontent.com/914443/66120591-80063600-e5db-11e9-9aac-617cc28db5bd.gif)

- [Internet Explorer](https://whatsmybrowser.org/b/477D9HB)
   ![Textarea-Tick-IE-Windows](https://user-images.githubusercontent.com/914443/66120781-fe62d800-e5db-11e9-8219-fd10003837f7.gif)

**macOS:**

- [Firefox](https://whatsmybrowser.org/b/UT4ERP7)
   ![Textarea-Tick-Firefox-Mac](https://user-images.githubusercontent.com/914443/66121306-2868ca00-e5dd-11e9-9966-33a4accebdc9.gif)

**Comment by raphaellueckl** [comment]
@kenaxa Is working on a solution.

**Comment by TommyHoliday** [comment]
As discussed in the team, pls see updated design specs in zeplin:
https://zpl.io/bLWZmKm

**Comment by LucaMele** [comment]
fixed with #1424  `@axa-ch/textarea@1.5.3`
