### ISSUE TITLE
AXA-Input: defaultValue does not work in react context

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1404]
Reproduce: http://patterns.axa.ch/?path=/story/atoms-input-text-react--input-text

Set anything as "defaultValue" and it does not get propagated.

**Comment by markus-walther** [comment]
From the README:

The string-valued `defaultValue` can only be used for React.

Like `value`, it sets the value of the underlying native HTML &lt;input&gt; &mdash; _but_ only once, on first render.

<hr>

In other words, the component behaves exactly as documented: when changing via knobs, the change is no longer the first render.  `defaultValue` is intended for [uncontrolled React components](https://reactjs.org/docs/uncontrolled-components.html#default-values), where such behaviour is desired

**Comment by raphaellueckl** [comment]
@markus-walther Thanks for clarifying that. I will close this issue.
