### ISSUE TITLE
Datepicker doesn't get rendered on IE anymore

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1407]
![Untitled](https://user-images.githubusercontent.com/8248662/66293649-6a4c8580-e8e7-11e9-9397-f7013b7a36d0.png)

Reproduce: https://www.dev.axa-ch.intraxa/en/forms/report-a-claim/miscellaneous-claims/rental-guarantee.html

**Comment by markus-walther** [comment]
This was likely a polyfill issue, notice the 'findIndex' errors.

Inspecting axa-datepicker attributes and internal composition, it moreover is clear this is a v1 datepicker component.
