### ISSUE TITLE
Textarea: maxlength = 0 if not overridden

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1408]
Maxlength should not default to 0.

**Comment by 01231** [comment]
If the `maxLength` attribute isn't set, there are unlimited characters allowed. It's just a problem with knobs.

**Comment by raphaellueckl** [comment]
Yes but this is also a problem with react I guess. Anyone keeping a hard reference in there. As soon as `undefined` gets into there, it will convert to `0`.
