### ISSUE TITLE
Datepicker: css: 5 days in week (wrapping bug)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1417]
Datepicker: css: 5 days in week (wrapping bug):

Screenshot:
![image](https://user-images.githubusercontent.com/43809369/66390686-7c075900-e9cb-11e9-8fc6-6b11fac61855.png)

**Comment by MarekLacoAXA** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/43809369/66752683-46161900-ee92-11e9-9c8d-b8e2ed7b43e2.png)

**Comment by markus-walther** [comment]
Please remove all v1 CSS that conflicts with reserved component-internal class names from the page.

Such mixed v1-v2 CSS use is not supported by v2 components.
