### ISSUE TITLE
Dropdown: css: icon to far away (css polution?)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1418]
https://www.dev.axa-ch.intraxa/de/test-pods/MyAxa.html?v9#/1001217/start

![image](https://user-images.githubusercontent.com/43809369/66394629-ede4a000-e9d5-11e9-9522-7ba0713fc9f6.png)

![image](https://user-images.githubusercontent.com/43809369/66394654-f63cdb00-e9d5-11e9-80ca-cab2291fd24b.png)

Side note: Is there a Chrome plugin that would allow to share the full DOM?

**Comment by markus-walther** [comment]
Please remove all v1 CSS that conflicts with reserved component-internal class names from the page.

Such mixed v1-v2 CSS use is not supported by v2 components.
