### ISSUE TITLE
Datepicker: css: sizes problem (css polution?)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1419]
Datepicker: css: sizes problem (css polution?)

https://www.dev.axa-ch.intraxa/de/test-pods/MyAxa.html?v9#/1001217/start

![image](https://user-images.githubusercontent.com/43809369/66396078-45d0d600-e9d9-11e9-94e3-c11a6739c2dd.png)

![image](https://user-images.githubusercontent.com/43809369/66396097-4a958a00-e9d9-11e9-8ffb-b8f4764c8f94.png)

(How could I serialize my DOM and share with you?)

**Comment by markus-walther** [comment]
Please remove all v1 CSS that conflicts with reserved component-internal class names from the page.

Such mixed v1-v2 CSS use is not supported by v2 components.
