### ISSUE TITLE
Dev env is unstable

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1422]
Build, release is not as it should be. We need to clean it up. Add the following folder structure:

`lib` -> for libs x each component
`src` -> for src x each component

Will improve it a lot. Sometimes due to package.json having `"main": "lib/index.js",` during development the lib export is taken instead of the root. Adding `src` folder will prevent this. `src` also make the regex on rollup much easier.

**Comment by raphaellueckl** [comment]
@danyball I think this is the reason why hot reloading doesn't work on the dropdown anymore. Only another "npm install" (or build) makes the changes visible. @LucaMele I adapt the prio of this issue, since this is extremely annoying.

**Comment by danyball** [comment]
Good point. After deleting lib it works.

**Comment by danyball** [comment]
It is solved by luca.
