### ISSUE TITLE
AXAIcon request for documentation

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1429]
src/components/10-atoms/icon/index.js

Please explain WHY and WHAT is the firstUpdated() method doing (as docblock). I would like to understand the purpose of it, because I am deciding whether to use individual SVG Icons or the AXAIcon compnent of PL.

Please explain why are the icons imported individually (and then mapped to kebab case)? Does the build process require this? Why not to `import * as allIcons` and then process the `allIcons` object?

Original source code:

```
import { LitElement, svg, css, unsafeCSS } from 'lit-element';
/* eslint-disable import/no-extraneous-dependencies */
import {
  ArrowLeftSvg,
  ArrowRightSvg,
  CollapseSvg,
  DocumentSvg,
  DownloadSvg,
  EmailSvg,
  ExpandSvg,
  MobileSvg,
  PhoneSvg,
  PlusSvg,
  SearchSvg,
  UploadSvg,
  CloudUploadSvg,
  AxaLogoSvg,
  AxaLogoOpenSvg,
} from '@axa-ch/materials/icons';
import iconCSS from './index.scss';
import defineOnce from '../../../utils/define-once';

class AXAIcon extends LitElement {
  static get tagName() {
    return 'axa-icon';
  }

  static get styles() {
    return css`
      ${unsafeCSS(iconCSS)}
    `;
  }

  static get iconsMapping() {
    return {
      'arrow-left': ArrowLeftSvg,
      'arrow-right': ArrowRightSvg,
      collapse: CollapseSvg,
      document: DocumentSvg,
      download: DownloadSvg,
      email: EmailSvg,
      expand: ExpandSvg,
      mobile: MobileSvg,
      phone: PhoneSvg,
      plus: PlusSvg,
      search: SearchSvg,
      upload: UploadSvg,
      'cloud-upload': CloudUploadSvg,
      'axa-logo': AxaLogoSvg,
      'axa-logo-open': AxaLogoOpenSvg,
    };
  }

  static get properties() {
    return {
      icon: { type: String },
      size: { type: String, reflect: true },
    };
  }

  constructor() {
    super();
    this.icon = '';
  }

  firstUpdated() {
    const { icon } = this;

    if (/\.svg/.test(icon)) {
      const req = new XMLHttpRequest();
      req.open('GET', icon);
      req.onreadystatechange = () => {
        if (req.readyState === 4 && req.status === 200) {
          this.size = 'auto';
          this.shadowRoot.innerHTML = req.response;
        }
      };

      req.send();
    }
  }

  render() {
    return svg([AXAIcon.iconsMapping[this.icon] || '']);
  }
}

defineOnce(AXAIcon.tagName, AXAIcon);

export default AXAIcon;
```

**Comment by LucaMele** [comment]
@MarekLacoAXA Thank you. We will discuss it. Main reason for not importing all is bundle size but as you said it does not allow to have automatically all icons. We kept this component for the "most important and mostly used" icons. But we adapt our design to customer needs so we will discuss if we should include all inside the bundle.

`firstUpdated` is called once DOM is rendered and ONLY once. Here i think is an error and we should have that logic inside `updated`. This was a mistake we did often and need to fix it. This is important for dynamically changed properties. I added a best practice guide about this topic: https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices

**Comment by MarekLacoAXA** [comment]
I would like to understand WHY the network request is being done - as we have the SVG icons strings already inlined.

**Comment by LucaMele** [comment]
Ah ok thats ONLY for those icon names having `.svg` at the end. This was a feature request from a consumer so that he can load its own icons from its assets folder

**Comment by MarekLacoAXA** [comment]
Ok, I see, thanks.
