### ISSUE TITLE
Custom attributes are not working for React

### ISSUE THREAD

**Issue by jan-capiak** [axa-ch/patterns-library#1443]
Custom attributes (data-something) are not sent to the custom elements when using React.

Example:
Axa Dropdown component

===============
import * as React from 'react';
import createAXADropdownReact from '@axa-ch/dropdown/lib/index.react';

const AxaDropdownReact = createAXADropdownReact(React.createElement);

export type AXADropdownChangeEvent = Parameters<
  Required<React.ComponentProps<typeof AxaDropdownReact>>['onChange']>[0];

export type AxaDropdownValue = string | number | undefined;

export interface AxaDropdownItem {
  name: string;
  value?: AxaDropdownValue;
  selected?: boolean;
  disabled?: boolean;
}

export type AxaDropdownProps = {
  seleniumId: string;
} & React.ComponentProps<typeof AxaDropdownReact>;

export const AxaDropdown = ({
  seleniumId,
  ...otherProps
}: AxaDropdownProps) => {
  return <AxaDropdownReact data-seleniumid={seleniumId} {...otherProps} />;
};

===============
And no data-seleniumid in the DOM:

![image](https://user-images.githubusercontent.com/39954604/66826703-5808c200-ef4d-11e9-800d-934b523fea01.png)

Would it be possible to white-list all custom attributes to the elements, so we can pass them thrugh?

Thank you

**Comment by LucaMele** [comment]
related to: https://github.com/axa-ch/patterns-library/issues/1380

**Comment by LucaMele** [comment]
Requirements:

- Display name should be set automatically to support react test frameworks (https://github.com/axa-ch/patterns-library#testing-with-enzyme-or-similar-test-frameworks)
- All react properties that are not WC properties should be WC Root Node attributes.
- When possible, **the react wrapper should apply** attributes where types are compatible with HTML (string, "number", boolean). Reason: as close to the usage under native as possible. Using reflect would not meet NFA "as close as possible". Important to check: updates.

**Comment by 01231** [comment]
I close this one, because it is implemented.
