### ISSUE TITLE
Components out of order in storybook tree

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1444]
Icon and Popup aren't sorted the right way.
<img width="207" alt="Screenshot 2019-10-15 at 13 51 21" src="https://user-images.githubusercontent.com/38284563/66829227-37436b00-ef53-11e9-91d3-35145658309c.png">

**Comment by raphaellueckl** [comment]
Some links for this issue:

https://github.com/storybookjs/storybook/issues/5827

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storysort-option

**Comment by raphaellueckl** [comment]
With the information we have now, we can only cleanup the old sorting property that does officially not work anymore. I will open a PR for that.

**Comment by danyball** [comment]
I cant reproduce that bug - close issue.
