### ISSUE TITLE
Input Text, when counter text is not set it should not show anything

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1455]
When we have a maxlength and a maxlength text show the error message only without showing the decreasing number as it doesnt make sense to show the counter without the text

**Comment by danyball** [comment]
Alternatives:

- default text if no text is set, f.a. "29 Max.", because "Max." is valid for all our languages
- some kind of error

**Comment by danyball** [comment]
What happens if maxlength limit reached? Error message is visible suddenly. Not a good user exp?!

**Comment by danyball** [comment]
Nach kurzer Rücksprache mit Thomas vor 10 Tagen:

> wenn nicht beides angegeben wurde zeigen wir keines von beiden an. Und machen auch keine maxlength-Beschränkung. Das tut niemanden weh und bei Tests sollte sowas auffalen

**Comment by raphaellueckl** [comment]
Another option: Only show the limit when it get's within the 10% range of maxlength.

**Comment by danyball** [comment]
@raphaellueckl Our problem is that only the number is not really nice without a text - even in a 10% range
