### ISSUE TITLE
Dropdownarrow on disabled has different background color

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#1469]
https://patterns.axa.ch/?path=/story/molecules-dropdown--dropdown

Under knobs + disabled, the whole dropdown is gray but there is a white background around the down pointing arrow. (And it's still blue, not sure if there should not be a disabled gray color)

**Comment by danyball** [comment]
Yes, that should be gray too. The white background also should be gray. Thanks!

**Comment by kenaxa** [comment]
Hi All, 

Please find the correct specs to this element including all states (inactive etc.) under this link. If any questions, please write us on slack #ux-ui-support.

cheers, 
Ken

https://zpl.io/25AXknj
