### ISSUE TITLE
Datepicker - Languages are all over the place and weekdays are confusing (AEM Forms)

### ISSUE THREAD

**Issue by sebastian-buchmann** [axa-ch/patterns-library#1471]
![image](https://user-images.githubusercontent.com/54097531/67866656-95627780-fb29-11e9-98ac-182c064ad34a.png)

As you see in the image, the datepicker contains more than one language. 
The datepicker is used in AEM Forms, in a form which got created before the migration of axa.ch to patternslib V2. 
I found this issue on my local AEM instance, but with the latest develop version.

**Comment by markus-walther** [comment]
The component is working as intended, simply respecting the `es-ES` locale you must've set by accident.

Reproducible via https://patterns.axa.ch/?path=/story/molecules-datepicker--datepicker&knob-inputfield=&knob-locale=es-ES
