### ISSUE TITLE
Popup cannot be used with react (new component requested)

### ISSUE THREAD

**Issue by marek-polak** [axa-ch/patterns-library#1479]
Despite of info in readme (of patterns-library/src/components/20-molecules/popup/), this element can't be used with react - dist folder of current version published in npmjs (1.1.7) doesn't contain `'@axa-ch/popup/lib/index.react';` what results in error:
`Module not found: Error: Can't resolve '@axa-ch/popup/lib/index.react'`

**Comment by raphaellueckl** [comment]
This component should not majorly released, wtf. @LucaMele Do you know what happened here? AFAIK this was never ready to be used.

**Comment by LucaMele** [comment]
@raphaellueckl this component is released. Only the desktop version is not done yet but is an additional feature. The component itself instead should work and is finished. Apart of course as described in the bug

**Comment by LucaMele** [comment]
So, this popup is  released as a major version because of its internal use inside axa-input-text. However, it is _only_  used there.

Now, the README is rather incomplete and the component is also not a molecule. To be clear, it is not intended to be used on its own ATM.

**Comment by danyball** [comment]
Should we re-label this issue to a feature request "Popup can be used on desktop layouts" ?

**Comment by LucaMele** [comment]
@danyball the popup as marek needs it is completely different then the one we have, regardless of missing desktop feature. His is more a Modal like popup

**Comment by raphael-suter** [comment]
This is no longer needed.
