### ISSUE TITLE
Dropdown: different indices in native and enhanced mode

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1487]
Setup:
Usage of dropdown:
```
<axa-dropdown
    onchange="console.log(event.detail)"
defaultTitle="Hallo"
```

If we are clicking the first element of the box:
On Desktop the logged object has index 0.
On Mobile  the logged object has index 1.

Should:
We need the same index on desktop and mobile.

**Comment by markus-walther** [comment]
As discussed with @danyball, the difference only manifests itself when a `defaultTitle` is present.

And the desired reference is the index of 'mobile', i.e. the one coming from the native &lt;select&gt;.
