### ISSUE TITLE
Materials should be split in multiple modules

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1491]
Icons, breakpoints, colors, etc. all are within the materials package. Not sure if this is the best approach, because it could be that the breakpoints get updated and one team decides not to use the newest version because of that. But at the same time, new icons are released which those teams would need to use. The team then needs to refactor the whole layout, just because of an icon update.

Please add your opinion to this request.

**Comment by danyball** [comment]
We do not have a need right now. But theoretical this issue can appear. If all the apps should look like the same a team have to refactor the layout. This kind of constraint is good if we want to have apps that have same UI.

**Comment by danyball** [comment]
Ich glaube wir sprechen da mal auf deutsch drüber ;)

**Comment by LucaMele** [comment]
Ich denke es macht kein Sinn Matierials aufzuteilen weil es nur SCSS files sind, sprich die Anwendung des Anwender wird nicht kleiner wenn er kleinere Matierials hat. 

Materials ist das konzept dass alles was applikationsweit gilt ist da drinnen und ich denke den Use-Case den du Beschreibst @raphaellueckl  wird nie auftreten weil wir werden sehr sehr selten die SCSS sachen refactoren.

Für den Anwender ist es eben super einfach ein repo mit all so sachen zu haben.

Ich würde dieses Issue schliessen wenn einverstanden bist

**Comment by raphaellueckl** [comment]
Ok, wenn ihr meint.
