### ISSUE TITLE
eSales: Dropdown: support for numbers

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1498]
Check if that problem still exists.

Support for Number values is missingDropdown currently supports only string.
--

**Comment by MarekLacoAXA** [comment]
This is intended, made per purpose. It's not a bug, it is a feature.
Types are already updated accordingly:
https://github.com/axa-ch/patterns-library/pull/1468

**Comment by markus-walther** [comment]
Since the TypeScript version of the React wrapper is already adapted, we can close this issue.
