### ISSUE TITLE
AXALink expand/collapse icon too large

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1513]
Using v @axa-ch/link 1.3.27

**Desired look (from designer):**

![image](https://user-images.githubusercontent.com/43809369/68870737-a1d6fa80-06fb-11ea-8256-f6b541256a0f.png)

**Actual result**

![image](https://user-images.githubusercontent.com/43809369/68870777-b7e4bb00-06fb-11ea-949a-8d47b8e8d612.png)

**Code**
```
<Link key={expanded.toString()} onClick={toggleExpand} variant="icon" icon={expanded ? 'collapse' : 'expand'}>
```

(Unsure if related to #1115 )

**Comment by danyball** [comment]
Our components are following the global styleguide, designed by our designteam. I dont think that we add a different design. Our goal are components that look like same in all our apps. But i will check that.

**Comment by danyball** [comment]
I think your actual design is ok. We do not have so much space between icon and text. This is what it should look like: 
https://patterns.axa.ch/iframe.html?id=atoms-link--hyperlink&knob-link=https://axa.ch/en/private-customers.html&knob-Link%20text=Weniger%20Filter&knob-variant=icon&knob-icon=collapse&knob-Background%20color=white

**Comment by danyball** [comment]
The text style changes if you set variant="icon" or not. I think that should not happen. We will fix that if thats a bug.

**Comment by 01231** [comment]
the font changes from `Source Sans Pro` to `Source Sans Pro SemiBold` as I have seen.

**Comment by LucaMele** [comment]
@MarekLacoAXA Is this still relevant?

**Comment by raphaellueckl** [comment]
Maybe we can close it. I like the design @MarekLacoAXA received way more, but there are still inconsistencies between some of the designs and the pattern library.

This is how the global styleguide did it: https://design.axa.com/web-guidelines/buttons-and-links

This looks to me like our design is closer to this "spec".

**Comment by danyball** [comment]
Please re-open if needed.
