### ISSUE TITLE
AXALink react property change "icon" ignored

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1514]
Using v @axa-ch/link 1.3.27

Rendered icon of Link stays the same even when the property `icon` changes over time.

Code:
```
      <Link onClick={toggleExpand} variant="icon" icon={expanded ? 'collapse' : 'expand'}>
        {expanded
          ? t('todo', 'Less Filter')
          : t('todo', 'More Filter')
        }
      </Link>
```

**Comment by danyball** [comment]
Thanks, we will try to reproduce it.

**Comment by 01231** [comment]
Does this bug also appear in older versions of the link, or is this a new thing?

**Comment by MarekLacoAXA** [comment]
Using v @axa-ch/link 1.3.27

**Comment by raphaellueckl** [comment]
@MarekLacoAXA Fixed in v1.3.28

**Comment by MarekLacoAXA** [comment]
Sorry, @raphaellueckl , it doesn't work. Did you test in React without doing mount/unmount?

v:
```
"@axa-ch/link": "^1.3.28",
```

code:
```
      <Link onClick={toggleExpand} variant="icon" icon={expanded ? 'collapse' : 'expand'}>
        icon={expanded ? 'collapse' : 'expand'}
        ---
        {expanded
          ? t('todo', 'Less Filter')
          : t('todo', 'More Filter')
        }
      </Link>
```

Output:

![image](https://user-images.githubusercontent.com/43809369/69129664-25ec0200-0aaf-11ea-8c88-db967dc6819c.png)

![image](https://user-images.githubusercontent.com/43809369/69129721-46b45780-0aaf-11ea-9397-d6e9a6242743.png)

**Comment by raphaellueckl** [comment]
Hi @MarekLacoAXA 

I created an example project where it works: https://github.com/raphaellueckl/axa-link-icon-update-example

Does that help you?
With that approach, the direct render logic is outside the template.

I tried to create property bindings and to reflect the icon property (so it syncs with the html attribute) but nothing of that worked.
