### ISSUE TITLE
AXACheckbox does not support refId

### ISSUE THREAD

**Issue by gabac** [axa-ch/patterns-library#1528]
The `AXACheckbox` component does not support a `refId`

I would provide a PR if you agree that this is a bug and not a desired behaviour.

Potentially we end up with two `label` pointing to the same `input` field

**Comment by 01231** [comment]
I'll take care of it

**Comment by 01231** [comment]
I made a separat issue for the double label problem #1530

**Comment by gabac** [comment]
That was fast 🚀 Thanks!

**Comment by 01231** [comment]
You're welcome!🍻
(I'll release it when the second issue is done)
