### ISSUE TITLE
<axa-table-sortable> : custom sort functions

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1544]
Please support custom sort functions for particular columns, for those odd cases.

Perhaps something like `customSort: { colId: (a,b) => { /* custom sort logic for column colId */ }}`.

Thanks

**Comment by LucaMele** [comment]
Makes sense and we should support it IMHO

**Comment by FrancescoRovetto90** [comment]
would it be possible with this function, to sort a column with [plz city] in one value and sort after the city and not the plz?

**Comment by danyball** [comment]
If we support custom sorting you can sort your rows like you want. If you have "8280 Kreuzlingen" you can split that string and sort just with Cityname. We will approach you if we are developing the solution. Thanks.

**Comment by 01231** [comment]
@FrancescoRovetto90 
Update to Dany's statement:  
We will implement a custom sorting for dates and it will be accessible per attribute. Per se you can't implement your custom sorting algorithms and you won't be able to sort [plz city] if they are in the same column. To sort a column with [plz city], we highly suggest to us two different columns.

**Comment by francescoRovetto** [comment]
@NoahLiechti , thank you for your statement! your suggestion concerning the [plz city] is a good one. Thank you for implementing the date sort, we appreciate that very much.

**Comment by 01231** [comment]
Hey @cge as posted above we will not implement custom support functions as such. Have you got any odd cases except date?
