### ISSUE TITLE
Footer-small react - when rerender, new disclaimer-item content is ignored

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1549]
Using v **@axa-ch/footer-small 3.0.8**

Under react: when switching language, and thus providing `AXAFooterSmall` with updated attributes:
- `<span slot="copyright">` is correctly updated (see italian content in screenshot)
- `<a slot="disclaimer-item">` isn't updated -- displays previous content (see english content in screenshot)

**Screenshot**

![image](https://user-images.githubusercontent.com/43809369/70433080-08dc9a80-1a81-11ea-8c92-364b554bd7d0.png)

**Code**

```
<AXAFooterSmall
        onLanguageClick={handleLanguageClick}
        onDisclaimerClick={handleLegalClick}
        dynamic
      >
        {languageOptions.map(l => (
          <a
            key={l.name}
            slot="language-item"
            className={l.isActive ? 'm-footer-small__link--active' : undefined}
            href="#"
          >
            {l.name.toUpperCase()}
          </a>
        ))}
        {legals.map(l => (
          <a
            key={l.name}
            slot="disclaimer-item"
            href={l.url}
            target="_blank"
          >
            {l.name}
          </a>
        ))}
        <span slot="copyright">
          {copyrightText}
        </span>
      </AXAFooterSmall>
```

**Comment by raphaellueckl** [comment]
```
<ul class="m-footer-small__list">
                ${repeat(
                  this.querySelectorAll('[slot="disclaimer-item"]'),
                  (disclaimerItem, index) => html`
                    <li class="m-footer-small__list-item">
                      <a
                        href="${disclaimerItem.href}"
                        @click=${ev => this.handleDisclaimerClick(ev, index)}
                        >${disclaimerItem.textContent}</a
                      >
                    </li>
                  `
                )}
              </ul>
```

This is the code in the footer-small webcomponent, that struggles with this request. Rebuilding it takes time and might break other requirements. We need some more time to find a good way to handle this situation.

We loop over the children and manipulate them. I guess that's why litelement doesn't notice the change or does not know how to handle it.
