### ISSUE TITLE
axa-datepicker is on 100% width

### ISSUE THREAD

**Issue by MarcSchneider1** [axa-ch/patterns-library#1555]
datepicker is always on 100% width. If i remove the attribute width=auto, the problem is resolved. But it's not possible for me to remove or overwrite the attribute permanently

![datepicker_bug](https://user-images.githubusercontent.com/38786289/70694059-09fb0b00-1cbf-11ea-9d32-eeda75dbf81c.PNG)

**Comment by LucaMele** [comment]
@MarcSchneider1 Width auto is always relative to the parent. Do you have floats on `<div class="col-75">`? If yes, do you have a clearfix? If not, that could be the problem.

@danyball will get in contact wit you.

**Comment by MarcSchneider1** [comment]
@LucaMele No, i don't have any floats in `<div class="col75">`

edit: The width of `class="col75"` is 75% tho. Does that mean the datepicker-width adapts to that and i need do create another wrapper?

**Comment by LucaMele** [comment]
@MarcSchneider1 i would say is a bug that our datepicker does not stretch to with 75%, but yes, `width=auto` is always relative to parent where it fills its with.

**Comment by LucaMele** [comment]
related to #1110

**Comment by 01231** [comment]
<img width="1075" alt="Screenshot 2019-12-12 at 11 38 58" src="https://user-images.githubusercontent.com/38284563/70710726-1f346180-1ce0-11ea-819c-49b7ec21e66e.png">

To my findings: The datepicker input adjusts its size when a width is set, but the container still uses 100% of its possible width.

**Comment by danyball** [comment]
I will check that...

Related to #1110 we need:
- possibility to strech to 100%
- and width should be parents width in "auto" mode
