### ISSUE TITLE
Footer is broken (doesn render anything) under react with version 4.0.1

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1568]
<img width="1440" alt="Screenshot 2019-12-17 at 16 28 47" src="https://user-images.githubusercontent.com/275235/71009455-87bd7d00-20ea-11ea-9a08-271127e42442.png">

**Comment by raphaellueckl** [comment]
- I guess 4.0.1 is a typo, because only 3.0.1 exists
- I just tested it and it with that version and it works perfectly. The problem must be somewhere else.

**Comment by raphaellueckl** [comment]
EDIT: I noticed that you meant footer-small. I also tested that and it worked with 4.0.1.

**Comment by MarekLacoAXA** [comment]
I also tested recently and these versions work okay:
```
"@axa-ch/footer": "^3.0.1",
"@axa-ch/footer-small": "^4.0.1",
```

**Comment by LucaMele** [comment]
thanks guys, i forgot to read the change-log and therefore my footer didn't respect anymore the interface: https://github.com/axa-ch/patterns-library/blob/develop/src/components/20-molecules/footer-small/CHANGELOG.md

Thanks marek yes i meant footer small
