### ISSUE TITLE
Npm run serve not working under Windows

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#157]
Problem:
Checking out master, npm i, npm run build, npm run serve runs into an error with nodemon.
Quickfix:
Delete package-lock.json and rerun npm install.
Why:
The Problem is that npm-watch uses nodemon, the new Version is 1.14.10 but with package-lock we are on 1.12 and this is causing problems on a Windows machine. npm-watch will use always the latest Version of nodemon if it's allowed to do so.

**Comment by AndyOGo** [comment]
@MatthiasDyballa 
Thanks for your feedback.

May I ask you to include your used **node** and **npm** version too?
Please provide the output of:
````sh
node --version
npm --version
````

**Comment by LucaMele** [comment]
Thank you very much for your feedback

**Comment by MatthiasDyballa** [comment]
node 8.9.3
npm 5.5.1

**Comment by AndyOGo** [comment]
I guess this is the related nodemon issue https://github.com/remy/nodemon/issues/1109 
According to that issue, it's fixed over there an can be safely updated...

**Comment by MatthiasDyballa** [comment]
Update:
Restarted my git-bash and it crashed with nodemon 1.14.10 as well BUT a simple rerun of the same command worked.
![nodemon](https://user-images.githubusercontent.com/35330328/34824881-34dc37aa-f6c8-11e7-8dd8-c3f3d6b825b6.png)
