### ISSUE TITLE
Checkbox validation design is not equal anymore

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1572]
The checkbox doesn't look correct anymore in its invalid state:

Please also consider hover states.

IS:
<img width="458" alt="Screenshot 2019-12-18 at 14 34 56" src="https://user-images.githubusercontent.com/8248662/71090821-34a80080-21a4-11ea-9478-2f116ae90c10.png">

SHOULD:
<img width="467" alt="Screenshot 2019-12-18 at 14 35 15" src="https://user-images.githubusercontent.com/8248662/71090823-35409700-21a4-11ea-965b-972be5f68faf.png">

SHOULD:
<img width="467" alt="Screenshot 2019-12-18 at 14 36 46" src="https://user-images.githubusercontent.com/8248662/71090824-35409700-21a4-11ea-9973-59aa5732a9f4.png">

And I guess this is also not valid. This state should only exist in hover-state, but this would have to be checked against the design guidelines or with the designers:
<img width="246" alt="Screenshot 2019-12-18 at 14 54 24" src="https://user-images.githubusercontent.com/8248662/71091938-70dc6080-21a6-11ea-9f96-e6e9e837a486.png">

**Comment by NoahLiechti** [comment]
@raphaellueckl This is just how native links behave.
