### ISSUE TITLE
Maxlength Input Text & Textarea

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1576]
When using safari's autocomplete feature on a inout field or textarea with maxchars enabled and the auto-filled content is longer than maxchars, the input field keeps the whole text.

When maxlength is reached, also via form autocomplete, the length should always be cut down to its max allowance

**Comment by LucaMele** [comment]
Due DATE: Next AXA Release (approx mid Januar). This issue breaks some Backend APIs.

**Comment by danyball** [comment]
Have problems to reproduce the problem.

- safari mac, https://www.axa.ch/content/axa/de/formulare/kontaktformular/beratung-versicherungsnachweis.html - street and no. field
  - working as aspected
- iOS with Browserstack: autocomplete not active
