### ISSUE TITLE
Documentation of the Atom AXA Text is incomplete

### ISSUE THREAD

**Issue by laesse** [axa-ch/patterns-library#1587]
In der Doku vom AXA Text fehlt der Hinweis das man Varianten kombinieren kann. 
zum Beispiel:
`<AXATextReact variant={"bold size-3"}>...` 
währe toll wenn man die Doku erweitern könnte

Chatverlauf mit Luca Mele:

Lars Volkheimer 9:39 AM
hey luca ich ha e luge i de doku vom axatext gfunde mer cha ja au variant="bold size-3" age zum bispiel.
Luca Mele:speech_balloon: 9:40 AM
Meinst du dass es möglich ist 2  varianten zu kombinieren? (edited) 
Lars Volkheimer 9:41 AM
ja im code sind die varianten mit include abgefragt und es funktioiniert auch
ich habs ausprobiert
Luca Mele:speech_balloon: 9:41 AM
sehr gut. Willst ein github issue machen? das sollte nicht sein :slightly_smiling_face:
danke dir vielmals
Lars Volkheimer 9:42 AM
ja kann ich machen

**Comment by raphaellueckl** [comment]
Hi @laesse 

Thanks! :)
Although that our api is kind of "non-restrictive", we agreed today in the daily that we will fix that by making the variants mutually exclusive. It was never idea to use `variant` in a plural sense.

Keep in mind that you should always do what the documentation tells. Our internals should be blackboxes. Thank you for bringing that up and share this finding with us!
