### ISSUE TITLE
npm run new displays not all chars under windows

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#159]
![npm_run_new](https://user-images.githubusercontent.com/35330328/34824106-0cf606ce-f6c5-11e7-9cb9-8bbe9c996131.png)

Not anything critical but it is a bit confusing when you need to choose what to create. Before I hit enter and got the new selection with 1, 2, 3 I thought the character behind ATOM and co would stand for the choice.

**Comment by AndyOGo** [comment]
That's a know limitation.
Not all shells (windows hasn't a proper one...) feature colouring and unicode entities.
So I think the easiest solution would be to resort to shell-feature-detecting libraries like [chalk](https://github.com/chalk/chalk) for colouring.

**Comment by LucaMele** [comment]
Thank you guys. We will look into it and evaluate the usage of chalk

**Comment by AndyOGo** [comment]
And [log-symbols](https://www.npmjs.com/package/log-symbols) for unicode codepoints...

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
