### ISSUE TITLE
npm i generates a change at hero-banner package-lock

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1590]
Reproducer:

- run `npx lerna clean && rm -rf node_modules && npm install && npm run test && npx lerna version && npx lerna publish from-package`

- the step `lerna version` will fail, because there are uncommited changes: the package-lock of hero-banner

- if you commit this change lerna version will release `hero-banner` because of a change in package-lock. A Workaround for that unneeded release is to run `npx lerna version --ignore-changes '**/package-lock.json'`

**Comment by raphaellueckl** [comment]
I fixed it by updating the hero banner to the newest version and now it won't change until it gets another update. If you still see the hero banner in you branch, you should rebase with develop.

We should have a process, like an `npm i` after the publishing to also include committing of all package-lock files.
