### ISSUE TITLE
Datepicker width issue in internet explorer with react

### ISSUE THREAD

**Issue by MarcSchneider1** [axa-ch/patterns-library#1601]
If datepicker is opened, the width changes so the window covers the whole screen.

Bug was explained in detail with @NoahLiechti

**Comment by 01231** [comment]
"Should" situation in chrome
<img width="916" alt="should" src="https://user-images.githubusercontent.com/38284563/72246803-d976fb80-35f3-11ea-8184-564f1b838f49.PNG">
"Is" situation in IE
<img width="917" alt="is" src="https://user-images.githubusercontent.com/38284563/72246804-d976fb80-35f3-11ea-899b-1f549da49026.PNG">
Both have a `width` of `400px`

**Comment by 01231** [comment]
![Screenshot 2020-01-13 at 13 04 21](https://user-images.githubusercontent.com/38284563/72254753-4646c180-3605-11ea-84a2-68a93b3005e1.png)

In addition the datepicker-wrapper needs the full width even when the input field has a fix width in react.
