### ISSUE TITLE
AXA Input Text - renders 'undefined' placeholder (react)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1602]
Version: 3.0.6

In react: Whereas the AXAInputText correctly handles undefined `label` and `error`, it fails on `placeholder` because it renders "undefined" instead of nothing.

See example: nothing as label, nothing as error, but: "undefined" instead of nothing as placeholder:

```
    <Input
      {...props.input as any}
      type={props.type}
      placeholder={undefined}
      label={undefined}
      invalid={true}
      error={undefined}
    />
```

![image](https://user-images.githubusercontent.com/43809369/72247713-c9601b80-35f5-11ea-99de-5e417c934c5b.png)

**Comment by danyball** [comment]
Thanks Marek. Found that bug and fixed it. Will release it later.

**Comment by danyball** [comment]
Successfully published:
 - @axa-ch/input-text@3.0.7
