### ISSUE TITLE
Datepicker: react datepicker throws error when onBlur udefined

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1613]
v 5.0.1

when passing `undefined` to `onBlur`, error happens:

![image](https://user-images.githubusercontent.com/43809369/72417529-60a1ac00-3779-11ea-8edd-96fb04ce7f36.png)

![image](https://user-images.githubusercontent.com/43809369/72417559-6f885e80-3779-11ea-8c04-fde91d76d6a1.png)

![image](https://user-images.githubusercontent.com/43809369/72417636-9777c200-3779-11ea-86de-bd733fc32f8a.png)

![image](https://user-images.githubusercontent.com/43809369/72417660-9fcffd00-3779-11ea-87e7-0af4c736baa7.png)

**Comment by markus-walther** [comment]
From README.md: The *function-valued* attributes `onFocus, onBlur` can be used as callback props for React and other frameworks.

Why do you expect that violations of the documented component spec should yield useful results?

**Comment by MarekLacoAXA** [comment]
Sometimes a property value is not hardcoded, but is evaluated in an expression. That expression might result in "no value" which is expressed in javascript with `undefined` type.

I would expect a react component to behave like a javascript function.

*In JavaScript, function parameters default to undefined.*
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by MarekLacoAXA** [comment]
Rather then a Datepicker-specific problem, I think, this might be a general issue (programatically or mentally) because same behavior is observed on several react components. See:
https://github.com/axa-ch/patterns-library/issues/1614

Maybe, in the react-wrapper, you could just strip each properties that have `undefined` value, so that PL components itself don't have to handle `undefined` gracefully on them self.

From my experience it is common in React world to pass down `undefined` value and expect that behavior of component is same as if none value would be passed:
this is because in React properties come to component in one object called `props`. So each property of `props` that does not exist is `undefined` on the end. So technically all unset properties are undefined for react components.

**Comment by MarekLacoAXA** [comment]
*Sometimes a property value is not hardcoded, but is evaluated in an expression.*

Here is an example (from a different component), see the `onClick` prop:

![image](https://user-images.githubusercontent.com/43809369/72727903-5ffb8200-3b8c-11ea-9078-0cb1db574de2.png)

**Comment by markus-walther** [comment]
As far as I can see, nothing from the above precludes simply pushing expression evaluation into React event handlers themselves.

E.g. `const onValueChange = ({disabled,value}) => event => { if (disabled) return; .... }`

together with ` <FeatureItem ... onClick={onValueChange(opt)}... />`.

This keeps event handlers constant, avoids unnecessary anonymous function creation and unmotivated rerendering.
