### ISSUE TITLE
Checkbox not rerendering child label

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1615]
Version: "@axa-ch/checkbox": "^2.1.1"

Axa checkbox does not rerender child node when child is changed.
Initial render is correct but subsequent changes are not rendered correctly.
This bug only happens when label is provided as child node, behavior is correct if label is passed as prop.

**Reproduction link:**
[https://codesandbox.io/s/eloquent-cdn-ebhnq](https://codesandbox.io/s/eloquent-cdn-ebhnq)

**Buggy behavior:**
Test label as child
- label shows AAAAAA (initial)
- label value is changed to BBBBBB
-  label shows AAAAAA

**Expected behavior:**
Test label as child
- label shows AAAAAA (initial)
- label value is changed to BBBBBB
-  label shows BBBBBB

**Comment by LucaMele** [comment]
Hello @salle18 , I'm on it. Thank you
