### ISSUE TITLE
React Event Typescript types are not exported for AxaDropdown and AxaRadio

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1616]
In AxaRadio index.react.d.ts is only AXARadioProps exported, but the AXARadioChangeEvent and Item are not making this more difficult to integrate into React with Typescript, Same goes for AxaDropdown.

```javascript
type Item = {
name: string;
value?: string;
checked?: boolean;
disabled?: boolean;
};

type AXARadioChangeEvent = {
target: Item;
};

export interface AXARadioProps {
```

**Comment by MarekLacoAXA** [comment]
I think you could export the needed types and then import them like this:
```
import { AXADropdownProps, default as createAXADropdown } from '@axa-ch/dropdown/lib/index.react';
```

To get the types now, @pavol-marko you can extract them from your AXADropdown component like this:
```
type AXADropdownChangeEvent = Parameters<Required<React.ComponentProps<typeof AXADropdown>>['onChange']>[0];
```

**Comment by raphaellueckl** [comment]
Nice workaround marek :D

I told Pavol that we will address this issue, because it doesn't make sense to not export them imho.
