### ISSUE TITLE
axa-text do not show text in storybook

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1619]
Reproducer:

Use axa-text in story.js this way:

`<axa-text>${color.name}</axa-text>`

-->do not render any string.

`<axa-text>Hallo Welt</axa-text>` works correctly.

See `src/components/00-materials/styles/story.js` for example.

**Comment by markus-walther** [comment]
The crux of the issue is that component consumers have a reasonable expectation that dynamic updates of <axa-text> children should just work. This  needs to be fixed.
