### ISSUE TITLE
Datepicker selects wrong date (mobile view)

### ISSUE THREAD

**Issue by quattromic** [axa-ch/patterns-library#1634]
Datepicker on Mobile (e.g. Safari on iPhone 7) shows the following oddities:
- The line with weekdays (Mo - So) starts with 'So' (as opposed to desktop, where it starts with 'Mo').
- 30.09.1980 was a Tuesday (Di). On mobile, it is shown as Monday (Mo).
- If date is selected on mobile, e.g. 30.09.1980, the set date is one day off (29.09.1980). 
- Date selected on desktop is correct (30.09.1980).

![2020-01-24_111805](https://user-images.githubusercontent.com/76531/73061786-3f3c7080-3e9b-11ea-8038-b31c53fb7281.png)

**Comment by LucaMele** [comment]
@quattromic 

Quick analysis:

Seems that on mobile you have used a different `locale`. The datepicker adaptat its format to the users locale. HINT: German on the right, English on the left.

Seems that is NOT a Desktop/Mobile issue, just a locale issue (date months are not correctly placed) and the calculation of the date at the end seems to be off due to not correct placement of the day cells

**Comment by LucaMele** [comment]
Also, _If date is selected on mobile, e.g. 30.09.1980, the set date is one day off (29.09.1980)_. -> if locale is `en`, you have to use english date format : `MM/DD/YYYY`. This can be the reason here

**Comment by LucaMele** [comment]
If no locale is set, the datepicker takes the browsers default locale

**Comment by quattromic** [comment]
Unfortunately, the problem is still reproducible.
rsv-pod 3.59.7

**Comment by markus-walther** [comment]
@quattromic: Please contact us on the patterns-lib-devs Slack channel of AXA Switzerland to get more information.

**Comment by chiquan-hong** [comment]
We still face this problem on our iPhones.
I figured out additional information on this bug. 

**This bug occurs in the following combination:**
1. the year has to be <= 1980
2. and the month has to be >= March

I hope it help you guys to find the reason for that bug.

**Comment by markus-walther** [comment]
@chiquan-hong We would like to have a minimal reproduction of the problem in isolation, testable at a public URL, using axa-datepicker version 6.0.1 or later. Please state the phone model, the iOS version, and the browser used.

**Comment by chiquan-hong** [comment]
hi markus,

public URL: https://axa-ch.github.io/pod-rsv/?path=/story/common-axa-datepicker--esalescomponents
ios Version: 13.3.1
device: iPhone 8
Browser: Safari and Chrome
we are using the newest version 6.0.2 of the datepicker.

**Comment by markus-walther** [comment]
I can confirm there is a bug. However, it is *not* restricted to mobile, contrary to what this ticket suggests. Rather, *all browsers based on Safari* are affected, including latest desktop Safari on latest MacOS (Catalina). 

From https://github.com/moment/moment/issues/4469#issuecomment-584896868 : 

> "This is an ongoing problem with dates and Safari both on desktop and on mobile. Unfortunately all browsers on iOS use Safari as an underlying platform, so they're all broken because Safari is."
