### ISSUE TITLE
Welcome page is always shown

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1635]
**IS**: Welcome page is always shown when you go to storybook
**SHOULD**: Welcome page is only shown when root link is shown. If a user copy past a link that refers to a other component, storybook must show story where the link is referring to

<img width="1079" alt="Screenshot 2020-01-24 at 12 50 23" src="https://user-images.githubusercontent.com/275235/73067338-ba585380-3ea8-11ea-9113-b257a6185f2b.png">
<img width="756" alt="Screenshot 2020-01-24 at 12 51 54" src="https://user-images.githubusercontent.com/275235/73067349-bf1d0780-3ea8-11ea-9596-92bd8bca459f.png">

**Comment by danyball** [comment]
The URL is not valid anymore. Because of grouping our stories in "Components" and "others", the URLs changed to:
https://patterns.axa.ch/?path=/story/components-organisms-container--container-default

**Comment by LucaMele** [comment]
Url was old.
