### ISSUE TITLE
Datepicker renders empty error block taking up vertical space

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1642]
version 5.0.4

Recently Datepicker begun to display the `div.m-datepicker__error` (when invalid=true) even when `invaliddatetext` is empty `string` or `undefined`. 
This breaks our design.

I would like the previous behavior: the error div would not be rendered when empty  `invaliddatetext` gets passed.

Thanks!

![image](https://user-images.githubusercontent.com/43809369/73350093-b2275c00-428c-11ea-9eb0-94c2c0215d04.png)

![image](https://user-images.githubusercontent.com/43809369/73350208-e69b1800-428c-11ea-8e61-0a574c07329b.png)

**Comment by markus-walther** [comment]
Thanks for the detailled bug report! We'll investigate and report back here.
