### ISSUE TITLE
Datepicker never rerenders on dropdown "month"

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1648]
![Screen Recording 2020-02-03 at 12 58 24](https://user-images.githubusercontent.com/38284563/73652372-1aa87b80-4687-11ea-8761-af16ff14af37.gif)

**Comment by danyball** [comment]
Bug only with native dropdown (size <md). Could be a Bug on `dropdown`. I am analysing...

**Comment by danyball** [comment]
The buggy dropdown has `isControlled` in his state. I think it depends on how we set the items. While init the dropdown, line 130 is setting `isControlled` to true. Thats wrong.
