### ISSUE TITLE
Dropdown - unfolded dropdown not visible

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#1661]
If u set attribute "maxHeight", the unfolded dropdown is not visible. We are using the newest Version 6.0.0. You can reproduce it in the Storybook of Patterns Library.
![image](https://user-images.githubusercontent.com/57704956/74653146-df7a7200-5187-11ea-9cd9-e1ffb16b395e.png)

**Comment by LucaMele** [comment]
Thank your very much for the reporting @chiquan-hong. We will start the analysis as soon as possible and get in touch afterwards.

**Comment by raphaellueckl** [comment]
@chiquan-hong When I reproduce it on storybook, it behaves as expexted. MaxHeight `5` means only 5 pixel height, which results in that mini-window that you are seeing. You can still scroll it though. The `maxHeight` attribute limits the list itself, not the dropdown.

**Comment by chiquan-hong** [comment]
Sorry that was my fault, i missunderstood something.

**Comment by LucaMele** [comment]
@chiquan-hong can we improve our documentation so that is clearer in future?

**Comment by chiquan-hong** [comment]
Hi Luca, in general the documentation is very good. May be at that point, you can mention, that the unit is in pixel, to make it more clearly.
Thanks for asking about improvement of the documentation...i can see u care very well for everything ;)
