### ISSUE TITLE
Travis keeps failing, we need to know why

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1662]
Even if tests passes on Azure and locally, we need to know why they keep failing on Travis since the last datepicker merges. Maybe different locale?

**Comment by LucaMele** [comment]
https://travis-ci.org/axa-ch/patterns-library/jobs/649564954

**Comment by danyball** [comment]
could be similar to #1611

**Comment by raphaellueckl** [comment]
@LucaMele Can we close this issue? We probably won't go back to travis and if any, use github actions I guess.
