### ISSUE TITLE
Group related components within DOM node

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#167]
Currently every single **atom**, **molecule** and **organism** is made visible or invisible by it's own, through adding/removing a visibility class called `.o-sg-section--visible`.

Instead I would rather group the related components into a single `<div>` and show/hide just that one to reduce number of need DOM ops.

![group-related-components-dom-ops](https://user-images.githubusercontent.com/914443/34868563-83cc820e-f784-11e7-9c9d-4da14cabef8c.gif)

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
