### ISSUE TITLE
Table: Maxheight only works in conjunction with innerscroll

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1670]
https://patterns.axa.ch/?path=/story/components-organisms-table--table

- In the knobs section, set a maxheight - Nothing happens
- Set also a value for innenrscroll - Innerscroll and maxheight visibly change the table as it should
- Remove only innerscroll - maxheight does not apply anymore

The maxheight property should work standalone.

**Comment by LucaMele** [comment]
i would also rename innerscoll to maxWidth. Cause both will implicitly enable "innerscoll"

**Comment by raphaellueckl** [comment]
This works as intended. Since the table is responsive, as long a no maxHeight is set.
