### ISSUE TITLE
Option to stretch Button to 100% width (due date 1.5.20)

### ISSUE THREAD

**Issue by TommyHoliday** [axa-ch/patterns-library#1686]
As already discussed with the design- and pattern library team, we would like to have the option to stretch a button to 100% width, especially on mobile. (but should also be possible on tablet and desktop)

possible solution as suggested by @LucaMele could be 3 booleans:

- stretch-on-mobile=true
- stretch-on-tablet=true
- stretch-on-desktop=true

<img width="292" alt="button-stretch" src="https://user-images.githubusercontent.com/1917941/76407436-a189fb80-638b-11ea-90b6-b7833b194ec6.png">
<img width="304" alt="button-normal" src="https://user-images.githubusercontent.com/1917941/76407440-a2bb2880-638b-11ea-828c-1743c8af1233.png">

**Comment by salle18** [comment]
I would propose single flag instead `block=true` and control the behavior from the app that is using the component

**Comment by danyball** [comment]
You just need Button = 100%? What about, for example, 80%? Should that be possible as @salle18 wrote?

**Comment by TommyHoliday** [comment]
flexible width would also be nice, but i think it's tricky because of multi language support? you would then potentially need to specify the width per language... i don't really think that's practicable. i also like the suggestion from @salle18

**Comment by TommyHoliday** [comment]
as discussed in slack already; the exact opposite behaviour should be possible for radio buttons. meaning, that on mobile there should be a possibility to choose flexible width. 
![flexible-width](https://user-images.githubusercontent.com/1917941/76619661-b0a7af80-652b-11ea-8a25-4a761054e842.png)
<img width="892" alt="100-width" src="https://user-images.githubusercontent.com/1917941/76619690-bef5cb80-652b-11ea-85de-227d0940b1c6.png">

**Comment by danyball** [comment]
Requirements:
1. possibility to stretch to 100% (desktop and mobile)
2. possibility to have fixed width to have buttons side by side (mobile)
3. possibility to let the width set by parent

**Comment by danyball** [comment]
> Requirements:
> 
> 1. possibility to stretch to 100% (desktop and mobile)
> 2. possibility to have fixed width to have buttons side by side (mobile)
> 3. possibility to let the width set by parent

Just talked to @salle18 - the only requirement is: "possibility to stretch `button` component to 100% width". So i just solve number 1 from the list above.

@TommyHoliday Please create own issues if you have other improvements that are similar to this one. thanks.
