### ISSUE TITLE
Add inputmode attribute to input text  (due date 1.5.20)

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1689]
Having inputmode="numeric" on the filed is useful for mobile users when we want to display numeric keyboard instead of the regular one.

Fields like zipCode and CHF amount comes to mind for our premium generator.

https://css-tricks.com/finger-friendly-numerical-inputs-with-inputmode/

**Comment by salle18** [comment]
With this in mind we should consider supporting pattern attribute as well

**Comment by danyball** [comment]
Thanks for your request. That makes sense. Lets check if we can build a solution for all the browsers.

@salle18 You just need that for mobile devices with chrome?

**Comment by salle18** [comment]
We need this for mobile devices in general, with focus on android/chrome and ios/safari
