### ISSUE TITLE
Radio buttons mobile (due date 1.5.20)

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1690]
It should be possible to display radio buttons on mobile next to each other as stated in the original comment by @TommyHoliday :
as discussed in slack already; the exact opposite behaviour should be possible for radio buttons. meaning, that on mobile there should be a possibility to choose flexible width. 
![flexible-width](https://user-images.githubusercontent.com/1917941/76619661-b0a7af80-652b-11ea-8a25-4a761054e842.png)
<img width="892" alt="100-width" src="https://user-images.githubusercontent.com/1917941/76619690-bef5cb80-652b-11ea-85de-227d0940b1c6.png">

_Originally posted by @TommyHoliday in https://github.com/axa-ch/patterns-library/issues/1686#issuecomment-598689961_

**Comment by markus-walther** [comment]
It seems all that is required is an option to switch off the responsive behaviour of `<axa-fieldset horizontal>`. Then the existing attributes for `<axa-radio>` are strong enough to facilitate the requested behaviour.
