### ISSUE TITLE
Datepicker has unclean border on iOS

### ISSUE THREAD

**Issue by bopplu** [axa-ch/patterns-library#1694]
Border is extending to far in and stops before the Datepicker button:

![image](https://user-images.githubusercontent.com/2726263/76955537-ae21cd00-6912-11ea-9415-6bf37fd5a3d7.png)

Issue cannot be reproduced on Android or desktop compatibility mode

**Comment by danyball** [comment]
Thanks for reporting - i can reproduce that on ios --> we will fix that

**Comment by danyball** [comment]
This is the bug: https://stackoverflow.com/questions/23211656/remove-ios-input-shadow

**Comment by danyball** [comment]
Successfully published:
 - @axa-ch/datepicker@6.0.4
