### ISSUE TITLE
Dropdown: Make the dropdown accessible

### ISSUE THREAD

**Issue by TheDadi** [axa-ch/patterns-library#17]

**Comment by AndyOGo** [comment]
Currently the dropdown is just a visual implementation, for most it's animation feature.

Maybe it would be better to split this into a `expander` / `collapser` molecule

**Comment by LucaMele** [comment]
i think is fixed.. feel free to reopen in case is not

**Comment by AndyOGo** [comment]
This expander/collapser is still not abstracted
