### ISSUE TITLE
Dist build/release does not commit updated docs

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#170]
If I run `npm run release` and I have added a new component or delete an existing one, the `docs` folder isn't commited respectivly, concretly:

- [x] new components don't being added
- [ ] old/deleted components aren't removed

**Comment by LucaMele** [comment]
The issue here is github caching. I notecied that as well. You need to open it in anoymous or delete cache

**Comment by LucaMele** [comment]
unless you mean it hasnt been copied in the docs folder during the build

**Comment by AndyOGo** [comment]
yes no copy to `./docs` after build during `npm run release`

**Comment by AndyOGo** [comment]
Still ne to check deletion
