### ISSUE TITLE
Radio Buttons are not accepting data-* attributes

### ISSUE THREAD

**Issue by bopplu** [axa-ch/patterns-library#1701]
Setting a data attribute on radio buttons does not work at all, they seem to be ignored entirely.

**Comment by raphaellueckl** [comment]
Hi @bopplu 

Thanks. Can you give an example, where it doesn't work?

For me, the following works:

```
<axa-radio
    data-hello-mister="hi"
    name="insurance"
    label="yes, take out insurance"
    value="1"
    checked
  ></axa-radio>
```

Result:
<img width="770" alt="Screenshot 2020-03-24 at 14 53 56" src="https://user-images.githubusercontent.com/8248662/77433452-add87480-6ddf-11ea-83b7-9bbc465f1409.png">

**Comment by bopplu** [comment]
Turns out our Version of the Radio button was to far back. Closing this.
