### ISSUE TITLE
Checkbox Fehlervalidierung: Nach korrektur der Fehlervalidierung, bleibt Label weiterhin rot

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#1706]
Hallo Patterns Library Team,

wir haben hier folgenden Bug:
Wir haben ein Formular mit einem Checkbox, in der man seine Zustimmung, durch setzen des Häckchens etwas zustimmen kann.
Wenn der Benutzer, dem nicht zustimmt aber fortfahren will, wird das Label rot eingefärbt. Das verhält sich soweit auch korrekt. Nun bleibt aber das rote Label, obwohl der Benutzer nun zugestimmt hat. Das war vorher nicht so, das hat vorher immer gut funktioniert.
Ich muss auch erwähnen, das dieses Problem Lokal nicht auftritt, sondern nur auf den Pod, sprich DEV und ACC.

Anbei noch die Screenshots und der Link,  in der ihr die Applikation ausführen könnt.

![image](https://user-images.githubusercontent.com/57704956/77750483-2760a480-7024-11ea-98a8-347bc05dd9bf.png)

Obwohl zugestimmt, ist Label immer noch rot:
![image](https://user-images.githubusercontent.com/57704956/77750497-2fb8df80-7024-11ea-98e9-abaa2354d537.png)

Link zur Applikation:
https://www.acc.axa.ch/de/test-pods/pod-rsv.html/#/start

Danke für eure Hilfe.

Gruss

Quan

**Comment by danyball** [comment]
Ihr setzt den Errorstate der Checkbox korrekt über das Attribut "error". Allerdings sehe ich keinen Code der dieses Attribut wieder entfernt?! Ihr nutzt den Callback "onChange" nicht, daher nehme ich an ein EventHandler darauf scheint nicht richtig zu funktionieren. Dafür bräuchte ich aber den Code davon.

**Comment by pavol-marko** [comment]
@danyball 
Da hast du leider nicht recht>
```
{this.state.bvbLoaded && (
                <LegalCheckbox
                  bvbList={this.props.offerStateContainer.state.bvbData}
                  isApplication={screenMode === OfferActionType.PURCHASE_OFFER}
                  avbLink={this.props.offerStateContainer.state.avblink}
                  checked={this.state.legalCheckboxChecked}
                  onChange={this.checkboxChangeHandler}
                  legalError={this.getLegalError()}
                  isLichtenstein={this.state.isCountryLI}
                />
              )}
```

und 
```

private getLegalError = (): any | undefined => {
    return !this.state.legalCheckboxChecked &&
      this.state.lastScreenSubmitTime != null
      ? tr(this.props.intl, 'FM_FELD_LEER')
      : undefined;
  };

  private checkboxChangeHandler = (checked: boolean) => {
    this.setState({ legalCheckboxChecked: checked });
  };
```

**Comment by pavol-marko** [comment]
Der Fehler kann umgegangen werden wenn anstatt Undefined ein leeres String {''} benutzt ist.
Der Fehler ist aus meine Sicht immer noch da denn am anfang wenn ich error = undefined mache ist der Checkbox nicht rot, danach schicke ich ein string im error, z.b. error = 'SOME ERROR', 
und danach gehe ich züruck zu Stand der am anfang war: error=undefined. Die anzeige des Errors bleibt aber offen.

**Comment by danyball** [comment]
Thats a minor bug at the react wrapper. 

SHOULD:
If you set error directly `document.getElementsByName("my-checkbox")[0].error = undefined` the error string is gone. --> This should happen with react, too.

IS:
If you set `undefined` in React to our component: Nothing happens, error state do not change. 
@pavol-marko We can not reproduce it in our React Example here: https://patterns.axa.ch/?path=/story/components-atoms-checkbox-react-demo--checkbox-default-with-label - try setting error with `document.getElementsByTagName("axa-checkbox")[0].error = undefined` -> it works?!

**Comment by markus-walther** [comment]
This is not a bug in the React wrapper. This behaviour is by design, and motivated by a request from another React user who argued convincingly that `undefined` as a property value should have no effect (#1613).

Attempting to set `undefined` for a property documented as of type String is simply a type violation, and as such unsupported. Therefore, this is not a bug but expected behaviour. 

As mentioned above, use the empty string to clear an error condition in a type-conformant way.
