### ISSUE TITLE
Autogenerate Changelog

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1712]
Issue:
Sometimes we forget to update changelog.md or have wrong version number there.

Solution:
Automated generated Changelogs. 

Details:
We have to do commits following some rules (f.a. `fix: upper-case message`) to get this:

![image](https://user-images.githubusercontent.com/7448004/79456161-4da7ad80-7fee-11ea-80b8-ed7e4f1ad003.png)

More:
https://michaljanaszek.com/blog/lerna-conventional-commits

**Comment by danyball** [comment]
remove this after testing:     "release_temp": "npm whoami && npx lerna clean && rm -rf node_modules && npm install && npm run test && lerna version && lerna publish from-package --conventional-commits",

**Comment by raphael-suter** [comment]
We don't see the need to implement this.
