### ISSUE TITLE
File-Upload overview thumbnail aspect-ratio is not the same

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#1714]
If I select image files, the thumbnails don't have the same aspect ratio as the original image.
https://patterns.axa.ch/?path=/story/components-molecules-file-upload-demos--feature-file-upload-in-a-form

**Test square image:**
https://commons.wikimedia.org/wiki/File:Windows_live_square.JPG (public domain)

<img width="810" alt="Screenshot 2020-04-06 at 10 05 16" src="https://user-images.githubusercontent.com/914443/78536748-a016ec00-77ee-11ea-9bfe-cbdfe892f577.png">

**Test portrait image:**

https://www.behance.net/gallery/32649225/Iron-Man-Illustrator-Portrait (copyrighted)

<img width="776" alt="Screenshot 2020-04-06 at 11 26 15" src="https://user-images.githubusercontent.com/914443/78543818-80d18c00-77f9-11ea-92cf-01c96565a8ca.png">

**Comment by 01231** [comment]
Hey Andy, thanks for submitting.
This is on purpose, due to the fact, that uploaded images doesn't have to follow specific aspect ratios.
All thumbnails must have an aspect ratio of 3x2 (120px x 80px). So if you upload a 1x1 picture there is no way to display it in the aspect ratio of the original image without distortion.

**Comment by AndyOGo** [comment]
Hey Noah,

Thanks for your answer.
Okay. Indeed uploaded images will have any aspect ratio.

I would suppose to crop/cover the image instead of stretching it, this would keep the relative aspect ratio.
CSS [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) could help or a JS based approach would also work.

I have added a second example with a portrait image of iron man - please see above.

**Comment by 01231** [comment]
When the image gets cropped, the relevant image section can't be provided. Therefore we stretch the image. So all relevant parts of the image are visible.

**Comment by AndyOGo** [comment]
Thanks for your quick answer.
I got it.
Object-fit `contain` would be an option too, without crop and without stretch.

**Comment by 01231** [comment]
Yes that's true. But then, there is a high chance that the thumbnails don't fill out the whole space of 120px x 80px. 
If it's ok for you I'll close this issue.  Or do you want a designer to re-review it?

**Comment by AndyOGo** [comment]
Hi Noah, thanks for your quick feedback.

Exactly, `contain` will not cover the full `120px` x `80px`.

Okay, I just checked the zeplin file. It does not clearly state how to deal with different aspect rations.
https://app.zeplin.io/project/5bed40045544f67ec5c16d69/screen/5ccc08f2c6b4b467850f0756

Yes please, may I ask you to review with a designer.

**Comment by LucaMele** [comment]
@AndyOGo Please be careful with Images under Copy Right. Remove them please

**Comment by AndyOGo** [comment]
Thank you for the hint @LucaMele

**Comment by 01231** [comment]
@AndyOGo I spoke with @TommyHoliday. The design is obsolete. There is a new design now. I close the issue, because this is not relevant anymore.
