### ISSUE TITLE
File-Upload max file size not considered for all file types

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#1715]
I have created large files of total `131.6MB` including images and pdfs.
The images show "File size exceeds maximum size" error, but not the pdfs.
I got large files from:
- https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf
- https://effigis.com/en/solutions/satellite-images/satellite-image-samples/

https://patterns.axa.ch/?path=/story/components-molecules-file-upload-demos--feature-file-upload-in-a-form

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/914443/78537533-ede02400-77ef-11ea-8077-0b5a23ee91fb.gif)

https://patterns.axa.ch/?path=/story/components-molecules-file-upload--file-upload

<img width="756" alt="Screenshot 2020-04-06 at 10 22 51" src="https://user-images.githubusercontent.com/914443/78538001-a1491880-77f0-11ea-8eee-b4db2f8cd616.png">

**Comment by markus-walther** [comment]
Thanks for the bug report!
