### ISSUE TITLE
Dropdown: overflowing texts

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1716]
Long text is overflowing, see screenshots:

![image](https://user-images.githubusercontent.com/43809369/78570803-be4c0e80-7825-11ea-9663-a61ea668e695.png)

This error can be solved on user side with this:
```
    // ensure that verylongwords get split into several lines rather then overflow the select box
    axa-dropdown {
      word-break: break-word;
    }
```

Unsure what can be done about this:

![image](https://user-images.githubusercontent.com/43809369/78570814-c2782c00-7825-11ea-86d3-072e0a61a061.png)

**Comment by danyball** [comment]
@MarekLacoAXA Sorry for the very late response! I cant reproduce that at

https://patterns.axa.ch/iframe.html?id=components-molecules-dropdown--dropdown (use f12 mobile view)

![image](https://user-images.githubusercontent.com/7448004/80686548-26121400-8ac9-11ea-947f-5999861df80e.png)

**Comment by MarekLacoAXA** [comment]
Current version (7.0.2) behaves like this:

"Native mode" for small screens -- as on your screenshot;

![image](https://user-images.githubusercontent.com/43809369/80717325-1a3e4600-8af9-11ea-944e-29a54c0b8dab.png)

"Enhanced mode" on larger screens:

![image](https://user-images.githubusercontent.com/43809369/80717373-288c6200-8af9-11ea-96e1-98f02e8f8e68.png)

**Comment by danyball** [comment]
Ah.. You are setting a width on the component. Now i can reproduce your 2 bugs. Will fix that.
