### ISSUE TITLE
IE: long running script error

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#172]
> SCRIPT438: Object doesn't support property or method 'call'
> File: webcomponents-lite.js, Line: 107, Column: 123

<img width="1438" alt="screen shot 2018-01-15 at 17 14 51" src="https://user-images.githubusercontent.com/914443/34951753-99125766-fa17-11e7-95c0-53b9193d265a.png">

<img width="1437" alt="screen shot 2018-01-15 at 17 18 50" src="https://user-images.githubusercontent.com/914443/34951958-537fdee8-fa18-11e7-8513-ceb1d312d01d.png">

<img width="1438" alt="screen shot 2018-01-15 at 17 19 35" src="https://user-images.githubusercontent.com/914443/34951959-53af171c-fa18-11e7-8559-2f9ea8332ce1.png">

**Comment by LucaMele** [comment]
will work on this a next

**Comment by LucaMele** [comment]
https://axa-ch.github.io/patterns-library = broken
https://axa-ch.github.io/patterns-library/#organism = OK

**Comment by LucaMele** [comment]
fixed
