### ISSUE TITLE
File Upload: Drag-and-drop flickering

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#1724]
If I drag files from the os over the dropzone, it's dragging state flickers.
Please see screen video below.

![File-Upload--rag-and-drop-flickering-Apr-15-2020 19-09-55](https://user-images.githubusercontent.com/914443/79367063-80e63000-7f4d-11ea-985b-296f348fe8b9.gif)

Used Browser details:
https://www.whatsmybrowser.org/b/KNLER

**Comment by danyball** [comment]
Thanks for reporting that bug. Can reproduce that.

**Comment by danyball** [comment]
We are setting css class`m-file-upload__dropzone_dragover` on every `@dragover` event. And this event is fired on every mouse move. So setting this class every "millisecond" the browser starts flickering.
