### ISSUE TITLE
Button with arrow is not displayed correctly

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1725]
When a customer uses our axa button, the arrow is shifted from the text. I disabled all CSS of the customer and it is still broken, therefore we have a bug on our side. We must be plug and play especially if there is no other CSS applied. A customer needs to go live asap therefore is high priority

<img width="227" alt="Screenshot 2020-04-16 at 10 59 04" src="https://user-images.githubusercontent.com/275235/79436800-a157ce00-7fd1-11ea-980c-c148700d9ad2.png">

**Comment by danyball** [comment]
"shifted from the text" - can you give more details?

**Comment by LucaMele** [comment]
The arrow is not aligned with the text but like 2px lower

**Comment by danyball** [comment]
Ok thanks. But such a minimal UX Bug cant be "blocking". I will fix that bug....

**Comment by danyball** [comment]
I think the problem is, that the arrow is not aligned correctly inside the svg:

![image](https://user-images.githubusercontent.com/7448004/79537579-d5d79280-8082-11ea-9d79-4fa82af8755b.png)

**Comment by LucaMele** [comment]
@danyball yes such a small little thing is blocking cause the app using it will refuse to go live with the plib if this error persists

**Comment by LucaMele** [comment]
@danyball dont remove blocking if I put it there, there is a reason

**Comment by danyball** [comment]
A minimal ux bug is blocking a golive? Lol - ok... never heard of that before. Will fix it anyway....

**Comment by LucaMele** [comment]
@danyball yeah it suprises me as well but it is how it is

**Comment by danyball** [comment]
Another bug there: border-bottom-color is different:

```
border-top-color: rgb(0, 0, 143);
    border-right-color: rgb(0, 0, 143);
    border-bottom-color: rgb(0, 0, 91);
    border-left-color: rgb(0, 0, 143);
```
