### ISSUE TITLE
Puppeteer Test for fileupload's drag'n'drop

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1730]
Because drag n drop tests in Testcafe are complicated, try to create a puppeteer test for this PR https://github.com/axa-ch/patterns-library/pull/1728

**Comment by markus-walther** [comment]
Puppeteer handles browser automation. However, the axa-file-upload element deals with dragging of *files*, which live outside of the browser in a finder/folder/file-browser abstraction of the windowing system. This would require automation on the level of the windowing system, which is something that Puppeteer cannot do.

**Comment by danyball** [comment]
> Puppeteer handles browser automation. However, the axa-file-upload element deals with dragging of _files_, which live outside of the browser in a finder/folder/file-browser abstraction of the windowing system. This would require automation on the level of the windowing system, which is something that Puppeteer cannot do.

Ok thats logic, thanks! What about to simulate these events?

**Comment by markus-walther** [comment]
I tried hard to make this work, but even after observing real events and issuing their synthetic counterparts in https://github.com/axa-ch/patterns-library/pull/1680/commits/c41694a29ef45248c57b3e950d9e25b2a1d44d5d, I could not make it work. For now, the conclusion is we can't simulate drag'n drop.
