### ISSUE TITLE
Update icons (and images) from Figma and add all materials icons

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1731]
At PR https://github.com/axa-ch/patterns-library/pull/1729 the icons (referenced by icon component) are updated from Figma. But they have internal bit more "margins". So they look a little bit smaller than the others.

TODO:
- Update all the icons from Figma. And update images as well makes sense.
- Message @sabine-schneider1990 if finished (#1915)

**Comment by 01231** [comment]
Some questions have arisen while working on this issue. 
- All icons already have the right size and viewBox. What exactly should be changed?
- What size/viewBox should the images have? Most of our images have `viewBox="0 0 96 96"` but some have not. Height and width vary on every image. While on Figma all images have a width and height of 24px and `viewBox="0 0 24 24"`.
- What is with the images that aren't on Figma? And there are a lot that are missing on Figma (about 75% are missing). If we say, we just update all images that are available on Figma, 2/3 of our images still have a completely a different size/viewBox...


So in my opinion there is not much to update...

**Comment by danyball** [comment]
> Some questions have arisen while working on this issue.
> 
> * All icons already have the right size and viewBox. What exactly should be changed?

Do they look exactly the same? The icons i have updated are all a bit different to the "old" ones.

> * What size/viewBox should the images have? Most of our images have `viewBox="0 0 96 96"` but some have not. Height and width vary on every image. While on Figma all images have a width and height of 24px and `viewBox="0 0 24 24"`.

> * What is with the images that aren't on Figma? And there are a lot that are missing on Figma (about 75% are missing). If we say, we just update all images that are available on Figma, 2/3 of our images still have a completely a different size/viewBox...

Hmm. dont know. I think images arent so important as icons. So... feel free to sync with Thomas. Maybay a third folder "figma images" could be a solution?!

> 
> So in my opinion there is not much to update...

**Comment by raphaellueckl** [comment]
@NoahLiechti @danyball Please close this issue if no longer relevant.

**Comment by raphaellueckl** [comment]
This issue will be split now, to ship smaller self-contained packages.
