### ISSUE TITLE
npm start makes the fans glow at mac

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1732]
If i run npm start and let it run for a while, the macbook fan is running very loud. If i stop that task, the fan goes down and is silent.

Whats wrong with that? webpack dev server?

**Comment by danyball** [comment]
Acticity Monitor says "220%" cpu usage of process "node" with 11 Threads. Node v. 10.16.3.

**Comment by danyball** [comment]
Same behaviour with LTE12.16.2

**Comment by danyball** [comment]
Same behaviour with `npm start` on mac terminal without intelliJ running.

**Comment by danyball** [comment]
![image](https://user-images.githubusercontent.com/7448004/79841605-f6238c00-83b7-11ea-9352-81b706ec13aa.png)

**Comment by danyball** [comment]
npm start without addons: same

**Comment by danyball** [comment]
without virusscanner > same

**Comment by danyball** [comment]
```
config.watchOptions = {
    poll: 1000,
    ignored: ["node_modules"]
  };
```
decreases cpu from about 270% to 150%. Fans seems to be quiet now.

**Comment by danyball** [comment]
More details here https://github.com/webpack/webpack-dev-server/issues/2140

**Comment by johanwannheden** [comment]
I had already solved this by installing `fsevents` on macOS, but the issue reappeared after upgrading from node version 13 to 14. The issues was fixed by `rm -rf node_modules && npm install`.

**Comment by danyball** [comment]
> I had already solved this by installing `fsevents` on macOS, but the issue reappeared after upgrading from node version 13 to 14. The issues was fixed by `rm -rf node_modules && npm install`.

Yes thanks i tried that, too. You fixed that by installing it `global`? Or at the project?

**Comment by johanwannheden** [comment]
Since only a few developers actually work on macOS, I added the dependency as follows:
```
"optionalDependencies": {
    "fsevents": "^2.1.2"
}
```
Hope that helps.
