### ISSUE TITLE
Update rollup dependency

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1733]
We need to catch up to not get stuck on old versions, which kind of is the case at the moment.

Someone should update rollup and all its plugins and take a lot of time to tests if everything still works.

**Comment by danyball** [comment]
`
"@rollup/plugin-commonjs": "^11.0.2", // v14
    "@rollup/plugin-node-resolve": "^7.1.1", //8.4
    "@rollup/plugin-replace": "^2.3.1", // keine neuen

"rollup-plugin-babel": "^4.3.2", @rollup/plugin-babel.
    "rollup-plugin-copy": "^2.0.1", https://github.com/vladshcherbin/rollup-plugin-copy#readme
    "rollup-plugin-sass",: "^1.1.0", // keine neueren
    "rollup-plugin-uglify": "^6.0.4", // keine neueren
`

**Comment by danyball** [comment]
Problem: Knobs Testimonial not working correctly. (show all inline)
