### ISSUE TITLE
Radio button/icon: DESIGN issue: support material icons

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1738]
**Radio button with icon**

This demo bellow looks as it should...

https://patterns.axa.ch/?path=/story/components-atoms-radio-demos--radio-button-icon

```jsx
const icon = `<svg xmlns="http://www.w3.org/2000/svg" width="60.2" height="34.74">
<defs/>
<g transform="translate(.1 .1)">
..... transform="translate(-8.473 -23.037)"/>
</g>
</svg>`;

<axa-radio
          button
          name="insurance"
          label="Option 1"
          .icon="${icon}"
        ></axa-radio>

```
... as you can see the icon is inlined.

**Output:**

![image](https://user-images.githubusercontent.com/43809369/79948248-c8038200-8473-11ea-91c4-f88fda3aaa98.png)

**With material icons used:**

![image](https://user-images.githubusercontent.com/43809369/79948285-dea9d900-8473-11ea-8121-9fd274fe1855.png)

I would like to keep the same design (icon size/margins) when using icon imported from materials:

```js
import car_svg from '@axa-ch/materials/images/car.svg.js';
```

Notice the difference in size/margins between the two screenshots above.

Discussed with Jonas on 21.4.2020.

Thanks!

**Comment by danyball** [comment]
Duplicate to #1731

**Comment by danyball** [comment]
@MarekLacoAXA You can not use materials icons for Radio buttons at the moment. Please have a look at the README: 

> The string-valued icon attribute receives a valid SVG icon with working dimensions 60×35 pixels.

A workaround could be that you import the materials icon, set width and height to the svg tag and then put that to radio button.

I will discuss that feature request at PL team and give u an answer if we implement a better solution.

**Comment by danyball** [comment]
We will change the implementation of radio buttons to the new standard:

![image](https://user-images.githubusercontent.com/7448004/80597975-f01d5300-8a28-11ea-901d-f0803508273d.png)

**Comment by MarekLacoAXA** [comment]
Thx!

**Comment by danyball** [comment]
Maybe it makes sense to fix this issue as well: https://github.com/axa-ch/patterns-library/issues/1731
