### ISSUE TITLE
Datepicker: "de-CH" locale enforcement for the date formatting

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1740]
Chromium/Chrome browser incorrectly formats date to "20/4/2020" format for "'it-CH'" locale.
This is not good. It would be better to use "20.4.2020" date format throughout the AXA website. 
(discusses with Jonas on 21.4.2020)

(unsure now if this should be the case also for "en-CH" locale ?)

Copy from slack channel:

>Luca Mele
> Datepicker uses the native INTL API in the Browser. I guess Chromium just didn't 
>bother making dd.mm.yyyy for it-CH . Neverthen less, feel free to make an issue and we will get in 
>contact with the Chromium Community and find out more.
>
>We can also think for de-CH enforcement for the date and use other locals for the month name. 
>But please make an issue if you desire a solution for it.
>
> https://stackoverflow.com/questions/44973627/intl-datetimeformat-produces-wrong-format

**Comment by danyball** [comment]
There is no right or wrong, the date format depends on many parts. Nice answer [here](https://stackoverflow.com/questions/52797070/intl-datetimeformat-with-format-options-doesnt-work-for-it-ch).

So we should implement a custom format for "it-CH" at the datepicker.

PS: https://momentjs.com/ outputs the "correct" format with "."
