### ISSUE TITLE
Datepicker (inputfield): minimal width question

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1741]
Datepicker's README.md correctly states that the minimal width is 197px:

>### width
>String-valued `width` allows to override the intrinsic dimensions of the datepicker. Default is `100%`.
>Note that there is a minimum of `260px` if you use it inline and `197px` if you use it as a inputfield.

![image](https://user-images.githubusercontent.com/43809369/79957296-a7422900-8481-11ea-94ad-4c2bc64a9015.png)

The reason for this minimal width is missing....
It is then tempting to wish a smaller width, so that space could be spared in situations like this:

![image](https://user-images.githubusercontent.com/43809369/79957397-cd67c900-8481-11ea-88ca-dbbdb3ae9f6a.png)

Please advice, thanks! 

(came up in discussion with Jonas on 21.4.2020)

**Comment by raphaellueckl** [comment]
<img width="382" alt="Screenshot 2020-04-22 at 12 12 55" src="https://user-images.githubusercontent.com/8248662/79970068-ad8cd100-8492-11ea-92a3-4e64e0dbf209.png">

I think, the reason for this is, that the placeholder text does gets fully displayed. But @markus-walther would be the person to answer that.

**Comment by danyball** [comment]
We will remove the `min-width`. The designers dont see any necessity.
