### ISSUE TITLE
axa-link 'external' property doesn't seem to work anymore

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1746]
Feedback from @MKaHead 

Reproduce: https://patterns.axa.ch/iframe.html?id=components-atoms-link--link&knob-link=https://www.axa.ch/en/information/data-protection.html&knob-Link%20text=Data%20protection%20statement&knob-external=true&knob-variant=&knob-icon=&knob-Background%20color=white

**Comment by pavol-marko** [comment]
Produktion of pod-rsv is strongly affected due to this issue.
