### ISSUE TITLE
[Child of #1755] Colors are outdated

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1748]
Feedback from @MKaHead

Some colors are deprecated and should be removed. And the colors file should be split.

**Comment by danyball** [comment]
Why to split colors file?

**Comment by MKaHead** [comment]
No need for splitting color was feedback for typography see here #1755

**Comment by 01231** [comment]
And which colours are outdated? Would be nice to have some details here or a source where to find more.

**Comment by danyball** [comment]
> And which colours are outdated? Would be nice to have some more details here or a source where to find more.

Some more details on the "parent" issue:

> remove depricated colors (!and its usages at the WCs!). Remove "Validation" Colorvariables because they differ from the designation of the other variables.

Or ask Marco for details.
