### ISSUE TITLE
AXA Radio Exception with Disconnected Callback

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#1752]
Issue reported by Yannick Streit from Zühlke Engineering:

"We’re using the AXA radio button component in version 2.1.5 for one of our features and are facing a strange issue. We would be glad if you can help us since it seems to be an issue with the AXA Radio component.
 
When we navigate forth an back in our wizard our React component containing the radio buttons gets mounted/unmounted accordingly. When navigating back to the component containing the radio buttons the “disconnectedCallback” of the AXA radio button gets called unexpectedly. Since the component is not set up yet, a “null pointer” exception is thrown by this component (see screenshot below from @axa-ch/radio/lib/index.react.js:751).
 
This is an excerpt the code where we use the radio buttons in a fieldset:
 
```
<div className="checkout-actions">
  <AXAFieldset horizontal>
       <AxaRadioButton
              name="service-offer-response"
             data-test-id="add-product"
             label={t('price.acceptOffer')}
             value="true"
             button
             noGap
             checked={props.selected === true}
             onChange={() => onToggle(true)}
       />
       <AxaRadioButton
             name="service-offer-response"
             data-test-id="remove-product"
             label={t('price.declineOffer')}
             value="false"
             button
             noGap
             checked={props.selected === false}
             onChange={() => onToggle(false)}
       />
  </AXAFieldset>
</div>
```
 
Could you help us out?"
![Screenshot](https://user-images.githubusercontent.com/46926507/80363542-a72c9980-8884-11ea-9a88-5357e4c2cdf8.PNG)

**Comment by ynnckth** [comment]
Hi @markus-walther it's me Yannick. 
Thanks for opening the issue. Let me know if you need further details.

**Comment by markus-walther** [comment]
Web component lifecycle methods are asynchronous and there are no strong ordering guarantees.

React's mounting/unmounting causes creation and destruction of axa-radio instances in your case. The internal lifecycle of those instances is not synchronized to React in any way.

So it seems you hit a case where a destruction lifecycle callback is called out-of-order.

The fix is on our side: make that callback check more carefully whether the conditions for its cleanup operation are fulfilled.

**Comment by ynnckth** [comment]
Thanks for the clarification. If I understand you correctly the `disconnectedCallback` we see when re-opening our component containing the radio buttons was probably fired asynchronously somewhen in between our unmount and re-mount of the component and as soon as we re-open our component this event gets triggered?

Do you know approximately when you could release a fix?
Thanks in advance

**Comment by AndyOGo** [comment]
@ynnckth 
If you are curious, I can recommend to study the `<custom-elemets>` specification.

As @markus-walther said correctly reactions callbacks of custom elements aren't guranteed to run in order per specification.

E.g.: in regard to `connectedCallback`:
> An element's `connectedCallback` can be queued before the element is disconnected, but as the callback queue is still processed, it results in a `connectedCallback` for an element that is no longer connected
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance:concept-custom-element-reaction

If you are curious, I published an interactive CE-reactions illustration:
https://andyogo.github.io/custom-element-reactions-diagram/
