### ISSUE TITLE
Datepicker seems to have css collision on DEV and ACC

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1753]
On dev and acc, there is a site that collects a lot of pods into one page. This is probably the issue here.

Selber use case auf beiden Links
DEV: https://aem-dispatcher-1.dev.axa-ch.intraxa/de/test-pods/pod-rsv.html/#/adresse
ACC: https://www.acc.axa.ch/de/test-pods/pod-rsv.html#/start

Steps to reproduce:
- OS/BROWSER: Windows / Chrome (latest)
- Answer the first two questions however you want.
- On the second chapter ("2. Leistungen"), scroll all the way down and click the orange "Online Abschliessen" button.
- You are now being redirected to the 3rd chapter ("3. Adresse").
- On any datepicker, open the year dropdown. You will only see cropped numbers...

**Comment by 01231** [comment]
This could possibly be fixed by out new component versioning, couldn't it?

**Comment by raphaellueckl** [comment]
This should be fixed with versioning. Outstanding: The multidimensional styles, but they have a separate issue.
