### ISSUE TITLE
[Child of #1755] Usage of SVGs in React projects

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1756]
Our docu said this is working. But it does not (at Markos project):

```
import {
  ArrowRightSvg
} from '@axa-ch/materials/icons';
...
<ArrowRightSvg />
```

**Comment by danyball** [comment]
Need to export the "raw" SVGs beside the .svg.js

**Comment by raphaellueckl** [comment]
Are there other frameworks that support that? Somehow sounds weird to me to blow up a package for react-specific use cases. I would rather prefer some external "module" or class that enables this for react (not necessarily a pattern library component), something like skatejs, that is not part of the modules we ship.

**Comment by danyball** [comment]
The problem is that our export of SVGs are not standard - we export like `.svg.js`. And the svg-tools can not parse javascript embedded svgs. They need `.svg`. So why dont export our svg's beside ouer .svg.js ?
