### ISSUE TITLE
Invisbile shapes in material icons can be dropped

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#176]
All material icons incorporate an additional invisible shape for design purposes, but those aren't needed in production.
Related issue at their github page: https://github.com/google/material-design-icons/issues/37

The respective shape is always:
```svg
<path d="M0 .5h24v24H0z" fill="none"/>
```

**Comment by AndyOGo** [comment]
Actually all our icons seem to be cleaned already. Guess `svgo` cleans that up for us???

**Comment by LucaMele** [comment]
we need to verify that

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
