### ISSUE TITLE
Dropdown: Ellipsis on mobile (native select) not working

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1760]
Reproduce:
Open chrome at mac with a very small window, so that native select is rendered. Put a long text to axa-dropdown:
![image](https://user-images.githubusercontent.com/7448004/80960961-3815ee80-8e0a-11ea-8d53-1c46ebf7acac.png)

 Or open up storybook on iPhone:

![image](https://user-images.githubusercontent.com/7448004/80960801-e2d9dd00-8e09-11ea-8767-1ed7256f3c1c.png)

This is not working although of these lines of code:

```
.m-dropdown__button {
    padding: 10px;
    box-sizing: border-box;
    width: 100%;
    line-height: 20px;
    white-space: nowrap;  //HERE
    overflow: hidden; //HERE
    text-overflow: ellipsis; //HERE
  }
``` 

PS: Maybe check other form elements, too. Like input-text.

**Comment by danyball** [comment]
Maybe theres no simple solution.... https://stackoverflow.com/questions/7289769/ellipsis-for-overflow-text-in-dropdown-boxes

**Comment by 01231** [comment]
As far as I see that’s how elipsis on select boxes work - it doesn't. In every browser I tested the text get's cut off. In my opinion we can close this issue, because this is an expected behaviour.

**Comment by danyball** [comment]
We need some lines of JS. Here is a solution: https://nikitahl.com/text-overflow-ellipsis-on-select-tag/
I will ask our designers.

**Comment by danyball** [comment]
A mobile select should never have so much text that it is cut off. This mobile situation should be prevented by customers of the component.
