### ISSUE TITLE
Fieldset horizontal style gets applied regardless if horizontal prop is true or false

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1768]
Version: "@axa-ch/fieldset": "^3.0.1"

Fieldset horizontal style is applied regardless of horizontal prop value.

This makes it really hard to apply dynamic styling like this
`<AXAFieldset horizontal={isHorizontal} >`

Reproduction link:
https://codesandbox.io/s/dreamy-kilby-uc7jv

**Comment by danyball** [comment]
This is a boolean attribute. Means, that the existence of `horizontal` controls the behaviour. Like in our example at the docu: `<AXAFieldset horizontal>...children</AXAFieldset>`

**Comment by salle18** [comment]
I understand that but that makes it difficult to dynamically control via flag.
IMO this behavior is not consistent with boolean properties on other axa components (checked, disabled on axa-checkbox come to mind).

**Comment by 01231** [comment]
With the newest version (3.0.0) of axa-fieldset the attribute `horizontal` is now string-valued with the submode `stretch`.

**Comment by raphaellueckl** [comment]
@salle18 If this answers your question, feel free to close the issue. Otherwise, let us know if you would have any feedback on that property. :) Thanks for reporting!

**Comment by salle18** [comment]
This does answer the question of why but not if this behavior is buggy or not.
In my opinion in React horizontal={false} should work same as horizontal={true} or horizontal="stretch".
This is especially true if you are applying horizontal attribute dynamically which forced us to create adapter around AXAFieldset.

Workaround: https://codesandbox.io/s/fervent-cache-yltbt

**Comment by 01231** [comment]
@salle18 I made some changes in the readme to describe our changes better (visible in PR #1768). I think the old readme was a little bit misleading which could make it appear that we support boolean values. If it is okay for you I would close this issue.

**Comment by salle18** [comment]
Closing issue, explanation is provided in the readme
