### ISSUE TITLE
POD sourecode analysis

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1771]
Need that issue for my own documentation. See details on our internal board.

**Comment by danyball** [comment]
https://rules.sonarsource.com/javascript/RSPEC-3271?search=storage

**Comment by danyball** [comment]
https://stackoverflow.com/questions/35438063/eslint-disable-localstorage-and-sessionstorage

**Comment by raphaellueckl** [comment]
why is this a pattern library issue? this has nothing to do with it.

**Comment by danyball** [comment]
oh jea sorry. wrong repo
