### ISSUE TITLE
IE: axa-radio "noGap" not working correctly

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1772]
Reported by "Nick Rascher" over Slack. 

Open this page with IE11 (**React** demo. VanillaJS demo is working!):

https://patterns.axa.ch/?path=/story/components-atoms-radio-react-demos--controlled-component-react-ified-radio-button

There is a gap between buttons:
![image](https://user-images.githubusercontent.com/7448004/81932678-6e165800-95ec-11ea-8ce2-5fed964b3c87.png)

There's a margin at the first button. The CSS rule is not working?
![image](https://user-images.githubusercontent.com/7448004/81932824-a87ff500-95ec-11ea-8988-80cfb2ee6b83.png)

**Comment by raphaellueckl** [comment]
The attribute `nogap` is not there on the radio buttons on IE11. Just an observation. Weird that this is a browser issue.

**Comment by markus-walther** [comment]
I suggest to research whether this is related to issue https://github.com/axa-ch/patterns-library/issues/1761 and possibly fixed by pending pull request https://github.com/axa-ch/patterns-library/pull/1762.

**Comment by danyball** [comment]
> I suggest to research whether this is related to issue #1761 and possibly fixed by pending pull request #1762.

Yes, your PR 1762 fixes that problem.
