### ISSUE TITLE
[Child of #1773] Create `Latest Releases/Whats new` section with dynamic content

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1776]
We want to display that something is going on at PL. So we want to create dynamic content.

TODO:
Display all our latest releases with its release notes. Do not show bugfix-releases without real changes.

**Comment by TommyHoliday** [comment]
https://github.com/axa-ch/patterns-library/releases

**Comment by danyball** [comment]
NPM public api: just find this old docu: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md
Its not possible to get the release date of a package. I think the api is outdated.

Github api: is much better documented. But we dont have any benefit to get the commit of a github repo. We just can create the latest-releases section at build time. -> will do that.
