### ISSUE TITLE
Datepicker - not able to select Date in IE 11

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#1782]
Hi all

I can open the selector for choosing the date without problem but when I chose a date the field stays empty.

**Comment by 01231** [comment]
Can you provide a sandbox/example? In our PL demo it seems to work.

**Comment by francescoRovetto** [comment]
Which sandbox do you use? I can't find one for IE11

By the way, I'm using babel for polifying

**Comment by francescoRovetto** [comment]
Hi Noah
I found out the issue- in IE 11, it only works with "onDateChange={date => console.log(`date changed ${date}`)}" - but we have only used "onChange" till now.

**Comment by 01231** [comment]
So is this something that worked before and now does not, or did you just noticed this yet?

**Comment by 01231** [comment]
@markus-walther do you have an idea?

**Comment by francescoRovetto** [comment]
Hi Noah - we noticed this while testing with IE11. Then I found out, that we can do it with this workaround I mentioned above. But I think, it's still something worth to look at for the sake of the libary itself.

the issue #1793 is of much greater value for us! :-)

**Comment by danyball** [comment]
`onChange` is triggered by all changes of the input field. `onDateChange` is just triggered if its a valid date.
If you want to get informed f.a. if the user deletes the last digit of a correct date like "7.6.202", use the onChange event. Its triggered correctly. Even on IE11.

What do you want to do here?

**Comment by francescoRovetto** [comment]
Hi Dany, we wanted to validate the date customized with onChange. So, we can just use onDateChange for validation?

**Comment by danyball** [comment]
I think so @francescoRovetto - just check out our example: https://patterns.axa.ch/?path=/story/components-molecules-datepicker-react-demos--external-validation-using-ondatechange-driven-react-ified-datepicker-with-inputfield

**Comment by danyball** [comment]
Re-open or create new issue if you want to. For now we do not see anything to fix.
