### ISSUE TITLE
axa-table-sortable out of range in IE11

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#1793]
Hi all
When I don't want to use "innerScroll" for axa-table-sortable, I get this in the IE11:
the container <axa-container> should limit the width of the table, like he does in Chrome or Firefox

How it looks now in IE11:
![untitled](https://user-images.githubusercontent.com/5209125/82874008-a6476000-9f35-11ea-9017-e6e0a062b64e.png)

How it should look:
![image](https://user-images.githubusercontent.com/5209125/82874059-b95a3000-9f35-11ea-8ac0-877eae2799e9.png)

**Comment by 01231** [comment]
Thanks for reporting. We'll have a look👍🏼

**Comment by NoahLiechti** [comment]
Findings so far: Bug only appears only on the `axa-table-sortable` (not on `axa-table)` togehter with the `axa-contaiener` in IE11. Appears only when `innerscroll` attribute is set.

**Comment by markus-walther** [comment]
@francescoRovetto Can you demonstrate this is a problem with axa-table-sortable? Can you demonstrate this is specific to IE11?

Because I see in Chrome using  https://patterns.axa.ch/iframe.html?id=components-organisms-table-sortable--table-sortable that axa-table-sortable expands to fill the width given by its container (i.e. it looks like your upper picture).

That would suggest your bug has to do with whatever container is around axa-table-sortable in your appliction, and not with the component itself.

If I restrict the width of a container appropriately, I can observe axa-table-sortable faithfully staying within the width given to it (i.e. it looks like your lower picture).

**Comment by francescoRovetto** [comment]
Hi @markus-walther - I restrict the axa-table-sortable also with axa-container. and this works totally fine with Chrome but not IE11.

This is the structure:

> 

              <AXAContainer>
                    <div style={{textAlign: 'left'}}>
                        <div className={'smallMainTitleWrapper'}>
                            <p className={'smallMainTitle'}>
                                <FormattedHTMLMessage id="kred.glob_polnr" defaultMessage="Policennummer"/>
                                &nbsp;
                              {polTitle}
                            </p>
                            <h1 className={'smallMainTitle'}>
                                <FormattedHTMLMessage id="kred.glob_claims" defaultMessage="Schäden"/>
                            </h1>
                            <p className={'smallMainTitle'}>
                                {adresseKunde}
                            </p>
                        </div>
                        <div style={{height: '10px'}}/>
                        <AXAButton onClick={() => {
                            stores[1].newClaim(this.props, stores[2].state.policeAusgewaehlt, stores[2].state.laenderAuswahl, stores[2].state.waehrungen, stores[0].state.rechtlichesTexte)
                        }}>
                            <FormattedHTMLMessage id="kred.claim_add" defaultMessage="Neuen Schaden erfassen"/>
                        </AXAButton>
                        <div style={{height: '25px'}}/>
                        <h2>
                            <FormattedHTMLMessage id="kred.claim_manage" defaultMessage="Schäden verwalten"/>
                        </h2>
                        <FilterInputWithDropdownAndExcel
                            dropdownValues={dropdownMenu}
                            changeDropdownInput={(e) => {
                                stores[0].dropDownChange(e, stores[2].state.policeAusgewaehlt)
                            }}
                            changeInput={stores[0].changeSuchFeld}
                            searchValue={stores[0].state.suchfeld}
                            ladeExcelHerunter={(e) => {
                                stores[0].ladeSchadenExcel(stores[2].state.policeAusgewaehlt, intl.locale)
                            }} filterAction={(e) => {
                            stores[0].sucheNachSchaedenAufGui(stores[2].state.policeAusgewaehlt)
                        }}
                            platzhalter={placeholderPol}/>
                        <div style={{height: '15px'}}/>
                                            <AXATableSortable model={model} maxheight="0" innerscroll="1140" datesortcolumnindex="9"/>

                        {noEntries}
                    </div>
                    <div style={{height: "100px"}}/>
                </AXAContainer>
``

**Comment by raphael-suter** [comment]
Note to the team:
Couldn't reproduce that - asked for a link.
Currently waiting.

**Comment by raphael-suter** [comment]
Never received a link. @francescoRovetto feel free to reopen this issue :)
