### ISSUE TITLE
Datepicker: Safari: Tap on Year dropdown distorts the look of whole component

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1794]
Just on Safari (iphone and mac) and just if Datepicker is NOT a inputfield.

Repro:
Open Storybook on iPhone an tap on year dropdown. 

![image](https://user-images.githubusercontent.com/7448004/82882795-d98fec00-9f41-11ea-9f60-cc8154b5bf93.png)

**Comment by 01231** [comment]
Indeed very weird
<img width="1173" alt="Screenshot 2020-05-28 at 15 16 46" src="https://user-images.githubusercontent.com/38284563/83146225-45b35100-a0f6-11ea-8ef3-f9548a8895f4.png">

**Comment by markus-walther** [comment]
As far as I can see nothing is 'destroyed'. The width is super-wide, that's all. In https://patterns.axa.ch/iframe.html?id=components-molecules-datepicker--datepicker there is a width attribute without a value, if you set it to, say, 80, everything is fine. My suspicion is some recent changes for width behaviour are not cross-browser.

**Comment by raphael-suter** [comment]
The problem only appears when the width attribute is set to an empty string. The datepicker gets wider with every date change or when you hover over a date in the calendar (there may also be other triggers).
