### ISSUE TITLE
Wrong font-weight on heading component

### ISSUE THREAD

**Issue by TommyHoliday** [axa-ch/patterns-library#1796]
The font-weight for Source Sans Pro on the heading component is wrong. It should be bold instead of regular.

https://patterns.axa.ch/?path=/story/components-atoms-heading--heading

**Comment by salle18** [comment]
Same applies to @axa-ch/materials/styles/20-typography-and-text

**Comment by LucaMele** [comment]
Thank you for the report, we will fix it
