### ISSUE TITLE
Nested .tmp folders in materials

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1802]
There are three nested `.tmp` folders. In my opinion one should be enough.
(also applies for the images-raw folder)
<img width="212" alt="Screenshot 2020-06-05 at 10 35 12" src="https://user-images.githubusercontent.com/38284563/83856908-89bbdc80-a71a-11ea-9240-77a25f38db20.png">

**Comment by danyball** [comment]
This is not a bug. Everytime you start the script to create the .tmp folder, it copies the whole structure, including the existing .tmp folder.

**Comment by 01231** [comment]
Script should delete `.tmp` folder before copying.
-> From conversation with @danyball
