### ISSUE TITLE
Datepicker: allowed years adds current year

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1805]
When I set the allowedyears to ['1999-2000'] the date picker also adds the current year.
Version 7.0.8
<img width="523" alt="Bildschirmfoto 2020-06-05 um 18 16 49" src="https://user-images.githubusercontent.com/617005/83899620-0c638c80-a759-11ea-9776-b6a96e350c3b.png">
<img width="550" alt="Bildschirmfoto 2020-06-05 um 18 16 06" src="https://user-images.githubusercontent.com/617005/83899623-0d94b980-a759-11ea-979b-0bef647c6d80.png">

**Comment by LucaMele** [comment]
@campsafari thank you very much for this!

**Comment by danyball** [comment]
@campsafari You are setting the attribute `year` to "2020". That value is automatically set to the default "current year" if you do not set it explicit. And the `year` attribute is automatically added to the range.

Documentation:
> The `year` property value is an automatic member of `allowedyears`.

We will discuss that behaviour at our team and will change that if it makes sense. But for now to quick fix your problem: Just set `year` to a year the datepicker should start with and which is member of your range.

**Comment by campsafari** [comment]
Thanks for replying. I didn't set the year explicitly. But it's still confusing that the date that is set per default is outside of the allowed years range.
Will use the suggested config to get around this issue for now.

**Comment by LucaMele** [comment]
@campsafari I agree, we will challenge the interface in the team. Thank you for your Feedback
