### ISSUE TITLE
Datepicker: correct date throws invalid date error

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1806]
When the value with a date older than 1979 is used the date picker throws an "invalid format" error even if the allowed dates range from i.e. 1960-2020
<img width="561" alt="Bildschirmfoto 2020-06-09 um 16 44 51" src="https://user-images.githubusercontent.com/617005/84162834-1cd57900-aa71-11ea-9e2c-5c31dd76a9fd.png">

**Comment by LucaMele** [comment]
@campsafari thank you very much for this!

**Comment by danyball** [comment]
:D 

Such a great comment:

// CAVEAT: Unix Epoch starts in 1970, as a consequence
  // years < 1970 lead to negative integers which are considered
  // invalid below! Rethink validity once such old dates need to be
  // considered.
