### ISSUE TITLE
TypeError in Demos (controlled inputs React)

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1814]
https://patterns.axa.ch/?path=/story/demos--controlled-inputs-react

<img width="1440" alt="Screenshot 2020-06-16 at 08 59 16" src="https://user-images.githubusercontent.com/38284563/84741686-b6d87c80-afaf-11ea-87a8-8f30c76450fe.png">

**Comment by markus-walther** [comment]
These demos are hopelessly outdated by now. I suggest to just delete them!

**Comment by danyball** [comment]
> These demos are hopelessly outdated by now. I suggest to just delete them!

+1
