### ISSUE TITLE
Submit button in form not firing events

### ISSUE THREAD

**Issue by ynnckth** [axa-ch/patterns-library#1815]
We're using the axa-button component in the current version (4.1.2) and observed the following behaviour:

We use the react-i18next translation library. After switching the language in a page with an AXA button (of type="submit") inside a form element the button stops firing click events. We don't see any errors in the console or anything suspicious.

If possible let's take a look together to show you how to reproduce the issue.
Thanks in advance & regards, 
Yannick

**Comment by danyball** [comment]
Internal: If button is not re-rendered and the label has changed (slot changed) the hidden button is gone:
![image](https://user-images.githubusercontent.com/7448004/84776292-6af1fb80-afe0-11ea-954d-68dfe3cbdbf6.png)

Implementation:
``` 
<AxaButton variant="secondary" onClick={() => navigationService.nextStep({
      page: Page.SCAN,
      pageSubstepIndex: undefined
    })}>{t('skipScan')}</AxaButton>
```

**Comment by markus-walther** [comment]
For diagnosing what's happening here I set a breakpoint on node removal in Chrome Developer Tools on the hidden (display:none) < button type="submit" >.

It fires and shows the call chain ending in an obfuscated React framework function.

The line of code that is about to remove the hidden button looks like this:
`t.textContent = e;`, where t is the outer axa-button and e is the new button text.

This line legitimately destroys all children of t, and replaces them with a single Text node with the new text e.

Unfortunately the current implementation of axa-button places the hidden submit button as a _sibling child_ of the text node representing the label text, and does so only once, after initial render.

Hence, predictably the hidden button is destroyed after non-initial button-text change.
