### ISSUE TITLE
add tagging feature

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#182]
I think it would make sense to make each component tag-able, e.g. `mandatory` for all currently implemented components.

**Comment by LucaMele** [comment]
im not sure if i understood this correctly. Is this the "depency" defenition of components? So that if comp A have a dependecy on Comp B, that dependecy is set? If yes, this IMHO would be high-prio

**Comment by AndyOGo** [comment]
No, more plain tags. For grouping, search, etc.
For example aller header related components could be tagged with `header`

**Comment by LucaMele** [comment]
ahh ok :) then no high-prio but good to have

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
