### ISSUE TITLE
InputText: Checkmark looks broken when Browser is zoomed

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1821]
When the user´s browser has a zoom level > 100% the checkmark looks broken.
<img width="90" alt="Bildschirmfoto 2020-06-22 um 11 08 52" src="https://user-images.githubusercontent.com/617005/85270121-213e6080-b479-11ea-9c8a-78defa8b28be.png">

**Comment by danyball** [comment]
Please always provide your environtments variables like OS and browser name. 

Chrome@mac:

![image](https://user-images.githubusercontent.com/7448004/85280193-f3144d00-b487-11ea-972e-54c621f6c97a.png)

**Comment by campsafari** [comment]
Environment: Chrome 83.0.4103.106 | OSX 10.15.4
Source: https://patterns.axa.ch/

<img width="1076" alt="Bildschirmfoto 2020-06-22 um 18 18 16" src="https://user-images.githubusercontent.com/617005/85310996-04278300-b4b5-11ea-808b-db9a4a92b89c.png">

**Comment by campsafari** [comment]
Environment: Safari 13.1 | OSX 10.15.4
Source: https://patterns.axa.ch/
In Safari it even looks broken without zoom
<img width="442" alt="Bildschirmfoto 2020-06-22 um 18 22 47" src="https://user-images.githubusercontent.com/617005/85311346-9c256c80-b4b5-11ea-8af6-d24d746191d1.png">

**Comment by campsafari** [comment]
From what I can see the icon in your screenshot doesn't look like 2 strokes compared to the icon included in the patterns.axa.ch InputText

**Comment by danyball** [comment]
> From what I can see the icon in your screenshot doesn't look like 2 strokes compared to the icon included in the patterns.axa.ch InputText

But it is. Cant reproduce that on Chrome here. But at Sarari you're right.

**Comment by 01231** [comment]
seems that out `check-mark-animated()` mixin is handled different in safari than in chrome.

**Comment by campsafari** [comment]
> seems that out `check-mark-animated()` mixin is handled different in safari than in chrome.

it is also the wrong design according to the AXA UI Kit
<img width="331" alt="Bildschirmfoto 2020-06-24 um 10 46 55" src="https://user-images.githubusercontent.com/617005/85524130-21b93180-b608-11ea-90d3-f6ffc3ea311a.png">

**Comment by 01231** [comment]
Good point. In my opinion it would be the easiest to just start implementing it from zero.
