### ISSUE TITLE
Datepicker: Calendar button can't be focused via keyboard navigation

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1824]
Environment: Safari 13.1 | OSX 10.15.4
Source: https://patterns.axa.ch/

In Safari the button inside the textfield can't be focused and triggered via keyboard.

**Comment by 01231** [comment]
I don't think that this is a bug. Apple handles accessibility differently than other browsers. You must enable user preferences that allow for tabbing between links.  I would not recommend implementing any custom solutions to modify this behaviour. It will likely create other problems.

http://www.weba11y.com/blog/2014/07/07/keyboard-navigation-in-mac-browsers/

**Comment by campsafari** [comment]
Yes, you are right, enabling “Press tab to highlight each item on a webpage” fixes it.
