### ISSUE TITLE
Interactive examples/demos

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#183]
Every component should have a full-fledged interactive demo, including but no limited to:

- [ ] checkboxes enabing/disabling boolean attributes
- [ ] providing JSON data if needed
- [ ] callback allerts?
- [ ] Enums/radios/dropdowns for value ranges

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
