### ISSUE TITLE
add fragment identiefier links to each components heading

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#184]
It would be nice to have the components hash also available at the components level, not only in the main menu, like in github readmes:

![hash-tag-component-names](https://user-images.githubusercontent.com/914443/35217408-78afff1a-ff6b-11e7-9a96-cbc2909a6a63.gif)

**Comment by LucaMele** [comment]
agree, it would be helpfull

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
