### ISSUE TITLE
axa-ch/input-text v4.1.0 fails to render with error: Cannot read property 'axa-popup' of undefined

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1842]
Reproduction
https://codesandbox.io/s/hopeful-varahamihira-f0ris?file=/src/App.js

This is content of `node_modules/@axa-ch/input-text/lib/index.react.js`

```
    var enrichedVersionInfo = {
      "axa-input-text": {
        "axa-input-text": "4.1.0",
        "axa-popup": "3.0.1"
      }
    };
    var commonPopupVersion = enrichedVersionInfo['axa-popup']['axa-popup'];
```

**Comment by danyball** [comment]
Thanks for submitting this issue and the sandbox example. we have already established this at #1832.

A quick workaround: Do not set the "versioned string" and use it without the versioned feature like so:
`const AXAInputText = createAXAInputTextReact(createElement);`

**Comment by salle18** [comment]
Workaround doesn't work.

Reproduction link without versioned string:
https://codesandbox.io/s/zealous-solomon-thcx6

Check the code snippet above taken from the published code, enrichedVersionInfo is hardcoded there and there is no way that `enrichedVersionInfo['axa-popup']['axa-popup'];` will work.

I am wondering how can we improve tests to cover this because they apparently pass but published version is not usable.

**Comment by gabac** [comment]
@danyball when are you planning to release a new version?

**Comment by danyball** [comment]
Today
