### ISSUE TITLE
DX: Replace negation boolean props with positive counterparts

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1843]
For some reason it is quite difficult to mentally process negative boolean flags, if logic gets even a bit complex the needed mental energy is quadrupled. 

Proposal, replace negation props with their positive counterparts to improve developer experience:
noAutoWidth => autoWidth
noGap => gap

Not sure if there are more examples in other components, these two props are on axa radio button

**Comment by 01231** [comment]
I think negation props are there for a reason. For example the radio component should have by default `autoWidth`. If the attribute changes from `noAutoWidth` => `autoWidth` the user has to set an attribute where now this would be a default behaviour.

**Comment by campsafari** [comment]
I think what he means is that noAutoWidth=true is mentally harder to process than autoWidth=false.
Also the default value for the prop could be "true" unless set via prop explicitly.

**Comment by salle18** [comment]
Exactly, no need to change default behavior, autoWidth=true can still be default and developer can still set it to false explicitly.

Let me try to appeal to authority 😄 

https://softwareengineering.stackexchange.com/questions/196830/boolean-method-naming-affirmative-vs-negative
https://stackoverflow.com/questions/1445836/positive-or-negative-boolean-field-names
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

**Comment by raphaellueckl** [comment]
Generally I agree and we used to do that when I was still a java backend developer.

But with Webdevelopment, outside of the react world, I don't really like the approach. Usually, a boolean looks like this:

`<axa-input autoWidth></axa-input>` This would set it to true for plain html attributes. But how to negate that while keeping up a default value for `true`? This is not so possible, without converting that attribute to a "string" value and then do some weird conversions (or just treat it like a string value, which is kind of an ugly workaround). I understand that in the react world, you have to assign `true` or `false` to a boolean property and I see the pain. But enabling this behavior would benefit react and I would prefer to write clean code for all frameworks and obviously for native html.

If we took your approach and just would not write that attribute, `<axa-input></axa-input>` would lead to `autoWidth` being false but then again convert it to true in the default case (I believe), which would make it always true, no matter if present or absent.

Here a link to the spec: https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes
`A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.`

**Comment by LucaMele** [comment]
Due to @raphaellueckl and @NoahLiechti argumentations, we, as a team decided to close this issue
