### ISSUE TITLE
axa-datepicker: change translations, but not date format

### ISSUE THREAD

**Issue by branislav-remen** [axa-ch/patterns-library#1845]
Hi, 

MyAXA portal supports english language, **not locales**. 
Our dates are formatted as `d.M.yyyy` in all languages.

To change translations in axa-datepicker, we have to use `locale` prop. 
There is no supported `en-CH` locale, and other en locales don't support our date format.

**What we need for myaxa is way how to change langues but not date-format.**

As workaround we temporary use german translations when `en` language is selected.
![image](https://user-images.githubusercontent.com/43781862/86337061-e692b000-bc50-11ea-9e4b-a4fb9dce1b19.png)

Demo - datepicker with visible input field and locale `en-GB` formats date as `d/M/yyyy`:
https://patterns.axa.ch/iframe.html?id=components-molecules-datepicker-react--datepicker-as-react-component&knob-inputfield=true&knob-locale=en-GB&knob-year=&knob-month=&knob-day=&knob-label=&knob-monthtitle=Choose%20Month&knob-yeartitle=Choose%20Year&knob-invaliddatetext=Invalid%20date&knob-placeholder=Please%20select%20a%20date&knob-defaultValue=&knob-width=400&knob-height=40&knob-allowedyears=[%221971-2000%22,2012,2014,%222018-2022%22]

**Comment by LucaMele** [comment]
Hello @branislav-remen, our datepicker is implemented accordingly with AXA CH Design. This feature must be approved by our designer. Till we discuss it with the designer, take the patterns library as main reference, therefore use it with the locale `en`. Because form elements are mandatory they undergo through a bit a longer procedure. I will let our designer know and then then they can define it.

**Comment by LucaMele** [comment]
Also, @branislav-remen we also dont have translation and your feature request will imply complex mechanisms for creating a non standard locale/translation combination. Internally we use Intl-API without any translation tool. We will have to map en-gb to de-ch format.

**Comment by TommyHoliday** [comment]
hi @branislav-remen and @LucaMele,
i just discussed the issue with Luca. from a UX perspective i don't have any concerns in displaying either `d.M.yyyy` or `d/M/yyyy` format for the english speaking users. i don't know what the challenges and efforts are from a technical side though – it's up to you guys to decide. :-)

**Comment by MarekLacoAXA** [comment]
Just to sum with simple words:
- for our app we need the datepicker to display day names and month names in english
- in the same time we need the datepicker to display EU-style date format (same as for DE/FR/IT languages)

**Comment by LucaMele** [comment]
@marek-polak there is not such a thing as EU-Style. The EU Commission uses one style (`dd.mm.yyyy`) yes but in Italy is with `/` same as in France and the UK. In Germany, Austria and Switzerland is with `.`. We need to evaluate which is more convenient to do: you transform it after or we always do. Cause we use a standard in Browser API, everything away from standard is hacky and needs to be considered carefully. The Locale `en-CH` unfortunately does not exist per standard and the closest one is `en-UK` where it is with slashes cause that's how they read dates there. Also US and AU uses `/` so almost all the english speaking community will be happy to see the dates in the format they know. We will internally discuss it what makes the most sense and we can have a call to know better where your need comes from.

Here a list of all date formats for all countries: https://gist.github.com/mlconnor/1887156

**Comment by LucaMele** [comment]
I discussed this with our BA and he said it will be better if date format is always in CH style
