### ISSUE TITLE
Datepicker: Calendar disappears after focus via Tab

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1846]
When the date picker is open and the user focusses the input and then shifts the focus per tab onto the date picker icon the calendar view disappears.
![datepicker](https://user-images.githubusercontent.com/617005/86364587-a515fb00-bc78-11ea-8c52-db282a8f2474.gif)

The behavior can be reproduced on the address screen:
https://www.acc.axa.ch/de/test-pods/pod-rsv.html#/start

Environment: Chrome 83.0.4103.116 / OSX 10.15.4

**Comment by LucaMele** [comment]
@campsafari I can't reproduce here: https://patterns.axa.ch/iframe.html?id=components-molecules-datepicker--datepicker&knob-inputfield=true&knob-locale=de-CH&knob-year=2020&knob-month=4&knob-day=22&knob-allowedyears=[%221971-2000%22,2012,2014,%222018-2022%22]&knob-label=&knob-monthtitle=Choose%20Month&knob-yeartitle=Choose%20Year&knob-invaliddatetext=Invalid%20date&knob-placeholder=Please%20select%20a%20date&knob-width=&knob-height=40

Please provide more environment information and Ideally a codepan where it can be reproduced

**Comment by campsafari** [comment]
I added a link where it can be reproduced. However in the link you mentioned it can't be reproduced

**Comment by LucaMele** [comment]
@campsafari ok thank you

**Comment by LucaMele** [comment]
@campsafari we need to know which version of datepicker and also if it happens on its own (code snipped only with datepicker). Do you know that?

**Comment by danyball** [comment]
I can repdroduce it on your app, but not at our showcase. Please use a new version of axa-datepicker. You are using a very old one which has buttons at the bottom. Reopen issue if you still have the issue with the latest datepicker. Thanks.
