### ISSUE TITLE
Remove all console.logs() from stories and demos

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1847]
In components like `inputfile` and many more console.log() are being used. Due the fact that not everybody has his console open (or even knows that a console exists), all logs should be printed onto the page.

**Comment by danyball** [comment]
There is a storybook plugin that displays the console...

**Comment by 01231** [comment]
In this is already in use?

**Comment by danyball** [comment]
Not yet. We could use it if we want.
