### ISSUE TITLE
only one top level story in storybook

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1848]
There are many components which don't follow our style of stories and demos. Some need to move their demos into the demo folder and create a story with knobs. 

<img width="210" alt="Screenshot 2020-07-03 at 09 59 22" src="https://user-images.githubusercontent.com/38284563/86446601-74839f00-bd14-11ea-9287-fc82a4035df7.png">
<img width="204" alt="Screenshot 2020-07-02 at 09 35 59" src="https://user-images.githubusercontent.com/38284563/86446585-7188ae80-bd14-11ea-8346-1e78d742ec3c.png">
<img width="208" alt="Screenshot 2020-07-03 at 09 56 45" src="https://user-images.githubusercontent.com/38284563/86446588-72b9db80-bd14-11ea-9102-936795f89a3a.png">
<img width="209" alt="Screenshot 2020-07-03 at 09 57 36" src="https://user-images.githubusercontent.com/38284563/86446592-73527200-bd14-11ea-9c73-d77462fa774a.png">
<img width="207" alt="Screenshot 2020-07-03 at 09 58 12" src="https://user-images.githubusercontent.com/38284563/86446597-73527200-bd14-11ea-8eb0-1e31df17f1fb.png">
<img width="209" alt="Screenshot 2020-07-03 at 09 58 28" src="https://user-images.githubusercontent.com/38284563/86446599-73eb0880-bd14-11ea-8139-037aa183b6f5.png">

**Comment by raphael-suter** [comment]
Is related to #1857
