### ISSUE TITLE
Reorder documentation files

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1851]
We have so many MD files, that we should restructure the project. Add a docs folder for those and update the links.

![Screenshot 2020-07-03 at 15 02 47](https://user-images.githubusercontent.com/8248662/86471895-7c583900-bd3e-11ea-804b-6de298eb77b9.png)

**Comment by 01231** [comment]
could move them to `.github/`

**Comment by LucaMele** [comment]
no
