### ISSUE TITLE
Pipeline script that tests components as if they were used by consumers/production

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1856]
We never test the published npm version, we always run the tests on our storybook which does not rely on the dist/lib folder that we publish.

We need a script that runs maybe one smoke test for each component or all tests with the PROD compiled components instead of the source code.

**Comment by markus-walther** [comment]
This is difficult to achieve, in particular when adding the sensible constraint to be able to test dist/lib **as if it were published**, but **without actually publishing to npm**.

I made an experiment using the approach of https://github.com/laftho/baresm and ran into tons of problems...

**Comment by markus-walther** [comment]
Because of the difficulties mentioned above, and the moderate payoff, closed for now.
