### ISSUE TITLE
Reorder Stories in Storybook

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1857]
The structure of stories is pretty messy. IMHO we should have stories with 1 plain story in it, that users can manipulate with the knobs.

All other examples and react examples (that are mostly only proof, that a component works properly and that are being used by our tests) should be put into a specific folder called "Examples" or "Demos" or whatever, that collects them all.

Reason: I think that most people that use our storybook, are not interested in those demos that are often in a lot of ways redundant to the main story. Therefore it may makes sense to reduce unnecessary complexity.

BEFORE:

![image](https://user-images.githubusercontent.com/8248662/86900307-75993f80-c10b-11ea-9c46-52e7f081b728.png)

AFTER:

![image](https://user-images.githubusercontent.com/8248662/86900457-ab3e2880-c10b-11ea-8c3f-86bbe5c88711.png)

Maybe we could even remove the containing "folder" with this approach.

**Comment by 01231** [comment]
This would also be cool for the welcome page.

<img width="207" alt="Screenshot 2020-07-08 at 08 53 58" src="https://user-images.githubusercontent.com/38284563/86916901-8efab580-c124-11ea-853d-c87e082570de.png">

**Comment by raphael-suter** [comment]
Is related to #1848
