### ISSUE TITLE
Demo for cookie disclaimer is broken

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1860]
![Screenshot 2020-07-08 at 14 07 03](https://user-images.githubusercontent.com/275235/86916910-928e3c80-c124-11ea-9cc8-7a77153b860d.png)

IS: No button is displayed
SHOULD: "Akzeptieren" should be displayed as an inverted button

**Comment by 01231** [comment]
There is a very old button version where `inverted` is not implemented is my suspicion.

<img width="528" alt="Screenshot 2020-07-13 at 13 12 18" src="https://user-images.githubusercontent.com/38284563/87298449-80d4dc80-c50a-11ea-9f83-83ae14479f78.png">

**Update**
Inverted seems to be implemented a long time ago.
