### ISSUE TITLE
Commercial HERO banner button is broken

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1862]
Is : button with fits container width
Should: button width should fit content width

![Screenshot 2020-07-08 at 14 11 48](https://user-images.githubusercontent.com/275235/86917366-42fc4080-c125-11ea-9ff1-b66d77c39eb5.png)

**Comment by 01231** [comment]
The button width fits the content width, doesn't it?

**Comment by LucaMele** [comment]
Yes but the component should change his width how it was as for commercial hero, this width is not right.
