### ISSUE TITLE
Make axa-button (size: default) the same height on all devices

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1869]
See Figma for the most recent updates and connect with Thomas Veit to discuss it, if needed.

This was discussed in a design critique meeting and agreed upon. It was also requested from some parts of the axa-ch team (Bettina).

**Comment by 01231** [comment]
this must be done also for button-link and input-file i guess

**Comment by LucaMele** [comment]
@raphaellueckl Why did you add label Accepted? We have not discussed it yet in a democratic majority

**Comment by LucaMele** [comment]
@raphaellueckl is it even a feature request or a bug? To me seems more like is a bug, then the label accepted can be added by another person that reproduce the issue

**Comment by LucaMele** [comment]
As discussed with Raffi, only Noah and him approved therefore the team majority is not reached yet and label accepted cannot be set accordingly to our CoC
