### ISSUE TITLE
Lint all files against editorconfig 

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#187]
ATM we don't lint according to our `.editorconfigrc` file.

May the following tools help:
- https://www.npmjs.com/package/editorconfig-checker
- https://www.npmjs.com/package/editorconfig-tools

**Comment by AndyOGo** [comment]
https://github.com/editorconfig/editorconfig/issues/340#issuecomment-366995983

**Comment by AndyOGo** [comment]
This feature isn't feature complete, still WIP

**Comment by AndyOGo** [comment]
Update 🌟 🌟 🌟 
**editorconfig-checker** just released line based disable support_
https://github.com/editorconfig-checker/editorconfig-checker.javascript/pull/24

Plus more advance checker controll issues are raised:
- https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/27
- https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/26
- https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/25

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
