### ISSUE TITLE
Versioning global: Uppercase version resumes in an error

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1873]
`const AXAButton = createAXAButton(createElement, 'eSales');`:
> Failed to execute 'define' on 'CustomElementRegistry': "axa-button-eSales" is not a valid custom element name

Fix:
`const AXAButton = createAXAButton(createElement, 'esales');` 

Todo:
We have to decide if we want to allow uppercase strings which are used by react developers. If we use `lowercase` we have to document that because the name of html element is not exactly the same a dev expected. `<axa-button-eSales>` vs. `<axa-button-esales>`

**Comment by LucaMele** [comment]
@danyball i would simply `.toLowerString` all keys in entry and document it. Generally in HTML there is no uppercase anyway
