### ISSUE TITLE
input-file & button-link: gap below component

### ISSUE THREAD

**Issue by raphael-suter** [axa-ch/patterns-library#1878]
There is always a little gap below an input-file/button-link.

<img width="359" alt="Screenshot 2020-07-16 at 09 54 48" src="https://user-images.githubusercontent.com/52913998/87643616-57ef5a00-c74b-11ea-850c-4af76341af9b.png">

**Comment by danyball** [comment]
Can reproduce that. (parent Background set to red)

![image](https://user-images.githubusercontent.com/7448004/87653619-10ba9680-c756-11ea-9ab2-742e635df820.png)
