### ISSUE TITLE
Dependencies are outdated at some components

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1882]
F.a. at `axa-footer`:

"dependencies": {
    "@axa-ch/container": "3.0.3",
    "@axa-ch/materials": "^2.0.2",  ---> OUTDATED
    "@skatejs/val": "^0.4.0",
    "lit-element": "^2.2.0",
    "lit-html": "^1.1.0"
  }

We need to know why because some other components may have other outdated dependencies.

**Comment by danyball** [comment]
We had 2 issues solved this week by simply updating these dependencies.

**Comment by danyball** [comment]
Maybe is `^` the problem?!

**Comment by danyball** [comment]
The problem is that `lerna version` is just replacing the version numbers of dependencies if they match the current version. From the example above:

`"@axa-ch/materials": "^2.0.2",`

- materials current version is 10.2.0, so 2.0.2 is never replaced.

**Comment by danyball** [comment]
How to find out which sub-packages have outdated dependencies?!.....

**Comment by markus-walther** [comment]
> The problem is that `lerna version` is just replacing the version numbers of dependencies if they match the current version. From the example above:
> 
> `"@axa-ch/materials": "^2.0.2",`
> 
> * materials current version is 10.2.0, so 2.0.2 is never replaced.

With the transition to versioned components no hat-versions should be used anymore anyways!
