### ISSUE TITLE
The github button as a traget_blank

### ISSUE THREAD

**Issue by johannabuguet** [axa-ch/patterns-library#1885]
For now, when we click on the button "Github" it open github on the same page and we want to avoid that behaviour.
The github button should lead to a new page. 

<img width="1059" alt="Capture d’écran 2020-07-20 à 16 16 56" src="https://user-images.githubusercontent.com/68434693/87948018-708da600-caa4-11ea-99eb-63ce0963b34d.png">

**Comment by markus-walther** [comment]
Hi @johannabuguet, unfortunately this issue belongs somewhere else: our product is showcased on https://patterns.axa.ch/, whereas your issues all have to do with https://axa-design-system.netlify.app/.
