### ISSUE TITLE
The button "know more" leads to the wrong page

### ISSUE THREAD

**Issue by johannabuguet** [axa-ch/patterns-library#1886]
<img width="909" alt="Capture d’écran 2020-07-20 à 16 18 20" src="https://user-images.githubusercontent.com/68434693/87948170-a6cb2580-caa4-11ea-96c7-be3d17c560d1.png">

Current behaviour: The button "know more" on the "[getting started](https://axa-design-system.netlify.app/start 
)" page leads to the wrong page. 

Expected Behavior: the button should open the "[structure approach](https://axa-design-system.netlify.app/structure )" page

**Comment by markus-walther** [comment]
Hi @johannabuguet, unfortunately this issue belongs somewhere else: our product is showcased on https://patterns.axa.ch/, whereas your issues all have to do with https://axa-design-system.netlify.app/.
