### ISSUE TITLE
404 Error on the AXA DS UI kit

### ISSUE THREAD

**Issue by johannabuguet** [axa-ch/patterns-library#1887]
<img width="833" alt="Capture d’écran 2020-07-20 à 16 22 05" src="https://user-images.githubusercontent.com/68434693/87948856-88b1f500-caa5-11ea-980c-d2bd00eafb66.png">

The button "download the AXA design system UI kit" on the "[getting started](https://axa-design-system.netlify.app/start)" page, leads to a 404 error.

Expected Behavior: the button should lead the user to the brand hub :  https://brandhub.axa.com/media/?mediaId=1EB5A285-444E-47F8-AEF1F5E7EE14106A

Current Behavior: the button leads to a 404 error

**Comment by markus-walther** [comment]
Hi @johannabuguet, unfortunately this issue belongs somewhere else: our product is showcased on https://patterns.axa.ch/, whereas your issues all have to do with https://axa-design-system.netlify.app/.
