### ISSUE TITLE
Change the title "hero" to "hero cover"

### ISSUE THREAD

**Issue by johannabuguet** [axa-ch/patterns-library#1889]
<img width="1362" alt="Capture d’écran 2020-07-20 à 18 02 43" src="https://user-images.githubusercontent.com/68434693/87959559-61fabb00-cab3-11ea-9c41-f6be4e640227.png">

To be compliant with the other platform design.axa.com and the vocabulary we use on github, it would be better to call this page "hero cover" and not just "hero" 

https://axa-design-system.netlify.app/components/hero

**Comment by danyball** [comment]
@johannabuguet I think you are on the wrong repo for this issue?! Our project is https://patterns.axa.ch/
