### ISSUE TITLE
Datepicker remove width property

### ISSUE THREAD

**Issue by raphael-suter** [axa-ch/patterns-library#1894]
As discussed, it isn't necessary to keep the width property because it only sets inline-styles to the component tag.
We can remove it.

<img width="284" alt="Screenshot 2020-07-22 at 13 06 44" src="https://user-images.githubusercontent.com/52913998/88169448-3fd07c80-cc1c-11ea-960d-d00f25a5971e.png">

**Comment by 01231** [comment]
Not being able to set inline-styles seems to be a global problem with our components...

<img width="301" alt="Screenshot 2020-11-10 at 14 46 45" src="https://user-images.githubusercontent.com/38284563/98681918-909ee900-2363-11eb-8d75-6d268a1b1b32.png">
