### ISSUE TITLE
Unwrap testimonials in storybook and fix alphabetical sorting

### ISSUE THREAD

**Issue by raphael-suter** [axa-ch/patterns-library#1898]
The story for testimonials should be top level like all other component stories.

![Screenshot 2020-07-24 at 11 26 58](https://user-images.githubusercontent.com/52913998/88378590-9915e880-cda1-11ea-98e5-193d9bb7690e.png)

Couldn't do it because of a strange storybook behaviour: when unwrapped, storybook moves the entire components section into a folder below 'OTHERS'

![Screenshot 2020-07-24 at 11 37 43](https://user-images.githubusercontent.com/52913998/88378857-1f322f00-cda2-11ea-9dae-40872a366f5b.png)

We should try again as soon as we have updated our storybook to 6.0.0 (#1774).

**Comment by raphael-suter** [comment]
Storybook doesn't want us to have top level stories. I assume it only works due to a bug in the storiesOf Api that we are using to create our stories and that's why we have this weird side effect.

I guess the update wont help.

Also have a look at #1900

**Comment by danyball** [comment]
new Story format CSF always group by title. But we want to have a flat list. (Is also related to the alphabetical sorting.) --> storybookjs/storybook#8255
