### ISSUE TITLE
Storybook: hot-reload shows SB error

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1900]
Since reordering the Stories (Raphi S. PR) the hot reload is not working any more. Because the structure of SB stories changed.

- Maybe it is fixed with SB 6. #1774 
- Maybe use the new story format fixes that https://storybook.js.org/docs/formats/storiesof-api/#component-story-format-migration
- maybe revert raphis change d118f2d9

**Comment by raphael-suter** [comment]
We decided to leave it like that for the moment because of the better customer experience.
CSF does solve this problem because it doesn't allow having top level stories.

Also have a look at #1898
