### ISSUE TITLE
Lerna updates major versions of all our components

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1906]
Found a possible problem:

Found at `file-upload`. It has a dependency to `input-file`. input-file had a breaking change (text of button is now a attribute, not a child). Lerna updated this breaking-change version of input-file (4.0.2). 

consequence: The red button of file-upload is not showing the text "DATEI HOCHLADEN" anymore. --> this bug is in Prod right now (and fixed by PR #1904 )!

Do we want to change lerna so that major versions are not updated automatically?

**Comment by raphaellueckl** [comment]
[Team decision] We will add that point to DOD.

**Comment by raphael-suter** [comment]
Add "Check peer dependencies of components, if they still work" or something like that to the merge checklist.
