### ISSUE TITLE
Datepicker: navigation icons

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1908]
from iWARP Gamme Team:

1)	Das Hin- und Herspringen vom Monat ist aktuell durch die Dropdown wenig intuitiv. Könnte man zusätzlich nicht noch zwei Arrows links und rechts vom Monat machen?

**Comment by TommyHoliday** [comment]
ich habe die beiden feature requests zum datepicker (1908 + 1909) mit dem team besprochen und das wurde für gut befunden :-)

hier nun unser vorschlag: https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=3066%3A1 

- heutiges datum bleibt grau markiert
- pfeile rechts und links um monat zu wechseln
- hover nur 1px anstatt wie bis anhin 2px (konsistent mit anderen hover-effekten)

**Comment by raphael-suter** [comment]
![Screenshot 2020-08-31 at 15 16 29](https://user-images.githubusercontent.com/52913998/91739926-e3656300-ebb2-11ea-9c3d-f2063b7e92aa.png)
Sieht zwar etwas komisch aus, da Inputfield und datepicker nicht mehr bündig sind, wurde aber von @TommyHoliday abgesegnet.
