### ISSUE TITLE
Datepicker: "Today" should be marked

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1909]
from iWARP Gamme Team 

2)	Das heutige Datum ist beim erstmaligen Öffnen hervorgehoben. Sobald ich aber ein anderes Datum wähle, ist das Heute nicht mehr hervorgehoben. Könnte man das noch machen?

**Comment by TommyHoliday** [comment]
ich habe die beiden feature requests zum datepicker (1908 + 1909) mit dem team besprochen und das wurde für gut befunden :-)

hier nun unser vorschlag: https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=3066%3A1 

- heutiges datum bleibt grau markiert
- pfeile rechts und links um monat zu wechseln
- hover nur 1px anstatt wie bis anhin 2px (konsistent mit anderen hover-effekten)
