### ISSUE TITLE
Dropdown: Add the name of the component to onChange

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1910]
From Slack channel pattern-lib-devs:

Use case seems like this:
```
formStore
{
   name: "hans" -> text input
   address: "123" -> text input
   lang: 'de' -> select(dropdown)
   job: 'troll' -> select(dropdown)
}
```
generic select handler
`setFormStore({ [event.currentTarget.name]: event.target.value })
` generic input text handler
`setFormStore({ [event.target.name]: event.target.value }

**Comment by MKaHead** [comment]
More like the user suggestion, but breaking change:
1. small change -> would only be fixing AxaChangeEvent event.target.name that it should use dropdown prop name
2. more sense change -> at them moment item prop { name, value } instead should be { label, value } and write name prop from dropdown in axa change event event.target.name.
