### ISSUE TITLE
Add edit icon

### ISSUE THREAD

**Issue by sabine-schneider0209** [axa-ch/patterns-library#1915]
Hei there,
Could you please add an edit icon to your icon repo?
I think this would be helpful for many of us.
Thanks in advance
Sabine

**Comment by 01231** [comment]
Thanks for reporting. Closing this one because it is covered in #1731

**Comment by 01231** [comment]
will be finished with #1731

**Comment by raphaellueckl** [comment]
Reopening, since it was combined in a too big issue before. I will do that after I added the images of the esales-team.
