### ISSUE TITLE
Neue Images für Haushalt

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1916]
While migration of Household rechner ins POD haben wir festgestellt das folgende Images uns im PL Fehlen.

[SVG.zip](https://github.com/axa-ch/patterns-library/files/5034920/SVG.zip)

Fals möglich bitte bis ende August.

Danke!

**Comment by mpbauer** [comment]
Leider wurden noch 4 weitere Bilder aus unserem Haushaltsrechner vergessen. Ich würde euch bitten die fehlenden Bilder zu prüfen und ebenfalls in die PL aufzunehmen.

[Additional_Icons.zip](https://github.com/axa-ch/patterns-library/files/5094377/Additional_Icons.zip)

**Comment by TommyHoliday** [comment]
ich habe die fehlenden icons zu unserem ui kit hinzugefügt. (siehe anhang) 
die icons im ordner "additional icons" sind funktionale icons. wir werden bald sämtliche icons von google material design in die pattern library einbauen. dann sind diese dort ebenfalls verfügbar.
[icons.zip](https://github.com/axa-ch/patterns-library/files/5101775/icons.zip)

**Comment by raphaellueckl** [comment]
I will do it like @TommyHoliday suggests it. First add the icons, release it (for @chiquan-hong) and then start with the material icons.

**Comment by raphaellueckl** [comment]
PR is open, I will release after a successful review.
