### ISSUE TITLE
axa-dropdown: various differences to native select

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#1923]
axa-dropdown degrades to native &lt;select&gt; in narrow viewports, and can also be configured to always appear in `native` mode.

1. In this mode, a closed but focussed dropdown can be opened via up/down arrow keys. (n/a)
1. <del>Also, disabled items - realized as options - are greyed out but visible (n/a), and skipped over by keyboard navigation.</del>

In enhanced mode, the above points are not available (n/a), creating a difference in UX.

Resolve the differences  in favour of native &lt;select&gt;'s behaviour.

**Comment by markus-walther** [comment]
As per agreement with the designers (Jonas, Thomas), showing disabled options is currently not desired UX for in-house applications. As we don't want to implement features that _might_ be requested in the future, the agreement reached is to **ignore `disabled:true` in `items`**.

Hence the strike-through above.

**Comment by 01231** [comment]
@markus-walther please set the right label (bug or feature). If it is a feature it must be confirmed by the team before somebody starts implementing.
