### ISSUE TITLE
Checkbox without label is not clickable

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1929]
## Expected Behavior
Checkbox should be clickable also when no label is provided (empty string or undefined)

## Steps to Reproduce
https://patterns.axa.ch/?path=/story/components--checkbox

1. Select knobs
2. Clear label
3. Click Checkbox

Checkbox cannot be clicked

## Context (Environment)
This Error could result into **Blocker** error in Production in pod-rsv and pod-esales-cyber where such checkboxes are allready used.

**Comment by danyball** [comment]
We can reproduce that issue. Please set a whitespace as label to workaround that bug. But we will fix that. Thanks.

**Comment by danyball** [comment]
An optical issue if no label is set:
![image](https://user-images.githubusercontent.com/7448004/91424989-d5ce7700-e85a-11ea-9b84-334175910cd5.png)
