### ISSUE TITLE
axa-table-sortable: add new attribute to allow sanitizing html value

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#1959]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

## Expected Behavior
displaying Texts with HTML as pure text: <img src=#onerror=alert(1)>

## Current Behavior
HTML text output active (for example: <img src=#onerror=alert(1)> triggers a popup) 

## Steps to Reproduce

1. intercept RESTful call and insert malicious code or simply put in input field the malicious code, if no character validation
2. call page with axa-table and fill up the saved data with the malicious code
3. click on the row and run the script

## Context (Environment)
All Browsers possible, using the React library

## Possible Solution
follow the REACT security boundaries - mask special characters

**Comment by danyball** [comment]
Our component is just a frontend part which displays what a consumer "gives" us. If you give us html, we display it. That could be useful if you want to show a button or something. If someone intercept a backend call, this is an issue for the "caller" which sends it. (Maybe you are not using https). If you are doing a REST call you must check the response before you set the response to axa-table.

I dont see an issue at our component here.

**Comment by francescoRovetto** [comment]
Hi danyball - yes the HTML should be displayed as pure text like in REACT and other framework and libraries. The Problem is, that it does not behave the same way like REACT. This is a huge Problem, because we would need to program an extra exception for patterns-libraries components.

**Comment by francescoRovetto** [comment]
Hi danyball - yes the HTML should be displayed as pure text like in REACT and other framework and libraries. The Problem is, that it does not behave the same way like REACT. This is a huge Problem, because we would need to program an extra exception for patterns-libraries components.

**Comment by francescoRovetto** [comment]
Hi danyball - yes the HTML should be displayed as pure text like in REACT and other framework and libraries. The Problem is, that it does not behave the same way like REACT. This is a huge Problem, because we would need to program an extra exception for patterns-libraries components.

**Comment by danyball** [comment]
Can you give us a code snippet that shows your implementation?

**Comment by francescoRovetto** [comment]
This is my implementation:

            for (let y = 0; y < stores[0].state.limiten.length; y++) {
       
                    let zeile = [
                      {html: '<span style="float: right">' + stores[0].state.limiten[y].climDossierNr + ' '},
                        {html: '<span>'+stores[0].state.limiten[y].climAdresse[0].adresseAllinOne+'</span>'},
                                    {html: '<span>' + stores[0].state.limiten[y].climRef + '</span>'},
                        {html: '<span style="float: right">' + new Intl.NumberFormat(lokalesFormat).format(stores[0].state.limiten[y].climGLimEW * 1000) + '</span>'},
                        {html: '<span style="float: right">' + new Intl.NumberFormat(lokalesFormat).format(stores[0].state.limiten[y].climLimite * 1000) + '</span>'},

                    ];

                    tbody.push(zeile);
                }


        let model = {
            thead: [
                {html: headlineDrNumber, sort: 'DESC'},
                {html: headlineBuyer, sort: 'ASC'},
                {html: headlineCountry, sort: 'ASC'},
                {html: headlineReference, sort: 'ASC'},
                {html: headlineLimitDesired, sort: 'ASC'},
                {html: headlineLimitApproved, sort: 'ASC'},
                {html: headlineValidFrom, sort: 'ASC'},
                {html: headlineStatus, sort: 'ASC'},
            ],
            tbody: tbody,
        };


                        <AXATableSortable model={model} datesortcolumnindex="6" maxheight="0"
                                          onClick={(e) => {
                                              stores[0].tableMenuShow(e, stores[1].state.policeAusgewaehlt)
                                          }}/>

**Comment by francescoRovetto** [comment]
Something like this we need desperately (JSX option for save output) :

let zeile = [
                  {JSX: stores[0].state.limiten[y].climDossierNr},
                    {JSX: new Intl.NumberFormat(lokalesFormat).format(stores[0].state.limiten[y].climLimite * 1000)},
                ];

**Comment by danyball** [comment]
With this solution we had to decide what "safe" is. Is a `<span>` safe? Is a `<img>` safe? Or filter out Javascript code? This is too much complexity for our component. We are giving you the freedom to put any html to the table like you want. but through this freedom also comes the responsibility to only inject "safe" ("safe" in your interpretation) content.
Because your app dont want to execute JS you inject, but another app could need that?! And why do you inject JS if you dont want to execute? Please senatize the strings on your own.

EDIT: I have got an idea and will discuss that with the team. Maybe we can implement a compromise.

**Comment by francescoRovetto** [comment]
Hi Danyball
I propose to you, that there is a simple solution for this.

If there would be two options, it would serve everyone. One html option, which you can use for all kinds of functions [{html: '<span> </span'}] , and one pure text option [{text: 'I'm sanitized. This code <img /> is fully displayed'}].

I don't see the complexity in this. 

In terms of your note, we cannot simply sanitze our content for customer reasons but have to mask the special characters. The problem is, that I cannot mask characters in REACT JSX. This would mean, I have to program a huge workaround, which makes me think of removing axa-table for the sake of keeping our code simple.

EDIT: Thank you for discussing this, appreciate it.

**Comment by danyball** [comment]
Result after discussing it at our team:

- axa-table: not possible to sanitize, because we just style the input. We do not transfrom it in any way.

- axa-table-sortable: It is possible. We can add a boolean attribute to switch to sanitized value.

**Comment by danyball** [comment]
Talked to @francescoRovetto : It would be a solution to add a switch to `AXA Table Sortable`.
