### ISSUE TITLE
Icon story is not in alphabetical order

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1961]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

All component stories are sorted alphabetically, but the icon comes on first position.
## Expected Behavior

The icon story should follow the sorting of the components
## Current Behavior

<img width="210" alt="Screenshot 2020-09-09 at 08 53 03" src="https://user-images.githubusercontent.com/38284563/92564856-20e48300-f27a-11ea-8485-cf6619cc0e51.png">

## Steps to Reproduce

1. Open patterns.axa.ch
2. Look to the left side
3.
4.

## Context (Environment)

Mac OS; Chrome 85.0.4183.83 and Safari

**Comment by danyball** [comment]
Icon is not the only story. The whole list is unsorted. We have a issue that tracks this problem indirect: https://github.com/axa-ch/patterns-library/issues/1898

**Comment by 01231** [comment]
Okay I'll close this one and add a more accurate title to the issue #1898
