### ISSUE TITLE
New Images for Household part II

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1972]
Part 2 of: https://github.com/axa-ch/patterns-library/issues/1916

Unfortunatly we missed two icons in above mentioned issue. 

Here are the missing SVGs:
[MissingIcons.zip](https://github.com/axa-ch/patterns-library/files/5262008/MissingIcons.zip)

regards 
  Pavol

**Comment by TommyHoliday** [comment]
hey @pavol-marko & PL team,
i've harmonised those two icons, we can add these two to our icon set. however, in the future i'd suggest that we don't include "custom"-icons in the pattern library – it's just not maintainable in long term. please check the KMU 2.0 team for example. there we have 80+ custom icons and new ones are being added regularly. 
[icons.zip](https://github.com/axa-ch/patterns-library/files/5291421/icons.zip)

**Comment by pavol-marko** [comment]
Thanks,

We can do it, we allready have a mechanism to add icons to our library, or as KMU in their Microservice.

**Comment by raphaellueckl** [comment]
We let our designers decide if we add this to the pattern library of it it should be inlined on your side.

Best practice for the second option of inlining, use our axa-icon component.

**Comment by raphaellueckl** [comment]
We decided that we put those icons into the plib.
