### ISSUE TITLE
AxaDatepicker : defaultValue does not affect preselected value in Picker.

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1974]
defaultValue in Datepicker sets the input field, however when user clicks on the Picker, Today is selected instead of the Date in input. Note: If input is clicked first then picker opened the date is correct.

## Expected Behavior
The default value in picker is same as value in defaultValue

## Current Behavior
The defaultValue does not define, the preselection in picker

## Steps to Reproduce
Demo:
1. https://axa-ch.github.io/esales-ui-components/?path=/story/common-axa-datepicker-pure--default-with-validations
2. Open picker. Today is selected instead of predefined date: 2001-05-04
![image](https://user-images.githubusercontent.com/55141857/94007308-8d46a280-fda1-11ea-9d82-5a63157b9f31.png)

## Context (Environment)
Usability of Picker by the users is impacted.

**Comment by danyball** [comment]
Thanks for reporting. Can reproduce that.

Just to inform you about the latest change: `@axa-ch/datepicker@12.0.0 - breaking change: inputfield formatting is always dd.mm.yyyy irrespective of locale. (#1845)`

**Comment by danyball** [comment]
Reproducer at PL:
`https://patterns.axa.ch/?path=/story/examples-datepicker-react--story&knob-inputfield=true&knob-locale=de-CH&knob-year=&knob-month=&knob-day=&knob-disabled=&knob-autofocus=&knob-checkMark=&knob-label=&knob-monthtitle=Choose Month&knob-yeartitle=Choose Year&knob-invaliddatetext=Invalid date&knob-invalid=&knob-placeholder=Please select a date&knob-defaultValue=04.05.2012&knob-width=400&knob-allowedyears=["1971-2000",2012,2014,"2018-2022"]`

**Comment by markus-walther** [comment]
Note that `defaultValue` is only available under React.
