### ISSUE TITLE
Scope of l10n/i18n?

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#198]
I'm curious if we want to deal with **l10n** and **i18n** support.
Personally I'm a huge fan of native ES localisation formatting and would favour utilising mighty tagged template strings for this, baked by the [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).

http://i18n-tag.kolmer.net/
https://jaysoo.ca/2014/03/20/i18n-with-es2015-template-literals/

**Comment by LucaMele** [comment]
intl api is supported and we used it for dates.

**Comment by AndyOGo** [comment]
Great, though I think we have more Intl use case, or not?

**Comment by LucaMele** [comment]
If it pops up, we discuss it

**Comment by AndyOGo** [comment]
IMHO:
Since we want the patterns-library to be accepted, we are in charge of providing working and tested solution for professional apps.
And I18n is a core functionality for all apps, especially in switzerland.
So let's not ignore this important feature set.

If we even don't need more code...
We should at least provide manuals and examples of how I18n is supposed to be implemented.
