### ISSUE TITLE
AxaDatepicker: Picker opens on bottom even when there is not enough space there

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1981]
When Picker in Datepicker is opened the first time, it gets opened in the bottom disregarding if there is space or not.
Tested version: "@axa-ch/datepicker": "^12.0.0",

## Expected Behavior
Positioning of the picker(Top/Bottom) is correct the first time picker is opened, not only after scrolling/resizing the viewport.

## Steps to Reproduce
1. https://axa-ch.github.io/esales-ui-components/?path=/story/common-axa-datepicker--with-some-knobs
2. remove the bottom tab (with knobs and actions)
3. Click on the picker
4. Picker is opened bottom, even there is not enough space
5. After scrolling the Picker moves correctly to top
6. Reopening opens the Picker top. Yet this behaviour is expected the first time picker is opened

## Context (Environment)
This forces the user to scroll, not nice in straight-forward wizard (esales-pod-hh)

**Comment by 01231** [comment]
Looks a bit buggy. (I'm not scrolling here, datepicker just switches position from top to bottom and vice versa)
![](https://im5.ezgif.com/tmp/ezgif-5-86135e32b68f.gif)
