### ISSUE TITLE
Use special "introduction stories"

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#1991]
Component stories can be told apart much easier to pages like contact, welcome, whats new, etc. if we 
<img width="208" alt="Screenshot 2020-10-06 at 13 52 36" src="https://user-images.githubusercontent.com/38284563/95296517-32b94600-0879-11eb-8747-f55514e62301.png">

**Comment by 01231** [comment]
https://storybook.js.org/docs/react/writing-docs/doc-blocks

**Comment by raphaellueckl** [comment]
I asked they storybook guys. To achieve this, we need to stick to this part of the documentation and use MDX apparently: https://storybook.js.org/docs/react/writing-docs/mdx#documentation-only-mdx

**Comment by raphaellueckl** [comment]
[Teamdiscussion] Close
