### ISSUE TITLE
new Icons "Floor" and "Chair" to small

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2002]
Hello,

thanks for integrating the two new Icons. There is one problem with these two icon...they are displayed to small, compared to the other icons:
 
![image](https://user-images.githubusercontent.com/57704956/95464930-d1799b80-097a-11eb-9df3-e55de3ffe254.png)

The differences of these two icons are, that they have fixed width and height values and all the others icons do not have that (see Screenshot).

Here an example of the other icons, which is displayed correctly:
![image](https://user-images.githubusercontent.com/57704956/95465612-a8a5d600-097b-11eb-8e57-0719c2cf707a.png)

thanks and best regards,

Quan

**Comment by 01231** [comment]
Thanks for reporting, I'll fix it.
