### ISSUE TITLE
Progressbar für Wizards

### ISSUE THREAD

**Issue by remo-pfister** [axa-ch/patterns-library#2007]
Es wäre toll wenn die Patterns Library eine Progressbar für Wizards anbieten würde. Aktuell verwenden wir die Komponente vom ESales Team: https://github.com/axa-ch/esales-ui-components/

Die ESales Komponente könnte hier als Inspiration dienen.

Die Progressbar sollte folgende Features beinhalten:
* Beliebige Anzahl von Schritten 
* Markierung bereits erledigter Schritte
* Fortschrittsanzeige innerhalb eines Schrittes (Wenn ein Schritt z.B. Formular heisst aber aus mehreren Unterschrit
ten besteht.
* Stepper State sollte von aussen gemanaged werden können

Bild:
Rot: Erledigter Step
Blau: Anzeige das der Step erledigt wurde (inkl. "rotem" balken unten)
Grün: Wenn es Unterschritte innerhalb eines Schrittes gibt (z.B. besteht das Formular aus mehreren Seiten (Schritten) und 1/4 Seiten wurde bereits ausgefüllt)

![Progressbar](https://user-images.githubusercontent.com/67362381/95726227-f15dd780-0c78-11eb-8f11-83a356fb5621.png)

**Comment by danyball** [comment]
Vorabklärungen:

- Do we have a figma layout?
- what about smaller devices?
- should this component handle the content below?
