### ISSUE TITLE
Rendering problem and slow loading

### ISSUE THREAD

**Issue by GHNewbiee** [axa-ch/patterns-library#2011]
First of all, after `import '@axa-ch/icon';` the page comparatively started delaying to get loaded.

Second, it causes the page not to get loaded at all! White screen!

It is used within another component. But nothing wired, `css` very basic!

**Comment by raphaellueckl** [comment]
We have too little info about this and we highly suspect that there is some issue in your code. We and other projects import axa-icon several times and none of us experienced an issue with that. This could be anything.

I will close this here. If you can provide any jsfiddle or a link that proves that this does not work from our side, we will gladly reopen. But we have way too little evidence that this is a problem to start looking into such issues (it would be a major problem for almost all of our users if that did not work). Thanks for reporting though! :)
