### ISSUE TITLE
Installing materials leads to some items being kind of duplicated

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2012]
Example:

We have `attach_file.svg` and after someone is building that, he gets two files:

`attach-file`
`attach_file`

They differ slightly in content (both svg-path and svg-attributes), but we need to find out why we get two. This has to be something in our icon build.

[Feedback from @branislav-remen]

**Comment by branislav-remen** [comment]
I noticed issue with these icons:
`attach-file` and `attach_file` 
`check-circle` and `check_circle`
`cloud-upload` and `cloud_upload` 
`delete-forever` and `delete_forever`

**Comment by LucaMele** [comment]
@raphaellueckl what does "kind of duplicated" exactly mean? are they duplicated or not? From the description or title I cannot really understand the issue

**Comment by branislav-remen** [comment]
They looks the same: https://stackblitz.com/edit/react-ts-shlgtc 
![image (3)](https://user-images.githubusercontent.com/43781862/96966578-57b2e780-150e-11eb-973c-12e23fd372f8.png)

**Comment by 01231** [comment]
`attach-file` seems to be the version before the 12.0.0 release, because back then all files were named with `-` and not with `_`. And attach-file is not exported in the index.js.

**Comment by NoahLiechti** [comment]
And `attach-file` is not exported in the index.js

**Comment by 01231** [comment]
I can see the duplicated icons in the package but can they do not appear locally after building.

**Comment by raphaellueckl** [comment]
This is fixed now in @axa-ch/materials 13.2.3.
