### ISSUE TITLE
Datepicker month changing arrows cause form to submit

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#2015]
When clicking on month changing arrows surrounding form is unintentionally submitted. 

<img width="544" alt="Screenshot 2020-10-26 at 13 59 30" src="https://user-images.githubusercontent.com/8245106/97175527-ee440a80-1793-11eb-80a8-2aba2804c379.png">

## Expected Behavior
Form that uses datepicker is not submitted on month change via arrows.

## Reproduction link
https://codesandbox.io/s/divine-firefly-onfxi?file=/src/styles.css

## Possible Solution
Add type="button" explicitly to arrow buttons

**Comment by danyball** [comment]
resolved by https://github.com/axa-ch/patterns-library/commit/f407b3bdce441ed7c9aca4c5d10f53031ce37de1
