### ISSUE TITLE
Remove @axa-ch/materials from dependencies of other components

### ISSUE THREAD

**Issue by remo-pfister** [axa-ch/patterns-library#2017]
The package @axa-ch/materials is rather big (600kB, contains a lot of images and icons) and most projects (at least from my point of view) will not require more than a few of them. Wouldn't it be better if the components that render such icons and images expect them as input (props or children)?

Currently @axa-ch/materials is a dependency of many components and bloats up the project size. In our case it's about 30% of the project size and we only require one icon.

![image](https://user-images.githubusercontent.com/67362381/97412397-cffc1d00-1901-11eb-87a6-b3b66540b2d9.png)

**Comment by danyball** [comment]
We found that issue and start analysing why webpack did not tree shake all the images. https://github.com/axa-ch/midgard/issues/106

**Comment by markus-walther** [comment]
`<axa-icon icon="<svg>...</svg>">` allows rendering of arbitrary SVGs (also via URL), which might be a possible workaround for you in the meantime.

Can you post the code snippet of how you import that one icon that you need, and sufficient context (React, bundler used, etc.)?

**Comment by remo-pfister** [comment]
The patterns library does not use "default imports" to import the icons. Additionally the screenshot above does not add any value as it's an analyzation of the webpack build, not the rollup build. The Rollup build does not contain any node_modules as they are added later by midgard.
