### ISSUE TITLE
Inconsistent file naming in materials icons/images

### ISSUE THREAD

**Issue by 01231** [axa-ch/patterns-library#2019]
Since the 12.0.0 release the icons are named with an underscore instead of a hyphen. Images still use hyphens. This leads to a bad experience for our customers.

My suggestion would be to reverse the renaming of the icons.

<img width="234" alt="Screenshot 2020-11-02 at 09 17 36" src="https://user-images.githubusercontent.com/38284563/97845246-a7529980-1cec-11eb-80ca-f4d2530eb62d.png">

In addition the internal-icons are also named with hyphens.
<img width="174" alt="Screenshot 2020-11-03 at 09 16 05" src="https://user-images.githubusercontent.com/38284563/97962355-45aa3200-1db5-11eb-8b7c-0a503d3cf217.png">

**Comment by danyball** [comment]
We will discuss that with the whole team.

**Comment by 01231** [comment]
Closing due to team decision. Till no customer gives negativ feedback we won't do this breaking change.
