### ISSUE TITLE
Input-Text: new attribute "ignoreTouched"

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2023]
remo:

something to not show error while the user not touched the component.

Setup:
Input-text, invalid=true, errormsg=Fehler

IS:
errormsg is shown on startup

Should:
errormsg should only be shown if user has "touched"/focused the element

**Comment by remo-pfister** [comment]
Important: "Focused/Touched" the element once. 

If the user selects the input field by clicking on it (focus) and clicks on another part of the page (blur) the error message should be shown as well. It should not be shown when the input field has never been klicked before.

**Comment by danyball** [comment]
You can handle the state by yourself via "invalid" attribute. (details at teams chat)
