### ISSUE TITLE
File Upload Component (React): Add event if file is added

### ISSUE THREAD

**Issue by raphageiger** [axa-ch/patterns-library#2024]
In React, there is currently no built in functionality in the file upload component to get the file a user just dropped/selected because there are no events available.

**Use case** 
We are using the file upload component for a document recognition, where a user can upload images of every single page of a multi-paged document. The detection of the document should be triggered right after the user dropped/selected the image - before a upload / continue button outside the component is clicked.

**Comment by danyball** [comment]
> We are using the file upload component for a document recognition, where a user can upload images of every single page of a multi-paged document

I dont get it. Whats your use case? And what do you need at file drop event and why?

**Comment by danyball** [comment]
Feature: A event when user drops a file.

**Comment by raphaellueckl** [comment]
Also add an event for when a user removed a file.
