### ISSUE TITLE
Input-Text with currency: user needs a number to work with

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2035]
Problem:
a user type "2000" and we change that value to "CHF 2'000". If the pod wants to validate that value (or want to save it to the DB), he has to remove "CHF" and the `'` to get a valid number.

This problem should be solved if we have a solution for https://github.com/axa-ch/patterns-library/issues/2022.

A quicker solution could be to save the real number internally und push that value at the events. F.a. "onBlur" gets "2000" instead of "CHF 2'000".

**Comment by danyball** [comment]
UX team will discuss how the "CHF" will be displayed. If that is final we can refoactor our code

**Comment by raphaellueckl** [comment]
[Teamdiscussion] Close
