### ISSUE TITLE
"Knobs" should be the first tab a user sees when he opens a component

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2040]
See the image below. We should open the knobs for a user to directly start playing around. If he really is interested, he can "read into it" later, but the experience is always better if you give someone some "tools"/"haptics" first to really catch his interest. The readme is the same for all components anyway, at least the beginning of it.

![image](https://user-images.githubusercontent.com/8248662/100062710-54be5600-2e30-11eb-887b-8d4dfc3f0c55.png)

**Comment by danyball** [comment]
minimal change at the array for addons. why not
