### ISSUE TITLE
[Discussion] Add a title over each of our components

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2041]
In the current state, our components look like "a report without a title". We should discuss if it would look better, if the components appear with a title, so that amongst the most dominat things on each page, is where you were actually routed to.

Some look and feel examples:

![image](https://user-images.githubusercontent.com/8248662/100063265-3e64ca00-2e31-11eb-9222-499c277e8337.png)

![image](https://user-images.githubusercontent.com/8248662/100063364-6b18e180-2e31-11eb-9543-5c5f7f0fe1c0.png)

![image](https://user-images.githubusercontent.com/8248662/100063653-d2cf2c80-2e31-11eb-983f-52fa3e3df9ba.png)

![image](https://user-images.githubusercontent.com/8248662/100063794-00b47100-2e32-11eb-9a6d-59191a53fbd8.png)

**Comment by raphael-suter** [comment]
Addon docs.
