### ISSUE TITLE
add a new "Loss" image in Patterns Library

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2049]
Hi Guys,

we need a new image for our Digital Household Application, could u please integrate it in the patterns library?

it is the following SVG:
https://jira.axa.com/jira/secure/attachment/642943/Loss_icon.svg

thanks a lot and best regards,

Quan

**Comment by markus-walther** [comment]
As a general comment, can I kindly ask you to only use public URLs in issues for this public repo?

**Comment by raphaellueckl** [comment]
[Needs permission] Waiting until designer has given a go.

**Comment by danyball** [comment]
@raphaellueckl Pls ask Quan if he still need it

**Comment by raphaellueckl** [comment]
not needed according to our designers
