### ISSUE TITLE
Input Text component enhancement

### ISSUE THREAD

**Issue by predragpjanovic** [axa-ch/patterns-library#2062]
It would be nice if Input Text component could support different colors for input border and the message.

Here is one example of desired behaviour:
![image](https://user-images.githubusercontent.com/24625351/101166134-1565e580-3638-11eb-86ce-011960ca61fc.png)

**Comment by 01231** [comment]
Thanks for reporting. What would be the condition for the border to be yellow?

**Comment by raphaellueckl** [comment]
Our designer decided against it, for now. Thanks for your submission!

This would also lead to problems with accessibility, because of contrast and so on.
