### ISSUE TITLE
Toggle Switch: new feature on error

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2074]
Aus der BOX:

- [ ] mit UX AXA Schweiz abklären

- [ ] danach umsetzen

- [ ] evtl. auch in AEM einbauen

Hallo zusammen

Es steht ein geupdatetes Element im AXA UI Kit zur Verfügung. Der Toggle Button wird neu bei einer Fehlereingabe rot umrahmt angezeigt. Das Element müsste aktualisiert werden. Seid ihr auf das Thema bereits aufmerksam gemacht worden? 

LG & merci für euer Feedback
Anna

https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=1765%3A888

**Comment by markus-walther** [comment]
To be clarified with designers: should the red error border be rectangular or rounded?

**Comment by marcwelz** [comment]
Optional: add a border when the toggle switch is focused
