### ISSUE TITLE
Remove componentName from Usage-Addon params

### ISSUE THREAD

**Issue by raphael-suter** [axa-ch/patterns-library#2075]
**Before:**
![Screenshot 2020-12-15 at 12 35 27](https://user-images.githubusercontent.com/52913998/102210390-672d2c00-3ed2-11eb-9bd9-4eb44e0fa2f6.png)

**After:**
![Screenshot 2020-12-15 at 12 35 51](https://user-images.githubusercontent.com/52913998/102210396-68f6ef80-3ed2-11eb-8e3f-0197ba15345f.png)

We should find another way to detect which component is opened.

**Comment by danyball** [comment]
also remove `innerHtml` from stories.
