### ISSUE TITLE
Carousel error: this.removeEventListenerAnimationEnd is not a function

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#2077]
Carousel version installed: `3.2.7`

Browser console reports a carousel error: `Uncaught TypeError: this.removeEventListenerAnimationEnd is not a function`

![image](https://user-images.githubusercontent.com/43809369/102988633-7afd1180-4514-11eb-947a-17afde7371f3.png)

![image](https://user-images.githubusercontent.com/43809369/102988831-dc24e500-4514-11eb-8a81-003500fe134f.png)

**Comment by danyball** [comment]
Hi Marek, 
when do this error occours? Can not reproduce it at https://patterns.axa.ch/?path=/story/components-carousel--carousel

**Comment by danyball** [comment]
I will provide a fix without reproducing the exact issue. Pls have a look at the new version of the compoment after i released it to be sure that your issue is fixed. thanks.

**Comment by MarekLacoAXA** [comment]
Thanks @danyball, it worked! 👍
