### ISSUE TITLE
AXAButton of type submit doesn't submit form on Enter keypress

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#2078]
@axa-ch/button v6.0.8

If AXAButton of type submit inside of form is focused using Tab key and then Enter is pressed submit event on form is not triggered.

## Expected Behavior
Enter key press on focused submit button should submit the form.

## Current Behavior
Enter key press on button does not submit the form.

## Reproduction
https://codesandbox.io/s/agitated-haibt-b1h2p?file=/src/App.js

**Comment by danyball** [comment]
Thanks for reporting. We will check that issue.

**Comment by danyball** [comment]
Internal comment: be sure this issue has nothing to do with that old one: https://github.com/axa-ch/patterns-library/issues/1815

**Comment by danyball** [comment]
Internal2: outline has rounded corners??
