### ISSUE TITLE
Button and Button Link react differently to the keyboard key "space"

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2087]
## Current Behavior
Button and Button Link have a different behavior when they are "clicked" through ENTER and SPACE. ENTER works for both, SPACE just for `axa-button`.

## Steps to Reproduce
https://patterns.axa.ch/?path=/story/examples-button-link-react--clickable

Focus the button, hit ENTER and it will count up. Hit SPACE and nothing happens.

Here, both keys work:
https://patterns.axa.ch/?path=/story/examples-button-react--clickable

## Expected Behavior
They should have the same behavior:
Only ENTER should trigger the action. (remove SPACE reaction from button).

**Comment by danyball** [comment]
I would say thats not a bug. A link is not able to open via space. But a button is clickable via space.

**Comment by danyball** [comment]
https://lists.w3.org/Archives/Public/w3c-wai-ig/2019JanMar/0086.html

**Comment by danyball** [comment]
https://www.w3.org/TR/WCAG20-TECHS/SCR35.html

> The default action occurs when the user clicks the element with a mouse, but it also occurs when the user focuses the element and hits enter or space, and when the element is triggered via the accessibility API.

**Comment by danyball** [comment]
Would say "enter, space" is default for button. 
And just "enter" is default for links". --> but our button-link is a link, just looking like a button. So what do we want do do here?

**Comment by raphaellueckl** [comment]
Let's close it then. Thanks.
