### ISSUE TITLE
AXAInputText has double outline when focused while page is zoomed in

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#2090]
@axa-ch/input-text v4.5.9

This issue was also reproducible on v83 of Firefox without zoom

<img width="468" alt="Screenshot 2021-02-01 at 11 54 52" src="https://user-images.githubusercontent.com/8245106/106449750-97318e00-6484-11eb-9bad-194fb1272f9a.png">

## Expected Behavior
Input text has solid outline regardless of zoom and browser.

## Current Behavior
Input text shows double outline when focused on zoomed page.

## Reproduction link
https://codesandbox.io/s/agitated-haibt-b1h2p?file=/src/App.js

## Context (Environment)
Can be reproduced on our acc environment:

https://www.acc.axa.ch/de/test-pods/kmu20.html#/wizard/company-name

**Comment by danyball** [comment]
Also at Dropdown, Textarea, Datepicker. We will ask the designers.

**Comment by danyball** [comment]
@salle18 This is not a bug. The component is designed to have a hover-border effect. And to see a different to "selected" state there is another, 2px border. If you/your team do not like it please tell us exactly why and label this issue as a "feature request". Thank you!

**Comment by danyball** [comment]
@salle18 Sorry for confusing. I talked to the designers. hover state should be 1px, active state should be 2px. And you found the bug that just at firefox and 150% zooming there is are 2 thin borders instead of one 2px border?

**Comment by danyball** [comment]
@salle18 is it still a problem for you? if not, please close issue.

**Comment by salle18** [comment]
Closing the issue as this is more of a niche feature request
