### ISSUE TITLE
AXADatepicker add option to change year dropdown sorting

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#2091]
We would like to get an option to change sorting of years in the datepicker dropdown.
When there are more options it gets a bit tedious for the user to go to the previous year, see attached screenshot.
If this would lead to inconsistency across datepickers we would like to ask for sorting direction to be changed.

![image](https://user-images.githubusercontent.com/8245106/106454262-c5b26780-648a-11eb-9c0e-0bf449ed14ab.png)

**Comment by danyball** [comment]
We will ask our designers, thanks for your input. However, a solution would be constrained by the native dropdown in mobiles.

**Comment by raphaellueckl** [comment]
[Teamdiscussion] We will reverse the sorting, so that it goes from current year at first position down.
