### ISSUE TITLE
AXADatePicker: change text-format validation to use locale

### ISSUE THREAD

**Issue by JLou** [axa-ch/patterns-library#2094]
We would like to use your component with a french locale, but since you force the use of dot as a date separator, we cannot use the format we want (aka _dd/mm/yyyy_). Using dots does not make sense in french.

If we could disable validation on the text-value of the component it could also be a workaround.

**Comment by danyball** [comment]
This was a company decision made by our designers for axa switzerland. its a company guideline. We had to do extra efforts to unify date formats.
