### ISSUE TITLE
Button and ButtonLink not registering clicks made by cypress / Dynatrace Synthetic Monitors

### ISSUE THREAD

**Issue by bopplu** [axa-ch/patterns-library#2107]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

Our dynatrace monitor fails to get past screens where a button has to be clicked. Cypress  fails with the same issue.

## Expected Behavior
Clicks on buttons do not end in a noop.

## Current Behavior
Clicks run into a noop

## Steps to Reproduce
I've set up a small cypress project to showcase the issue in an isolated sandbox:
https://github.com/bopplu/patterns-lib-robo-test

Sandboxes:
old (working) version of the button and button-link: https://codesandbox.io/s/agitated-grass-2ocvd?file=/package.json
new (not working) version of the button and button-link: https://codesandbox.io/s/bold-shape-jvnv6?file=/package.json

## Context (Environment)
Issue is affecting us in testing and monitoring of our application, which currently has to be turned off.

**Comment by danyball** [comment]
Thanks for the 2 codesandboxes. But i dont get it? Where is the problem? A click on both buttons changes the text on my browser.

**Comment by bopplu** [comment]
Did you run the cypress test? Currently cypress and dynatrace fail to progress properly through the application for us.

**Comment by danyball** [comment]
No. Our components are designed for browsers. Maybe you have to set up cypress differently now. Please see details in our changelog.

**Comment by danyball** [comment]
We also have this issue at Testcafe. We will check that in detail.

**Comment by bopplu** [comment]
As far as we could tell so far, this commit seemed to change how it behaves 95fa8c4e3f52a9ee6e92f2b434aa4723b5ff4723

**Comment by raphaellueckl** [comment]
Teamdecision: axa-button and axa-button-link will become NoShadowDom. Remove the afterwards unnecessary code.

**Comment by markus-walther** [comment]
Actually, https://github.com/axa-ch-webhub-cloud/pattern-library/issues/2107#issuecomment-809261406 points to a simpler alternative than NoShadowDom conversion for these components: undo the hacky IE-11 compatibility work from the past. This has to be researched, and - if it works - is far less invasive, hence preferred as a solution to this bug.
