### ISSUE TITLE
3 standard sizes for icons?

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2110]
From Design Gilde:
Discuss how to set 3 standard sizes for icons/svgs

![image](https://user-images.githubusercontent.com/7448004/111483381-09a8b580-8735-11eb-9523-3ff36fde1049.png)

**Comment by danyball** [comment]
- at axa-ch/icon as a knob
- tell users that we recommend only these 3 sizes
- what about sizes at mobiles?

**Comment by marcwelz** [comment]
Do these sizes also account for the images?
