### ISSUE TITLE
Versioning: Datepicker 9.1.0 and 15.0.0 are not compatible - Versioning issue?

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2117]
Datepicker 9 and 15 (probably all others too) have a difference in CSS, which leads to the conclusion that component versioning probably does not work.

## Expected Behavior
Datepicker 9 and 15 can be displayed on the same page, without looking crippled.

## Current Behavior
Datepicker 9 and 15 can NOT be displayed on the same page, without looking crippled.

## Steps to Reproduce
1. Add Datepicker 9 to index.html
2. Add Datepicker 15 to index.html
3. Check the styling

## Context (Environment)
This occurred here: https://www.acc.axa.ch/de/rechner/mietkaution.html#/mieter

## Possible Solution
- Use Datepicker 15
- Create Datepicker 16 Alpha with massive CSS impact
- Check if issue still persists. If yes, we have a problem with component.versioning.

**Comment by markus-walther** [comment]
The statement "a difference in CSS, which leads to the conclusion that component versioning probably does not work." is incorrect. A difference in CSS, without specifics and detailed examination can not lead to such a conclusion.

What is evident from a brief inspection of index.scss:
 The basic rule of the CSS side of component versioning has been violated in line 79!

The basic rule is this:
![Screenshot 2021-03-24 at 11 56 10](https://user-images.githubusercontent.com/46926507/112299278-ef705980-8c97-11eb-89f7-9d07e9429ed4.png)

Section 'Solution', point 2, of https://github.com/axa-ch/patterns-library/blob/develop/COMPONENT_VERSIONING.md says the same thing.

The correct conclusion therefore is that component versioning works as intended, its users sometimes make mistakes in applying it.

We need to fix line 79 by transforming it into `axa-datepicker .m-datepicker`.
