### ISSUE TITLE
Datepicker test fails sometimes randomly (Azure Pipelines)

### ISSUE THREAD

**Issue by marcwelz** [axa-ch/patterns-library#2124]
The Datepicker playwright test sometimes fails randomly. 

## Expected Behavior
The test should not fail randomly.

## Current Behavior
The test fails randomly. If you re-run the test, the datepicker test won't fail anymore. 

The failing test is following:
  _Datepicker > should submit datepicker correctly in form_
  
  _Expected: "29.2.2020 (of 1 submittable elements)"_
  _Recieved: "29.02.2020 (of 1 submittable elements)"_

**Comment by raphaellueckl** [comment]
Team: Could be that this is related to a blur event that probably triggers after playwright validates the value.
