### ISSUE TITLE
Idea: publish our components to a CDN

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2135]
He serves a simple html website and wanted to use the button. He would prefer a CDN for that because of security reasons.

Do we want to deploy our components to our (new) cdn? pro/con?

**Comment by danyball** [comment]
If we have our own CDN this would be a useful thing. Until then use `unpkg`.

**Comment by raphaellueckl** [comment]
This ticket is not needed imho, as that will happen anyways, as soon as we have a CDN (whenever that will be the case). https://unpkg.com/ is sufficient until then. This just pollutes our issue board for the time being.

**Comment by raphaellueckl** [comment]
[Teamdiscussion] Close
