### ISSUE TITLE
TS interface AXAButtonProps lacks event argument for onClick function

### ISSUE THREAD

**Issue by CodeDatPiece** [axa-ch/patterns-library#2136]
## Expected Behavior
When using the AXAButton Component  it should be possible to pass an event as argument to the onClick function.

## Current Behavior
When using the AXAButton Component with TypeScript, it is not possible to access the event in the provided onClick function, 
without making use of @ts-ignore because the onClick function attribute in the interface AXAButtonProps does not allow any arguments (such as an event).

## Steps to Reproduce
```
<AXAButton
  type='submit'
  variant='red'
  // @ts-ignore --> HERE WE NEED TO USE @ts-ignore because the onClick function does not allow arguments.
  onClick={e => {
    e.preventDefault();
    fooBar();
  }}
>
  suchen
</AXAButton>
```

## Context (Environment)
We want to prevent the defualt event of an submit button.

## Possible Solution
Add an event argument to the onClick function on interface AXAButtonProps.

**Comment by danyball** [comment]
Thanks for reporting. We will check that in detail and give u feedback soon.
