### ISSUE TITLE
Add linear progress loader

### ISSUE THREAD

**Issue by marcwelz** [axa-ch/patterns-library#2140]
Adding a progress loader who can be utilised when the length of a specific task can be determined. 

Figma: **https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=6107%3A2**

**Comment by marcwelz** [comment]
To the team: should we use `<progress>` or a `<div>` tag?

**Comment by danyball** [comment]
> To the team: should we use `<progress>` or a `<div>` tag?

if `<progress>` is style-able then use it (like Markus said).
