### ISSUE TITLE
package-lock seems to toggle these changes on every release

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2141]
Should:
Release script should not stop.

Is:
 release stops every time because of "uncommitted changes"

![image](https://user-images.githubusercontent.com/7448004/115883208-d3ee9f00-a44d-11eb-96c1-a1b03e90f78d.png)

**Comment by danyball** [comment]
maybe its fixed with latest release-script update of raphi

**Comment by raphaellueckl** [comment]
Closed in peer review with Amir.
