### ISSUE TITLE
File Upload: extend range of allowed files with the *.xlsx format

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#2174]
Hi all,

In our AXA department, we are currently using the old version of the File Upload, which allows a wide range of file formats.

For the new business requirement, we need to upgrade the module to the current version with the drag & drop feature. 

We tested it out and found out, that the range of allowed file formats does not include *.xlsx. Now, we analyzed the need of this format and found out that we cannot be without the allowed type of *.xlsx. We are also very confident, that it is of a great use when excel files still can be uploaded, since there are especially many business customers uploading their calculated reports for the analyzation of the data. It is also hard to format big excel sheets in a way, that it is still readable in a PDF.

The manager of our debt collection department wrote following:

"Betreffend Excel-Dokumente sehe ich die Notwendigkeit klar als gegeben an, alleine wegen Forderungsaufstellungen (z.B. OP-Listen). Dies sieht man ja auch am WF-Archiv, wo immer wieder Excel-Dateien abgelegt sind.
Bei Word-Dokumente sehe ich dies weniger, weil dies eher im Text-Format unnötig ist und vielmehr als PDF hoch geladen werden kann. Bei Excel-Dateien geht dies zwar auch, aber man kann nach Transformation in ein PDF nicht mehr funktional arbeiten.

Also: Excel ist sicher notwendig, Word eher weniger. Die Frage ist, ob man nicht einfacherweise beides ermögliche will. Das hängt natürlich von den Ressourcen ab."

Our AXA department has only business customers, that's why we receive also business relevant data. And that's why *.xlsx is a must have to communicate.

We appreciate your work and are grateful for the many components that you keep on maintaining! :-)

**Comment by danyball** [comment]
Doublette https://github.com/axa-ch/patterns-library/issues/2134

**Comment by 01231** [comment]
Thanks for reporting. I'll close the issue because there is already a similar issue. (#2134)
