### ISSUE TITLE
Consistent Prefilled Placeholder Text for Datepicker

### ISSUE THREAD

**Issue by jojackpot** [axa-ch/patterns-library#2175]
A useful pattern for users to understand the expected date format is to display am example format in the input field. 
For example: dd.mm.yyyy

This would also ensure consistency for all consumers all over the hub. 

Request: 
- Change Placeholder Text to "dd.mm.yyyy"

**Comment by marcwelz** [comment]
You can change the placeholder on your own with the `placeholder` attribute.

**Comment by 01231** [comment]
Closing this one because feature is already implemented.
