### ISSUE TITLE
Deprecation warning due to latest Sass Version

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2177]
We changed from node-sass to latest Sass Version and now we get some deprecation warnings which relates to the patterns library (see screenshot).
here is the reason why we changed from node-sass to sass described https://sass-lang.com/blog/libsass-is-deprecated.

![image](https://user-images.githubusercontent.com/57704956/120643320-4d7aa380-c476-11eb-84d9-bebf4a48198b.png)

KMU is also using Sass and will run into the same problem, if they upgrade Sass to the latest Version.

And here is what needs to be done:
https://sass-lang.com/documentation/breaking-changes/slash-div.

Thanks and best regards,

Quan

**Comment by 01231** [comment]
Maybe we have to switch from node-sass to dart-sass package:
`Node Sass does not work with Yarn PnP feature and doesn't support @use rule.` 
https://www.npmjs.com/package/sass-loader
