### ISSUE TITLE
Getting Startet React example mistake

### ISSUE THREAD

**Issue by tim-dubath** [axa-ch/patterns-library#2192]
Getting Startet React example mistake

## Expected Behavior
It should work if you just copy and paste the example.

## Current Behavior
It can't find the name AxaButtonReact

## Steps to Reproduce

https://patterns.axa.ch/?path=/story/guides-getting-started--getting-started
Scroll down to the React section and copy the Code. 

## Context (Environment)

It's nothing that concerns me but the example code from the pattern library should already work with copy and paste.

Windows 10, IntelliJ IDEA 2020.2

## Possible Solution

import {createElement} from 'react';
import createAXAButtonReact from '@axa-ch/button/lib/index.react';

const AXAButtonReact = createAXAButtonReact(createElement);

<AXAButtonReact motionOff>
                I am a Button
</AXAButtonReact>

Of course you could also add an onClick function

This form does not allow me to paste my code. For this reason I could send it to you via email. However, I do not know your email address. Therefore I ask you to send me an e-mail at: tim.dubath@axa.ch

Kind regards
Tim Dubath

**Comment by LucaMele** [comment]
@tim-dubath thank you very much for the submission, we will look at it and comment here our result. Please note, if you need to contact us, you can find details here: https://patterns.axa.ch/?path=/story/others-contact--contact

**Comment by tim-dubath** [comment]
@LucaMele 
Hi Luca, I just noticed it is in every single component on the usage Tag. In the open-tag you write AXA in Caps and in the close tag you write it "Axa". I noticed it only in the react "usage" part.

**Comment by 01231** [comment]
Ups, didn't see your issue and opened a similar one.

**Comment by raphaellueckl** [comment]
This is fixed now, thx.
