### ISSUE TITLE
Feature deployment announcements in Slack

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2199]
Slack notifications no longer work, since the repo was moved. Plz investiage.

Hint: I guess it's connected to the slack token, check the pipeline logs.

**Comment by 01231** [comment]
They do work, don't they?
<img width="499" alt="grafik" src="https://user-images.githubusercontent.com/38284563/124710209-be412f80-defc-11eb-8c99-f3200f9bdaa5.png">

**Comment by 01231** [comment]
Closing the issues because it's resolved.
