### ISSUE TITLE
build error when trying to build with the latest version of materials

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2202]
in our esales-ui-component-library, we wanted to import the latest version of the axa materials, cause patterns library replaced node-sass with sass in that latest version.
when we imported the latest materials version and try to build, we got the following error message:
![image](https://user-images.githubusercontent.com/57704956/123106596-078f7a80-d439-11eb-93a2-8346c59b557e.png)

so at the moment we are not able to use the latest version of axa-materials.

thanks for your help.

best regards,

Quan

**Comment by 01231** [comment]
It looks like, I have to revert the changes made. There is an open issue with rollup-plugin-css here:
https://github.com/thgh/rollup-plugin-scss/issues/70

I guess we have to live with this warning for now. #2177

**Comment by chiquan-hong** [comment]
oh....ok. can you let me know when u have done an revert. 

Thanks Noah for your help.

**Comment by 01231** [comment]
yes I will @chiquan-hong
