### ISSUE TITLE
Border and Hover Styling issues of Table Component (Browser Incompatibility)

### ISSUE THREAD

**Issue by remo-pfister** [axa-ch/patterns-library#2203]
## Expected Behavior
I expect that the borders of the rows do not disappear when I hover over a row and leave the row again

## Current Behavior
After hovering over a row and leaving again, the upper border is missing.

## Steps to Reproduce
1. Open Microsoft Edge (Version specified below)
2. Navigate to https://patterns.axa.ch/?path=/story/components-table--table
3. Hover over an entry row
4. Leave the hovering area of this row
5. Upper border should now disappear (if you hover over it again, it will reappear)

![image](https://user-images.githubusercontent.com/67362381/123369196-99080500-d57d-11eb-8fcc-eade1548e47b.png)

## Context (Environment)
* Microsoft Edge Version 91.0.864.41 (Official build) (64-bit) (Maybe in others as well, Chrome is not affected)

## Possible Solution
Most likely this is related to the styling changes performed when hovering over an element. Maybe you need to add some Microsoft specific css.

**Comment by remo-pfister** [comment]
Additionally, sometimes the right border stays blue after unhovering a row.

**Comment by 01231** [comment]
I can reproduce it (also that with the right border)👍🏼

**Comment by 01231** [comment]
After investing a good amount of time we decided that this must be an issue in the Edge Chromium itself. No other browser has the same problem and it should behave like Chrome...
It you can prove that this is not a browser bug feel free to reopen the isse.
