### ISSUE TITLE
Interrupted Border in Table Component

### ISSUE THREAD

**Issue by remo-pfister** [axa-ch/patterns-library#2204]
## Expected Behavior
There are no interruptions in the borders.

## Current Behavior
The borders of the table rows areinterrupted.

## Steps to Reproduce
1. Open Browser and navigate to https://patterns.axa.ch/?path=/story/components-table--table

![image](https://user-images.githubusercontent.com/67362381/123369824-cdc88c00-d57e-11eb-9b0a-23b4fe4f3130.png)

## Possible Solution
Most likely are the borders defined for each table cell but should actually be defined for the whole row.

**Comment by 01231** [comment]
I can reproduce it on Chrome 👍🏼

**Comment by 01231** [comment]
Also top left corner doesn't look correct.
<img width="363" alt="grafik" src="https://user-images.githubusercontent.com/38284563/125084021-5d1a8700-e0c9-11eb-9775-648c4e9b1b67.png">
