### ISSUE TITLE
Modal does not close in setting "open" to false

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#2210]
Having following code, the modal does not close if setAttribute is set to false. It closes only using X or ESC

```html
<axa-modal class="js--modal"></axa-modal>
<axa-button variant="secondary" class="js--trigger-modal">Toggle Debug Modal (or Press "d")</axa-button>
<script>
    const modal = document.querySelector('.js--modal');
    const btn = document.querySelector('.js--trigger-modal');
    let open = false;

    const toggleModal = () => {
      open = !open;
      modal.setAttribute('open', open);
    }

    document.addEventListener('keyup', (e) => {
       if (e.code === 'KeyD') {
         toggleModal(e);
       }
    });

    btn.addEventListener('click', toggleModal);
</script>
```

![image](https://user-images.githubusercontent.com/275235/124940536-5e38af00-e00a-11eb-98e5-3c17b8233fff.png)

**Comment by marcwelz** [comment]
Thanks for reporting this bug!
I will have a look.

Therefore you can use `removeAttribute()` to close the Modal

**Comment by LucaMele** [comment]
@marcwelz thank you, actually in HTML attributes are considered as "false" if not there and "true" if there empty or there with value same as name. So removeAttribute is actually the correct way, so i guess no bug. thanks! Feel free to close it
