### ISSUE TITLE
Center datepicker on mobile screen

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#2216]
We got a request from our BAs that it would be nice if datepicker was centered on mobile screens.
Since datepicker is positioned dynamically there was no way for us to do this through css or other means.

![image-2020-11-03-08-59-17-731](https://user-images.githubusercontent.com/8245106/126135786-4b285aa5-8185-4529-86e2-b2b480fcb592.png)

**Comment by raphaellueckl** [comment]
We need a decision from our designers for this request. Ken or Jonas. I will forward it, thank you!

**Comment by kenaxa** [comment]
Hoi zusammen,

Wie besprochen wäre die beste Lösung jeweils den Native Date Picker auf den Geräten anzuzeigen. Es gibt einen android und ios Datepicker dazu. Windows Phones müsste man kurz in erfahrung bringen wie unser date picker dargestellt wird.

Und wenn man unseren Datepicker auf Mobilen Geräten anzeigen will und es so grossflächig ist braucht man oben Rechts ein "X" um das fenster zu schliessen.

Raphi komm auf mich zu wenn Du weitere Details dazu brauchst.

**Comment by markus-walther** [comment]
Witness the following screenshot:
![Screen Shot 2021-10-05 at 14 54 51](https://user-images.githubusercontent.com/46926507/136026678-ccc4e7dd-3c01-4847-a505-28fabd2241b2.png)

It shows that always centering the datepicker on mobile is likely not a sensible request. Here we have a datepicker that operates in inputfield mode. In this mode, with datepicker dropped down, users will instinctively align the left vertical borders of both the input field and the datepicker proper. A centered datepicker would destroy that sensible perception.

Conclusion: at best, the feature request can be narrowed to non-inputfield mode.

As the horizontal red arrow nicely demonstrates, there _is_ in fact a way to solve the issue depicted in the original screenshot of the reporter, namely by changing the left margin responsible for positioning `<axa-datepicker>` in client CSS. Wouldn't that be a solution?

@kenaxa: while in general your suggestion is reasonable advice, a native datepicker does not have all the functionality built into `<axa-datepicker>`, which was specified and engineered to be responsive, including to mobile viewport sizes. Changing that deeply entrenched assumption now would incur a very high reengineering cost.
