### ISSUE TITLE
axa-table-sortable does stop sort big numbers

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#2219]
Trying to sort big currency numbers fails when the Number is >= 1'000'000

## Expected Behavior
Sorting the numbers also above 999'999

## Current Behavior
Stops sorting after 999'999

## Steps to Reproduce
1. Provide List with numbers below and above 1'000'000 and format them like a currency.
2.  Click on the title of the Currency Column to sort.
3.  look for the numbers above 999'999 and you will find them out of order.

## Context (Environment)
Customer tries to find a number by sorting them
Edge, Chrome, Firefox

## Possible Solution
-

**Comment by marcwelz** [comment]
What do you mean with "format them like a currency"? When I use an integer above 999'999 and add the "$" symbol, it works perfectly fine (Safari & Chrome).

![image](https://user-images.githubusercontent.com/68916291/131666056-8df6096b-2089-45c4-a240-b7cbf3629e01.png)

**Comment by marcwelz** [comment]
Closed due inactivity and I can not reproduce the issue.

Reopen if necessary

**Comment by francescoRovetto** [comment]
Hi Marc! you forgot to add the decimal separator. I think that might be the cause of the problem.

Sorry I haven't seen your response. How can I reopen the case?

**Comment by francescoRovetto** [comment]
This issue is continued in the following feature request: https://github.com/axa-ch-webhub-cloud/pattern-library/issues/2235
