### ISSUE TITLE
File Upload - Show server validation

### ISSUE THREAD

**Issue by Hatzman91** [axa-ch/patterns-library#2222]
We'd need the posibillity for E-Forms to show the user an errormessage on the File Upload component when a file throws an error on the server validation (e.g. maleware check, to big over all components)

Our wish would be to have a function, where we just give the file-id and the error message, and then the component and the mentioned file is set to invalid

**Comment by asalinifugoch** [comment]
@Hatzman91 can you please give me a feedback about the time frame of this FR? Do you need more information about it? Thank you, Altug

**Comment by raphaellueckl** [comment]
@asalinifugoch Simon contacted me over slack before some time and as far as I remember, you guys would try it out with the information I gave him. Server side validation has to be made on your side and you should set the file upload to "invalid" and add an error message (which will be defined by the server).

**Comment by markus-walther** [comment]
Today's meeting with @asalinifugoch clarified the requirements of this feature request:

- The 'file-id' is the value of the `id` attribute of the browser-native `File` object, which serves as cross reference to the server-side validation
- The desire is to allow asynchronous invalidation of already uploaded files, once server-side validation has declared them invalid

We should either 

- provide a worked example showing how this can be achieved with existing functionality _or_
- accept this feature request and provide suitably designed functionality

**Comment by markus-walther** [comment]
This cannot be achieved using the public, documented API. Here is a patch for an `invalidate(file, clear, globalErrorMessage)` method:
[patch.txt](https://github.com/axa-ch-webhub-cloud/pattern-library/files/7454895/patch.txt)

**Comment by asalinifugoch** [comment]
Your patch looks good. Thank you @markus-walther
