### ISSUE TITLE
Reset File Upload possibility

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2223]
Francesco Rovetto had a request regarding resetting the file upload's content. He had a dropdown with different categories of files. When the dropdown changes, the fileupload should become empty. This is currently not possible without recreating the file upload component.

Step by step:
- A user has to upload several documents in several areas.
- User choses "mortgage" in the category dropdown, and adds mortgage related documents to the file upload.
- User clicks the "submit" button.
- User choses "insurance" in the category dropdown.
- The file upload resets to zero files.
- User adds insurance related documents to the file upload.
- ....

**Comment by raphaellueckl** [comment]
@markus-walther We should discuss this.

**Comment by markus-walther** [comment]
Since this is easy in native `<input type="file">` https://stackoverflow.com/q/1703228, we should indeed support it, too.
