### ISSUE TITLE
Button Link doesn't change height to show long text when styled with a width

### ISSUE THREAD

**Issue by stefan-kueenzi** [axa-ch/patterns-library#2234]
## Expected Behavior
Button Link changes height to show long text when styled with a width

## Current Behavior
Button Link doesn't change height to show long text when styled with a width.

## Steps to Reproduce
Go to https://patterns.axa.ch/?path=/story/components-button-link--button-link
Set a long text for the button
Use Browser DevTools to set width of the Button Link

## Possible Solution
Should have same behavior as the Button, which changes it's height for a long text.

**Comment by markus-walther** [comment]
![Screen Shot 2022-07-25 at 11 25 26](https://user-images.githubusercontent.com/46926507/180744448-0011436e-a3ce-4e41-8c84-b4e82faa3ea2.png)
I did exercise the steps you listed and could **not** reproduce the issue (see screenshot above).

**Comment by stefan-kueenzi** [comment]
2 Lines of text fit within the 40px of the default height. Maybe try with a text that would need more than 2 lines to display?

**Comment by markus-walther** [comment]
Yes, further testing reveals the problem occurs with long-enough text. Will discuss with the team. It would have been good to be precise with what text has been tested and show the level of detail that I showed with my screenshot.
