### ISSUE TITLE
Controlled Input Text won't render updated value

### ISSUE THREAD

**Issue by branislav-remen** [axa-ch/patterns-library#2236]
Controlled Input Text won't render updated value when field already had some focus on it in Safari browser.

## Expected Behavior

In Safari browser, when we set value to controlled input text, value should be visible in the field.

## Current Behavior

When we set value to controlled input text, new value is not visible in the field in Safari browser.

## Steps to Reproduce

https://patterns.axa.ch/?path=/story/examples-input-text-react--controlled-uncontrolled

1. Open link above
2. Click to first field = add focus (in images Safari on the left, Chrome on the right side)
![image](https://user-images.githubusercontent.com/43781862/140048722-cbb624e3-0388-471d-8798-818219bdb8fe.png)

3. Click to second field.
![image](https://user-images.githubusercontent.com/43781862/140049264-ca4163e6-8630-488e-851c-9c946d984d48.png)
 
4. Change value in the first or second field (In screenshot I changed in the second field).
In chrome - value is changed in both fields. 
In safari - value is changed only in second field.
![image](https://user-images.githubusercontent.com/43781862/140049043-88b550c4-d30f-49a1-8f2d-fe53ba306c8a.png)

#### Note: It works when you won't add focus to the second field. Just click only to first field (with label `Controlled *`) and change value. It works in both browsers.

![image](https://user-images.githubusercontent.com/43781862/140048365-4760755c-3913-41fb-ac1b-247e9f7ad219.png)

![image](https://user-images.githubusercontent.com/43781862/140048396-724451a2-d290-4714-94e3-b127ecb8a8b7.png)

#### example from pod-myaxa:

1. When editing Communication data block, we have option to fill email field by clicking on Link. It will set new value to email field.

2. We click to link:
![image](https://user-images.githubusercontent.com/43781862/140046978-5bc82c1a-74ba-4db9-adf1-a5290c557971.png)

3. Form is now valid - email field is set but new value is not visible (only in Safari browser).
![image](https://user-images.githubusercontent.com/43781862/140047036-c806ba56-619d-44f3-8c77-bed72d6cf655.png)

#### env
macOS BigSur 11.6.1
The latest version of component (bug is also in your storybook)
Safari 15.1 (16612.2.9.1.30, 16612)

## Possible Solution

🤔

**Comment by raphaellueckl** [comment]
Thanks for this detailed issue. I'm not sure when we will be able to fix it as we are very low in number of staff at the moment.

**Comment by markus-walther** [comment]
**New test URL for reproduction:** https://patterns.axa.ch/?path=/story/examples-input-text-react--input-text-controlled-uncontrolled

**Comment by markus-walther** [comment]
Accepted, since I could reproduce it on MacOS Monterey 12.5.1  Safari Version 15.6.1 (17613.3.9.1.16).

**Comment by MKaHead** [comment]
There was a Safari hack that caused this problem. To me it made no sense at all code-wise. Besides, everything runs fine in Safari, maybe there was a problem on a mobile Safari. The comment was about the cursor. As long as it's just an exceptional problem, we can live with it.
