### ISSUE TITLE
Falsche Position der Fehlermeldung und Löschen der Files ergibt einen Fehler

### ISSUE THREAD

**Issue by asalinifugoch** [axa-ch/patterns-library#2239]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

Vom Server abgewiesene Files müssen im UI als Fehler markiert und vom Benutzer gelöscht werden können. Aktuell wird das falsche File im UI markiert. Und beim Löschen gibt es einen Fehler. 

## Expected Behavior

Die Fehlermeldung soll an der richtigen Position / File  angezeigt werden.
Löschen der Fehlerhaften Files soll funktionieren.

## Current Behavior

Die Fehlermeldung des fehlerhaften Files wird immer am Ende der Liste im UI angezeigt, obwohl sich das fehlerhafte File an einer anderen Position im Array befindet. Siehe Screenshot. Es handelt sich um die Files die nicht zum Server hochgeladen werden, weil sie aus irgend einem Grund nicht erlaubt sind. Mit der Methode invalidate() kann der error gesetzt werden, jedoch an der falschen Position. Die Files, welche so invalidiert wurden lösen einen Fehler beim Löschen in der Konsole aus. Das File bleibt dann noch in der Liste, bis alle Files aus der Liste gelöscht wurden.

Mir ist aufgefallen dass es nur auftritt bei den Fehlermeldungen die per invalidate() gesetzt wurden.

## Steps to Reproduce

1. auswählen von mehreren Files und hinzufügen.
2. löschen des Files
3.
4.

## Context (Environment)

Ich versuche fehlerhafte Files, welche vom Server abgewiesen wurden, zu markieren und dem Benutzer die Möglichkeit zum Löschen der Files geben.

## Possible Solution

![error-ondelete](https://user-images.githubusercontent.com/2573534/142228749-caa03648-537b-4fe5-b1f4-e2cc81908691.PNG)
![Wrong-Erromessage-Position-UI](https://user-images.githubusercontent.com/2573534/142228753-eeee23a8-21ff-4ca3-be14-e2e25dcfa039.PNG)

**Comment by markus-walther** [comment]
Thank you for the bug report!

The delete aspect of this bug has been reproduced and needs to be fixed.

As for the order aspect - faulty files are always at the end in left-to-right, top-to-bottom UI order - this is consistent with internal validation and unlikely to be fixed in this ticket (since it appears to be in line with the UX spec for this component).

**Comment by asalinifugoch** [comment]
Thank you for your feedback.

Ok, but how we shoud set the correct faulty file in the ui, if ist not possible to set it by id? Do you have any suggestion?

**Comment by markus-walther** [comment]
> Thank you for your feedback.
> 
> Ok, but how we shoud set the correct faulty file in the ui, if ist not possible to set it by id? Do you have any suggestion?

I am not sure I understand. The correct faulty file is identified by the .id value of a File object passed as arg 1 of the invalidate method, as per the README. This works, and is tested in an end-to-end test. Any faulty files are consistently moved to the end of the file-preview UI, *visually*, as per approved UX for this component. This behaviour is desired, and will not be fixed (at least not quickly, if ever).
