### ISSUE TITLE
focus() inside of axa-container doesn't work

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#2240]
## Expected Behavior
in the lifecycle method componentDidMount(), I want to set the first text field on focus, so that the customer doesn't need the mouse to click on the field.  The text field, which needs to be set on focus, is inside of the axa-container.

## Current Behavior
When setting the text field on focus, nothing happens. Probably the shadow-dom of the axa-container causing this.

## Steps to Reproduce
1. search textfield with findElementById in the lifecycle method componentDidMount()
2. proof if the textfield is available.
3. if available, add .focus() to the found element.
4. refresh
5. cursor should appear in the chosen textfield, but nothing happens

## Context (Environment)
- Working with React Lib, issue appears in all browsers.

## What it affects
- restricted user handling.

**Comment by raphaellueckl** [comment]
Hi Francesco

Do you have a site where we can reconstruct this? And can you tell us how you were looking for that element to set the focus? Thanks in advance. :)

**Comment by francescoRovetto** [comment]
Hi Raphael, do you have a sandbox, which I can reuse? The only site I can share is our customer frontend Project:

https://github.axa.com/axa-ch-opk/opk-frontend

This is what I'm trying to do - without the axa-container, it would work: (see row 16)

```
import React, {Component} from 'react';
import {FormattedHTMLMessage, injectIntl} from 'react-intl';
import {withRouter} from 'react-router-dom';
import policenContainer from '../../../containers/Policen/policenContainer';
import connect from 'unstated-connect';
import {AXAContainer} from '../../patterns-library';


class PolicenUebersicht extends Component 

	componentDidMount() {
		const stores = this.props.containers;

		if (document.getElementById('firstField')) {
			document.getElementById('firstField').focus();
		}
	}

	render() {
		const stores = this.props.containers;
		const intl = this.props.intl;
		const headerPolNr = intl.formatMessage({
			id: 'kred.glob_polnr',
			defaultMessage: 'Policennummer',
		});
		const headerCompany = intl.formatMessage({
			id: 'kred.adress_company',
			defaultMessage: 'Firma',
		});
		const headerAdress = intl.formatMessage({
			id: 'kred.adress',
			defaultMessage: 'Adresse'
		});

		const searchFilterLimits = intl.formatMessage({
			id: 'kred.pol_ph_search',
			defaultMessage: 'Policennummer, Firmenname, Adresse',
		});

		return (
			<div style={{minHeight: 'calc(100vh - 190px)'}}>
				<AXAContainer>
					<div style={{textAlign: 'left'}}>
						<h1 className={'smallMainTitle'}>
							<FormattedHTMLMessage
								id="kred.pol_policies"
								defaultMessage="Ihre Policen"
							/>
						</h1>
                                        <input
						id={'firstField'}
						onChange={
							   (e) => {
								   stores[0].changeInput(e)
							   }}
                                                value={stores[0].state.searchValue}
                                                className={'inputFieldWide'}

					/>
				</AXAContainer>
				<div style={{height: '100px'}}/>
			</div>
		);
	}
}

export default connect([
	policenContainer
])(withRouter(injectIntl(PolicenUebersicht)));
```

**Comment by francescoRovetto** [comment]
Hi Raphael, is my information sufficient?

**Comment by raphaellueckl** [comment]
@francescoRovetto @amir-ag will soon write his findings here. :)

**Comment by amir-ag** [comment]
Hi @francescoRovetto I couldn't reproduce this issue by running the code snippet below. Not sure, but afaik you access dom elements in react using refs, have you tried that?

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test</title>
    <meta name="description" content="This is an example of a meta description.">
    <link rel="stylesheet" type="text/css" href="theme.css">
</head>
<body>
    <axa-container>
        <input></input>
        <input class="input_1"></input>
        <input></input>
        <input></input>
    </axa-container>
    <script src="node_modules/@axa-ch/container/dist/index.js"></script>
    <script>
        document.querySelector(".input_1").focus();
    </script>
</body>
</html>
```

**Comment by francescoRovetto** [comment]
Hi Amir, thank you for trying.
you use plain JavaScript in your example - can you try to reproduce the error with React, the way I did?

**Comment by amir-ag** [comment]
Hi Francesco, tested it like you see below and it works fine. Have you create a React element as stated here (and used in my snippted below): https://patterns.axa.ch/?path=/story/components-container--container under 'usage'? Can't see it on the snippet above.

```
import {createElement, useEffect} from 'react';
import createAXAContainerReact from '@axa-ch/container/lib/index.react';

function App() {
    const AXAContainerReact = createAXAContainerReact(createElement);

    useEffect(() => {
        document.querySelector(".input_1").focus();
    }, [])

    return (
      <AXAContainerReact>
        <input></input>
        <input className="input_1"></input>
        <input></input>
        <input></input>
      </AXAContainerReact>
  );
}

export default App;

```

**Comment by francescoRovetto** [comment]
Hi Amir,

thank you for your response!

I call the element in componentDidMount in a class component. The field, which I try to focus on, is also in a class component and this class component is in the axa container.

I also create a React element, it's created in a separate file and then used in there.


Could it be, that nested class components are the issue?

**Comment by amir-ag** [comment]
HI Francesco, I have no idea why it doesn't work in your app, it could be a timing issue if there are components in between. I'd debug using a timeout just to make sure it's not a timing issue.
