### ISSUE TITLE
We need to have a Phone Number selection

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#2246]
Feature requests posted here should be of a smaller scope. Kind of like a "wishlist".

See requirements here: 
https://jira.axa.com/jira/browse/MYAXATA-9483

How it should look at first, then to be finalised with design in Januar
![image](https://user-images.githubusercontent.com/275235/143471313-9211fcc0-bd54-402c-aa3b-099352835283.png)

**Comment by markus-walther** [comment]
Link to finalized design has become available in AXA's UIKit.
