### ISSUE TITLE
NPM run new does not generate import for "usage" und "changelog" in storybook

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2249]
The marked parts don't get auto-generated when running `npm run new`. These should be included.

![Screen Shot 2021-12-15 at 10 00 11](https://user-images.githubusercontent.com/8248662/146155677-041811db-4278-4436-863c-cab8f58b2499.png)

Reference commit: c670912bccf49b93903bdd2cac4189701ee90a66

**Comment by markus-walther** [comment]
This will be looked at in the wider context of How-To-Start-A-New-Component, including documentation. Therefore, we close this narrow ticket here (also, since @MKaHead changed the infrastructure in the meantime that is mentioned here).
