### ISSUE TITLE
Firefox: super slow to load

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#225]
https://axa-ch.github.io/patterns-library/#organism
Firefox takes almost 5 seconds to load/render...
Are web-components really that slow? Or is it the polyfill? Anyway, that's a serious blocker!

![firefox-loads-slowly](https://user-images.githubusercontent.com/914443/35733683-969e2766-081e-11e8-8dfb-09d4c395ea2c.gif)

**Comment by LucaMele** [comment]
better now, still a bit slow on molecules. reasons is polyfills. end of 2018 native support should be there

**Comment by AndyOGo** [comment]
Indeed overhaul page load has improved very nice 🎉 But as you say, webcomponents itself are still slow.
Guess we can't do much about it, what a bummer 😭
