### ISSUE TITLE
We should allow "change", "focus", "blur" events on all input elements for consistency!

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2250]
I wanted an easy way to set focus and blur methods:

![image](https://user-images.githubusercontent.com/8248662/146333177-d14252c2-ebf0-42e2-abff-95c1cbab3611.png)

@focus and @blur did not work, because they are either eaten or not bubbling from `axa-dropdown` and `axa-input-text`, which is a problem in my opinion. Those components allow methods for some of the stuff, but I did not find a way in the documentation how to use "functions" from the template directly (I know you can write a queryselector afterwards and attach one, but that's pretty messy for a simple task like this).

I got that feedback for "input phone" and decided doing that would be pretty messy for this PR, so I took it out. Thanks for mentioning this @MarekLacoAXA

**Comment by MKaHead** [comment]
There is no need at the moment. Therefore, we are closing the issue. I note that this may change.
