### ISSUE TITLE
Fix flakey end-to-end tests

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#2259]
Here is a list of currently flakey e2e tests:

- [ ] Icon: should not render svg icon (times out a lot)
- [ ] Icon: Size checks > should render svg icon with correct default size  (times out a lot)

Additional info: these are Playwright tests, and they run on the Azure CI/CD pipeline.

Fix all flakey tests so that pipeline testing becomes reliable again.

There is anecdotal evidence that such flakeyness does not occur (or not as often) for local testing on a developer's laptop.

**Comment by markus-walther** [comment]
A possible approach to see what's going on here is to run the Playwright tests on a headful Chromium instance and with lower speed and/or debug breakpoints.

**Comment by MKaHead** [comment]
Moved to #2284
