### ISSUE TITLE
Green colored Button

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#2266]
Feature request to allow green-color-variant Button.
(there is an approved status color $color-malachite = #1CC54E)

Since axa-button uses ShadowDOM, it is needed to extend the component.

Thanks @markus-walther !

![image](https://user-images.githubusercontent.com/43809369/159268801-f754147d-a279-43d9-9d6f-840892c434de.png)

**Comment by MKaHead** [comment]
@MarekLacoAXA The design team sees no use in making this variant generally accessible. It simply comes to the fact that the button is a mandatory element and there is hardly any room for manoeuvre. Therefore, I am closing the feature request.
