### ISSUE TITLE
Dropdown usage with limited space

### ISSUE THREAD

**Issue by domirs** [axa-ch/patterns-library#2270]
In our MF calculator we use the dropdown component in a 3 column layout. On mobile devices, the space is very limited and the text (e.g. "CHF 10'000") gets cut off.

![Dropdowns with limited space](https://user-images.githubusercontent.com/5699880/161943889-a32b1205-2374-4fbe-b58f-1aa9f41ecfda.png)

It would be nice, if there is a switch for limited space which will then reduce the padding or font size of the item.

Thanks a lot.

**Comment by domirs** [comment]
@markus-walther do you have any news on this topic?

**Comment by markus-walther** [comment]
@domirs Not yet. However, @MKaHead supports us in maintaining the Pattern Library, so there's a good chance this will be adressed in the near future.

**Comment by MKaHead** [comment]
@domirs I think it's primarily a UX question: is the dropdown of the type and shape the right element at all? My first thoughts immediately the design is really bad for mobile.

If designers come around the corner with nothing better, feel free to reopen issue.

**Comment by domirs** [comment]
@MKaHead This was also our first impression and we discussed it with our UX specialist, but they didn't find a better solution.

Please reopen the issue. Thx

**Comment by MKaHead** [comment]
Sorry, I could have immediately offered suggestions, examples and of course my support:
- First of all, it is not difficult for us to adjust the dropdown. However, it does not make dropdown more readable and usable for the end user.

Three columns on mobile is just too much:
- One possibility would be to show one and a half packages and put them in a carousel with slide dots. This way the user on mobile devices can see that there are more packages and has the possibility to swipe or click on slide points which also serve as orientation. See screenshot 1
- Another option would be to display only one column at a time on mobile devices, see screenshot 2.

**Screenshot 1:**

<img width="584" alt="screen1" src="https://user-images.githubusercontent.com/11683864/176472095-0c89312f-1504-4ecb-9ffe-795d9660f53a.png">

**Screenshot 2:**

<img width="436" alt="screen2" src="https://user-images.githubusercontent.com/11683864/176472136-8239bf09-0359-4fb6-8e5a-2bf83994d5af.png">

**Comment by MKaHead** [comment]
We have only fixed text-overflow from our side. Now the text is not cut off abruptly, see here
![Bildschirmfoto 2022-07-01 um 11 28 47](https://user-images.githubusercontent.com/11683864/177144610-8dcce393-4fc0-4fb3-b6e0-c6d94ee56427.png)
`@axa-ch/dropdown@11.0.1`
