### ISSUE TITLE
Source Sans Pro Semibold rendering ugly at windows

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#228]
The fonts implemented as specified [here](https://design.axa.com/web-guidelines/typography) do not look nice on windows.

The **Static HTML** loads just Source Sans Pro Regular & Bold -> Bold is used to display Semibold as `600`.
[axa.com](https://www.axa.com) loads even less, just Source Sans Pro Regular and uses it to display all weights of `400`, `600` and `700` (Normal/Regular, Semibold and Bold) 

Compare the provided fiddle on windows and Mac:
http://jsfiddle.net/JWwpK/113/

Originally submited at https://github.axa.com/axa-winterthur/helios/issues/261

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
