### ISSUE TITLE
axa-text implementation violates lit contract

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#2288]
The current axa-text implementation has no `render()` method, but manipulates DOM. 

The new lit version we use is more strict in demanding that lit controls the DOM, and may issue error messages in certain usage scenarios, as has been observed for this component. Axa-text _is_ used embedded in other lit-based PL components, therefore the problem is already observable within our own collection of components.

Research an implementation alternative that preserves axa-text semantics but does not use lit's base class.

Then implement it.

**Comment by MKaHead** [comment]
I fix the whole thing with a rewrite of the text component. Furthermore, the text component does not comply with the current styleguide.
