### ISSUE TITLE
axa-accordeon: wrong hight in certain cases because width changes when opened.

### ISSUE THREAD

**Issue by christoph-schlumpf** [axa-ch/patterns-library#2290]
Wrong hight of accordion in certain cases because width changes when opened. Therefore some content is sometimes not visible.

![image](https://user-images.githubusercontent.com/7869150/171636538-6063adcc-f54c-4ae7-b197-b0f903b5c57c.png)

## Expected Behavior
Hight of accordeon-content slot must match content hight.

## Current Behavior
When the accordeon is opened, the margin of the contents changes from margin: auto; to margin: 0px 4px 16px.

Because the width of the content changes by -8px the content might use more vertical space (e.g. text flow to a new line). But the hight of the accordeon-content slot is not changing, some content is not visible.

## Steps to Reproduce
1. Put text inside an accordeon that wraps if the accordeon width is reduced by 8px (see example screenshot)
2. Open the accordeon --> last line of text is not visible

## Context (Environment)
Issue potentially occurs on any OS / Browser. I tested on Edge on Windows (AXA Switzerland).

## Possible Solution
- Preferred solution: do not add margin to the accordeon-content when it is opened. This should be an easy fix.
- Alternative solution: dynamically recalculate the hight of the accordeon-content slot when it is opened ( might be fixed together with https://github.com/axa-ch-webhub-cloud/pattern-library/issues/2279 )

**Comment by MKaHead** [comment]
Hi @christoph-schlumpf,
sorry for the late reply, there are several issues regarding accordion. I finally have time to take care of them.

**Comment by christoph-schlumpf** [comment]
Hi @MKaHead ,

Unfortunately this issue is not solved.

The issue is that you add an additional margin of 4px in 'm-accordion__content--open'. Either remove it here or add it to the closed accordion too. I think this is an easy fix. Can you please Re-Open this issue?

![image](https://user-images.githubusercontent.com/7869150/177175455-71cc320f-55cc-44a5-b89a-30038c3257fe.png)

**Comment by MKaHead** [comment]
There are a few more hacks there. We will take care of it. @christoph-schlumpf

**Comment by MKaHead** [comment]
@christoph-schlumpf I removed the 4px, but the accordion need really a rework.

@axa-ch/accordion => 1.0.2
