### ISSUE TITLE
Modal - inverted desktop and mobile close icons for noheader size option

### ISSUE THREAD

**Issue by bozojovicic** [axa-ch/patterns-library#2293]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

## Expected Behavior

White close icon should be displayed on mobile screen while the standard blue icon should be displayed on desktop screen.
The white close icon is needed on mobile screen because of the possible dark background images.

<img width="445" alt="Screenshot 2022-06-20 at 11 19 07" src="https://user-images.githubusercontent.com/37440641/174569474-3456de2a-071a-48ab-a0ff-adc70ca9d7a5.png">

## Current Behavior

At the moment the blue close icon is displayed on mobile while the white icon is displayed on desktop screen.

## Possible Solution

Should be fixed in CSS

**Comment by MKaHead** [comment]
fixed in #2301
