### ISSUE TITLE
axa-file-upload: fix logic to determine if uploaded file was an image

### ISSUE THREAD

**Issue by baumkaenguru** [axa-ch/patterns-library#2328]
File-upload molecule cannot handle (non image/* and non application/*) files properly. e.g. text/csv

## Expected Behavior
If I upload a file which is not an image and doesn't contain 'application' in its MIME-Type e.g. "text/csv", I'd like to see the usual paperclip icon in the list of added files. Also, I'd expect the readme to match the change logs description that all filetypes are now allowed (since 5.1.0)

## Current Behavior
Currently the component thinks it has to handle an image since the check for non-image-files looks something like this:
`const isNonImageFile = file.type.indexOf('application') > -1;`
Therefore it wants to create a preview, which obviously doesn't work. 

## Steps to Reproduce
1. Open [Codesandbox](https://codesandbox.io/s/objective-pond-72lk2g?fontsize=14&hidenavigation=1&theme=dark)
2. Try to drag and drop a random csv file into the file-upload component
3. ????
4. Profit

## Possible Solution
fix [this](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/a300c12b25826323d805bc156d4a48c05dedc717/src/components/20-molecules/file-upload/index.js#L535) line

**Comment by MKaHead** [comment]
Hi @baumkaenguru, thanks for creating the issue. I'm a little surprised that all file types would be allowed. As I remembered that it should not be possible for security reasons. However, that also depends on the context of where your app is running, I'll look into that. Otherwise nothing in the way to fix it.

**Comment by baumkaenguru** [comment]
Hi @MKaHead: Thats at least what it said in the changelog for version 5.1.0:

Allow all file types
- Added an allowedFileTypes attribute.
- Now, every file type can be uploaded.

**Comment by baumkaenguru** [comment]
awesome, thank you!

**Comment by MKaHead** [comment]
@baumkaenguru release will come on Monday 12. September. I should close next time after release.
