### ISSUE TITLE
Introduce prop for changing autocomplete attribute

### ISSUE THREAD

**Issue by AarKro** [axa-ch/patterns-library#2364]
Some of our users have trouble using the browsers form autocomplete features, so we want to be able to set the `autocomplete` attribute on inputs to make sure this works smoothly.

Currently this seems to be set to `off` by default, with no way for us to change it.

Maybe a possible solution would be to introduce a prop to pass the autocomplete value into a component, while having it default to `off`.

**Comment by MKaHead** [comment]
Thank you for the suggestion @AarKro. It is legitimate to have an attribute to activate it. A solution for the inputs will come soon.
