### ISSUE TITLE
Adjust behaviour of invalid FileUploads

### ISSUE THREAD

**Issue by corsin-ragettli** [axa-ch/patterns-library#2370]
We currently have a way to check if the FileUpload reports any files that are invalid with `<FileUpload invalid={foo}/>`.  But this is pretty clunky for react developers because we can't put the invalid boolean in a state (since we can't set the state in any way when the invalid prop changes). So we have to use `useRef()` which works until we have a parent which needs this information, then again, it's very clunky to use (we could another `useRef()` but then again, there could be a cleaner solution). My suggestion is that instead of the `invalid`prop directly, I would take a prop i.E. `onInvalid` which is a function that passes a boolean telling if the FileUpload is invalid. The typing could be `onInvalid: (invalid: boolean) => void`. this would make the experience for react devs better.

**Comment by MKaHead** [comment]
We will provide the callback prop onInvalid with the parameter boolean invalid and if we have an errorMessage we will provide it as the second parameter. The callback will be triggered whenever the invalid status changes.

**Comment by corsin-ragettli** [comment]
Currently my IDE says that the `onValidityChange()` is required, probably should be optional imo.
