### ISSUE TITLE
Latest version of react datepicker doesn't show month and year dropdown 

### ISSUE THREAD

**Issue by veljko3ap** [axa-ch/patterns-library#2389]
Starting from the latest version of Datepicker dropdowns for months and years are not displayed anymore in our latest eSalesP web app for vehicle insurance.

## Expected Behavior
Dropdowns for months and years should be displayed in datepicker.

## Current Behavior
At the moment users are not able to select desired month and/or year in datepicker.

## Steps to Reproduce
1. visit either prod version https://www.axa.ch/de/rechner/autoversicherung.html#/start or preprod version https://www.acc.axa.ch/de/rechner/autoversicherung.html
2. Navigate to the screen that asks for contract begin date (e.g. https://www.axa.ch/de/rechner/autoversicherung.html#/begin-date)
3. Try to select month and year in AXA's react datepicker

## Context (Environment)
This happens in all environments localhost, prod. OS, browser doesn't matter.

## Possible Solution
Pass on pod name as version suffix to dropdown inside datepicker?

**Comment by MKaHead** [comment]
Thank you @veljko3ap. We will check it.

**Comment by MKaHead** [comment]
@markus-walther
```js
 const versionInfo = __VERSION_INFO__;
 defineVersioned([AXADropdown], {'axa-dropdown': versionInfo['axa-datepicker']});
```
is a workaround at the end of the datepicker's constructor. Unless we understand deeper _why_ the bug suddenly occurred, we could split defineVersioned into simpler-to-understand individual functions that each handle one versioning subcase only. Note, though, that we have to care about the case of multiple PL dependencies in a given component (not evidenced by the datepicker, but elsewhere, e.g. axa-top-content-bar).

**Comment by markus-walther** [comment]
We are aware of this bug and will work on it as soon as we have capacity. In the meantime, npm versions prior to the bug are of course usable - please use them wisely for your applications.

**Comment by amir-ag** [comment]
This issue was fixed with the latest release of the datepicker v17.1.5 as shown [here](https://codesandbox.io/s/optimistic-dew-gyhuul?file=/src/App.js). 
<img width="803" alt="Screenshot 2023-02-21 at 13 35 14" src="https://user-images.githubusercontent.com/40580705/220346481-86f5b2ff-bb96-4d50-8373-a062870d6f98.png">
