### ISSUE TITLE
Add better documentation for `allowedFileTypes` on the AXAFileUpload

### ISSUE THREAD

**Issue by corsin-ragettli** [axa-ch/patterns-library#2401]
Currently, the [documentation (Storybook)](https://axa-ch-webhub-cloud.github.io/plib-feature/develop/?path=/story/welcome--to-pattern-library) only states the following about  `allowedFileTypes`:
> In the `allowedFileTypes` attribute, you can declare the allowed file types that a user can upload (ex: only pdf's are allowed). If the attribute is empty, every file type is allowed.

The user can only guess which format this attribute should have. According to [mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept) file inputs accept both extensions (i.E. `.docx`) or MIME types (i.E. `image/png`). After some testing I found out only the latter was true for the AXAFileUpload. My suggestion is to change the documentation so the user understands how to correctly use this attribute.

My suggestion:
> In the `allowedFileTypes` attribute, you can declare the allowed file types that a user can upload (ex: only pdf's are allowed). If the attribute is empty, every file type is allowed. The allowed File types should be in the [MIME Standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). The allowed file types should be separated by a `, ` for example `text/plain, image/jpeg, image/png`.

**Comment by MKaHead** [comment]
Thank you @corsin-ragettli. We will update the docs.
