### ISSUE TITLE
Datepicker dropdown let's you choose the default value of "Choose month" and "Choose year"

### ISSUE THREAD

**Issue by amir-ag** [axa-ch/patterns-library#2416]
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

A user can select the default values of "Choose month" and "Choose year".  When one of these values is selected, a type error stating "Cannot read properties of undefined (reading 'name')" is thrown.

## Expected Behavior
The default values of "Choose month" and "Choose year" shouldn't be options to available to select.

## Current Behavior
A user can select the default values of "Choose month" and "Choose year"

## Steps to Reproduce
[Codesandbox](https://codesandbox.io/s/optimistic-dew-gyhuul?file=/src/App.js)

1. Click on one of the two dropdowns and select "Choose month" and "Choose year".
2. A type error is thrown.

## Possible Solution
Remove default values from selectable options.

**Comment by markus-walther** [comment]
This is most likely a consequence of this 1-character typo in **axa-dropdown**: `_disable` instead of `_disabled`, cf. https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/src/components/20-molecules/dropdown/index.js#L98

**Comment by markus-walther** [comment]
Note that the bug appears if the mobile view is triggered, e.g. on smaller screen widths, forcing the native `<select>` of the embedded dropdowns to be used. 

Thus, testing that the bug is fixed must be done primarily on smaller screen widths.

**Comment by markus-walther** [comment]
This is tracked on https://jira.axa.com/jira/browse/WEBHUB-2210 as well.
