### ISSUE TITLE
Modal dialog

### ISSUE THREAD

**Issue by adrian-hoehn** [axa-ch/patterns-library#243]
For business applications we need an AXA wide modal dialog component

**Comment by LucaMele** [comment]
Absolutly. You are free to contribute and implement it. Better to ask first the design team whats their status on it

**Comment by AndyOGo** [comment]
Seems that there isn't any design spec regarding modals at the global style guide 😞 
https://design.axa.com/web-guidelines/search?q=modal

@adrian-hoehn 
There are basically two instances involved:

1. The global design guidelines from paris -> https://design.axa.com
2. Then AXA-Switzerland is approving those guidelines locally, maybe some corrections. @anja225 is responsible for it locally.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
