### ISSUE TITLE
TypeError: window.customElements is undefined

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#25]
Firefox gives this error:

> TypeError: window.customElements is undefined

<img width="1436" alt="screen shot 2017-12-04 at 19 02 14" src="https://user-images.githubusercontent.com/914443/33568160-cca479be-d925-11e7-9729-c609570dbdb9.png">

@LucaMele 
Maybe this is still related to webcomponents not initialising properly.

**Comment by LucaMele** [comment]
On FF works when dev console is closed... Weird

**Comment by LucaMele** [comment]
but anyway, WC are not enabled yet in FF so is not a bug. Normal user mode works

**Comment by LucaMele** [comment]
ah is beacause the loader loads the polyfill after the js for the components when console is open

**Comment by AndyOGo** [comment]
ahaaa
then it should be easy to fix, though its strange
