### ISSUE TITLE
Simple Publish Subscribe Intercom not working

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#26]
So I just tried to add a simple `pubsub` library to enable intercom between components.

**Unfortunately**:
- At the moment all our components code is bundled as separate modules!
- This redundantly imports all modules and thus affects the scope of a each module being a new one for every used module within each component
- this breaks simple intercom possibilities, because private vars within modules aren't shared with their redundant friends...

Reproducible bug can be found at this PR #24 

# Must have features

- [x] DOM Mutation agnostic
- [x] loose coupling
- [x] ideally it would work with bundle or redundant modules (though redundant modules are a bug)

**Mention:** I really want to say that I mentioned this culprit weeks ago, but wasn't believed...
Though I know that I'm very competent in my profession and I always look from a wide point of view at tasks, including various very different angles.

**Mention 2:** Indeed there is a possible workaround, by polluting the global `window` object like: `window.__sharedVarAmongRedundantModules`. But **NO**; the correct way is bundling/loading each module never more than once.

**Comment by AndyOGo** [comment]
It seems the simplest approach to get it working with all of above constraints is to utilize DOM custom events and make them bubble up for `publish` and `subscribe` to `document`.
This way it will work with DOM mutations, should work if the same module is loaded reduntant (because, data will be stored in event object of browsers native API) and this makes it loosely coupled

**Comment by LucaMele** [comment]
After our conversation, we have a solution that should work. We clarified the definition of holistic components and what is expected from a System containing them. We will implement a component that will fix the issue (either like a gear component between two or a holding one).

**Comment by AndyOGo** [comment]
So I just pushed a first version of DOM centric `pub/sub` implementation to PR #24 

I utilized `Event` and `CustomEvent` interfaces, though they are pretty new and I guess we need to polyfill them with deprecated API's like `document.createEvent`.

**Comment by LucaMele** [comment]
the "foifer unds weggli" solution :)

**Comment by AndyOGo** [comment]
This issue is still not correctly fixed, as it creates #521

**Comment by LucaMele** [comment]
as the reference bug is closed, i assume this is as well

**Comment by LucaMele** [comment]
ok need to understand it better

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
