### ISSUE TITLE
Scrolling on the menu and/or background closes the menu

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#268]
![ezgif-5-e7157c816e](https://user-images.githubusercontent.com/275235/36672202-bca94344-1afe-11e8-8277-4598d450db18.gif)

**Comment by AndyOGo** [comment]
According to can i use support of `overscroll-behaviour` is really bad:
https://caniuse.com/#feat=css-overscroll-behavior

**Comment by AndyOGo** [comment]
> index.js:1845 Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080bodymove @ index.js:1845
index.js:1841 bodymove -> undefined
