### ISSUE TITLE
Let‘s move away from web components

### ISSUE THREAD

**Issue by TheDadi** [axa-ch/patterns-library#28]
Let‘s discuss with the all the frontend guys/girls if it‘s still a good practice to build webcomponents, since we have now a more clear sight who is using which framework and what the trend shows for axa switzerland. The new disussions with multiple teams shows a trend from moving away from angular to react. Let‘s discuss this since we are facing multiple problems with webcomponents... and they are not as simple to use in an other franework as thought.

**Comment by LucaMele** [comment]
Well, the framework of choice should always be React these days in AXA. I fully agree, we should not move away from react. Web Components can be integrated in other framework as they are pure html/js. I underline it: they **can**. 

The Style guide here is only a reference and Web-components are chosen as the framework agnostic technology in order to show the DEMOS. Develoeprs can include Web-Components, can also just use plain HTML for their React classes. 

I can't see other options at the moment. I Don't want to make another toolkit that strictly depends on A specific Framework. The goal here is to GUIDE developers in creating awesome fronted stuff. What isn't the GOAL is to be another Toolkit that lives only as long as the Framework of choice.

**Comment by LucaMele** [comment]
This Style-guide uses ONLY Custom Element from the Web Components proposed Standard. Nothing else. And only to make developing holistic components easier. Other Developers CAN import the component into their framework of choice or not.

**Comment by LucaMele** [comment]
And, this has already been discussed in the glide this sommer and communicated at the ARP PI5. The Style Guide will be pure HTML JS CSS (with SCSS as a helper here, but traditional CSS is visible). Web-components is something I added to help the integration. If we want to discuss about that i'm in. But i won't discuss again if its a Toolkit with React components. This has been discussed in the glide and now is too late. If the web-components disturbs, i can remove them and provide pure Living Standard JS.

**Comment by LucaMele** [comment]
So, do we want just Living Standard JS in our Style-Guide OR Proposed Standard JS.

**Comment by AndyOGo** [comment]
Interesting discussion. I will try to elaborate from different use cases and view points.
So I would like to look at the following separately:
- **Web Components themselves**
- **SPA, Large Scale Website Suitability**
- **Third Parties, Reference Implementation, Living Guide Lines**

# Web Components themselves

The original idea of custom HTML `<elements>` isn't brand new. I'm sure every developer wished he could just write what he thinks suits best.
The first draft arrived an 2011 and was presented at [fronteers](https://fronteers.nl/congres/2011/sessions/web-components-and-model-driven-views-alex-russell). Nope, even earlier with `XHTML` in 2000, but...

| Pros | Cons |
|---|---|
| Everyone loves the idea | Still in Draft state |
| | The only *Living Standard* `<template>` tag, doesn't even incorporate a usable template language. Man it's like saying black is white, it's a bug... |
| | API Specs have changed over time |
| [Polyfills](https://www.webcomponents.org/polyfills/) provided | [weak Browser support](https://caniuse.com/#search=components) |
| | According to our test/problems: components lifecycle including initialisation is vague |
| | forced wrapping root aka container node for every component (React is much smarter in this regard) |
| Polymer [claims SSR support](https://www.youtube.com/watch?v=yT-EsESAmgA) | not verified |
| | efficient Bundling and reuse of modules way more complex |

# SPA, Large Scale Website Suitability

In general there are way to many features missing to say that Web Components alone can serve as  a SPA, LSW foundation.

| Pros | Cons |
|---|---|
|reuseable tags||
||just `string` props|
||slow DOM|
||missing template language|
||no context|

# Third Parties

This is imho the biggest benefit of web components.
In case we want to provide a reference implementation of the defined living style guide, it's super  beneficial to build it framework- and library-agnostic. This way any agency, external or internal people don't have to grasp their head around very advanced and complex Frameworks like `React`, ~~`Angular`~~, `Vue`, you name it (I admit they still need to grasp Web components).

And yeah even if I don't like it, in terms of collaboration, freedom of choice, etc; this is really what we get from using Web Components.
Does this make them production ready? IMHO never in the next 20 years.

**Comment by LucaMele** [comment]
I would add, there is more risk for prudction, but a lot of big websites are build just with them (YouTube as an example). Therfore, they are productive already, event with some headaches and. 

When we develop something, it has to be goal oriented. Everything else is pointless. This is valid for any Software language and every framework.

Engineers, as practitioners of engineering, are people who invent, design, analyse, build and test machines, systems, structures and materials to fulfill objectives and requirements while considering the limitations imposed by practicality, regulation, safety, and cost.

The objective for the styleguide is to reach out as many people as possible. Therefore I believe that the best tool for it is WC.

**Comment by LucaMele** [comment]
This is not a discussion on which technology is absolutely better. It is a discussion which technology is better for a certain objective. Im not a FanBoy of Web-Components or React or whatever. They are just tools to fulfill a goal/objective

**Comment by LucaMele** [comment]
As said, use them at own Risk. I think they can be tested and implemented and if it works why not use them. Are they mature? no. Are they mature enough? i think yes. Not just google is behind them. Also the EDGE is developing them. Is only a matter of time till they are standard. But developers will decide if they make sense to use or not.

**Comment by AndyOGo** [comment]
Got it.
As I said, for third party stuff, I really see the benefit

**Comment by AndyOGo** [comment]
Those critical features are enough reason to continue discussion
#42 #31

**Comment by LucaMele** [comment]
Those two bugs are personal preference. The specs say:


Because element definition can occur at any time, a non-custom element could be created, and then later become a custom element after an appropriate definition is registered. We call this process "upgrading" the element, from a normal element into a custom element.

Upgrades enable scenarios where it may be preferable for custom element definitions to be registered after relevant elements have been initially created, such as by the parser.

**Comment by LucaMele** [comment]
Sorry only one is personal preference: #42

**Comment by AndyOGo** [comment]
I understand.
Unfortunately the "specs" are in **draft** state, has changed and will change in the future.

**Comment by LucaMele** [comment]
Agree. But we keep within the proposal and not invent new features.

**Comment by LucaMele** [comment]
I encourage you to report it to the w3c community

**Comment by AndyOGo** [comment]
IMHO working 7 years and not making a good product indicates lag of competence

**Comment by LucaMele** [comment]
The custom elements is proposed standard and therefore not normative. But till it changes we adapt to it. And obviously browser implementation follows the proposal so far. So if we want our custom need to be implemented, we need to ring the door bells as google, Mozilla, Microsoft  and apple. Plus all the w3c community. Totally out of scope. Please srick to the non normative proposed specs.

**Comment by LucaMele** [comment]
U are free to tell google, Mozilla, Microsoft, apple and the whole w3c community your personal opinion

**Comment by LucaMele** [comment]
Both bugs are irrelevant to this and therefore closing again

**Comment by AndyOGo** [comment]
@LucaMele 
Please stop closing issues because you don't agree with them personally.
We have rudimentary issues regarding Web Components and it's valid to discuss those in an open manner.
It's paradigm shift and we need to be aware of what that means and all it's consequences.

**Comment by LucaMele** [comment]
See issue #45
