### ISSUE TITLE
Add cross interface tap event type

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#287]
To improve mobile responsiveness to `click` events we should introduce a custom cross-interface `tap` event type.

- [x] Should not be ignored by `passive` events - except if specified
- [ ] should be able to `preventDefault` click actions
- [x] Should support plug and play of touch interfaces
- [x] needs to works with **Touch Events**, **Pointer Events** and classic **Mouse Events**
- [x] We should never need to use any `cursor: pointer` hacks to enable them
- [ ] Scroll needs to be prevented in case of a valid tap
- [x] mitigates click delay #20 
- [ ] **IMPORTANT** remove this iOS shame to make outer click events work:
   - delete [`outer-ios-SHAME.js`](https://github.com/axa-ch/patterns-library/blob/master/src/js/outer-ios-SHAME.js)
   - remove it's usage from [`outer.js`](https://github.com/axa-ch/patterns-library/blob/master/src/js/outer.js#L19)

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
