### ISSUE TITLE
sub menu texts not aligned

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#289]
due to css columns, the height is not alligned of sub menu items
![image-1](https://user-images.githubusercontent.com/275235/36781305-cd5a9d78-1c75-11e8-80fb-a88e6c031d07.jpg)

**Comment by AndyOGo** [comment]
no good news 😞 
https://stackoverflow.com/questions/14248095/how-to-make-3-li-columns-with-variable-height-content-the-same-height

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
