### ISSUE TITLE
Stroke on nav doesnt work correctly on IE11

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#29]
<img width="1435" alt="bildschirmfoto 2017-12-05 um 12 59 59" src="https://user-images.githubusercontent.com/275235/33606017-44e5b186-d9bc-11e7-9fa8-e9e6bf621e40.png">
<img width="718" alt="bildschirmfoto 2017-12-05 um 13 00 15" src="https://user-images.githubusercontent.com/275235/33606018-45188958-d9bc-11e7-8b2e-0f943c955f3f.png">

**Comment by AndyOGo** [comment]
ohhh nooo.
that is super ugly.

Thanks for bug report.

**Comment by LucaMele** [comment]
very welcome
