### ISSUE TITLE
GPU accelerated rendering

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#293]
I really like the idea of enabling the GPU to increase render performance, by utilising CSS properties like `transform: translate3d(0, 0, 0)`. **BUT:** we faced various glitches triggered by enabling this feature.

- messed up `z-index` stacking context #263 
- render issues #101
- iOS momentum scrolling renders a black background on overscroll #280
- `position: fixed` and overscroll and GPU accelerated rendering is like a misery

So what we could do is:
- using 2D-Transforms at the beginning and only if we face performance issues, opt-in for hardware-accelerated rendering.
- Only enable GPU rendering temporarily, e.g. for an animation.
- It would also be possible to have always an opt-in modifier like `--gpu`

A good reason to avoid it is our `m-button` component which will break `z-index` by default 😱

**Comment by LucaMele** [comment]
Generally speaking, i really like the YAGNI Software principle (https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

Therefore, i like the idea of disabling it per default and offer the possibility to enable it by using a css class with the modifier (as u said: `--gpu`).

It should be documented as well
