### ISSUE TITLE
EDGE Menu on axa.ch broken

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#304]
The menu does not work as expected on edge. Clicking between major menu points brakes the menu and the animation is not correct of the stroke element

**Comment by AndyOGo** [comment]
**Edge 14:**
![edge-14-stroke-bug](https://user-images.githubusercontent.com/914443/36926361-ac08a81e-1e77-11e8-909a-f1badd4aaf18.gif)

**Comment by LucaMele** [comment]
EDGE 16:

![edge-doesnt-repaint](https://user-images.githubusercontent.com/275235/36963628-4d5a6b2a-2054-11e8-8cad-b698c9573c59.gif)

**Comment by AndyOGo** [comment]
😱 OMG, we just tested this at **Edge 12** and indeed everything works as expected there.
Microsoft must have introduced at least two bugs, one regardings CSS trasistions and another from 16+ with repaint/reflow algorithm.
