### ISSUE TITLE
Edge-16 WTF menu bug

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#309]
#304  isn't completely fixed.

If the user clicks a left-side menu item, it's not shown, if he clicks a right-side menu item it is shown 😱 

![edge-16-menu-wtf-small](https://user-images.githubusercontent.com/914443/36985585-f6feb7ec-2097-11e8-8a9d-b1200f35de4b.gif)

**Comment by LucaMele** [comment]
Ahahahahahaha magic edge!

**Comment by AndyOGo** [comment]
I wonder if it's the correct DOM node to force a repaint on `move` 🤔 

https://github.com/axa-ch/patterns-library/blob/master/src/components/m-header-navigation/js/header-sub-navigation.js#L52-L55

**Comment by AndyOGo** [comment]
Okay, and here we go with take 2 😒 

![edge-16-menu-wtf-2](https://user-images.githubusercontent.com/914443/36995139-7d57d150-20b3-11e8-8526-b7070b16562e.gif)
