### ISSUE TITLE
contextual communication between components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#31]
After I quickly fixed #26 (publish/subscribe) I see the possible use case of a list of child components who need to communicate between each other within a specific context.

```html
<axa-context>
  <axa-foo></axa-foo>
  <axa-bar></axa-bar>
</axa-context>

<axa-context>
  <axa-foo></axa-foo>
  <axa-bar></axa-bar>
</axa-context>
```

With a small hack this can be archived currently using incremental channels, like:
```js
let n = 0;
publish(`channel-${n}/change`, ...)
subscribe(`channel-${n}/change`, ...)

...
++n;
publish(`channel-${n}/change`, ...)
subscribe(`channel-${n}/change`, ...)
```

# Requirements

- [x] enable intercommunication between hierarchy-agnostic components
- [x] opt-in to select kind of context
- [ ] pass contextual data down

**Comment by AndyOGo** [comment]
A concrete use case is the showing/hiding the mobile main navigation upon burger button click.

**Comment by AndyOGo** [comment]
Well, seems that the `constructor` of a parent Web Components is called after the `connectedCallback` of child components, which breaks context retrieval...

<img width="1440" alt="screen shot 2017-12-06 at 13 35 29" src="https://user-images.githubusercontent.com/914443/33661993-7a135a7e-da8a-11e7-9bb2-814a9546e796.png">

**Comment by LucaMele** [comment]
regarding ur last comment: Thank you, but as said in the #41 it follows the proposed standard and therefore no issue.

**Comment by LucaMele** [comment]
regarding ur last comment: Thank you, but as already said it follows the proposed standard and therefore no issue.

**Comment by AndyOGo** [comment]
Okay, I got your point.
Nevertheless we currently face this problem and this makes it a bug.
I'm fine if you want to call it feature, but it needs to be handled for the sake of this project.

**Comment by LucaMele** [comment]
Agreed, as an enhancement and with the title as finding a valid solution to a problem and not complaining the specs. Lets sit together and find a solution

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
