### ISSUE TITLE
Sub Navigation does not close after first click

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#314]
![sub-menu-not-closing-after-first-click](https://user-images.githubusercontent.com/914443/37139887-e9f24356-22af-11e8-95c4-d454b1695819.gif)

**Comment by LucaMele** [comment]
I will fix it right now

**Comment by LucaMele** [comment]
thanks

**Comment by AndyOGo** [comment]
Maybe it's related to the removal of `js-header-navigation-close` class

**Comment by AndyOGo** [comment]
BTW Why is there so much space between the links?
Is it intented?

**Comment by LucaMele** [comment]
yes.. and on dev it behaves also again totally different than here. This is not good

**Comment by LucaMele** [comment]
no its how it came out :)

**Comment by AndyOGo** [comment]
@LucaMele 
I just checked locally the configuration passed to `UIEvents` from the **Stroke** and **Header Navigation**.
In fact they are not equal. `useDefaultEvent` is `false` for the patterns library, but true for axa.ch

<img width="1440" alt="screen shot 2018-03-08 at 13 39 58" src="https://user-images.githubusercontent.com/914443/37151598-6a8989fe-22d6-11e8-8c0e-1c7011a7a65e.png">

**VS**
<img width="1440" alt="screen shot 2018-03-08 at 13 40 09" src="https://user-images.githubusercontent.com/914443/37151610-712d0c0e-22d6-11e8-90ef-480a5b31107f.png">
