### ISSUE TITLE
device state should trigger initially

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#32]
Since we switched component initialisation to `DOMContentLoaded`, the `device-state/change` event doesn't trigger anymore after the component was initialised (cause this initial trigger is itself also triggered by `DOMContentLoaded`).

Thus just fire always an initial event on subscription, if possible 🎉  

Well, that's not so easy because of **redundant modules**.
So it seems it's time to start attaching data to DOM...

Or just provide a static `getDeviceState` function which needs to be used for initial value retrieval

**Comment by LucaMele** [comment]
sorry about that

**Comment by AndyOGo** [comment]
no worries, I think I found a smart workaround.
subscribing to subscribtions 💪
