### ISSUE TITLE
Define which builds we need

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#332]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

We need two kind of builds:
- [ ] one bundle per component
- [ ] code splitting into single chunk `common.js`
- [ ] one for **consumers** ready to use (ES5, UMD; w/o web components polyfill, React, etc.)
   -> lets call it `library` or `lib`
- [ ] one for the **webapp** including stuff like web components polyfill, React, etc.
   -> lets call it `app`

**Comment by AndyOGo** [comment]
@LucaMele 
I went to implement above requirements by various bundler/loaders, here are my results:

Bundler | PR| Multi-Entry | Multi-Format | Code-Splitting | Code-Split into single file | Custom Loader | UMD | Issue
--- | --- | --- | --- | --- | --- | --- | --- | ---
WebPack | #303 | ✅  | ✅ | ✅ | ✅ | ❌| ❌ | https://github.com/webpack/webpack/issues/2471
Rollup | #333 | ✅ | ✅ | ⁉️ | ❌ | ✅ | ❌ |

**Comment by LucaMele** [comment]
we need to go through it

**Comment by AndyOGo** [comment]
Yes, I may I ask you to upvote those two issues linked at the table on the right side above?

**Comment by LucaMele** [comment]
yes sorry.. done :)

**Comment by AndyOGo** [comment]
Rollup has some updates 🎉 

- Chunk Groupings https://github.com/rollup/rollup/issues/2070
- Consider UMD / IIFE support for code splitting https://github.com/rollup/rollup/issues/2072

@LucaMele 
@TheDadi 
Please carefully read those issues and if you agree, please upvote 👍

**Comment by AndyOGo** [comment]
And a new ticket for webpack's bug https://github.com/webpack/webpack/issues/6818

**Comment by AndyOGo** [comment]
As a workaround we could may use [Rollup's `--external` option](https://rollupjs.org/guide/en#external-e-external) to exclude our common JS from the components build and may have an additional commons build - I will try that.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
