### ISSUE TITLE
Incremental rendering duplicates DOM nodes

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#335]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

Web-Components with children (slots) have proper incremental rendering.

- [ ] Content / Slots have changed by `appendChild`, `replaceChild`, `insertBefore`, `innerText`, `VDOM`, etc.
   ```html
   <axa-foo><div>Some Content</div></axa-foo>
   <!-- Next the same component instance, but with different content -->
   <axa-foo><div>Other Content</div></axa-foo>
   ```
- [ ] Attributes have changed by `setAttribute`, `remove Attribute`, setting properties, etc.
   ```html
   <axa-foo></axa-foo>
   <!-- Next the same component instance, but with different attribute -->
   <axa-foo some-attr="bar"></axa-foo>
   ```

## Actual Behavior

Each Component does only render once.

## Specifications

Every Browser

**Using `<slot />` Tag**
![incremental-dublication](https://user-images.githubusercontent.com/914443/37393851-99e014b6-2772-11e8-9fda-3b348d8b83d3.gif)

**Comment by AndyOGo** [comment]
Setting `innerText` on a Web-Component's instance does not trigger Lifecycle events 😱 

![no-lifecycle-events](https://user-images.githubusercontent.com/914443/37397298-89e8b3e8-277b-11e8-91d2-f4390897dda2.gif)

**Comment by LucaMele** [comment]
ok.. seems like lots of work :)

**Comment by AndyOGo** [comment]
Yep, indeed. I think we have 3 options:

- Relying on `DOMSubtreeModified` mutation event (deprecated)
- Relying on `MutationObserver`
- Monkey Patching DOM API's with getters/setters (ES5 only)

All aren't nice IMHO.

**Comment by AndyOGo** [comment]
https://developers.google.com/web/fundamentals/web-components/shadowdom#lightdom

**Comment by AndyOGo** [comment]
seems that [`<slot />` is intended for ShadowDOM only](https://developers.google.com/web/fundamentals/web-components/shadowdom#slots)?
>A component can define zero or more slots in its shadow DOM.

**Comment by AndyOGo** [comment]
setting properties or calling `setAttribute` form outside does not trigger `attributeChangedCallback` 😱
