### ISSUE TITLE
Make UIEvents lazy

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#346]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

I expect, that `UIEvents` starts it'S magic upon all necessary resources are available.
May it's also important for re-rendering.

But doing so may break existing code. So maybe both should be possible - sync and async.

## Actual Behavior

`UIEvents` will setup all DOM refs, event binding etc. at construction time.
Though in case like the **Stroke** it's necessary to lazily initialize all of those.

## Steps to Reproduce the Problem

See this PR #345 

## Specifications

All

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
