### ISSUE TITLE
Keep existing css classes

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#35]
If a custom component has some classes attached to it, then they should be kept and not thrown away.

**Edit:**

```html
<axa-custom class="any-classes-here"></axa-custom>
```

```js
Custom extends HTMLElement {
  connectedCallback() {
    // remove all classes, in above case: .any-classes-here
    this.className = 'a-custom';
  }
}

window.customElements.define('axa-custom', Custom);
```

Results in:
```html
<axa-custom class="a-custom"></axa-custom>
```

**Comment by LucaMele** [comment]
Can you describe the issue with more details please? Do you mean that if u have something like this.aclass = new Aclass() in the constructor of the CE, the this.aclass will be lost??

**Comment by LucaMele** [comment]
i think css classes are meant here right? Easy issue then. Thank you
