### ISSUE TITLE
IE SCRIPT5022: Exception thrown and not caught

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#36]
![virtualbox_ie11 - win7_06_12_2017_10_53_11](https://user-images.githubusercontent.com/914443/33655597-c7747968-da73-11e7-84d1-370a27fc5411.png)
![virtualbox_ie11 - win7_06_12_2017_10_53_37](https://user-images.githubusercontent.com/914443/33655598-c78b72bc-da73-11e7-94ec-fe2a43378dbb.png)

**Comment by LucaMele** [comment]
This bug is weird and have to be analysed. Thank you for reporting it

**Comment by LucaMele** [comment]
i think is fixed.. feel free to reopen in case is not

**Comment by AndyOGo** [comment]
hmh, IDK. We would need to check IE11
