### ISSUE TITLE
Should we inline icons?

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#363]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

Icons should be easily reused for consumers.

## Actual Behavior

Currently we use SVG-Sprites, which are awesome, but for consumers they come with some pain

- [ ] User need to bundle those icons according to patterns-libs format
- [ ] They need to serve the icon's sprite SVG file
- [ ] The path needs to be correct

**Note:** If we decide to inline icons, our consumers won't need to load/bundle them.
But several components provide dynamic icons.

May we should be able to provide both.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
