### ISSUE TITLE
Reduce FOUC of Web-Components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#365]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

Each Web-Component should display it's content upon **Connection** and not any time sooner.

## Actual Behavior

Each Web-Components renders it's children without any styles, once the custom element gets asynchronously **connected** it re-renders again, flattening it's local and light DOM and applies it's custom CSS styling. This process is visible as an ugly FOUC (Flash of unstyled content).

## Steps to Reproduce the Problem

1. just go to https://axa-ch.github.io/patterns-library/organisms.html

![web-components-fouc](https://user-images.githubusercontent.com/914443/37959364-3ff2e942-31b3-11e8-9134-e0024ba5c3b6.gif)

## Specifications

Any browser

**Comment by AndyOGo** [comment]
Related article:
https://www.stevesouders.com/blog/2013/11/26/performance-and-custom-elements/

**Comment by AndyOGo** [comment]
IMHO the best approach would be to disable `visibility` until the custom element is connected.

**Comment by AndyOGo** [comment]
Dealing with FOUC of custom elements is really pure pain 😭 
I mean we can fix it for the Plib, **but** each consumer of the patterns library has to fix every single custom element by themselves, we can't do it reliably in advance...

Here are all approaches I came up with (and all of them suck):
- inline `<axa-foo style="visibility: hidden;">` - most bullet proof IMHO
- global `<axa-foo class="is-custom-element-disconnected">` - CSS must be loaded before any custom element (ideally in the `<head>`)
- CSS tag wildcard selector `axa-* { visibility: hidden; }` - nice idea, but such a selector does not exist and again must be loaded before any custom element
   **Note:** we could fake this and maintain a curated list of AXA custom element selectors, like:
   ```css
   axa-icon, axa-dropdown, axa-button, ... {
     visibility: hidden;
   }
   ```
   But that is just stupid...
- the global HTML `hidden` attributes is the equivalent of CSS `display` not `visibility` - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
- add a [PostHTML](https://github.com/posthtml/posthtml) plugin which adds the inline style - needs an additional build step for our users...

**Note:** This whole issue and many others arise from the custom element's asynchronous nature. They start in `disconnected` state, but display their unstyled children (the **FOUC**), then in the best case they become `connected` and their styles display (the **FOUC**). And to make this even more complicated, any nested parent/child custom element will trigger those state changes multiple times, which leads us to the **FOUC chain**_saw_ massacre 😱 

**Note 2:** The main issue is server generated code. Client side integrations like `withReact` can be extended to automatically add inline `style="visibility: hidden;"` for all custom elements.

**Comment by AndyOGo** [comment]
@jojackpot and @kenaxa suggest to mitigate this with skeleton views - including an SVG-animation loaded inline with the HTML markup (before CSS and JS).

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
