### ISSUE TITLE
Edge/Chrome Active submenu broken

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#366]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

The sub navigation should also work with an active item.

## Actual Behavior

The sub-navigation open/close is broken with an active item.

## Steps to Reproduce the Problem

1. Got to https://www.acc.axa.ch/en/private-customers/offers/vehicle-travel/car-insurance.html
2. Click on the menu

## Specifications

Any Browser
 
## Failure Logs

```sh
frontend-lib.4e9627a54726eaf9feb9aab54286885f.js:100 Uncaught TypeError: Cannot read property 'className' of undefined
    at Yi (frontend-lib.4e9627a54726eaf9feb9aab54286885f.js:100)
    at Ai (frontend-lib.4e9627a54726eaf9feb9aab54286885f.js:100)
    at t.value (frontend-lib.4e9627a54726eaf9feb9aab54286885f.js:133)
    at frontend-lib.4e9627a54726eaf9feb9aab54286885f.js:133
```

**Comment by LucaMele** [comment]
looks like is that the place where it crashes. node does not exist

**Comment by LucaMele** [comment]
Called from here


<img width="661" alt="bildschirmfoto 2018-03-27 um 12 58 09" src="https://user-images.githubusercontent.com/275235/37963435-8aba57f2-31be-11e8-92a0-da4ad57da12a.png">

**Comment by AndyOGo** [comment]
I found it. It happens by adding `'is-stroke-interactive'` class (`this.options.interactiveClass`).
Cause `this._list` is undefined, but shouldn't be...

<img width="1414" alt="screen shot 2018-03-27 at 13 00 07" src="https://user-images.githubusercontent.com/914443/37963544-dffd2b0e-31be-11e8-8990-926e5feb3957.png">

**Comment by AndyOGo** [comment]
May this is just a binding issue at axa.ch, we will see soonish...

**Comment by AndyOGo** [comment]
DEV released, issue fixed, will wait for ACC though...

**Comment by AndyOGo** [comment]
ACC almost works, except **EDGE 16** for first click - but this issue isn't related to this one...
