### ISSUE TITLE
Use official custom elements es5 adapter script

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#372]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

We need to transpile our code, hence we wan't to provide Custom Elements in ES5 style inheritance.
We should make use of the [official `custom-elements-es5-adapter.js` adapter script](https://github.com/WebComponents/webcomponentsjs#custom-elements-es5-adapterjs).

Or from the direct source https://github.com/webcomponents/custom-elements#es5-vs-es2015

## Actual Behavior

We do custom, complex **Reflection** to get Custom Elements working.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
