### ISSUE TITLE
Firefox inspector does not trigger attributeChangedCallback

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#374]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

I expect changing attributes of custom elements within Firefox's inspector to trigger `attributeChangedCallback`

## Actual Behavior

Nothing happens.

## Steps to Reproduce the Problem

1. Open https://axa-ch.github.io/patterns-library/ in Firefox
2. inspect the logo
3. try to change the `icon="logo-AXA"` to `icon="facebook"`

![firefox-inspector-attribute-change-bug](https://user-images.githubusercontent.com/914443/38016082-3c433c8c-326e-11e8-8f88-db9a8fc20840.gif)

## Specifications

 - Browser: Firefox
 - Browser Version: 59
 - Ticket in Firefox's issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1449489
 - Related Issue: https://github.com/webcomponents/webcomponentsjs/issues/391

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
