### ISSUE TITLE
Illustrate web components life cycle diagram

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#380]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

The Web-Components Lifecycle should be accompanied by an illustration - following #359.

I started to illustrate it at [draw.io](draw.io):
![web-components-lifecycle](https://user-images.githubusercontent.com/914443/38255128-4a31257e-375b-11e8-9c2a-b9cd0f40b000.png)

## Actual Behavior

No illustration available right now.

## Steps to Reproduce the Problem

Go to https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements

**Comment by AndyOGo** [comment]
like this 💪 
http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

**Comment by AndyOGo** [comment]
https://twitter.com/dan_abramov/status/981712092611989509

**Comment by AndyOGo** [comment]
Alright, I forked the awesome react lifecycle diagram and started converting it to custom elements v1 🚀 
Still work in progress and a draft.
I do this is my spare time fro free (not paid by axa).
My big picture is to have it as a community project, with the goal that it will be forked or serve as inspiration for other library/framework creators based on custom elements, so that they only need to add their custom/non-standard magic.
PR: https://github.com/AndyOGo/custom-element-reactions-diagram/pull/1

<img width="1268" alt="screenshot 2019-01-22 at 10 21 06" src="https://user-images.githubusercontent.com/914443/51526540-ea52be00-1e32-11e9-9028-4a8a5fdfbf0e.png">

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
