### ISSUE TITLE
Use absolute imports

### ISSUE THREAD

**Issue by TheDadi** [axa-ch/patterns-library#382]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Can use absolute imports instead of relative '../../js/' etc.

## Actual Behavior

Relative imports

## Steps to Reproduce the Problem

Add a new component and have fun doing some relative path imports

**Comment by AndyOGo** [comment]
I totally agree, everything form `js/`, `styles/` and `components/` should be easily resolved absolutely.

But any consumer of raw source would need to implemented this resolve magic into their build.
Would be keen to solve this though.

**Comment by AndyOGo** [comment]
and `icons/` I guess 🤔

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
