### ISSUE TITLE
deliver zero specificity CSS

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#383]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

It's expected that our consumers don't have to deal with CSS specificity hell originating form the patterns-library itself.

The goal is to avoid `.adjoining.classes` or `.parent .classes` and only get the desired CSS by
- proper cascading order
- `@media` queries

Let's discuss how we want to approach this and if we need common rules.

I think the downside is:
- same modifier/state classes have to be added to multiple DOM nodes (performance decrease)
- bigger maintenance and more efforts needed for implementation

## Actual Behavior

States and some modifiers increase CSS specificity slightly.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
