### ISSUE TITLE
first class props

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#39]
How do we support properties other than `string`?

**Requirements:**

- [ ] Data down, actions up
- [ ] support prop types of `Number`, `String`, `Boolean`, `Object`, `Array` `Null`
- [ ] `Function` as property

**Note:**
We already parse the given property string with `JSON.parse()`. This way we can support `true`, `false`, `1234`, `'string'`, `[]`, `{}`, `null`

**Nice Reads:**
- http://robdodson.me/interoperable-custom-elements/
- React discussion: https://github.com/facebook/react/issues/7901

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
