### ISSUE TITLE
Add a define Element Decorator

### ISSUE THREAD

**Issue by TheDadi** [axa-ch/patterns-library#391]
First, thank you for contributing.
Please provide us with at least the following data.

# Prerequisites
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

I hate to do this 
`wcdomready(() => {
      window.customElements.define('axa-button', AXAButton);
    });`

## Actual Behavior

But i like this 

```
@defineElement()
export default class AXAButton extends BaseComponentGlobal {
  static get observedAttributes() { return ['arrow', 'classes', 'color', 'ghost', 'motion', 'size', 'tag', 'url']; }

  constructor() {
    super(styles, template);
  }
}
```

## Steps to Reproduce the Problem

What do we need to do, to reproduce your issue?
Please provide screencasts and/or screenshots - awesome tools are:
- MacOS: [GIPHY Capture](https://giphy.com/apps/giphycapture)
- Windows: [ScreenToGif](http://www.screentogif.com/)

1. Implement a component

**Comment by LucaMele** [comment]
Agree. Im a bit afraid of consumer of the library that want to include the source files. We provide a "service" for easy use ad reuse of components. But at the end we provide disted files and if someone includes the WC as source, we expect that he knows what is doing and therefore that he has familiarity with Babel and extra Plugins.

So, if we start listing all the Babel plugins needed in the contribution file, we can do this feature that helps us a lot while developing. Thanks @TheDadi

**Comment by AndyOGo** [comment]
We definitely should provide several disted formats like `umd` and `mjs`

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
