### ISSUE TITLE
JSON.stringify within templates slow

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#397]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

I expect to be able to pass first class properties also within templates to other web-components.

## Actual Behavior

Currently first-class props have to be provided stringified to the consuming component and this component will parse it in turn again. 😱 

## Steps to Reproduce the Problem

https://github.com/search?utf8=%E2%9C%93&q=JSON.stringify+repo%3Aaxa-ch%2Fpatterns-library+path%3A%2Fsrc%2Fcomponents&type=Code&ref=advsearch&l=&l=

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
