### ISSUE TITLE
SCSS/CSS not optional

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#40]
> Error: File to read not found or unreadable: /Users/axawinterthur/dev/axa-ch_style-html-guide/src/components/o-deterministic-lifecycle/index.scss

**Comment by LucaMele** [comment]
What is the issue exactly? That scss have to have a index.js at the moment?

**Comment by AndyOGo** [comment]
I get this, if a component's folder does not have an `index.scss` file.

**Comment by LucaMele** [comment]
and do you include in the component the styles? in the index.js do you do import './index.scss'? if so, please remove the import and the issue should be fixed

**Comment by AndyOGo** [comment]
Nope, I don't. It's a bug in the build script.

**Comment by LucaMele** [comment]
ok thank you, I will fix it.

**Comment by AndyOGo** [comment]
I guess it's in here https://github.com/axa-ch/patterns-library/blob/master/stack/tasks/build-examples.js#L97-L100

**Comment by LucaMele** [comment]
fixed
