### ISSUE TITLE
Develop Branch has old dist files, missing new components

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#400]
- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Be able to use the new components in the develop branch

## Actual Behavior

Currently the develop branch has a-choice as a component, the dist files are missing it. (For example a-choice)

**Comment by LucaMele** [comment]
We need to release it in order to create and update the dist folder. I will talk with @AndyOGo to find out when is possible

**Comment by AndyOGo** [comment]
@MatthiasDyballa 
Thanks for feedback.

Please correct me if I'm saying something not correct.

I assume that you install the **patterns-library** not through NPM, but rather by GIT.
If so it's important to differentiate between a package we have build and released for NPM, and any non-tagged git commit or branch.

Every release is [properly tagged within our Git history](https://github.com/axa-ch/patterns-library/releases) and at NPM we currently provide only tagged `beta` releases.

None of any untagged commits, rc, alpha and beta releases do represent a latest version.
