### ISSUE TITLE
Clean up link

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#405]
## Are you reporting a bug or a feature?

 - [ ] Feature
- [x] Bug
 
## Expected Behavior

~~I would like to place any icon either left or right.~~

Any Icon should always be on the left side, except for an arrow icon, which is:
- on the right side
- on the left side if listed

https://design.axa.com/web-guidelines/buttons-and-links#types-of-links

## Actual Behavior

Currently we have `icon`, `listed` (for left) and `arrow` (special hardcoded for right).

**This will lead to breaking changes**

**Comment by NoahLiechti** [comment]
I don't see exactly what here is to do. In my opinion it behaves just like expected.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
