### ISSUE TITLE
Rerender loses focus of input

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#408]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All components should re-render in an incremental manner, meaning:
- doing just updates und **NOT** replacing whole DOM sub trees -> DOM diffing
- be scoped at component level - should only mess with it's **local-DOM**
- keep intrinsic state of interactive HTML elements like `<input />`

## Actual Behavior

The whole DOM sub-tree is removed and re-written, this leads all interactive HTML elements to starts at it's initial state and in case of `<input />` loses it's focus during user interacting with it.

**Note:** `shouldUpdateCallback()` possibly mitigates this problem, but it's not a complete solution.

## Steps to Reproduce the Problem

![react-input-loses-focus-within-ce](https://user-images.githubusercontent.com/914443/38878707-e018ca86-4261-11e8-97b1-911f114dad8d.gif)

**Comment by MarekLacoAXA** [comment]
I think this issue is not resolved. The `axa-input` still looses focus on change.

**Comment by MarekLacoAXA** [comment]
Is this a possible fix for axa-input?
**Skip re-render** (updated() fn call) in axa-input in case the WC value is same as the last change originating from the internal input element. (e.g. coming from the input itself, not from the outside).

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
