### ISSUE TITLE
Generic pattern of iterator components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#410]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

For all components who iterate over data (like `<axa-header-navigation>`, `<axa-header-languages>`, `<axa-header-others>`, `<axa-footer-languages>`, `<axa-footer-social>`, `<axa-accordion>`, etc.) I would like to be able to choose between a
- intrinsic iteration implementation (the web-component knows how to render `items`)
   ```html
   <axa-iterator items='[1, 2, 3, ...]'></axa-iterator>
   ```
- and a custom iteration implementation (the web-component just renders the children)
   ```html
   <axa-iterator>
      <!-- I do the iteration myself here or even static code -->
      <axa-item>1</axa-item>
      <axa-item>2</axa-item>
      <axa-item>3</axa-item>
      <axa-item>...</axa-item>
   </axa-iterator>
   ```

This would be extremely useful for big data and framework-integrations like react and if I want to utilize an improved iteration library like [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List).

**Note:** I don't intent to create a new component `<axa-iterator>`, but rather want to distill an iterator pattern. 

## Actual Behavior

Item iteration is always done by the component itself.

**Comment by TheDadi** [comment]
I would do something like this:
``` 
<axa-iterator element="ul" items='[{key: "test", value: "test"]'>
  <li>
    <span>${key}</span>
    <span>${value}</span>
 </li>
</axa-iterator>
```

**Comment by AndyOGo** [comment]
@TheDadi 
Hmh, I think we speak about two different thinks 🤔 
I don't intent to create a new component `<axa-iterator>`, though may it will be usefull in the future.

I would like to define a generic API for all components who iterate over data, `<axa-header-navigation>`, `<axa-header-languages>`, `<axa-header-others>`, `<axa-footer-languages>`, `<axa-footer-social>`, `<axa-accordion>`, and all others

**Comment by TheDadi** [comment]
Sry for that one 😂

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
