### ISSUE TITLE
Migration Paths and Release Notes

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#412]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

I expect for every kind of release to have:

- **Release Notes** listing all introduced features and bug fixes accompanied by their linked issue/pr ticket.
- **Migration Paths** listing all changes to be made to keep up with braking chances.

**Ideally** most of this will be auto-generated, especially regarding GIT grouped branches.
- `bugfix/*` groups all bug fix branches
- `feature/*` groups all feature branches

We should also provide a `CHANGELOG.md` file.

## Actual Behavior

We don't have neither.

## Specifications

- https://help.github.com/articles/creating-releases/
- https://developer.github.com/v3/repos/releases/#create-a-release
- https://github.com/github-tools/github-release-notes
- https://github-tools.github.io/github-release-notes/concept.html
- https://github.com/ariatemplates/git-release-notes

**Comment by TheDadi** [comment]
https://github.com/semantic-release/semantic-release

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
