### ISSUE TITLE
Double check each component if it's ready for integrations

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#418]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

Each component has to make sure that it:
- defines static `observedAttributes`
- uses proper lifecycle methods `willRenderCallback`, `didRenderCallback`, etc.
- makes sure to keep event handling working after incremental rendering
- provides proper namespaced custom events triggered at the root DOM node of the custom element itself to be consumed by react, angular, you name it

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
