### ISSUE TITLE
After hotfix release NPM version GIT tag already exists

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#422]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

After we released a **hotfix** at `master` I expect that a following normal release from `develop` run through seamlessly.

## Actual Behavior

The new tagged version isn't in sync with `develop` and thus subsequent releases are blocked by NPM, because the next bumped version to be released from `develop` was already released at `master` by the hotfix release.

Additionally we get merge conflicts for `dist/`, `docs/` and `package.json`.
Somehow we have to optimize **hotfix** release tp prevent this from occurence.

## Failure Logs

```sh
Error: Command failed: npm run bump-beta
fatal: tag 'v2.0.1-beta.121' already exists

Error: Command failed: git tag "v2.0.1-beta.121"
fatal: tag 'v2.0.1-beta.121' already exists
```

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
