### ISSUE TITLE
Broken Button With React after master merge

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#424]
`<AXAButtonReact onAxaClick={this.handleClick} key={1} >{this.state.isToggleOn ? 'ON' : 'OFF'}</AXAButtonReact>` does not update (always ON is shown. Is ONLY appeared after master merge as it was tested before mergin and worked correctly

on localhost

**Comment by AndyOGo** [comment]
Damn the `axa-click` event should be triggered from here:
https://github.com/axa-ch/patterns-library/blob/develop/src/components/m-button/js/button.js#L52

**Comment by AndyOGo** [comment]
I think I got it.
`shouldUpdateCallback` does only check if attributes/properties have changes.
But in case of the button neither does, **though** the `children` do update...

**Comment by AndyOGo** [comment]
Okay since we don't use shadowDOM React see not only it's own children but also our web-components local DOM.
So somehow we have to sync up Reacts children within a web-components light DOM 🤔

**Comment by AndyOGo** [comment]
May this helps...
https://reactjs.org/docs/integrating-with-other-libraries.html

**Comment by AndyOGo** [comment]
http://robdodson.me/interoperable-custom-elements/

**Comment by AndyOGo** [comment]
https://www.sitepen.com/blog/2017/08/08/wrapping-web-components-with-react/

**Comment by AndyOGo** [comment]
https://medium.com/dev-channel/the-case-for-custom-elements-part-1-65d807b4b439
https://medium.com/dev-channel/the-case-for-custom-elements-part-2-2efe42ce9133
