### ISSUE TITLE
Visualize colors

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#429]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Colors nicely visualized, including different color formats :)
https://design.axa.com/toolkit/v2/getting-started/colors.html

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I would still like to have colour visualisations 💪

**Comment by LucaMele** [comment]
legit

**Comment by raphaellueckl** [comment]
@LucaMele What is the state here? We have colors, but they are not yet released?

@AndyOGo You want the plib to contain a collection of colors like in your link? If yes, we should do that soon. AFAIK the colors are finished, but not released yet. Would probably make sense to create storybook stories for such a thing.

**Comment by AndyOGo** [comment]
Thanks @raphaellueckl for looking into this :)

Yes, as far as I know colors are mandatory and I would wish to have an interactive color palette, describing it's usage and all that design related stuff.

**Comment by NoahLiechti** [comment]
@raphaellueckl Is this component already planned for a specific sprint or is somebody working on it?

**Comment by raphaellueckl** [comment]
@NoahLiechti No, not right now. But I also think this is kind of a "most wanted" feature and should get more attention. We should add it to our next PI "wishlist". I will do that here: 

https://github.com/axa-ch/patterns-library/projects/3

**Comment by raphaellueckl** [comment]
@AndyOGo We planned this feature for this PI. 😎

**Comment by danyball** [comment]
https://benrobertson.io/frontend/color-swatches-storybook
