### ISSUE TITLE
What if we could transform/compile Web-Components to React, Angular, etc.

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#435]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

As an alternative to **integrating** Web-Components within other Libraries/Frameworks like React, Angular, etc.
It would be super awesome if we can **transform** them from Web-Components to React, Angular, you name it.

This would enable intrinsic SSR features of the respective transformation target 🎉 

## Actual Behavior

First React-Integration is ready, but SSR would not work and it would need two steps (first from React, then from web components)

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
