### ISSUE TITLE
Delete git tag if release was interrupted

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#438]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Cleanup should remove git tag if release is not successfully finished.

## Actual Behavior

Git tag is not cleaned up and prevents further releases, because that tag exists already.

## Steps to Reproduce the Problem

1. run `npm run release`
2. if something fails the git tag is not removed

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
