### ISSUE TITLE
Make input-wrapping components controllable by React

### ISSUE THREAD

**Issue by pavestru** [axa-ch/patterns-library#439]
## Are you reporting a bug or a feature?

 - [x] Bug (or is it a feature?)

## Expected Behavior

The recommended way to implement forms with React is to [use controlled components](https://reactjs.org/docs/uncontrolled-components.html).  That means that the state of React component controls the state of forms input elements, like checked, value or disabled. Changing React state from outside changes state of form input elements.

## Actual Behavior

Currently custom elements like axa-checkbox wrap form elements and create a facade for their attributes. In case of axa-checkbox, it wraps an `<input type="checkbox" />` with attribute `checked`. However, these attributes do not reflect well between the custom element and its own wrapped inputs. For example, in case of axa-checkbox, when set `checked={true}` from outside, it gets reflected to input's `checked="checked"` correctly once, but changing axa-checkbox's checked attribute further from outside does not change the `checked` attribute of the input element.

However, interacting with the element itself directly (e.g. by clicking) changes its internal state and is able to trigger event listeners.

Observed in components:
 - axa-choice
 - axa-checkbox
 - (possibly others)

## Steps to Reproduce the Problem

Notice when clicking first time on AxaCheckbox, its input's internal checked state is changed to unchecked first (independently of the app state) and from the 2nd click on is in sync with state:

![controlled_axa-checkbox](https://user-images.githubusercontent.com/10186479/40559944-be737d12-6058-11e8-8029-2f92b3ed4a00.gif)

```js
// App.js
import React, { Component } from "react";
import "@axa-ch/patterns-library/dist/components/a-checkbox/index.js";

class App extends Component {
  state = {
    checked: false
  };
  componentDidMount() {
    this.checkbox.addEventListener("change", this.onCheckBoxChange, {
      passive: false
    });
  }
  onCheckBoxChange = e => {
    const checked = e.target.checked;
    this.setState({ checked });
  };
  render() {
    return (
      <div>
        State: {JSON.stringify(this.state.checked)}
        <axa-checkbox
          checked={this.state.checked}
          name="test-name2"
          ref={el => (this.checkbox = el)}
        >
          AxaCheckbox
        </axa-checkbox>
        <label>
          <input
            type="checkbox"
            checked={this.state.checked}
            onChange={this.onCheckBoxChange}
          />
          Native checkbox
        </label>
      </div>
    );
  }
}

export default App;
```

## Specifications

 - Browser: Chrome 66 on macOS

**Comment by LucaMele** [comment]
thank you very much for reporting this

**Comment by AndyOGo** [comment]
@pavestru 
Thank you for this superp and very detailed failure description.

Actually this is really weird, because as you say **controlled inputs** should work just fine.
I absolutely agree, if your change some internal state from outside by React or whatever it should:

1. detect the change of the attribute (through `observedAttributes`)
2. trigger an incremental render phase (which should just update the `checked` DOM property - not the HTML attribute, which isn't live)
3. display a nice checked/unchecked state

**Comment by TheDadi** [comment]
I commented on your pr why this is happening.

**Comment by AndyOGo** [comment]
@pavestru 
Sorry, I just realised.
You aren't using the `withReact` integration.
Utilising it will probably solve your issue.

**Comment by AndyOGo** [comment]
@pavestru 
You should now be able to import transpile ES module of [`withReact`](https://github.com/axa-ch/patterns-library/blob/develop/lib/js/with-react.js)

**Comment by AndyOGo** [comment]
Please let us know that we can close this

**Comment by AndyOGo** [comment]
Fixed by adding ESM build

![axacheckboxreact](https://user-images.githubusercontent.com/914443/41352760-91f8f1d8-6f1a-11e8-8a0a-90dbc5711a8d.gif)

**Comment by AndyOGo** [comment]
@LucaMele 
Apparently this seems to be still broken 😞 

@pavestru 
We should have a full test publicly accessible somewhere, a gist or JSBin. So that we are sure testing under the exact same conditions.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
