### ISSUE TITLE
Implement common module. Activate ES Modules in pkg.module prop and IFEE modules that global namespace

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#44]
ATM we bundle up isolated bundle which include identical modules redundantly.

This breaks access to local variables between same module instances.

```js
// this variable is scope within each redundant import/bundle of this module
// and not accessible to other instances of this same module
const localVar = {}

export function foo() {
  localVar.key = 'value';
}

export function bar() {
  return localVar.key;
}
```

**Comment by AndyOGo** [comment]
I think DOM data warehouse could be a feasible workaround, though perfect would be to clean up the build and extract common chunks into a separate vendor file.

**Comment by LucaMele** [comment]
I think a module should contain and not contaminate variables so therefore the behaviour is correct IMHO. What is missing is a mechanism that can be used everywhere like u said global js or similar. We will discuss it. I dont see it as a bug, just a missing feature.

**Comment by AndyOGo** [comment]
Okay.

Let's look at an example:

**shared module `push.js`:**
```js
const localVar = [];

export default function push(value) {
  localVar.push(value)

  return localVar;
}
```

**consumer foo:**
```js
import push from `push`;

const allVars = push('foo');

console.log(allVars); // => ['foo']
```

**consumer bar:**
```js
import push from `push`;

const allVars = push('bar');

console.log(allVars); // => ['bar']
// expected
// => ['foo', 'bar']
```

## Our current bundling result in this

The bug is that shared modules are bundled more than once.

**bundled consumer foo:**
```js
const localVar = [];

function push(value) {
  localVar.push(value)

  return localVar;
}

const allVars = push('foo');

console.log(allVars); // => ['foo']
```

**bundled consumer bar:**
```js
const localVar = [];

function push(value) {
  localVar.push(value)

  return localVar;
}

const allVars = push('bar');

console.log(allVars); // => ['bar']
// expected
// => ['foo', 'bar']
```

**Comment by LucaMele** [comment]
as discussed:

dist should have:
common.js -> IFEE that uses global namespace for common. Ready for <script src=""> imports
common.module.js -> ready for webpack/rollup/etc imports

index.js -> IFEE that uses global namespace for common. Ready for <script src=""> imports
index.module.js -> ready for webpack/rollup/etc imports

**Comment by AndyOGo** [comment]
@LucaMele 
To clarify I talk about the de facto standard **module** prop within `package.json` file.
Documentation can be found [here](https://github.com/rollup/rollup/wiki/pkg.module).

An I suggest to add another folder called `es/` container transpiled files but keep ESNext Module Syntax (Babel allows for that very easily).
