### ISSUE TITLE
Uncaught TypeError: Cannot set property 'StyleGuideWebComponent' of undefined

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#448]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

If i Import the disted UMD checkbox, like

```js
import AXACheckbox from '../../../dist/components/a-checkbox/index.umd';

// or

import * as AXACheckbox from '../../../dist/components/a-checkbox/index.umd';
```

## Actual Behavior

It throws:

at buildtime:
```sh
UnhandledPromiseRejectionWarning: Error: 'default' is not exported by dist/components/a-checkbox/index.umd.js
```

at Runtime:
```sh
all-demos.js:8110 Uncaught TypeError: Cannot set property 'StyleGuideWebComponent' of undefined
```

**Comment by AndyOGo** [comment]
Btw. where does this name **StyleGuideWebComponent** come from?

**Comment by LucaMele** [comment]
i think is the module name that is used to register in the `global | window` object. If u include like it is a esmodule this is undefined and therefore i think it cant append the component name to the this object (window or global). Im not dure thought, but i would start to look in this direction

**Comment by AndyOGo** [comment]
How this name is crafted is still weird, but since it's an **IIFE**. It is never supposed to export anything usable...
