### ISSUE TITLE
Should we use proposed Custom Element

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#45]
Due to different limitations and not standardised specs, should we keep investing in the Web-Components Custom Element or should we use **only** already standardised technology. Matter of the topic is about being fully standard or use experimental technology. Other frameworks, comparison between Web-Components and React are **out of topic** here as they don't move in direction of the main objective of the Style-Guide.

Objective: **Create a Guide in HTML/CSS that is perfectly working and Semantically correct with some components that can be used within every framework**

**Comment by LucaMele** [comment]
PROPOSED SPECS: https://www.w3.org/TR/custom-elements/

**Comment by AndyOGo** [comment]
To answer this question, we need to define which features we expect from a component and then let's just face if Web Components can satisfy/deliver those.

**Comment by LucaMele** [comment]
i guess this is now sorted

**Comment by AndyOGo** [comment]
Yeah, of still some open issues with custom elements, like SSR.
But the most stuff is working

**Comment by LucaMele** [comment]
SSR is not a requirement yet therefore not an issue
