### ISSUE TITLE
Existing DOM properties can't be used as attribute names

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#451]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

I would like to use `prefix` as attribute name, but since it is defined within the DOM API I can't.
- https://developer.mozilla.org/en-US/docs/Web/API/Element/prefix
- https://developer.mozilla.org/en-US/docs/Web/API/Node/prefix

## Actual Behavior

Using `prefix` as attribute name throws an error.

**Comment by AndyOGo** [comment]
But how do we setup `DOM` property getters then?

**Comment by AndyOGo** [comment]
This affects all inherited DOM properties and methods...

- Element Interface https://developer.mozilla.org/en-US/docs/Web/API/Element#Properties
- Node Interface https://developer.mozilla.org/en-US/docs/Web/API/Node#Properties

**Comment by AndyOGo** [comment]
And it needs to be documented in the contribution docs!

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
