### ISSUE TITLE
Composition over Inheritance - or not?

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#456]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Actual Behavior

We just splitted all our components features in 6 higher order class by this PR #455 

Now @LucaMele pointed out a very interesting, rather intrusive aspect of utilising class [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).

- The number of possible combinations is factorial, in our case that are `6!` = `1*2*3*4*5*6` = `720` possible permutations!
- Extension has to work bidirectional, i.e. `A(B(Foo))` === `B(A(Foo))`

**Comment by LucaMele** [comment]
Extension has to work ~~unidirectional~~ -> bidirectional

**Comment by pavestru** [comment]
What about using something like `compose` function from [recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md)? Nicer code, imho:

```js
const composedHoc = compose(hoc1, hoc2, hoc3)

// Same as
const composedHoc = BaseComponent => hoc1(hoc2(hoc3(BaseComponent)))
```
(I'm for composition)

**Comment by pavestru** [comment]
I think `compose()` function (see my previous comment) could be implemented in a way that it would ensure the right order of application regardless of the order of its arguments if designed specifically for a particular set of HOCs, where order of application is important, i.e.:
```js
const composedHoc = compose(hoc1, hoc2, hoc3)
// same as
const composedHoc = compose(hoc2, hoc3, hoc1)
// same as
const composedHoc = BaseComponent => hoc1(hoc2(hoc3(BaseComponent)))
```

**Comment by pavestru** [comment]
Probably not the most efficient way, but could be done like so:
```js
const compose = (...funcs) => {
  const used = {};
  funcs.forEach((f) => {
    // check use of every HOC in arguments
    used.withContext = used.withContext || f === withContext;
    used.withMonkeyPatch = used.withMonkeyPatch || f === withMonkeyPatch;
    used.withRender = used.withRender || f === withRender;
    // ...
  });
  // Now apply the right order - each no more than once:
  let HOC = Component => Component;
  HOC = used.withContext ? Component => HOC(withContext(Component)) : HOC;
  HOC = used.withMonkeyPatch ? Component => HOC(withMonkeyPatch(Component)) : HOC;
  HOC = used.withRender ? Component => HOC(withRender(Component)) : HOC;
  // ...
  return HOC;
}
```

Not `A(B(Foo)) === B(A(Foo))`, but at least `compose(A, B)(Foo) === compose(B, A)(Foo)`.

**Comment by AndyOGo** [comment]
`reduceRight` fits perfecto to implement a `compose` helper

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
