### ISSUE TITLE
Following Header is above sub navigation

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#459]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Sub Navigation should be on top of following headers.

## Actual Behavior

Sub Navigation if below following headers.

## Steps to Reproduce the Problem

<img width="1364" alt="screen shot 2018-06-07 at 09 32 22" src="https://user-images.githubusercontent.com/914443/41084961-dd386b0e-6a35-11e8-840c-c01715b5a019.png">

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
