### ISSUE TITLE
Fonts Slow Network is detected

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#46]
Chrome dev tools log:

>Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff2
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff2
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff2
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff2
index.js:925 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff2
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff2
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff2
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff2
index.js:1781 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff
Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-regular.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-700.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/source-sans-pro-v10-latin-600.woff
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff2
:3000/#o-header:1 Slow network is detected. Fallback font will be used while loading: http://localhost:3000/assets/fonts/PublicoHeadline-Bold-Web.woff

**Comment by LucaMele** [comment]
I noticed that as well. It disappears after npm run serve restart. Need to investigate

**Comment by LucaMele** [comment]
seems like this is not happening anymore. @AndyOGo can u confirm?

**Comment by AndyOGo** [comment]
@LucaMele 
Indeed I can't observe anymore. I also checked the typo atom here:
https://axa-ch.github.io/patterns-library/atoms.html#a-typo
