### ISSUE TITLE
Add Generic Loading Indicator

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#461]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We need a component `<axa-loading>` to display a generic loading indicator.

It's basically a flat blue surface, rotating form left to right und up til down.

- [ ] Positioning should be choosable - `fixed` (at document level), `absolute` (scope contained)
- [ ] Responsive
- [ ] May need a fallback, if 3D animations is not available

http://better-react-spinkit.benjamintatum.com/#RotatingPlane

Existing Implementation can be found at the old swiss style guide:
- https://github.com/axa-ch/style-guide/blob/develop/docs/components/snippets/loading-spinner.pug
- https://github.com/axa-ch/style-guide/blob/develop/scss/style/blocks/spinner.scss
- https://github.com/axa-ch/style-guide/blob/develop/js/jquery/spinner.js

**Comment by AndyOGo** [comment]
https://pages.github.axa.com/axa-singapore/sg-react-components/#/basics/loader

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
