### ISSUE TITLE
move device state to utility

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#468]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

**Device State** atom should be an **Utility**.

## Actual Behavior

**Device State** is an atom

**Comment by LucaMele** [comment]
absolutly agree

**Comment by LucaMele** [comment]
and we need maybe a new section called `utility` also navigable with menu

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
