### ISSUE TITLE
fatal: pathspec './docs' did not match any files

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#474]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Release script should work.

## Actual Behavior

Release script broken.

## Steps to Reproduce the Problem

1. `npm run release`
 
## Failure Logs

```sh
fatal: pathspec './docs' did not match any files
```

**Comment by LucaMele** [comment]
??

**Comment by LucaMele** [comment]
dafuq
