### ISSUE TITLE
Provide easier npm import for components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#479]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

I expect to easily `import` components,
- [ ] without the need to specify a long path and the module format I wish to use.
- [ ] All of these should happen automatically just by writing `import '@axa-ch/button'` (the bundler will pick the right module format that he understands)
- [ ] I don't have to download the whole pattern-lib just for a button.
- [ ] the patterns-lib-app could be it's own package.
- [ ] utilize lerna.js https://lernajs.io/

**Note:** May it should have it's own namespace for the patterns-library 🤔 

## Actual Behavior

- All within one package.
- Consumers have to know the correct path to module formats (`dist/` for umd, `lib/` for esm, `src/` for original, non-transpiled code)
- Application-Build and Library-Build in same package (though the app build is only needed for, well the app)

**Comment by sventschui** [comment]
I'd rather not do that.

```
import { Button, Container, Whatever } from '@axa-ch/patterns-library'
```

is much more convenient. Having to download the whole npm package is not an issue if you don't provide huge binaries - what we shouldn't IMHO.

**Comment by LucaMele** [comment]
Agree with @sventschui . We will create a index.js that imports/exports all the components and when we create a new component useing the command `npm run new` it will append the imprt/export in the index.js automatically. Does that sound good?

**Comment by AndyOGo** [comment]
an `index.js` file is a great idea.
Though I'm still very unhappy with our current build setup and the confusing distribution build we have atm.

We could still create separate packages for each component and provide an "accumulater" package ´, which `imports/exports` every single component 🚀

**Comment by LucaMele** [comment]
i dont think is a good idea atm to create separate packages (even if i can see the point) as it increases tremendously complexity and in my opinion is not necessary for our use case as is more likely a use uses more then one component and therefore the work he would have to do to include the components is more than if is done with `index.js`.

The build currently satisfy all the needs apart of the easy import and we should stick to what is possible to do and not what is the golden best thing. When we have a central team, then we have more capability and we can do it better. Main desicion criteria however should always be: What is the easiest and most maintainable solution to fulfill a use-case/needs and not what would be cool or what makes me unhappy :) but i agree generally with you andy. Simply now is not needed and the build does his job and is maintainable (as it allowed me to create the ES Module lib/component bundle in 4 hours).

**Comment by LucaMele** [comment]
But where i agree on you is that users should not know what they have to import and we can fix that, even if is not hight prio

**Comment by AndyOGo** [comment]
I agree, would be a big jump, though I'm sure will be desirable one day.

Nevertheless I definitely favour to add a quick win `index.js` file 🎉

**Comment by LucaMele** [comment]
yepp

**Comment by pavestru** [comment]
There are definitely ways how to make even using one `index.js` [tree-shakeable](https://survivejs.com/webpack/optimizing/tree-shaking/#tree-shaking-on-package-level) once we use ESM. I think there are examples for that with lodash or RxJS.

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
