### ISSUE TITLE
Button should still look nice if it has an icon only

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#480]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

If I display a button just with an icon, I expect it to still look nice.

## Actual Behavior

I looks really broken, no text on the left but still a left border.

**Comment by AndyOGo** [comment]
hmh, I think this whole button has become really big.
And no doclets, I would rather refactor this whole component, adding complementary comments, etc.

**Comment by LucaMele** [comment]
I think is not intended to be without a text due to UX. Please double check with Anja or Ken

**Comment by LucaMele** [comment]
well people do lots of stuff that are not intended and allowed :)

**Comment by LucaMele** [comment]
as there is no answer from style people, lets assume better to have something not broken then not in styleguide
