### ISSUE TITLE
do not inject styles manually if extend global base component

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#483]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

`extend`ing `BaseComponentGlobal` takes the `styles` via it's constructor and does it's magic, no need to append styles manually upon `DOMReady`.

## Actual Behavior

`<axa-button>` and `<axa-dropdown>` do append styles manually.
As a result they show up twice within the `<head>`!

**Comment by LucaMele** [comment]
there was a reasion why. The function should prevent to add css twice with the memory trick. This must have changed if this bug occured

**Comment by AndyOGo** [comment]
Well it's broken now, because I removed the using the whole `styles` as key lookup.

**Comment by AndyOGo** [comment]
Regardless they reason, we should never do this adding it manually if we extend `BaseComponentGlobal`.

**Comment by LucaMele** [comment]
ok agree
