### ISSUE TITLE
Non-Native Dropdown needs double click on iOS

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#490]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

One click should open the dropdown.

## Actual Behavior

First click set's focus and second click opens the dropdown.

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/molecules.html#m-dropdown
2. and play with non-native dropdowns on iOS

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
