### ISSUE TITLE
horizontal scrollbar at iPhone

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#491]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We shouldn't have horizontal scrollbars at mobile devices.

## Actual Behavior

My iPhone's viewport is blow-up and creates a horizontal scrollbar.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/molecules.html#m-dropdown

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
