### ISSUE TITLE
Shared CSS loaded multiple times at axa.ch

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#492]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Integrations of the patterns-library and various SPA's should not generate multiple duplicates of exact same CSS rules.

- This increases load time
- bloats our CSS, and thus the browsers memory
- really bad for mobiles

## Actual Behavior

Consuming the patterns-library's SASS and integration a third-party SPA like eClaim's UI-Renderer generates multiple duplicates of the same CSS.

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this is still valid too

**Comment by LucaMele** [comment]
@AndyOGo please provide proof in V2, we should have fixed it with shadowDom and with this: https://github.com/axa-ch/patterns-library/blob/develop/src/utils/no-shadow.js. Feel free if issue is still there in v2
