### ISSUE TITLE
Add editable explanations of the components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#494]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Each component should explain:

- [ ] What it is, when and how it is used
- [ ] How it's supposed to be composed with other components
- [ ] Links to the relating style guide or incorporate it's content (I favour the second, because it is confusing to need to jump between different guide lines)
- [ ] Has tags for being **approved**, **experimental**, etc
- [ ] incorporate generated docs from related docslets of SassDoc and JSDoc 
- [ ] Ideally it should be easily editable by designers without any knowledge of git or release processes

**Suggestion:** use markdown for prose, in the form of one `README.md` file for each component.
Markdown for SassDoc and JSDoc should be automatically generated and automatically linked by dependent components.

## Actual Behavior

No prose documentation at all.

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
