### ISSUE TITLE
add flow

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#496]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

https://flow.org/en/

**Comment by LucaMele** [comment]
super idea.. but im wondering, as we accept only string as param for component, will this actually help? Or am i missunderstanding something?

**Comment by AndyOGo** [comment]
It would help for all the other js.
Regarding attributes I have filed #495

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
