### ISSUE TITLE
Dropdown is not using event delegation for it's items

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#498]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All events needed for two or more events must be delegated.
Hence all elements of the dropdown shall use delegation.

## Actual Behavior

Currently it selects a **non-live** DOM list of it's elements and iterates through it's items to add a distinct event handler for each item.

~This does not scale and does not support dynamic addition and removal of items!~ -> not true for dropdown due to forced re-rendering

Got introduced by https://github.com/axa-ch/patterns-library/pull/478

Buggy lines are:
- https://github.com/axa-ch/patterns-library/blob/develop/src/components/m-dropdown/js/drop-down.js#L29
- https://github.com/axa-ch/patterns-library/blob/develop/src/components/m-dropdown/js/drop-down.js#L37-L40
- https://github.com/axa-ch/patterns-library/blame/develop/src/components/m-dropdown/js/drop-down.js#L48-L52

## Specification

https://jsfiddle.net/wotx507z/5/

**Comment by LucaMele** [comment]
I will fix this "not niceness" now
