### ISSUE TITLE
add error pages

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#500]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

https://design.axa.com/web-guidelines/error-pages

## Actual Behavior

No error pages

**Comment by AndyOGo** [comment]
@LucaMele 
I started, though special error page and a login mask is still open.
And error pages seem to consume at least the full viewport height 🤔

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
