### ISSUE TITLE
IE11 logo does not always show

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#513]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All icons should **always** show up in **any** browser!

## Actual Behavior

At least IE11 does not always show the logo icon, this seems to be a problem with asynchronous loading of the `icons.svg`

## Steps to Reproduce the Problem

1. Open BrowserStack or local IE
2. And goto any page

**How to restore failed icon:**
![ie-restore-logo-lost](https://user-images.githubusercontent.com/914443/42365392-a4a6b39c-80fe-11e8-9c07-a4ee32630c82.gif)

**Full Page Load of Atoms in IE11:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/914443/42365642-562d4be4-80ff-11e8-920f-105750dcd76f.gif)

## Specifications

 - Browser: IE
 - Browser Version: IE 11
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by AndyOGo** [comment]
Original Video in MP4:

[ezgif.com-gif-maker.mp4.zip](https://github.com/axa-ch/patterns-library/files/2169421/ezgif.com-gif-maker.mp4.zip)

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
