### ISSUE TITLE
Each Component should check that all the elements are defined which it needs for rendering

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#522]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

If a custom element depends on another custom element, e.g. by using it inside it's local DOM template, it should warn the user if that other custom element is not available.

**Note:** Since we load those other elements asynchronously, it's maybe a good idea to delay this check upon `DOMContentLoaded` 🤔 

## Actual Behavior

Not a single component states anything about it's dependencies of other custom elements...

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
