### ISSUE TITLE
Support custom icons

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#523]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

All global and material icons are allowed to be used.

## Actual Behavior

Only a specific subset of possible icons is available through the patterns library.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Agree to re-think the icons logic, but the requirements are not sure yet (especially about material icons)

**Comment by nakovskijosif** [comment]
At the moment we need a way to use the u-core and set the icons url globally.

Additionally:
1. We need to add another option to the icon to be able to resolve a url - "iconUrl" attribute (this will have priority over the "pathPrefix" and "icon" combo).
2. We need to be able to override the iconsPath( used for the "pathPrefix"):
 - Globally - we can maybe use the u-core and set window.__axaPLibConfig.iconsPath ( if set with jquery the icons are resolved from any sprite at the moment)
 - Locally - every component should accept iconsPath as attribute which if not set than the patterns-lib sprite will be used.

This way the icon component can resolve any url or any sprite with defaults to the patterns-lib sprite.
If we refactor the component this way it won't break any existing functionality.

Feel free to add any additional options you think this component might need to have.

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
