### ISSUE TITLE
Parent text-align can break header logo/burger, footer links/social etc.

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#524]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

All components should be guarded against inheriting CSS properties like `text-align`.

## Actual Behavior

None of the components are able to protect themselves against inherited CSS properties.

## Steps to Reproduce the Problem

https://github.com/axa-ch/patterns-library-examples/blob/master/react/src/App.scss#L4

![parent-text-align-center](https://user-images.githubusercontent.com/914443/42616306-0f20a152-85ae-11e8-96bc-6a652dfd0a35.gif)

## Specifications

 - Browser: All
 - Browser Version: *

**Comment by AndyOGo** [comment]
@LucaMele 
This potential bug applies for **all** [inherited CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#Inherited_properties) 😲 

https://stackoverflow.com/questions/5612302/which-css-properties-are-inherited

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
