### ISSUE TITLE
Every component appending classes in index.js breaks when parent re-renders

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#531]
Every component appending classes in index.js breaks when parent re-renders cause willRenderCallback is not called due to no attribute change callback

**Comment by AndyOGo** [comment]
Okay.
My first guess is that we may need to move the `className` setting to `connectedCallback` 🤔 

May I asked you to provide a screenvideo or screenshot?

**Comment by LucaMele** [comment]
Closing as we are live with v2, if author think is still relevant, please re-open
