### ISSUE TITLE
After fixing styling header, pattern lib broken on mobile

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#534]
<img width="997" alt="bildschirmfoto 2018-07-17 um 10 55 44" src="https://user-images.githubusercontent.com/275235/42807021-0685878c-89b0-11e8-83d9-533dabe5b41d.png">

**Comment by AndyOGo** [comment]
Damn that was my fault.
Actually I though if I should introduce an extra attribute for my fix or just depend on `axa-header-search` ... well I made a wrong decision. sorry.

**Comment by AndyOGo** [comment]
this is still broken right?

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues?page=5&q=is%3Aissue+is%3Aopen
