### ISSUE TITLE
Cookie disclaimer broken on forms

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#536]
after we removed the waiting of the DOM LOAD event, cookie disclaimer is still broken on forms.

https://axa.ch/de/formulare/kontaktformular.html
plib versions: from 168 till 177

**Comment by LucaMele** [comment]
Fixed by inverting order of loading (disclaimer BEFORE JS). This is a BUG IMHO. The component should work anyway, indipendently of the order.

**Comment by AndyOGo** [comment]
Thanks @LucaMele for investigating this.
It seems to be a real problem and it's so weird.
I'm really curious now whats going on there with order of loading and asynchronous instantiation of custom elements 🤔  
Do we know of any stable utilization of web components, which we could compare with our implementation?

**Comment by LucaMele** [comment]
@AndyOGo well only with polymer... u tube for example.. but i mean normally the DOM should exist before the JS is loaded.. but still in my opinion it should either work correctly or not work at all. I think here is a bug in chrome and they might fix it :)

**Comment by LucaMele** [comment]
But neverthanless, i would like to keep this issue on track

**Comment by AndyOGo** [comment]
Yeah, absolutely. Order should not be a problem, but is some how (only exception polyfills first).
Indeed we need track and fix it

**Comment by AndyOGo** [comment]
@LucaMele I would like to describe this issue by concrete steps, may I ask you to confirm or correct my understanding?

**Issue:** Custom Elements are broken if their definition by JS through `CustomElements.define()` API is executed before a tag like `<axa-foo></axa-foo>` is used in the HTML markup or the DOM.

**Goal:** Order of Script Execution and Custom Element Tag usage should not break functionality, i.e. both following examples should work. Ideally without deferring their definition until `DOMContentLoaded`.

**Todo:** find out what the spec says about this process. As far I understand it all of that should be asynchronous and independent.

**Broken (JS before CE):**
```html
<html>
  <head>
    <!-- Loading and executing Custom Element Definitions before it's usage seems to be broken (without DOM-Ready) -->
    <script src="js/custom-element-polyfill.js"></script>
    <script src="js/axa-foo.js"></script>
  </head>

  <body>
    <axa-foo></axa-foo>
  </body>
</html>
```

**Working (JS after CE):**
```html
<html>
  <head>
  </head>

  <body>
    <axa-foo></axa-foo>

    <!-- Loading and executing Custom Element Definitions after it's usage seems to be the only way (without DOM-Ready) -->
    <script src="js/custom-element-polyfill.js"></script>
    <script src="js/axa-foo.js"></script>
  </body>
</html>
```

**Comment by AndyOGo** [comment]
According to this example in the spec, order shouldn't be an issue:
https://dom.spec.whatwg.org/#example-c5b21302

**Comment by LucaMele** [comment]
mmm we need to look at it together. I think in most cases it works. With the cookie disclaimer maybe there is a special combination of stuff (WC inside WC as fragment)

**Comment by AndyOGo** [comment]
Oh yes, that is an interesting combination. Definitely need to distill the problem

**Comment by LucaMele** [comment]
now it works
