### ISSUE TITLE
The o-commercial-hero-cover uses a picture. We need a molecule for it!

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#538]
We need to create the picture molecule. It have to handle:

* responsive images + media query
* It have to work with cover positioning and also where the focus is
* IE11 compatible

**Comment by Ben-Zahler** [comment]
polyfill for object-fit used in AEM frontend-lib:
https://github.com/constancecchen/object-fit-polyfill
    "objectFitPolyfill": "^2.0.5",

**Comment by LucaMele** [comment]
i just saw that @AndyOGo  had a open PR for AEM with changing the polyfil due to a IE bug.. so we might change this..

**Comment by LucaMele** [comment]
ah now on blog i can reproduce it!

**Comment by LucaMele** [comment]
i will try andy suggestion with debounce on aem. here on plib we should use the new suggested polyfill maybe

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues?page=5&q=is%3Aissue+is%3Aopen
