### ISSUE TITLE
Accordion Item open by default

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#544]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Accordion Items should be openable by default.

## Actual Behavior

Does not seem to be supported (may need to be varyfied).

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues?page=5&q=is%3Aissue+is%3Aopen
