### ISSUE TITLE
We need tables

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#546]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Various apps need to display their data in tables.

**Features:**

- [ ] Table Headers with:
   - [ ] optional check-all - meaning check/uncheck all checkboxes of each row (if used)
   - [x] sorting visual - up/down
   - [ ] sorting function ascending/descending (alphanumeric, numeric, enum, date), custom, etc.)
- [ ] Table Rows with:
   - [ ] optional indexing
   - [ ] ~~striped/zebra style~~,
   - [ ] checkboxes
   - [ ] drag & drop ordering (manual sorting)
   - [ ] CTA
   - [ ] inline edit
- [ ] Table Cells with:
   - [x] various display formats like light, normal, bold, states, etc.,
   - [x] automatic width
   - [ ] icons
   - [ ] in-place editing
   - [ ] CTA
- [ ] Table Columns (dynamic column display)
- [ ] ~~Pagination (maybe separate component)~~ see #548 
- [x] Captions
- [x] May support both classic HTML Tables markup and custom components
- [x] Responsiveness
- [ ] Data in (.csv, .json, etc.) -> fancy Table out 🎉 
- [ ] Business-Logic is external (custom sorting, iteration, filtering etc. - data in, presentation out) 
- [ ] add your feature request

**Table:**
https://html.com/tags/table/

**Caption:**
https://html.com/tags/caption/

**Table Head:**
https://html.com/tags/thead/

**Table Foot:**
https://html.com/tags/tfoot/

**Table Body:**
https://html.com/tags/tbody/

**Table Row:**
https://html.com/tags/tr/

**Table Cell:**
https://html.com/tags/th/
https://html.com/tags/td/
https://html.com/tables/rowspan-colspan/

**Out of Scope:**

- Comparison Tables

**Inspiration:**

- [Bootstrap 4 Tables](http://getbootstrap.com/docs/4.0/content/tables/)

**Design Specs:**

Tables do not exist yet as distinct components but they exist in following style guide sections:

- [Quote funnel - Step 2 - Your Quote](https://design.axa.com/web-guidelines/quote-funnel#quote-process-layout)
  <img width="957" alt="screen shot 2018-08-21 at 12 48 36" src="https://user-images.githubusercontent.com/914443/44397367-68d3c880-a540-11e8-9e9e-62e99efe38ad.png">

- [Contact module's components - Floating buttons](https://design.axa.com/web-guidelines/contact-module#contact-modules-components)
  <img width="683" alt="screen shot 2018-08-21 at 12 49 37" src="https://user-images.githubusercontent.com/914443/44397405-8739c400-a540-11e8-97b2-1df19f941479.png">

- [Generic modules - Operations status card/Documents list card](https://design.axa.com/web-guidelines/contract-page#generic-modules)
  <img width="972" alt="screen shot 2018-08-21 at 12 50 20" src="https://user-images.githubusercontent.com/914443/44397437-a173a200-a540-11e8-82db-8c28cc06c5ed.png">

- [Claim tracking navigation - Documents](https://design.axa.com/web-guidelines/claim-tracking#claim-tracking-experience)
  <img width="981" alt="screen shot 2018-08-21 at 12 51 02" src="https://user-images.githubusercontent.com/914443/44397476-bf410700-a540-11e8-921c-edb044582557.png">

**Allocation styles:**

<img width="783" alt="screen shot 2018-11-20 at 13 46 03" src="https://user-images.githubusercontent.com/914443/48782149-ce6d5780-ecdd-11e8-84b6-b1ecd444eb65.png">

**Related Issues:**

- [Generic pattern of iterator components #410 ](https://github.com/axa-ch/patterns-library/issues/410)

**Comment by LucaMele** [comment]
yes indeed..

**Comment by TheDadi** [comment]
I‘m working on a responsive table for a private project with the same functionality i will port it when i have time this evening!

**Comment by TheDadi** [comment]
Will come back on this when we discussed some stuff...

**Comment by LucaMele** [comment]
@TheDadi , the u-thing is for generic components (utility). Thumb rule for a utility: Webcomponent exists primarily for styling and therefore it can make sense to only use css classes. Example is the grid.

Table IMHO is not utility as the css scope of its classes is contained to the table

I have not understood correctly which styles style the host element. If you use BEM all through your classes u shouldn't have that problem. Or do you HAVE TO style the host element (im sorry but i have not looked at your solution yet).

**Comment by AndyOGo** [comment]
Correct, `.u-*` classes are for generic utility styles, perfect example is the grid - it has classes for containers, rows and columns but also very basic webcomponents which use those utility classes.

I would really like to have utility classes for tables (similar to [BS4](http://getbootstrap.com/docs/4.0/content/tables/)) but also custom elements `<axa-table>`, `<axa-tr>`, `<axa-th`, `<axa-cell>`, etc.

**Comment by LucaMele** [comment]
I would not have utility classes as for utility classes is the grid system in place (also for table like structure).

table here is very specific design.

**Comment by LucaMele** [comment]
the grid system already has col and row as utility.. if we add table as well we have `u-col` and `u-table-col`.. doesnt make sense to me

**Comment by LucaMele** [comment]
or also `u-col` and `u-cell` is very confusing. so no i prefer `o-table` and `m-table-row`, `m-table-cell` etc

**Comment by AndyOGo** [comment]
You are right, it's confusing.

I would definitely use `u-table-*` classes to clarify this distinction.
And I would really like to support semantic classic table markup.

**Comment by AndyOGo** [comment]
BTW I just download the newest Sketch file:
https://brandhub.axa.com/web/50c319ab5dae9493/axa-web-guidelines-ui-kits--psd---sketch-/?mediaId=38B57F4E-8BA9-4E1D-9CFB9BB8CE8B7470

All tables are there, it's awesome.
We have to check with Jonas before we merge/implement it.

**Comment by NoahLiechti** [comment]
@AndyOGo what exactly does the feature "Table Headers with optional check-all" do?

**Comment by AndyOGo** [comment]
@NoahLiechti 
Often tables allow to check/uncheck all checkboxes of each row, that is what it means

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues?page=5&q=is%3Aissue+is%3Aopen
