### ISSUE TITLE
onChange and value for all form elements

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#547]
We have to implement onChange events and value for input, radio and checkbox. Dropdown should already have it

**Comment by LucaMele** [comment]
I will do it right now

**Comment by AndyOGo** [comment]
absolutely, also other components and associated events are affected.
Also we need to make sure, to properly forward custom events to the `wcnode`.

Related #418

**Comment by LucaMele** [comment]
fixed
