### ISSUE TITLE
we need pagination

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#548]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We need pagination.

**Features:**

- [ ] Indexing, dynamic update
- [ ] Click event forwarding
- [ ] Next/Previous links
- [ ] Responsiveness

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues?page=5&q=is%3Aissue+is%3Aopen

**Comment by AndyOGo** [comment]
@LucaMele Guess this is still needed 🤔

**Comment by LucaMele** [comment]
Desired requirements/feature please discuss at ARP
