### ISSUE TITLE
We have to finish forms

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#549]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We have to finish forms, with complete examples, including semantic markup, validation, error handling, event handling/forwarding, etc.

**Comment by LucaMele** [comment]
yepp.. so true

**Comment by AndyOGo** [comment]
would say iskinda a duplicate of #588

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
