### ISSUE TITLE
Add warning logs if dependencies are missing

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#55]
Currently `device-state` is the only component which is implemented without an associated custom element.
Instead it's class `a-device-state` needs to be attached to an existing DOM node to be working(`<body>` recommended).
If somehow the consumer of the patterns-lib `import`s `device-state` but forgets to add the class to an existing DOM, it should log a Warning/Error to help fix the issue.

I think this is a generic issue, which should be taken into consideration for every component.

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
