### ISSUE TITLE
ToDo that came out while implementing date picker

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#561]
- a-device state maybe as utility
- all event consts in a separate file
- `o-datepicker` iso ready
- close other datepicker -> use ui-events
- scroll out of view triggers a leave events
- onresize close
- what if input field is on the father most right?
- in fullsize mode the arrow in the dropdown shouldn't overlap the month

**Comment by MarekLacoAXA** [comment]
It seems that events are missing in the datepicker components.
To get a full date via callback in React when a day was chosen in o-datepicker, resp. when a "Confirm" button was clicked in m-datepicker.

**Comment by LucaMele** [comment]
@MarekLacoAXA i released a new version with the fix. Example can be found here: https://github.com/axa-ch/patterns-library/blob/develop/src/demos/todomvc/todos.jsx

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
