### ISSUE TITLE
define integration policy

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#57]
To ease development and keep quality high we should define and stick to an integration policy.

I recommend:

- [x] establishing a `develop` branch
- [x] prevent merges in case of failing linters or tests (can be setup by travis, appveyor, you name it)
- [x] fast-forward merges only into `master`
- [x] versioning strategy (semver)
- [ ] deprecation warning (static analysis vs runtime analysis)

**Comment by LucaMele** [comment]
I agree on all points. The last one can be done later on. We should do this

**Comment by AndyOGo** [comment]
I just created a `develop` branch and made it the default branch.

So now we need to update how we make a release.
- [ ] all future branches branch off `develop`
- [ ] all future PR get merged into `develop`
- [ ] current release script needs to be rewritten to work with `develop` instead of `master`
- [ ] plus at the end of the release script we need a fast forward merge from `develop` into `master`

**Comment by LucaMele** [comment]
i think is fixed.. feel free to reopen in case is not
