### ISSUE TITLE
Maintainable CSS != !important rule

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#573]
We use a lot of `!importants` so far. IMHO that is a big issue. Important is only needed if you can anwers this question:
Do we EVER want to override the attribut? if answer is yes, DONT use important.

**Comment by AndyOGo** [comment]
here are all affected files:
https://github.com/axa-ch/patterns-library/search?q=%21important&type=Code

**Comment by LucaMele** [comment]
@AndyOGo thank you for taking care of this
