### ISSUE TITLE
Namespace all CSS class names with axa

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#579]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [x] Feature

## Expected Behavior

We should do all to mitigate CSS class collisions.
So lets update our classes to include **axa** from `a|m|o|u|js|is|has-*` to `a|m|o|u|js|is|has-axa-*`

Or may **axa** is to generic and **pl** (for patterns library) fits better, or **axapl**

**Comment by LucaMele** [comment]
I dont think is a good idea tbho. Is a bit a hack. Since it is the patterns library, all the other applications should specify the class name. And we cannot do it anyway now as too much depends on it.

**Comment by AndyOGo** [comment]
You are right, it would be a breaking change.

I would still do it, because as of now we use still kinda generic classnames, which could be used by other frameworks/libraries. And we are still in beta and we just saw the issues of classname collisions with aletheia.

**Comment by LucaMele** [comment]
I agree we should do it but not now, not without a team and not without tests. I won’t have time before spring next year to refactor aem and we are already in a big refactoring

**Comment by LucaMele** [comment]
Most applications start now feom scratch so they will make their namespaced classes and so no issue. For existing applications the chance is very low that they use atomic design prefixes.

Never than less, we should do it one day in the future

**Comment by LucaMele** [comment]
It should be between 2 major versions, then is the best moment. Now is too late the impact is too big so we can’t do it

**Comment by AndyOGo** [comment]
I think we would have two impact cases:

- People who use custom elements, which is ideal, they should not see any side effects (unless they did some styling which relies on our classes)
- Teams who just use our CSS/SCSS would suffer the most, currently I guess just AEM, right?

I would go for a change as early as possible, so that we can limit the damage and keep the work as small as possible.
A pro is also that this is a simple renaming, which could be automated with a migration script 💪

**Comment by LucaMele** [comment]
No is AEM, IAM, MyAXA and The error pages that uses classes as far as i know. Effort is too big ATM it have to be between 2 majors. Cost / Benefit Ratio is absolut negativ ATM so i put my final veto to it and wont discuss it anymore. Thank you for Suggestion this. I would make a milestone for release major 2 and 3 and link it at the 3.

**Comment by AndyOGo** [comment]
Let me convince you with a migration script 😃

**Comment by AndyOGo** [comment]
Btw we can also provide deprecated class names to accomplish this migration in two steps, same as I did with the relocation of mixins.

**Comment by LucaMele** [comment]
@AndyOGo your very precious time is much more useful somewhere else. Please dont waste time as it wont get merged before major 3

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
