### ISSUE TITLE
Refactor Header sub navigation

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#582]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

The navigation should only render the actually painted sub navigation.

**Note**: I guess this could mitigate/workaround Edge's WTF bug #309 

**IMPORTANT**: this will possibly break the sub navigation for AEM 😞 

## Actual Behavior

Currently die all DOM of every sub navigation is rendered and only the active one is `display: block`, all others are `display: none`.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
