### ISSUE TITLE
Get rid of template and replace it with render method

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#583]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We shouldn't use a separate file `template.js` because it's not necessary, instead lets use the familiar `render` method to return the next DOM.

This way we will need to refactor a few things.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
