### ISSUE TITLE
refactor the build or use nwb toolkit

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#584]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We should have a full featured build with great dev experience including linting, testing, hot reloading, bundling for production, bundling for library, etc.

I just found NWB which supports vanilla JS projects.
We should give it a try.

https://github.com/insin/nwb

https://github.com/insin/nwb/blob/master/docs/FAQ.md#what-does-nwb-stand-for

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
