### ISSUE TITLE
We have two AXADatepicker classes

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#589]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [ ] Feature

## Expected Behavior

We should have unique class names for each components.

## Actual Behavior

`AXADatepicker` defined in:
- [`https://github.com/axa-ch/patterns-library/blob/de79adb0ed39e1d3e50e78ababafb9c9508dcde9/src/components/o-datepicker/index.js#L10`](https://github.com/axa-ch/patterns-library/blob/de79adb0ed39e1d3e50e78ababafb9c9508dcde9/src/components/o-datepicker/index.js#L10)
- [`https://github.com/axa-ch/patterns-library/blob/de79adb0ed39e1d3e50e78ababafb9c9508dcde9/src/components/m-datepicker/index.js#L12`](https://github.com/axa-ch/patterns-library/blob/de79adb0ed39e1d3e50e78ababafb9c9508dcde9/src/components/m-datepicker/index.js#L12)

## Rewording

**`axa-calender-sheet`** would be semantically better wording for `m-datepicker`

**Comment by LucaMele** [comment]
Idea: Prefix M and A with the letter and keep organism without prefix

**Comment by LucaMele** [comment]
All components

**Comment by AndyOGo** [comment]
good idea.
I would still avoid having atoms, molecules or organisms with the same name.
We should use descriptive and semantic names.

**Comment by jackblackCH** [comment]
I find it generally difficult to have the same component existing as an organism and a molecule, these terms are super to solve tech issues with group and naming, it's hard though for a consumer of the pattern library.

We could also merge both existing versions into one component and work with modifiers, to have the same type of component only once. It is also lot of code we could share more easily.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
