### ISSUE TITLE
We should have a better overview to display components

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#590]
We should have a better overview on how we display components, especially if they grow in number

We need an evaluation of https://github.com/frctl/fractal (The "Storybook" of Vanilla.js)

## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Better overview and usability of the main demo page of the patterns library (Example: https://axa-ch.github.io/patterns-library/molecules.html)

## Actual Behavior

Difficult to have a overview on all the components

**Comment by AndyOGo** [comment]
Sounds great, we would save ourselves a whole lot of work.

**Comment by LucaMele** [comment]
thank you @jackblackCH for this input :)

**Comment by AndyOGo** [comment]
I nice read about storybook and web components
https://medium.com/storybookjs/how-to-combine-web-components-with-storybook-a-match-made-in-heaven-9d9939eedc76

**Comment by LucaMele** [comment]
So we need to evaluate fractal and Storybook for WC. 

Main Requirements (Functional and Non Functionals):

- Semplicity (a apprentice can use it)
- Full With Pure Html testable
- Better usability then today (max 2 seconds to find the desired component starting of the main page and 1 second needed to know how to test it)

**Comment by AndyOGo** [comment]
I would a themability

**Comment by AndyOGo** [comment]
I would add themability

**Comment by LucaMele** [comment]
Ok you can add but if is a requirement is would like to have it „measurable“

**Comment by AndyOGo** [comment]
BTW, since we have our `withReact` helper, we could use storybook with our reactified web components 💪

**Comment by LucaMele** [comment]
i would reccomend something that supports them natively so we are not bound to a technology

**Comment by MarekLacoAXA** [comment]
It would be helpful to include a demo of a real-world micro site, including header/nav. menu/columns/form/validation/footer.
Perhaps as a bootstrapping template.

**Comment by AndyOGo** [comment]
@LucaMele 
@MarekLacoAXA 
@jackblackCH 
We should have a checklist of features we need, so I start:

**For devs:**

- [ ] custom elements V1 support
- [ ] easy attribute updates (called [knobs addon in Storybook](https://medium.com/kadira-voice/introducing-storybook-knobs-9d97069b309a))
- [ ] it has to be **maintained**
- [ ] markdown support
- [ ] feature to parse and render doclets like jsdocs, sassdoc, you name it
- [ ] extensible API

**For AXA branding**

- [ ] Theming

**Evaluation chart:**

Feature | Fractal | Storybook
------------ | ------------- | -------------
**Maintained** | [Nope 💣](https://github.com/frctl/fractal#project-update---please-read)  | Yes
**Custom Elements V1** | Yes | Yes ([through Vue, Polymer](https://medium.com/storybookjs/how-to-combine-web-components-with-storybook-a-match-made-in-heaven-9d9939eedc76))
**Knobs** | Nope | Yes - [knob addon](https://medium.com/kadira-voice/introducing-storybook-knobs-9d97069b309a)
**Markdown** | [Yes](https://fractal.build/guide/documentation/configuration-reference.html#global-configuration-options) | Yes - [through notes-addon](https://www.npmjs.com/package/@storybook/addon-notes#using-markdown)
Doclets support | n/a | can be [added](https://github.com/storybooks/storybook/tree/master/addons/info)
Extensible API | n/a | Yes called [addons](https://storybook.js.org/addons/introduction/)
Theming | [Yes](https://fractal.build/guide/customisation/web-themes.html) | [Yes](https://storybook.js.org/configurations/theming/)

**Comment by LucaMele** [comment]
thank you for this overview @AndyOGo we need to sit down the 3 of us and dicuss it

**Comment by jackblackCH** [comment]
There is a new kid on the block: https://www.docz.site/

**Comment by jackblackCH** [comment]
And a discussion on spectrum.chat about the different tools: https://spectrum.chat/react/general/what-is-the-best-documentation-tools-for-a-react-library~d3649a8b-9c62-4b58-a504-3626cd60eec1

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
