### ISSUE TITLE
Reorganize our code base, go monorepo

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#591]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [y] Feature

## Expected Behavior

I expect to have all of our sections together in one giant monorepo, this includes but not limited to:

- [ ] The Patterns-Library itself as it is published at NPM
- [ ] The Patterns-Library app https://axa-ch.github.io/patterns-library/
- [ ] Patterns-Library examples repo: https://github.com/axa-ch/patterns-library-examples

## Actual Behavior

We have two github repos, the app is intermixed with the library.

**Comment by LucaMele** [comment]
not sure about this yet. There are pro and cons. One pro to not forget, in having them separately we can "test" the lib module and the npm dependency. On the other hand, is more difficult to create examples. But if we see the styleguide itself as an example, again it make sense having the pure WC implementation in one place and all the library examples in another. Immagine having react, vuejs, angular and backbone examples togehter with the WC.. it will get a big massive unmaintainable mess. so i think IMHO the pros having it separately are more than the cons

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
