### ISSUE TITLE
Icon root node is not styled

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#593]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We should fully control the size and stlye of it's root node `<axa-icon>`

## Actual Behavior

`<axa-icon>` hasn't any class nor styles. By default it's rendered as an inline element, so it's inherited `line-height`, `font-size` etc. properties affects how it is displayed and sized.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
