### ISSUE TITLE
Custom Elements always have inline root nodes

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#595]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We should be able to control, whether we want/need a root node for each component.
It should be controlable to have no `inline` style by default.

## Actual Behavior

Every custom element of `<axa-*>` always:
- has a root node
- is styled as `display: inline` by default w3c/webcomponents#224
- which contributes to FOUC #365 

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
