### ISSUE TITLE
dev build does not resolve dependency tree

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#601]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

If I change a scss file within `src/styles/` I expect that the app is correctly rebuild including those latest updates.

We should really move to a professional tool like webpack or parcel.

## Actual Behavior

If I change a scss file within `src/styles/` the app is not correctly updated and the build does not resolve the dependency tree in reverse order.

**Related:**
#584

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
