### ISSUE TITLE
Dropdown needs style changes à la design.axa.com

### ISSUE THREAD

**Issue by NoahLiechti** [axa-ch/patterns-library#604]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

https://design.axa.com/web-guidelines/forms-update

- when there is no value set there the value should be prefilled in grey color
- arrow must be blue even when not in hover
- implement field label
- dropdowns should have a [disabled] style and correct disabled behavior

## Actual Behavior
- when there's no value, the dropdown is either empty or deformed
- the arrow is only blue on hover or when selected
- there's no disabled style

**Comment by AndyOGo** [comment]
Please note that the patterns-library does not implement the global styleguide 100%.
Stuff like the blue VS grey arrow is a change by intention made just for switzerland.
But now that Anja left, I guess @jojackpot or @kenaxa will decide if we keep it different or streamline it.

In general blue is for showing interaction.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
