### ISSUE TITLE
Document CSS structuring and organisation for large scale

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#605]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

Our CSS should be well structured, organized and maintainable for large scale CSS.
It should be clearly stated i.e. documented how we organize our CSS code base, this should also be criteria for Pull Requests.

I really recommend [ITCSS (Inverted Triangle CSS)](https://itcss.io/) by Harry Roberts from https://csswizardry.com/
https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/

## Actual Behavior

Our codebase ist mostly structed according to ITCSS, but nowhere documented that this is expected.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
