### ISSUE TITLE
Extending builtin elements not supported

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#607]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The [`CustomElementRegistry.define()` API](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) specifies the [ability to extend builtin elements](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Customized_built-in_element).
So it should be working as specified.

## Actual Behavior

Extending builtin elements isn't fully supported by:
- [not all browsers support it and safari even refuses to implement it](https://developers.google.com/web/fundamentals/web-components/customelements#extendhtml) 😨 
   > **Note:** Only Chrome 67 supports customized built-in elements ([status](https://www.chromestatus.com/feature/4670146924773376)) right now. Edge and Firefox will implement it, but Safari has chosen not to implement it. This is unfortunate for accessibility and progressive enhancement. If you think extending native HTML elements is useful, voice your thoughts on [509](https://github.com/w3c/webcomponents/issues/509) and [662](https://github.com/w3c/webcomponents/issues/662) on Github.
- https://github.com/w3c/webcomponents/issues/727
- the polyfill does not implement it https://github.com/webcomponents/custom-elements/issues/13

## Steps to Reproduce the Problem

Currently we face this issue especially with tables #546 but it's also kinda existing with `<axa-button>`

**Comment by LucaMele** [comment]
@AndyOGo 

Builtin element extension is NOT defined fully yet as there are still discussion about it and till its final, we should avoid to find solution in that way. We can keep tables how they are ATM as is the second best way to implement it.

https://github.com/w3c/webcomponents/issues/509

**Comment by LucaMele** [comment]
mmmm https://github.com/WebReflection/built-in-element#built-in-element

**Comment by AndyOGo** [comment]
That could help us:)

Though be aware of it's [caveats](https://github.com/WebReflection/built-in-element#caveat).
> You cannot use the `constructor` in any meaningful way if you want to ensure API consistency.

**Comment by AndyOGo** [comment]
Actually their own polyfill could be better than the official one 🤓 
https://github.com/WebReflection/document-register-element

**Comment by AndyOGo** [comment]
definetily a good read
https://hackernoon.com/extending-built-in-elements-9dce404b75b4

**Comment by AndyOGo** [comment]
hmh, seems to have a bug...
https://github.com/WebReflection/document-register-element/issues/154

**Comment by AndyOGo** [comment]
Turns out that `nanohtml` doesn'T support extension of built-in custom elements too
https://github.com/choojs/nanohtml/issues/136

PR provided:
https://github.com/choojs/nanohtml/pull/137
