### ISSUE TITLE
Datepicker month +1 index bug

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#608]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

10/15/2018 == 
Mon Oct 15 2018 00:00:00 GMT+0100

## Actual Behavior

10/15/2018 == 
Thu Nov 15 2018 00:00:00 GMT+0100

## Steps to Reproduce the Problem

1. navigate to https://axa-ch.github.io/patterns-library/react.html
2. open JS console
3. open datepicker calendar
4. click on today's day
5. see console result

## Specifications

The bug is probably in src/components/m-datepicker/js/datepicker.js on line 95, where the month's **index** is expected in the Date constructor function.

BTW. I would much appreciate some help on how could I possibly test and fix using the PL repository. 
Namely:
- which html file in dist/docs to edit containing the datepicker 
- how to attach on-change debug behavior to an above <axa-datepicker>
- which npm command to use while fixing datepicker. The "npm run serve" takes 2 minutes to run after each file change (windows OS)

Thanks!

**Comment by AndyOGo** [comment]
@MarekLacoAXA 
Thanks a lot for contributing.

Indeed our build is slow, not dev-friendly and not cross-OS optimised, please upvote or contribute to the relevant issues #130 #592 #601 #54 You can also check the build milestone.

In case you are interested to contribute code please make sure to carefully study our contribution guide lines https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md
Familiarity with `<custom-elements>` is a must.
