### ISSUE TITLE
Datepicker is ignoring value attribute (probably not implemented yet)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#619]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [x] Feature

## Expected Behavior

Value attribute passed to `<axa-datepicker>` and `<axa-m-datepicker>` should set the component to that date.

## Actual Behavior

Value attribute does not set the component to desired date. Today's date is show as placeholder instead. As if no value attribute would be set.

## Steps to Reproduce the Problem

```
  <axa-datepicker id="ap1" value="10/18/2018" locale="en-en"></axa-datepicker>
  <axa-datepicker id="ap3" value="18.10.2018" locale="de-ch"></axa-datepicker>
  <axa-m-datepicker id="ap4" value="18.10.2018" locale="de-ch"></axa-m-datepicker>
```

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
