### ISSUE TITLE
Datepicker: disallow overlapping calendars when multiple instances opened (usability/nice to have)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#621]
## Are you reporting a bug or a feature?

 - [x] Feature

## Expected Behavior

When using two datepickers (lets say date-from and date-to), then when opening a second one calendar, this second calendar would be shown **above** the previously-opened calendar (higher z-index) OR the previously-opened calendar would collapse.

## Actual Behavior

The opened calendars are overlapping, the z-index is defined (presumably) by position in DOM and not by the order in which the calendars were opened.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/organisms.html#o-datepicker
2. start opening the calendars of the Datepickers starting from the bottom.
3. see calendars are overlapping and therefore unusable

![image](https://user-images.githubusercontent.com/43809369/47086678-7775ed80-d21a-11e8-8171-3dff9f2e8be6.png)

(related to #561)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
