### ISSUE TITLE
Dropdown component - attribute value does not select option in native mode.

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#623]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

When value is set to the dropdown corresponding option should be selected by default.

## Actual Behavior

Value set is ignored in **"native"** mode only.

## Steps to Reproduce the Problem

1.
![screen shot 2018-10-22 at 1 43 53 pm](https://user-images.githubusercontent.com/42141843/47290705-090da280-d601-11e8-98e0-de2ab4693ab8.png)

2.
![screen shot 2018-10-22 at 1 43 25 pm](https://user-images.githubusercontent.com/42141843/47290709-0f038380-d601-11e8-8e3a-ed374a215963.png)

3.
![screen shot 2018-10-22 at 1 43 17 pm](https://user-images.githubusercontent.com/42141843/47290714-132fa100-d601-11e8-95c0-ce9462e1369b.png)

## Specifications
Operating system OS X 10.13.5
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2247 x 1063
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by AndyOGo** [comment]
this is because of transforming HTML string-only attributes to first class properties as mentioned:
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#first-class-props

**Comment by AndyOGo** [comment]
this is because of transforming HTML string-only attributes to first class properties as mentioned:
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#first-class-props
