### ISSUE TITLE
Dropdown component - option with empty value is rendered as 0 (native)

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#624]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior
When I add empty value in the options that need to be rendered, the value is the itemIndex instead.

## Actual Behavior
The option value should be empty string instead of itemIndex.

## Steps to Reproduce the Problem

1.
Use the html below.
`<axa-dropdown value="2" size="sm" items='[{"value": "","name": "Item 1 looooooooong", "url": "#"}, {"value": "2","name": "Item 2", "url": "#"}, {"value": "3","name": "Item 3", "url": "#"}]' native>
  </axa-dropdown>`
2.
The value in the first option should be "" - empty string but it is "0" instead.
3.
![screen shot 2018-10-22 at 1 43 25 pm](https://user-images.githubusercontent.com/42141843/47290982-41fa4700-d602-11e8-9ae7-ca78878770c7.png)

## Specifications

Operating system OS X 10.13.5
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2247 x 1063
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by AndyOGo** [comment]
this is because of transforming HTML string-only attributes to first class properties as mentioned:
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#first-class-props
