### ISSUE TITLE
Dropdown component - title="title"

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#625]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

when the attribute title="title" is set to the dropdown, the displayed value should be title in both the native and enhanced mode.

## Actual Behavior
 the displayed value is "true"

## Steps to Reproduce the Problem
use title="title" as attribute.
`<axa-dropdown title="title" items='[{"name": "Item 1", "url": "#"}, {"name": "Item 2 loooooong", "url": "#"}, {"name": "Item 3", "url": "#"}]'>
  </axa-dropdown>`

## Specifications

Operating system OS X 10.13.5
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2247 x 1063
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by AndyOGo** [comment]
this is because of transforming HTML string-only attributes to first class properties as mentioned:
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#first-class-props
