### ISSUE TITLE
Input component - attribute value as empty string.

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#626]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

When the attribute value is set as empty string the component is generated with "" as input value.

## Actual Behavior

When the attribute value is set as empty string the component is generated with "true" as input value.

## Steps to Reproduce the Problem

1.
use the html below.
`<axa-input value name="test-name"></axa-input>`
2.
Expected input with no value
3.
The input has value "true"

## Specifications

Operating system OS X 10.13.5
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2247 x 1063
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by AndyOGo** [comment]
this is because of transforming HTML string-only attributes to first class properties as mentioned:
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#custom-elements
- https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#first-class-props
