### ISSUE TITLE
Datepicker selected value seems to be a timestamp

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#634]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

It should display a localised Date format

## Actual Behavior

Display a time stamp

## Steps to Reproduce the Problem

![date-picker-timestamp-values](https://user-images.githubusercontent.com/914443/47420953-df2eba00-d77f-11e8-963f-a0c0e108cdd9.gif)

**Comment by MarekLacoAXA** [comment]
Fixed by #635
