### ISSUE TITLE
Implement Textarea

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#637]
@kenaxa Please add designs and specs

**Comment by kenaxa** [comment]
Please find the text area image attached. 

For specifications you can find them here: https://app.zeplin.io/project/5b0bf99a238ad071517e9ae2/screen/5bc8a7560cd71b0a7bfa3e43

![text area](https://user-images.githubusercontent.com/43201567/47488753-46627200-d845-11e8-870e-d498686b7698.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
