### ISSUE TITLE
Providing possibility to set name/ id to Datepicker 

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#640]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

The possibility to set an identifier to get the origin of datepicker from the fired event to have one function that can set the state of multiple datepickers.  On other components we had the name tag and could write a state setter with

`handleChange(event) {
    this.props.onFilterFieldChanged(event.target.name, event.detail);
  }`

and 

`onFilterFieldChanged: (filterName, value) =>
    dispatch(updateFilterData(filterName, value))`
## Actual Behavior

Currently id is not set and gets set as random ui string. From the three triggered events we have one fixed name set as get-local-day-month-year and the others are not set.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
