### ISSUE TITLE
Add data attribute to component for selenium

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#641]
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

Axa has a selenium toolkit project https://github.axa.com/eClaims-SV/selenium-toolkit 
It works if components have an unique `data-seleniumid` ~~tag~~ attribute on them for read/ write access. On the project schadenmeldung claims we used it already with an old branch by mirroring the id (see [dist-3](https://github.com/axa-ch/patterns-library/blob/form-components-with-dist3/src/components/a-form-input/_template.js
)). This should not break any existing functionality that way and even improve slightly the code by forcing the coder to supply an id to each used component. (If none is set, the selenium tests won't work since the random ui id can't be used as identifier to get the component)

The toolkit creates a testreport, creates java classes for easy access to the components and provides some generic methods for setting/ getting the data, handles the browsers and co.
There is a small playground/ demo project available [demo](https://github.axa.com/eClaims-SV/selenium-playground)

**Comment by AndyOGo** [comment]
If `data-seleniumid` isn't provided it should be derived from `id` automatically at runtime, if that isn't set either nothing happens.

I suggest to implement a higher-oder-class `SeleniumTestId` to implement this for components.
Only question do we want this inside the patterns library?

**Comment by MatthiasDyballa** [comment]
The problem that I see if it outside of pattern library, it can be a bit tricky to get the attribute attached to the correct child in order for it to work correctly.

**Comment by LucaMele** [comment]
I would say it should not be in the patterns library but i can see why it kinda have to ( as Matthias said ). 

We need to think on a concept for it. Maybe a generic attribute that can be set on every component as a api attributed and that adds this code. It have to be as less invasive as possible

**Comment by AndyOGo** [comment]
I see.

So I think in general the most complex are iterator components, which my need special iteration magic.
I would like to have just another HOC ideally, we need to see it that is feasible.

@MatthiasDyballa PRs always welcome

**Comment by LucaMele** [comment]
I dont like the HOC approach as it cannot be set or unset on specific components on runtime

**Comment by AndyOGo** [comment]
May I missunderstand, but I'm sure it can

**Comment by MatthiasDyballa** [comment]
For example on a dropdown I added it to
`<select class="m-dropdown__select m-dropdown__select--sm" data-seleniumid="${id}">` 
as a single entry point to select items, dropdown would need a second attribute on the label that displays the selected value with data-seleniumid="${id + value}" or similar and is done. On Input I added it at the end of the definition of input `disabled="${disabled}" 
      data-seleniumid="${id}">`

**Comment by MatthiasDyballa** [comment]
The actual logic or behavior is coming from the selenium toolkit, it just needs to know on which child it should click or sentKey information (for input etc)

**Comment by MarekLacoAXA** [comment]
My question regarding (selenium) testing of PL components:
It is possible to "automatically" focus the axa-input's **input-type-text,** when the axa-input WC gains focus?
If it worked, then the axa-input itself could be referenced during testing (e.g. focus the axa-input, write bla bla, submit form...)

**Comment by AndyOGo** [comment]
Well, ideally you should not need to know about or deal with the internals of a web component.
Instead the Web-Component should provide a sufficient interface for you to archive your goals.

How that shall work in details is still to be defined.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by MarcSchneider1** [comment]
is still a problem

**Comment by LucaMele** [comment]
REF: #1536

**Comment by raphaellueckl** [comment]
Closing this, as #1536 has been merged.

selenium-id's can now be set on the component level, but it is not the idea, that the user can reach into our components, because we want the internals to be seen as a blackbox. If people adapt css and grab elements from within the components, it becomes cumbersome for them to update a component.

We make sure that the components are of good quality. Our users should test their business logic and not redundantly test our components. All the interactions can be made over the API, that we provide to the user.

Please reach back to us if you have any questions regarding this.
