### ISSUE TITLE
Datepicker Bug fixes

### ISSUE THREAD

**Issue by kenaxa** [axa-ch/patterns-library#643]
Thank you for the date picker. 

There are some minor bugs that I've found: 
- Mouse over with the blue circle and the transparent date; Take out the transparency of the date on hover. 
- "Abbrechen" & " Bestätigen" should be in the middle of the space (same space as top or down)
- The arrow on the dropdown Year should be as defined in zeplin not as narrow as now. 
- The user should be able to close the date picker when clicking outside the datepicker box OR when clicked on "Abbrechen"

For Infos and questions just hit me up over skype or slack. 

cheers, 
Ken

**Comment by jackblackCH** [comment]
All mentioned issues should be fixed by #767
