### ISSUE TITLE
Icons in Dropdown

### ISSUE THREAD

**Issue by Ben-Zahler** [axa-ch/patterns-library#646]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

When using the Dropdown Molecule, I want to see an icon for the Dropdown.

## Actual Behavior

When used outside of the patternslibrary, the icon is not displayed.

## Steps to Reproduce the Problem

1. Create a react component and use the dropdown molecule. This is our code from AEM frontend-lib:
 <AXADropDownReact
                  size="sm"
                  title="Switch status"
                  value={this.props.filterForm.status}
                  onAxaChange={this.onChangeDropdown}
                  items={[{ value: '', name: i18n(texts, 'all') }, { value: ACTIVE, name: i18n(texts, ACTIVE) }, { value: INACTIVE, name: i18n(texts, INACTIVE) }]} />
             
2. Include with axa-code the correct path for icons:
<axa-core icons-path={data.iconsUrl}></axa-core>

3. Icon does still not appear.

**Comment by AndyOGo** [comment]
Hey ben, icons are build into <axa-core> component. You habe to import that to (no need to render it, loadibg should be sufficient)

**Comment by AndyOGo** [comment]
See the react examples in the patterns library examples repo

**Comment by LucaMele** [comment]
i think there is an issue in axa core and icon. The axa icon does not use the path given with axa core on the setting set in the window objet

**Comment by Ben-Zahler** [comment]
hi Andy,
we checked the examples, but unfortnuately that does not work because the example loads the icons from this url:
https://axa-ch.github.io/patterns-library/assets/icons/icons.svg
we should not have axa.ch depend on this url...
And as Luca mentioned, setting the icons path with axa-core does not work as expected.

Btw: I cahgned the title of the issue, this does not affect the datepicker, but the dropdown!

**Comment by AndyOGo** [comment]
What a bummer, then luca can help you best

**Comment by nakovskijosif** [comment]
The issue was that the icons path had to be set in order the icon to show up. 
This is no longer necessary when axa-core is loaded. I will make a PR removing the icons-path-prefix property and if axa-core is loaded properly this should work now.
