### ISSUE TITLE
New compoment: Tile

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#650]
We need a "Tile" compoment with these props (all voluntary):
- disabled (would render as grayed-out)
- title
- subTitle
- icon
- actionIcon
- actionOnClick (action clicked event)

It would render as a white box with a shadow. 
Examples:

![image](https://user-images.githubusercontent.com/43809369/47999337-9ae9d500-e102-11e8-8b62-68927a10a3f0.png)

![image](https://user-images.githubusercontent.com/43809369/47999426-da182600-e102-11e8-9e5a-cf4da4b980a0.png)

![image](https://user-images.githubusercontent.com/43809369/47999486-016ef300-e103-11e8-9e5d-3697474e0c36.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this component is still desired 🤔

**Comment by LucaMele** [comment]
If desired, please come to our team at the ARP. Closing here
