### ISSUE TITLE
New compoment: Modal

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#651]
We need a Modal compoment:

Props:
- title
- onClose event
- children

It would render similar as Tile compoment (#650) (may leverage that comp.) without a box shadow, on an overlay. Click on overlay closes the modal.

On mobile devices, the would (optionally?) open on the bottom edge of the screen - so that the presented options (children of component) would be easily accessible with thumb finger.

![image](https://user-images.githubusercontent.com/43809369/47999776-dd5fe180-e103-11e8-8eb2-bd1deec230a8.png)

(need nested modals?)

**Comment by AndyOGo** [comment]
This will also need proper modal management, one vs multiple modals open at a time.
I would favour a portal-like implementation

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
