### ISSUE TITLE
New compoment: Tooltip

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#652]
We need a Toopltip component. That would be basically an blue "i" round icon. OnMouseOver (plus onClick for tap touch devices) a message would pop up.

(The AXAFormGroup's info is impractical for this, as we need to place the "i" anywhere on a page)

Challenges:
 - auto position during resizing (on smaller screens) so thay the popup stays on visible screen.

Example:

![image](https://user-images.githubusercontent.com/43809369/48000326-69263d80-e105-11e8-9217-962d4047a980.png)

**Comment by AndyOGo** [comment]
The global design guidelines specify this as **Contextual Help**:
https://design.axa.com/web-guidelines/forms-update

<img width="1255" alt="screen shot 2018-11-06 at 10 42 19" src="https://user-images.githubusercontent.com/914443/48055705-8237f880-e1b0-11e8-8186-a4d9dc4fbdf1.png">

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this component is still desired 🤔

**Comment by LucaMele** [comment]
If desired, please come to our team at the ARP. Closing here
