### ISSUE TITLE
New compoment: Monthpicker

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#653]
We need an input that would allow user to choose Month and Year.

At least as a combination of two Dropdowns.
Ideally a Datepicker-like UI.

![image](https://user-images.githubusercontent.com/43809369/48000509-f49fce80-e105-11e8-975e-869b2113a65d.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
