### ISSUE TITLE
New compoment: Message

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#654]
We need a component that would display a warning/success/info message (similar to bootsrap css framework)

Props:
- type (warning/success/info)
- children

![image](https://user-images.githubusercontent.com/43809369/48000932-4c8b0500-e107-11e8-9c59-f3cd13ad249e.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
