### ISSUE TITLE
New component: Label-value pairs

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#656]
We need a component, that would display label-value pairs that would fit nicely into the available container width.

It would be suitable to present content like shown here:

![image](https://user-images.githubusercontent.com/43809369/48001307-7d1f6e80-e108-11e8-9efe-8eb6ed3ce5fe.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
