### ISSUE TITLE
New component: Timeline

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#657]
We need a compoment, that would display a "Timeline".

Props: array of {title, content} objects.

Example:

![image](https://user-images.githubusercontent.com/43809369/48001600-54e43f80-e109-11e8-9b1b-8ad923701670.png)

(Future enhancement: control the expanded/collapsed state of content)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this component is still desired 🤔

**Comment by LucaMele** [comment]
If desired, please come to our team at the ARP. Closing here
