### ISSUE TITLE
New component: Progress 

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#658]
We need a Progress tracker compoment. It would visualize the current step in a multi-page form.

Props:
- steps: string[]
- currentStep: number

Example:

![image](https://user-images.githubusercontent.com/43809369/48001798-e784de80-e109-11e8-8282-641bb2c3f9fd.png)

**Comment by MarekLacoAXA** [comment]
Alternative designs found in Zepelin mockup tool:

![image](https://user-images.githubusercontent.com/43809369/48129550-217cee80-e28a-11e8-9788-37cf89a8364a.png)

Mobile:

![image](https://user-images.githubusercontent.com/43809369/48129556-26da3900-e28a-11e8-9ddf-97feaf8256fd.png)

Vertical kind:

![image](https://user-images.githubusercontent.com/43809369/48129636-60ab3f80-e28a-11e8-8e58-363b25bdf39d.png)

**Comment by AndyOGo** [comment]
We need the same Component for the UI-Renderer (but we call it "Stepper").

Anyway we face several issues:

- The UI-Renderer is not made yet for vertical layout of components or off-layout/positioned components
- The horizontal version is limited in space and number of steps visible, how to display it if the texts don't fit within the available  space?

**Comment by kenaxa** [comment]
Regarding missing specifications, please reach out to us if anything is unclear. We'll always have time to take a closer look if needed.

**Comment by AndyOGo** [comment]
@MarekLacoAXA 
@kenaxa 
We just clarified the issues for the UI-Renderer use cases :)
- all steps columns have equal width
- if any text overflows, only show the badge
- stepper stays always at last edited step, if user goes back active step has a highlighted background

![stepper-clarified](https://user-images.githubusercontent.com/914443/56815446-af04c880-6841-11e9-9408-d6cb659fac91.gif)

**Comment by MarekLacoAXA** [comment]
@AndyOGo thanks for info! Where can I find the styles for this component? Will this go to PLv1 , PLv2?

**Comment by AndyOGo** [comment]
@MarekLacoAXA 
We use React and I have directly implemented it within the **aletheia** project.

Components can be found here: https://github.com/axa-ch/aletheia/tree/develop/src/components/stepper
And we also use JSON-Schema: https://github.com/axa-ch/aletheia/blob/develop/docs/components/Stepper.md

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this component is still desired 🤔

**Comment by LucaMele** [comment]
If desired, please come to our team at the ARP. Closing here
