### ISSUE TITLE
New compoment: Badge

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#659]
We would like to display a "badge" that notifies the user that there is something new (and the count of) behind the link.

This would be combined _somehow_ with existing compoments (menu item / Tile header)

Example:

![image](https://user-images.githubusercontent.com/43809369/48003195-06856f80-e10e-11e8-83b9-24f28414ea28.png)

Brainstorming ideas how to implement:
- Batch component as a wrapper to display the batch above its children
- Batch compoment as individual compoment to be included within the others (f.e. menuitem) as a child
- Batch compoment as a renderProp in react
- batch as a number-type prop of the compments which implement it. (use common styles)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele I guess this component is still desired 🤔

**Comment by LucaMele** [comment]
If desired, please come to our team at the ARP. Closing here
