### ISSUE TITLE
New component: Side floating buttons

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#660]
We need this type of compoment: it display with fixed position on the right side of screen. Icon is shown. On hover, the button expands with animation and the title is shown also. More then one such buttons can be present.

Example:

![image](https://user-images.githubusercontent.com/43809369/48003611-33865200-e10f-11e8-836a-62935ae80828.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
