### ISSUE TITLE
New components: summary

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#661]
Summary of the recent "New compoment" issues, to discuss/refer them together.
In our team we need beginning new year these compoments:

Tile, Modal, Tooltip, Monthpicker, Message, Label-value pairs, Timeline, Progress, Badge, Side floating buttons:
#650 #651 #652 #653 #654 #656 #657 #658 #659 #660 #461

Also we need to be able to build on Windows: #648

**Comment by MarekLacoAXA** [comment]
Tile, Modal, Tooltip, Monthpicker, Message, Label-value pairs, Timeline, Progress, Badge, Side floating buttons.
Which of these above mentioned components *make most sense* to be added to Patterns Library? Are there some you don't think are needed for PL?

**Comment by LucaMele** [comment]
Here @kenaxa answer over slack for documentation purpuses
![e1fe28c0-3421-403a-90a4-806d64d506c5](https://user-images.githubusercontent.com/275235/48080391-d01f2180-e1ed-11e8-97e5-f951932ac93a.png)

**Comment by LucaMele** [comment]
@MarekLacoAXA @AndyOGo: The windows capability is very important. I will try to find time over xmas Holidays to finish the build in all aspects: DEV xpierience is also not perfect yet. #130 #601 #503 #553 etc

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
