### ISSUE TITLE
AXA header languages webcomponent onChange bug

### ISSUE THREAD

**Issue by BarboraBardunova** [axa-ch/patterns-library#662]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
-->
## Are you reporting a bug or a feature?

 - [x ] Bug
 - [ ] Feature

## Expected Behavior

when using header language dropdown with withReact like this: 

import withReact from '@axa-ch/patterns-library/lib/js/with-react';
import AXAHeaderLanguages from '@axa-ch/patterns-library/lib/components/m-header-languages';
const AXAHeaderLanguagesReact = withReact(AXAHeaderLanguages);

...
<AXAHeaderLanguagesReact onChange={this.handleLanguageChange} items={this.props.languages} />

I expect to fire handleLanguageChange function, but nothing happens

## Specifications

whatsmybrowser.org/b/2BH3DUC

Please provide any relevant information about your setup - os, browser, node, npm, etc. -->

 - Browser: Chrome
 - Browser Version: 70
 - Node Version: 8.9.2
 - NPM Version: 5.5.1
 - Platform: Win 7

**Comment by LucaMele** [comment]
Thank you for reporting this, we will have a look into it

**Comment by MarekLacoAXA** [comment]
I am unsure what is the intended way to listen to language change in react.
Why do you think *handleLanguageChange* event would be fired?
onClick callback works, see screenshot. Href attr can be parsed from e.target

My idea is to **write a react wrapper** that would receive a "onLanguageChange" cb, and call this cb with the parsed language code from href attr from e.target as cb's argument.

![image](https://user-images.githubusercontent.com/43809369/48190281-9b70ae80-e342-11e8-8ffe-7e4ed0ef0f08.png)


Let me know if there is a better way then have such react wrapper.
Unless I'll hear of a better solution, I would use such react wrappers for **all PL compontents** that have clickable items and I need track its clicks, that is:
AXAHeaderOthers, AXAHeaderLanguages, AXAHeaderNavigation, AXAHeaderMobileNavigation, AXAHeaderMobileLanguages, AXAHeaderMobileOthers, AXAFooterLanguages.

**Comment by MarekLacoAXA** [comment]
This is proposed change to PL from Luca: "Ideal would be that an onAxaChange event is triggered
and value property is set on the WC root".

@BarboraBardunova, after this change in PL, we will be able in React to pass onAxaChange CB to ```<AXAHeaderLanguages/>```

**Comment by NoahLiechti** [comment]
@MarekLacoAXA when language changes in PL, set the value like on the screenshot. (`axa-dropdown` has something similar)
<img width="425" alt="bildschirmfoto 2018-11-08 um 13 42 14" src="https://user-images.githubusercontent.com/38284563/48199360-201bf680-e35c-11e8-99b9-db376cfd746c.png">
After the value has changed an `AxaChange` Event  will be triggered automatically.

**Comment by NoahLiechti** [comment]
Are you able to implement this by yourself? @BarboraBardunova @MarekLacoAXA

**Comment by MarekLacoAXA** [comment]
Yes, I will give it a try during the following days!

**Comment by MarekLacoAXA** [comment]
@BarboraBardunova until the PR #667 is ready and a new PL version is published, you can use the attached [index.zip](https://github.com/axa-ch/patterns-library/files/2575517/index.zip) file as a replacement of:
\node_modules\@axa-ch\patterns-library\lib\components\m-header-languages\index.js

Then in react you can use this api:
```
<AXAHeaderLanguages
  onAxaChange={(e: any) => console.log('AXAHeaderLanguages onAxaChange', e.detail)}
  items={[
      {"name": "de", "url": "#de", "isActive": true},
      {"name": "en", "url": "#en"},
      {"name": "fr", "url": "#fr"},
      {"name": "it", "url": "#it"}
  ]}
/>
```

**Comment by LucaMele** [comment]
I will publish the PL asap as the branch is merged
