### ISSUE TITLE
When Loading the patterns-lib in the head element, some patternslib component are broken

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#663]
When Loading the patterns-lib in the head element, some patternslib component are broken. This issue is here since the removal of ondomloaded. Issue is found on the form refactoring. Reproducible when using buttons or choice elements after the import of the patterns lib is done

**Comment by AndyOGo** [comment]
whaaaaaat? That's not coool

**Comment by LucaMele** [comment]
yepp

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
