### ISSUE TITLE
separate detail views for components

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#672]
It is time-consuming to work on a simple component without being able to view them separately on it's own detail page, without all other components. 

This and a lot of other features could be provided (and a lot more features) by a  style guide lib like fractal or storybook.js
ref #590

**Comment by AndyOGo** [comment]
I agree absolutely, though why do we have a duplicate issue, if you found the existing already?

**Comment by AndyOGo** [comment]
keep discussion in our issue at #590
