### ISSUE TITLE
verbose cli outputs

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#673]
Verbose outputs should be opt-in and set behind a `-v --verbose` flag.  
At the moment, the CLI output, for instance `npm run serve` is polluted with verbose output per default which decreases the developer experience.

**Comment by LucaMele** [comment]
Totally agree on this one!

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
