### ISSUE TITLE
Button should extend built-in elements

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#674]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All our buttons should extends bultin-ins `<button is="axa-button">` and `<a is="axa-button">`.

## Actual Behavior

Atm. it's:

- [ ] semantically incorrect, especially how links and buttons are marked-up
- [ ] Currently we have `<axa-button>` and the tag is chosen from the `tag="a|button"` attribute.
- [ ] It also introduces further styling boundaries originating by it's wrapping DOM node, which can be avoided by built-in elements
- [ ] consequences for SEO, crawlers, etcs

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
