### ISSUE TITLE
Testimonials Uncaught TypeError

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#675]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

No error thrown.

## Actual Behavior

**Uncaught TypeError** thrown:

```sh
index.js:4108 Uncaught TypeError: Cannot read property 'length' of undefined
    at Testimonials.hideAllSlides (index.js:4108)
    at Testimonials.showSlide (index.js:4128)
    at index.js:4156
```

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
