### ISSUE TITLE
TypeError: this.disclaimerHandler is undefined

### ISSUE THREAD

**Issue by mjenny** [axa-ch/patterns-library#677]
Expect no TypeError:
![image](https://user-images.githubusercontent.com/4191545/49003677-b9237d80-f162-11e8-8a45-e6eb09421c84.png)

**Comment by mjenny** [comment]
This was happening inside Firefox when running Schadenmeldung on ACC

**Comment by LucaMele** [comment]
Thank you @mjenny. I saw this one as well, is not breaking anything but uncool that it creates a error. It refers to the Cookie Disclaimer. I will fix it asap.

**Comment by mjenny** [comment]
Sure, just wanted to let you know. 😄

**Comment by LucaMele** [comment]
Thanks :)
