### ISSUE TITLE
standarsize commit messages

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#678]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

If our team grows we should embrace standards and conventions.

Personally I'm a big fan of [`commitlint`](https://github.com/marionebl/commitlint) to enable fundamental tooling to help everyone [become a good commitizen](https://commitizen.github.io/cz-cli/)

**Comment by jackblackCH** [comment]
We definitely need a standard to make the log readable.
I also like the 7 rules style, which for instance they use at the linux core git and a lot of other famous companies.

https://chris.beams.io/posts/git-commit/
tldr:
Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to explain what and why vs. how

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
