### ISSUE TITLE
Base components flex display on large content.

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#680]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Icons should not be shrink on multiline content and the content should be displayed inline.

## Actual Behavior

When multi line content with links is inserted as child fragment the content and icons are not displayed properly.
Icons are not displayed properly in IE.

## Steps to Reproduce the Problem
![screen shot 2018-11-22 at 3 02 08 pm](https://user-images.githubusercontent.com/42141843/49010722-66eb5800-f174-11e8-9713-abea6a71f52e.png)

Use the below as childrenFragment

`<axa-checkbox
  value="b"
  name="test-name2"
  error>
  hello hello <a href="#" target="_blank">hello hello hello hello hello hello hello hello</a> hello hello hello hello <a href="#" target="_blank">hello hello hello hello </a> hello hello hello hello.
</axa-checkbox>
`

**Comment by AndyOGo** [comment]
@nakovskijosif 
Thanks for your feedback, very appreciated.
Which version of IE are you talking about, IE `11`?

Unfortunately all form elements aren't considered stable yet: #549 #588 #563
