### ISSUE TITLE
group related components

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#683]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

All related components should be:

- [ ] together in source and at documentation pages
- [ ] should have their own link/menu item including for all sub components
- [ ] they should be stripped out of organism, molecules or atoms page (only if they are in a group)
- [ ] the build should auto-detect groups
- [ ] create-a-m-o script should be able to initialise a group and maybe to turn an existing component into a grouped component

**Affected Components:**
- [ ] Header
- [ ] Footer
- [ ] Error Pages
- [ ] Sticky
- [ ] Table

Definition of group is the highest material type possible. For example for Table is the group `o-table` where all its components are directly under it inside a folder `subcomponents`. ONLY the components that have a hard coupling should be grouped

**Comment by AndyOGo** [comment]
Quote @jackblackCH feedback from https://github.com/axa-ch/patterns-library/issues/782#issue-399827625

> The more components we have, it becomes harder to find the desired components (scrolling through a huge prefixed components directory).

> It makes it more readable to group it within the directories.
Sidenote: Tools like Fractal, Storybook or other pattern library helpers, allow this sub directories per default.

```
src/components
  - atoms
     - a-caption
     - a-checkbox
  - molecules
     - m-button
     - m-col
  - organisms
     - o-datepicker
```

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
