### ISSUE TITLE
Navigation should be agnostic to routing tools

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#697]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

I expect that all navigations, whether from header, footer, normal links to compatible with routing tools, like [`react-router`](https://reacttraining.com/react-router/)

## Actual Behavior

Not possible to use `<NavLink>`, `<Route>`, `<Link>` from react-router or any other routing tools without hacking, monkey patching...

**Related:**

Iterator components #410

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
I don't think that this is working 🤔

**Comment by LucaMele** [comment]
Routing works with v2. Here a demo: https://github.com/axa-ch/patterns-library-examples/blob/master/create-react-app/src/App.js

If there is an issue with v2, please show where and re-open. Thank you
