### ISSUE TITLE
Build of preview broken since last release

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#702]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Build and preview should display working, full-width components.

## Actual Behavior

Since one of the last two PRs #695

- [x] Clicking Home -> **404** Page (all components)
   ![click-home-404](https://user-images.githubusercontent.com/914443/49256148-6251c880-f42e-11e8-8808-6cf41f504f33.gif)
- [x] All components can't use full width
   <img width="1438" alt="screen shot 2018-11-29 at 23 35 59" src="https://user-images.githubusercontent.com/914443/49256464-6500ed80-f42f-11e8-8ac5-001ae27e9fe7.png">
- [x] _All single component pages have no complete navigation_ -> Its a feature
- [ ] Header broken, Top Content bar, button not working
   <img width="1341" alt="screen shot 2018-11-29 at 23 26 55" src="https://user-images.githubusercontent.com/914443/49256075-29b1ef00-f42e-11e8-9eb6-0ece0c5f1c22.png">
- [x] Commercial Hero Cover looks weird
   <img width="1405" alt="screen shot 2018-11-29 at 23 30 34" src="https://user-images.githubusercontent.com/914443/49256262-ae047200-f42e-11e8-9801-84712c07ad77.png">
- [x] Datepicker broken
   <img width="688" alt="screen shot 2018-11-29 at 23 31 45" src="https://user-images.githubusercontent.com/914443/49256290-d12f2180-f42e-11e8-99ee-70f58ce8bb1e.png">
- [ ] maybe more

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/

## Specifications

 - Browser: all
 - Browser Version: any

**Comment by LucaMele** [comment]
https://github.com/axa-ch/patterns-library/issues/701

**Comment by LucaMele** [comment]
Thank i already opened an issue

**Comment by LucaMele** [comment]
Before 700 was completely broken as the js files were referenced wrong

**Comment by LucaMele** [comment]
Now some dependencies are missing on the single components and the home button needs a check for env

**Comment by LucaMele** [comment]
I only fixed linting issues and the relative url

**Comment by LucaMele** [comment]
@AndyOGo the " All single component pages have no complete navigation" is a feature as we just wanted to have ONE Webcomponent on

**Comment by LucaMele** [comment]
Polyfill on single components not loaded. Same issue as HOME button. Paths are different

<img width="738" alt="bildschirmfoto 2018-11-30 um 01 16 56" src="https://user-images.githubusercontent.com/275235/49260401-b021fd00-f43d-11e8-972f-b9886c56a858.png">

**Comment by LucaMele** [comment]
I added a checked checkbox on the issues i fixed.

**Comment by AndyOGo** [comment]
@LucaMele 
Thank you very much for your late night work to fix these errors 👍 

> the " All single component pages have no complete navigation" is a feature as we just wanted to have ONE Webcomponent on

Okay, I couldn't find a feature issue description for it? And is it agreed upon by Design/UX?

**Comment by LucaMele** [comment]
We decided that on the single component page we only have the webcomponent under test for easier development. There is no description am sorry about that and no it does not have to be agreed with design as it is a patterns library charatersic rather then design. Nether than less, if u or design prefer having a header we can talk about it. The idea was as said to have obly those webcomponentsbon the page that are under test/view

**Comment by LucaMele** [comment]
HTML preview is missing

**Comment by AndyOGo** [comment]
Okay.

So please follow our contribution guide lines next time, first an issue describing the feature, then an implementation.
Otherwise you exclude other people and they have no chance to give feedback.
The navigation is important and as you said correctly the info buttons for each components are missing.

**Comment by LucaMele** [comment]
Agree, we should have described it for communication purposes. Sorry wont happen again.
