### ISSUE TITLE
Please describe axa-core, React question

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#706]
Please describe in short (as a JS docblock) the purpose of the AXACore component.

Why is there no react-export of this component?

What is the recommended way to "make the PL icons work" in a react app?

Thanks!

**Comment by MarekLacoAXA** [comment]
I see, I assume the "recommended way" is included in the "patterns-library-examples" here:
https://github.com/axa-ch/patterns-library-examples/blob/master/react/src/index.js

**Comment by LucaMele** [comment]
Hello Marek,

Yes axa core ist still a bit grey on what it is and does. It also is not compatible with `with-react`.

to use custom icon spritesheet, you have to do following:

```
ReactDOM.render(<Fragment>
  <axa-core icons-path="icons.svg"></axa-core>
  <App />
  </Fragment>, document.getElementById('root'));
registerServiceWorker();
```

**Comment by LucaMele** [comment]
this will load the `icons.svg` and prepare it for `<axa-icon>`
