### ISSUE TITLE
Sticky Funktioniert nicht richtig bei Single Component. Korrekt aber wenn alle organism angeschaut werden

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#709]
<img width="808" alt="bildschirmfoto 2018-11-30 um 12 38 23" src="https://user-images.githubusercontent.com/275235/49287222-f22e5b80-f49c-11e8-989f-81dcf4edb2ed.png">

**Comment by LucaMele** [comment]
Klasse `is-sticky-sticky` scheint es nicht zu geben

**Comment by AndyOGo** [comment]
interesting

**Comment by MKaHead** [comment]
The problem is not reproducible on Axa.ch.
I would recommend to delete the prod_issue label, can I do that @LucaMele @AndyOGo ?

I could reproduce it, in the pattern library like @LucaMele

**Comment by MKaHead** [comment]
Issue is not that relevant.

The problem cause by the header mobile nav because that thing is not relative to the header bar.
When the header bar is at the top, it's all fine, but we should make it more stable.

I'm going to remove the prod_issue label and high-prio flag.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
