### ISSUE TITLE
Clearly document how the plib was supposed to be consumed

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#710]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

At the beginning of this project, we focused to make the patterns-library usable only by it's CSS without web comonents, because:

- [ ] We did not know how AEM would work with custom elements and wanted to try this in two steps - first CSS-only, next with custom elements
- [ ] We don't know how SEO, page-speed, preformance is affected (still unknown, but accepted)
- [x] AEM design importer tag checker (already mitigated by luca)
- [ ] The wrapping DOM node of all custom elements can bring a challenge to HTML markup and CSS selectors and it's cascade behavior, e.g. `flexbox` can break -> built-in extension will help us here #682 
- [ ] because we couldn't use custom elements at the beginning we had to extract event handling by JS -> adapter pattern, custom elements reduced to "selector-api", to easily exchangable by `document.querySelector`...

## Actual Behavior

Not all is documented.

**Comment by LucaMele** [comment]
I will close this Issue as should not be in the plib and:

 AEM design importer tag checker is documentd: https://github.com/axa-ch/patterns-library#usage-guide---with-aem-design-importer

I dont know what u mean with incopatibility but custom elements did work and work perfectly in AEM everywhere apart of design importer

**Comment by LucaMele** [comment]
CSS standalone not always as we go with pure Webcomponent approach ATM

**Comment by LucaMele** [comment]
Event handling needs to be possible without custom elements -> adapter pattern, custom elements reduced to "selector-api", to easily exchangable by document.querySelector... -> Deprecated. Is since ages we are not looking on this anymore. Since Webcomponents are now accepted, this extra layer of complexity is not needed. We desiced to use the adapter cause we were scared of WC. Now is good.

**Comment by AndyOGo** [comment]
@LucaMele 
Please trust me on this.
We had to make a lot of decisions to make the CSS working without custom elements.
Therefore a lot of limitations and incompatibilities had to be mitigated.

And it belongs to the patterns-library, because these mitigations are implemented intentionally here, so we should document all off these special cases.

**Comment by AndyOGo** [comment]
> Since Webcomponents are now accepted, this extra layer of complexity is not needed. We desiced to use the adapter cause we were scared of WC.

Sorry Luca, but for example Safari does still not accept bult-ins, they refuse to implemented them.

**Comment by LucaMele** [comment]
@AndyOGo we did them cause we were scared. This is not requeried anymore and if it brakes somewhere we implent it

**Comment by LucaMele** [comment]
@AndyOGo we have polyfills

**Comment by LucaMele** [comment]
all forms will have WEB COMPONENTS soon, PUG will be deleted and AEM already has Custom element so lets not make a deal where is not and if there is an issue in AEM we track it there

**Comment by AndyOGo** [comment]
@LucaMele 

> we did them cause we were scared.

Yes, that is true. And since it is the statos quo. We have to track and communicate it.
Please leave it open, we can also decide to undo all of these incompatibility mitigations.

But before we haven't fixed and tested it, it's to be an open issue.

**Comment by LucaMele** [comment]
@AndyOGo dont make me loose time. Is not end of discussiomn

**Comment by LucaMele** [comment]
@AndyOGo if u reopen, i delete the issue

**Comment by AndyOGo** [comment]
nice read about SEO and custom elements:
https://react-etc.net/entry/web-components-seo

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
