### ISSUE TITLE
dev build status and speed unclear

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#714]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We should see when the dev build is finished and it should be much faster since #695 

As @jackblackCH claimed:
> Improves build time. It's much faster

## Actual Behavior

We don't see when dev build is finished (because all logs are gone).

The build time has not improved, since no measurements where provided here they are:

**[@v2.0.1-beta.222](https://github.com/axa-ch/patterns-library/releases/tag/v2.0.1-beta.222)** `time npm run build`

> real    1m48.047s
> user    3m21.263s
> sys    0m8.170s

**[@develop](https://github.com/axa-ch/patterns-library)** `time npm run build`

> real    1m52.794s
> user    3m20.704s
> sys    0m8.223s

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
