### ISSUE TITLE
Refactore components to extend built-in elements

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#716]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

All our components should be semantically correct, allow SEO crawlers to rate them, should not break CSS styles like `flexbox` and should allow iterating items of `<ul> > <li>` correctly.

To mitigate and fix those issues, we should refactor our components to extend built-ins.

- [ ] `<axa-header>` -> `<header is="axa-header"`>
- [ ] `<axa-header-navigation>` -> `<nav is="axa-header-navigation"`>
- [ ] `<axa-header-others>` -> needs to extract item and use semantically correct markup (`nav` or `ul`)
- [ ] `<axa-header-mobile-navigation>` -> `<nav is="axa-header-mobile-navigation"`>
- [ ] `<axa-footer>` -> `<header is="axa-footer"`>
- [ ] `<axa-button tag="a|button">` -> `<button is="axa-button">` and `<a is="axa-button">` #674 
- [ ] '<axa-container>' -> would be valid for multiple tags, like `<article is="axa-container">`, `<section is="axa-container">`, `<div is="axa-container">` (it depends upon context)
- [ ] all other components, also `<aside>` makes sense for less important navigations, etc.
- [ ] `<axa-row>` -> `<div is="axa-row">`; `<axa-col>` -> `<div is="axa-col">`

IF we do this we can properly enable iterator components #410 
 
## Actual Behavior

We almost only have autonomous custom elements

## Nice read

https://hackernoon.com/extending-built-in-elements-9dce404b75b4

## Related

IE11 built-ins have to working for this refactoring #698

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele 
I would not consider this as fixed, but rather ignored 🤔
