### ISSUE TITLE
build huge script waterfall

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#720]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

All `<scipts>` should be loaded asynchronously **as fast as possible** in **all browsers** - ideally by a sophisticated bundler/loader.

- [ ] Load just one bundle
- [ ] Or ideally lazy-load in-view components by `import().then()`, like react-loadable

## Actual Behavior

All `<scipts>` are loaded synchronously and therefore block the next script.

## Steps to Reproduce the Problem

1. inspect network traffic.

![build-script-huge-waterfall](https://user-images.githubusercontent.com/914443/49392353-764b4200-f72e-11e8-8e8c-8ea8aac69271.gif)

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
