### ISSUE TITLE
IE11 randomly gives long running script errors

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#722]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We should never have long running scripts.

## Actual Behavior

IE11 randomly gives long running script errors

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
