### ISSUE TITLE
Dependencies between components not expressed

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#723]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All components should clearly state on which other components they depend upon.

This is fundamental for **Single Component Views**.

## Actual Behavior

We have no dependency tree between components.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele 
Has there been a settlement regarding this.
I would say it's rather important.

**Comment by LucaMele** [comment]
@AndyOGo fixed in v2 with npm dependencies like so: https://github.com/axa-ch/patterns-library/blob/develop/src/components/10-atoms/button/package.json

```json
"dependencies": {
    "@axa-ch/icon": "^1.0.4",
    "@skatejs/val": "^0.4.0",
    "lit-element": "^2.1.0",
    "lit-html": "^1.0.0"
  }
```
