### ISSUE TITLE
Datepicker with-react makes errors but seems to work correctly in the react section of the plib

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#727]
<img width="773" alt="bildschirmfoto 2018-12-04 um 11 11 35" src="https://user-images.githubusercontent.com/275235/49434815-6e82b080-f7b5-11e8-91cd-c8d5134a34f1.png">

**Comment by AndyOGo** [comment]
@LucaMele 
Is this fixed by recent PRs?

**Comment by AndyOGo** [comment]
Should be fixed by one of recent PRs #741, #745, #746  and/or  #748
