### ISSUE TITLE
IE Unexpected character in comment end. Expected "-->"

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#73]
<img width="1070" alt="screen shot 2017-12-18 at 09 11 24" src="https://user-images.githubusercontent.com/914443/34095937-b3c5ab94-e3d3-11e7-900d-c0e59e9ebe1a.png">

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
