### ISSUE TITLE
Feature Request/Supporting custom attributes data-*

### ISSUE THREAD

**Issue by jan-capiak** [axa-ch/patterns-library#731]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [X] Feature

## Expected Behavior

I know Michel is already making PR: https://github.com/axa-ch/patterns-library/pull/676 about putting `data-seleniumid` attribute to patterns-library components with `withSeleniumId` HOC...

The idea is that patterns-library componets will be supporting custom attributes at all.
So when i send to AxaDropdown `data-*` attribute, i want it to be rendered in DOM of AxaDropdown element.

**Comment by AndyOGo** [comment]
@jan-capiak 
I just released a new version `v2.0.1-beta.232` of `withReact` which does only forward `observedAttributes` and events to the custom element, all other props are passed directly to JSX.

I would be keen to know if that solves your problem 😃

**Comment by LucaMele** [comment]
Thank you andy for this

**Comment by jan-capiak** [comment]
Hello Andy, thank you, it helped. Now i can pass custom attributes to axa-dropdown when using withReact 👍 
Screenshot:
![image](https://user-images.githubusercontent.com/39954604/49501952-56be3180-f874-11e8-8d72-0ffc508ca128.png)

**Comment by AndyOGo** [comment]
Fixed by #728, #689 and #685
