### ISSUE TITLE
Footer Language does not trigger onAxaClick Handler

### ISSUE THREAD

**Issue by ranostaj** [axa-ch/patterns-library#732]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

# Footer Languages Component
## Tested version 
 `2.0.1-beta.229`

## Expected Behavior

I have Footer Language component and instead of using href attribute to navigate I'd like to trigger onClick event and change the application state.  I'm using library version `2.0.1-beta.229`

```
<AXAFooterLanguagesReact
              onClick={this.handleLanguageClick}
              items={this.props.languages}
            />
```

So I suppose that the `onClick` event is captured like so:

```
handleLanguageClick = (e) => {
    e.preventDefault();
    const language = e.target.getAttribute('href');
    this.props.onLanguageChange(language);
  };
```

## Version it works
In version `2.0.1-beta.200` it works just fine

## Actual Behavior

The  `onClick` event doesn't get triggered.

# Header Languages Component
## Tested version 
 `2.0.1-beta.229`

The same problem applies to `HeaderLanguage` :   

## Expected Behavior

```
<AXAHeaderLanguagesReact
     onClick={this.handleLanguageClick}
      items={this.props.languages}
        />
```

Handler:
```
 handleLanguageClick = e => {
    e.preventDefault();
    const language = e.target.getAttribute('href');
    this.props.onLanguageChange(language);
  };
```
## Actual Behavior

The  `onClick` event doesn't get triggered.

## Version it works
In version `2.0.1-beta.200` it works just fine

**Comment by AndyOGo** [comment]
Thanks a lot.
I will add an `onAxaClick` event.
