### ISSUE TITLE
Header Language item is not selected when isActive attribute set to true

### ISSUE THREAD

**Issue by ranostaj** [axa-ch/patterns-library#738]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

I suppose that isActive item attribute  will set active item as selected
```
<AXAHeaderLanguagesReact
                onAxaClick={this.handleLanguageClik}
                items={this.props.languages}
              />
```

## Actual Behavior

Instead I have to manually set value of selected item
```
<AXAHeaderLanguagesReact
                onAxaClick={this.handleLanguageClick}
                value={this.props.languages.find(lg => lg.isActive).code}
                items={this.props.languages}
              />
```

## Specifications

 - Browser: Chrome
 - Patterns Library version  2.0.1-beta.236
- Using with React

**Comment by AndyOGo** [comment]
Either remove `value` or only use `value`, but not both.
@LucaMele 
Does this affect the adapter pattern used for AEM?

**Comment by LucaMele** [comment]
we need to test

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
