### ISSUE TITLE
Safari with-react and built-in styles not global

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#747]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All `<style>`s should be in `<head>`

## Actual Behavior

All `<style>` tags are multiple within the `wcNode`.

## Steps to Reproduce the Problem

1. https://github.com/axa-ch/patterns-library-examples/tree/master/react
2. `npm start`
3. open `http://localhost:3000` in Safari

<img width="1266" alt="screen shot 2018-12-05 at 20 46 04" src="https://user-images.githubusercontent.com/914443/49539878-f27c8b80-f8ce-11e8-947e-fc47177079ec.png">

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by AndyOGo** [comment]
@LucaMele 
Just to let you know, this also caused the performance issue in Safari and IE.
It seemed it fast a long running or infinite loop problem, but we just create a whole bunch of `<style>` tags, which triggers the whole CSSOM (CSS Object Model) chain additionally to DOM mutations and that is slow, really slow

**Comment by LucaMele** [comment]
@AndyOGo why are the style tags here and not in the header? But yes it make sense if every component appends its styles, it will re calculate css and therefore has performance impact :) thank you andy

**Comment by AndyOGo** [comment]
because `_appendStyles` was bound to the wrong context within `constructor` instead of `init`.
I fixed it by this code:
https://github.com/axa-ch/patterns-library/pull/748/files#diff-70d72b50ba4e3a116679e4be64b5ff86

**Comment by LucaMele** [comment]
Yepp that makes sense :) Am glas that i was on the right track during my investigation :) Thank yopu again.

**Comment by LucaMele** [comment]
@AndyOGo IS WORKING ON IE NOW IN AEM!!!!!!!!!!!!!
