### ISSUE TITLE
Table row unmounting bug

### ISSUE THREAD

**Issue by BarboraBardunova** [axa-ch/patterns-library#752]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Expecting to proper render/destroy of table when using withReact

## Actual Behavior

The table is dependent on data recieved from backend, when rerendering the table with fewer rows than was rendered before, it has problem destroying the excessive rows and throws an error: 

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

whatsmybrowser.org/b/2BH3DUC

Please provide any relevant information about your setup - os, browser, node, npm, etc. -->

 - Browser: Chrome 
 - Browser Version: 71
 - Node Version: 8.9.2
 - NPM Version: 5.5.1
 - Platform: Windows 7
 
## Failure Logs

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
▼ 28 stack frames were expanded.
removeChild
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:9119
unmountHostComponents
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:17300
commitDeletion
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:17351
commitAllHostEffects
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:18110
HTMLUnknownElement.callCallback
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:147
invokeGuardedCallbackDev
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:196
invokeGuardedCallback
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:250
commitRoot
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:18327
completeRoot
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19894
performWorkOnRoot
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19817
performWork
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19722
performSyncWork
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19696
requestWork
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19551
scheduleWork
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:19358
enqueueSetState
C:/eplatform/git-repos/webrep-ui/node_modules/react-dom/cjs/react-dom.development.js:12789
Connect.push../node_modules/react/cjs/react.development.js.Component.setState
C:/eplatform/git-repos/webrep-ui/node_modules/react/cjs/react.development.js:354
Connect.onStateChange
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/components/connectAdvanced.js:205
notify
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/utils/Subscription.js:23
Subscription.notifyNestedSubs
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/utils/Subscription.js:62
Connect.onStateChange
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/components/connectAdvanced.js:202
notify
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/utils/Subscription.js:23
Subscription.notifyNestedSubs
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/utils/Subscription.js:62
Connect.onStateChange
C:/eplatform/git-repos/webrep-ui/node_modules/react-redux/es/components/connectAdvanced.js:202
dispatch
C:/eplatform/git-repos/webrep-ui/node_modules/redux/es/redux.js:214
dispatch
<anonymous>:1:40228
(anonymous function)
C:/eplatform/git-repos/webrep-ui/node_modules/connected-react-router/lib/middleware.js:40
(anonymous function)
C:/eplatform/git-repos/webrep-ui/node_modules/redux-thunk/es/index.js:11
dispatch
C:/eplatform/git-repos/webrep-ui/node_modules/redux/es/redux.js:613

**Comment by AndyOGo** [comment]
@BarboraBardunova 
You can also import all table components and build the whole table by yourself, similar to the react examples https://github.com/axa-ch/patterns-library-examples/blob/master/react/src/Table.js, like:

```js
import {
  AXAContainer,
  AXATable,
  AXACaption,
  AXAThead,
  AXATfoot,
  AXATbody,
  AXATr,
  AXATd,
  AXATh,
} from '@axa-ch/patterns-library/lib/js/react-exports';

const Table = ({ items }) => (<AXAContainer>
    <AXATable>
      <AXACaption side="bottom" align="right">Caption</AXACaption>

      <AXAThead>
        <AXATr>
          <AXATh>Head</AXATh>
          <AXATh sort="up">Sort Up</AXATh>
          <AXATh sort="down">Sort Down</AXATh>
          <AXATh sort="up" sortActive>Sort Up Active</AXATh>
          <AXATh sort="down" sortActive>Sort Down Active</AXATh>
          <AXATh align="left">Left</AXATh>
          <AXATh align="center">Center</AXATh>
          <AXATh align="right">Right</AXATh>
        </AXATr>
      </AXAThead>

      <AXATfoot>
        <AXATr foot>
          <AXATd colspan="3" align="left" float="left" bold>Deposit Plan</AXATd>
          <AXATd colspan="5" align="right" float="right" bold>+ $ 1200 monthly</AXATd>
        </AXATr>
        <AXATr foot>
          <AXATd colspan="3" align="left" float="left" bold>Withdrawal Plan</AXATd>
          <AXATd colspan="5" align="right" float="right" bold>- $ 1200 yearly</AXATd>
        </AXATr>
      </AXATfoot>

      <AXATbody>
        {items.map(({ id, foo, bar, baz }, index) => (
          <AXATr key={id || index}>
            <AXATd>{foo}</AXATd>
            <AXATd strong>{bar}</AXATd>
            <AXATd bold>{baz}</AXATd>
        </AXATr>
      )}
    </AXATable>
  </AXAContainer>
);
```

**Comment by BarboraBardunova** [comment]
tried your solution but the same error still appears, I guess I will wait for the pull request and test it then

**Comment by AndyOGo** [comment]
@BarboraBardunova 
Interesting.

So I started to add two example within my PR, using each component directly works with dynamic data, code here:
https://github.com/axa-ch/patterns-library/blob/3a3895d8c6d6a3bad99361bc46c0258330a1bc6c/src/demos/todomvc/todos-table.jsx#L47-L67

What I found is that changing of children text-node does not update, I tracked it here #755 

May I ask you to provide complete reproduction code?

**Comment by AndyOGo** [comment]
@BarboraBardunova 
Thanks for the code.
So the first issue I see is that you are not using our components wrapped by `withReact`.
React itself still does not have proper custom elements support, so you can't use custom elements directly.
Please always make sure to use properly wrapped custom elements for React by `withReact` or directly from our react-exports file here:
https://github.com/axa-ch/patterns-library/blob/57cb263111706067f99ae0110e70e51479489c7b/src/js/react-exports.js#L163-L185

**Comment by BarboraBardunova** [comment]
I tried this and it still behaves the same: 

```
import React, { Component } from 'react';
import { i18n } from '../../i18n/i18n';
// import '@axa-ch/patterns-library/lib/components/o-table';
import '@axa-ch/patterns-library/lib/components/m-row';

import {
  AXAContainer,
  AXATable,
  AXACaption,
  AXAThead,
  AXATfoot,
  AXATbody,
  AXATr,
  AXATd,
  AXATh,
} from '@axa-ch/patterns-library/lib/js/react-exports';

import PropType from 'prop-types';

export default class Table extends Component {
  linkTo = (eventId, seqNr) => this.props.linkTo(eventId, seqNr);

  processingStatusClass(parentStatusCode) {
    if (!!parentStatusCode) {
      if (parentStatusCode.key === '100') {
        return 'a-td--state-ok';
      }
      if (parentStatusCode.key === '101' || (parentStatusCode.key === '102')) {
        return 'a-td--state-pending';
      }
      if (parentStatusCode.key === '103') {
        return 'a-td--state-error';
      }
      else return '';
    }
    return '';
  }

  render() {
    const tHead = [
      'txtTableEventdate',
      'txtTableProcessingStatus',
      'txtTableRequestType',
      'txtTableModel',
      'txtTableNumberPlate',
      'txtTableEventLocation',
      'txtTableCarOwner',
      'txtTableDossierNr'
    ];

    const headerItems = tHead.map((item, i) => (
      <AXATh key={i} sort="down">
        {i18n(item)}
      </AXATh>
    ));

    const table = (
      <AXATable action>
        <AXAThead><AXATr>{headerItems}</AXATr></AXAThead>
        <AXATbody>
          {this.props.data.map((dataObject, rowIndex) =>  (
            <AXATr
              key={rowIndex}
              onClick={this.linkTo.bind(null, dataObject.id.eventId, dataObject.id.seqNr)}>
              <AXATd>
                {dataObject.claimDate}
              </AXATd>
              <AXATd>
                {dataObject.processingStatus}
              </AXATd>
              <AXATd>
                {dataObject.requestType}
              </AXATd>
              <AXATd>
                {dataObject.model}
              </AXATd>
              <AXATd>
                {dataObject.numberPlate}
              </AXATd>
              <AXATd>
                {dataObject.incidentLocation}
              </AXATd>
              <AXATd>
                {dataObject.ownerName}  {dataObject.ownerSurname}
              </AXATd>
              <AXATd>
                {dataObject.nr}
              </AXATd>
            </AXATr>
          ))}
        </AXATbody>
      </AXATable>
    );

    const tableErrorRow = this.props.errorMessage ? (
      <div className="wr-row wr-table-error">
        Error: {this.props.errorMessage}
      </div>
    ) : (
      ''
    );


    return (
      <div>
        {tableErrorRow}
        <div className="wr-row">{this.props.data.length > 0 && table}</div>
      </div>
    );
  }
}


Table.propTypes = {
  data: PropType.array,
  errorMessage: PropType.string,
  linkTo: PropType.func
};
```

and also tried it like this: 

```
import React, { Component } from 'react';
import { i18n } from '../../i18n/i18n';
import PropType from 'prop-types';
// import '@axa-ch/patterns-library/lib/components/o-table';
import '@axa-ch/patterns-library/lib/components/m-row';
import withReact from '@axa-ch/patterns-library/lib/js/with-react';
import AXATableWC from '@axa-ch/patterns-library/lib/components/o-table';
import AXATheadWC from '@axa-ch/patterns-library/lib/components/m-thead';
import AXATbodyWC from '@axa-ch/patterns-library/lib/components/m-tbody';
import AXATdWC from '@axa-ch/patterns-library/lib/components/a-td';
import AXATrWC from '@axa-ch/patterns-library/lib/components/m-tr';
import AXAThWC from '@axa-ch/patterns-library/lib/components/a-th';

export const AXATable = withReact(AXATableWC);
export const AXAThead = withReact(AXATheadWC);
export const AXATbody = withReact(AXATbodyWC);
export const AXATd = withReact(AXATdWC);
export const AXATr = withReact(AXATrWC);
export const AXATh = withReact(AXAThWC);

export default class Table extends Component {
  linkTo = (eventId, seqNr) => this.props.linkTo(eventId, seqNr);

  processingStatusClass(parentStatusCode) {
    if (!!parentStatusCode) {
      if (parentStatusCode.key === '100') {
        return 'a-td--state-ok';
      }
      if (parentStatusCode.key === '101' || (parentStatusCode.key === '102')) {
        return 'a-td--state-pending';
      }
      if (parentStatusCode.key === '103') {
        return 'a-td--state-error';
      }
      else return '';
    }
    return '';
  }

  render() {
    const tHead = [
      'txtTableEventdate',
      'txtTableProcessingStatus',
      'txtTableRequestType',
      'txtTableModel',
      'txtTableNumberPlate',
      'txtTableEventLocation',
      'txtTableCarOwner',
      'txtTableDossierNr'
    ];

    const headerItems = tHead.map((item, i) => (
      <AXATh key={i} sort="down">
        {i18n(item)}
      </AXATh>
    ));

    const table = (
      <AXATable action>
        <AXAThead><AXATr>{headerItems}</AXATr></AXAThead>
        <AXATbody>
          {this.props.data.map((dataObject, rowIndex) =>  (
            <AXATr
              key={rowIndex}
              onClick={this.linkTo.bind(null, dataObject.id.eventId, dataObject.id.seqNr)}>
              <AXATd>
                {dataObject.claimDate}
              </AXATd>
              <AXATd>
                {dataObject.processingStatus}
              </AXATd>
              <AXATd>
                {dataObject.requestType}
              </AXATd>
              <AXATd>
                {dataObject.model}
              </AXATd>
              <AXATd>
                {dataObject.numberPlate}
              </AXATd>
              <AXATd>
                {dataObject.incidentLocation}
              </AXATd>
              <AXATd>
                {dataObject.ownerName}  {dataObject.ownerSurname}
              </AXATd>
              <AXATd>
                {dataObject.nr}
              </AXATd>
            </AXATr>
          ))}
        </AXATbody>
      </AXATable>
    );

    const tableErrorRow = this.props.errorMessage ? (
      <div className="wr-row wr-table-error">
        Error: {this.props.errorMessage}
      </div>
    ) : (
      ''
    );


    return (
      <div>
        {tableErrorRow}
        <div className="wr-row">{this.props.data.length > 0 && table}</div>
      </div>
    );
  }
}


Table.propTypes = {
  data: PropType.array,
  errorMessage: PropType.string,
  linkTo: PropType.func
};
```

**Comment by AndyOGo** [comment]
@BarboraBardunova 
Your React code is not ideal.
Once you check `this.props.data.length > 0 && table` and conditionally include `table` at:
> <div className="wr-row">{this.props.data.length > 0 && table}</div>

But on the other side you always render `table` before, even when `this.props.data.length` is `0`.

That is not how React is designed to be used and isn't good practice.

**Comment by BarboraBardunova** [comment]
you are right, reseting the input data before recieving new data from backend helped
thank you very much for your help :)
