### ISSUE TITLE
should update check for children

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#755]
Currently our `shouldUpdateCallback` compares only attributes.

But what if only the children of type text-node changed?
How should DOM morphing take place, also taking into account custom elements **asynchronicity** and **nested** custom elements 🤔 

Also we have template-less and template-full custom elements.

https://github.com/axa-ch/patterns-library/blob/57cb263111706067f99ae0110e70e51479489c7b/src/js/abstract/hocs/with-update.js#L212-L214

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
