### ISSUE TITLE
Datepicker is not setting value in IE.

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#757]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

When I select a date in IE the "value" attribute on <axa-datepicker ../> should be updated accordingly.

## Actual Behavior

the value is always set to false.

**Comment by jackblackCH** [comment]
Please always add the exact version of IE version and OS

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
