### ISSUE TITLE
Datepicker sets a "wrong" iso date compared to the "clicked" one 

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#764]
When you chose a date and click ok, the iso-date that is set, is not matching with the chosen one, it's actually set to the day before.

## How to reproduce:
`const date = new Date(2020, 11, 31)` `// Thu Dec 31 2020 00:00:00 GMT+0100 (Central European Standard Time)`

`date.toISOString()` `// 2020-12-30T23:00:00.000Z`

It looks as if the output date of `date.toISOString()` is one day behind.
This is technically correct but probably not the expected behavior.

Update:
If we really work correctly with iso-dates, we should accept them and convert them back on the backend accordingly.

**Comment by LucaMele** [comment]
wow ok.. i didnt see that! thanks @jackblackCH
