### ISSUE TITLE
Font is not Correct on header

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#766]
The font used on www.axa.ch and patterns-library seems not correct.

IS: Georgia
EXPECTED: publico as defined here www.design.axa.ch

![hssepkx](https://user-images.githubusercontent.com/275235/50226247-fdd9b780-03a2-11e9-95f5-78a8dbf3df06.png)

Thank you Nils

**Comment by LucaMele** [comment]
@jojackpot can you check if this is an issue or a desired feature?

**Comment by jojackpot** [comment]
@LucaMele Should be Publico Headline in both cases, Georgia is only the backup font. I quickly checked it on Chrome (MacOS) and it rendered Publico Headline ...
![screenshot_klein](https://user-images.githubusercontent.com/17493343/50230981-0aafd880-03ae-11e9-967e-1b38b58d1521.jpg)

**Comment by nilsbuehrer** [comment]
@jojackpot On Chrome on my mac the rendered font is Georgia, too (but it is Publico Headline on www.axa.com and www.axa.ie. 
And on your screenshot the font's still not looking right (compare it to the axa.com).

![image](https://user-images.githubusercontent.com/18344358/50233210-3aadaa80-03b3-11e9-990c-ba828c1adfe4.png)

**Comment by TheDadi** [comment]
Well if you do not load publico it will never be shown😅

**Comment by TheDadi** [comment]
@Jojackpot if you installed the font on your device it get‘s shown correctly 😊

**Comment by LucaMele** [comment]
I will look tomorrow if its loaded or not. Thank u guys

**Comment by LucaMele** [comment]
@nilsbuehrer and @TheDadi apparently somewhen the font loading disappeared from the css resources. Thank you Dario for your hint, thats the reason why @jojackpot can see it even if is not loaded.

@nilsbuehrer , officially is Georgia the fallback font from axa design perspective, therefore still is "compliant". We will try to fix this Issue asap. 

Thank you again, please keep posting issues you find. This helps us enormous.

**Comment by NoahLiechti** [comment]
https://github.com/axa-ch/patterns-library/blob/develop/src/styles/typo/_typo-webfonts.scss
Publico Headline should be loaded here, doesn't it?

**Comment by LucaMele** [comment]
@NoahLiechti yes it should. But on the network tap is not loaded for some reason

**Comment by TheDadi** [comment]
The naming in the font family is wrong
