### ISSUE TITLE
Firefox: TypeError: window.customElements is undefined

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#77]
> TypeError: window.customElements is undefined

<img width="1440" alt="screen shot 2017-12-18 at 11 20 19" src="https://user-images.githubusercontent.com/914443/34101256-6be5ba5a-e3e5-11e7-9366-d98409ab882b.png">

**Comment by LucaMele** [comment]
Cannot reproduce so far

**Comment by LucaMele** [comment]
Same FF Version

**Comment by AndyOGo** [comment]
restarted my Firefox and issue was gone... 🤔

**Comment by LucaMele** [comment]
Ok, so its a timing issue related to the open console. Is reproducible only with console open and several reloads

**Comment by LucaMele** [comment]
If the DOM is loaded before the polyfill, then it happens
