### ISSUE TITLE
Dropdown with long list overflows out of screen

### ISSUE THREAD

**Issue by ranostaj** [axa-ch/patterns-library#771]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Dropdown should act with a scrollbar to keep items within the reasonable box height, instead it runs out of the screen

## Actual Behavior

Dropdown overflows the screen

![image](https://user-images.githubusercontent.com/61942/50823327-01be8100-1334-11e9-8ca6-f0f73b30cc3b.png)

## Specifications

 - Browser: Chrome

**Comment by LucaMele** [comment]
thank you @ranostaj , this is actually a known issue and we will fix it soon

**Comment by ranostaj** [comment]
@LucaMele Thank you, have you any rough estimate, when we can expect it to be fixed?

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
