### ISSUE TITLE
Input field trigger validation on change

### ISSUE THREAD

**Issue by BettinaRussenberger** [axa-ch/patterns-library#774]
Validation Message in AEM Forms für Inputfields with Input validation & validation message: 

Actual State: Validation on Change
--> Behaviour (e.g. field E-Mail): Enter 1 letter and validation says you should enter a valid E-Mail beofre you even had a chance to enter it correctly. 

Should Behaviour: 
--> on leave the field, entered E-Mail-Address should be validated.

Concerns fields with validation message with **E-Mail and Phone Number**.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
