### ISSUE TITLE
dynamic custom elements loose react refs, never connect and do not update props

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#778]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All extended built-ins should connect if wrapped by `withReact` and should batch attributes by `setProps`.

## Actual Behavior

`<td is="axa-td">` does never call `connectedCallback` and attributes aren't batched by `setProps` call from `withReact`.

**Edit:**
I'm sure the issue is that the `withMonkeyPatches` HOC is always included.
Instead it should only be composed if it is really needed, especially if a custom-element does not define a **local-DOM** it get's into the way.

https://github.com/axa-ch/patterns-library/blob/eeaaf2e59207f5af09ac12b974aa78b715d460fa/src/js/abstract/hocs/index.js#L25-L27

## Steps to Reproduce the Problem

1. https://github.com/axa-ch/patterns-library-examples/pull/16
2.
3.

## Specifications

 - Browser: Latest Chrome
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by AndyOGo** [comment]
@LucaMele 
@jackblackCH 
@MKaHead 
OMG, that is fantastic.

It seems that **statically** added extended built-in children work, but **dynamically** generated don't:
![dynamic-build-ins-broken](https://user-images.githubusercontent.com/914443/51263924-89039880-19b5-11e9-8d66-2b9a52cb01ca.gif)

**Comment by LucaMele** [comment]
shit bro.. but i belive in u!

**Comment by AndyOGo** [comment]
hehe thanks.
Well so far we have at least a reproduction.
But it is a very non-deterministic bahaviour...

**Comment by AndyOGo** [comment]
Okay the element itself is actually connected 😕 
So maybe the `ref` isn't correct.

<img width="932" alt="screenshot 2019-01-17 at 14 51 47" src="https://user-images.githubusercontent.com/914443/51323114-8b262f80-1a67-11e9-831d-1ce108b07709.png">

**Comment by AndyOGo** [comment]
Indeed, we loose `ref` to live DOM 😱 

![ref-lost](https://user-images.githubusercontent.com/914443/51323423-75653a00-1a68-11e9-8cd9-a32359d17573.gif)

**Comment by AndyOGo** [comment]
@LucaMele 
Alright, I have narrowed it down further.

If I replace `AXATable` with `<table className="o-table">` and `AXATBody` with `<tbody className="m-tbody">` then rerendering works.

So it seems we have an issue with **nested custom elements** and **updating them dynamically**.

**Comment by AndyOGo** [comment]
@LucaMele 
I can approve it affects **both** autonomous `<custom-elements>` and extended `<div is="built-in">` elements 😞

**Comment by AndyOGo** [comment]
@LucaMele 
I just made a further test and dropped `withReact` completely, by just using plain custom elements, **styles work, synthetic events still broken** :(

```js
<axa-container style={{ marginTop: '40px' }}>
          <h3>Native custom elements (styles working, synthetic events broken)</h3>

          <table is="axa-table" className="o-table">
            <caption is="axa-caption">All your policies</caption>

            <thead is="axa-thead">
              <tr is="axa-tr">
                <th is="axa-th">Title</th>
                <th is="axa-th">Price</th>
                <th is="axa-th">State</th>
              </tr>
            </thead>

            <tbody is="axa-tbody">
              {Array.isArray(policies) && policies.map(({ title, price, state }, index) => (
                <tr is="axa-tr" key={index} id={index}>
                  <td is="axa-td" bold>{title}</td>
                  <td is="axa-td">{price}</td>
                  <td is="axa-td" state={state} action onClick={() => shuffleState(index)}><span>{state}</span></td>
                </tr>
              ))}
            </tbody>
          </table>

          {Array.isArray(policies) && policies.map(({ title, price, state }, index) => (
            <axa-row key={index} id={index}>
              <axa-col size={2}>{title}</axa-col>
              <axa-col size={4}>{price}</axa-col>
              <axa-col size={2} onClick={() => shuffleState(index)}><span>{state}</span></axa-col>
            </axa-row>
          ))}
        </axa-container>
```

![react-nested-dynamic-native-custom-elements](https://user-images.githubusercontent.com/914443/53107691-de434480-3535-11e9-865b-65cd6a7020bf.gif)

**Comment by AndyOGo** [comment]
@LucaMele 
@markus-walther 
I just disabled the **Monkey Patching Hoc** and my example above starts working.
So the issue seems to be that `<custom-elements>` without a **local-DOM** should not include this Hoc at all 🤔 
Further tests are need to proof my assumption.
