### ISSUE TITLE
inspect reported vulnerabilities

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#779]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Ideally zero vulnerabilities

## Actual Behavior

> found 558 vulnerabilities (444 low, 95 moderate, 18 high, 1 critical)

## Steps to Reproduce the Problem

1. `npm i`

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
