### ISSUE TITLE
Firefox: unreachable code after return statement

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#78]
> unreachable code after return statement

<img width="1437" alt="screen shot 2017-12-18 at 11 24 39" src="https://user-images.githubusercontent.com/914443/34101453-1543d280-e3e6-11e7-800d-1a69934f2340.png">

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
