### ISSUE TITLE
Add separate folders per component type [atoms,molecules, organisms]

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#782]
The more components we have, it becomes harder to find the desired components (scrolling through a huge prefixed components directory).

It makes it more readable to group it within the directories.
Sidenote: Tools like Fractal, Storybook or other pattern library helpers, allow this sub directories per default.

```
src/components
  - atoms
     - a-caption
     - a-checkbox
  - molecules
     - m-button
     - m-col
  - organisms
     - o-datepicker
```

**Comment by AndyOGo** [comment]
I agree, and I would also group related components #683 

@LucaMele 
@jackblackCH 
If all agree I would mark it as duplicate and close this issue to continue discussion in #683

**Comment by AndyOGo** [comment]
Cool, I quoted your suggestion to #683
