### ISSUE TITLE
established prototype chain has other class names

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#789]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [ ] Feature
 - [x] Curiosity

## Expected Behavior

I expect to have all our Higher-Order-Class'es names of the established prototype chain visible in Chrome's dev tools.

## Actual Behavior

I can't see a single correct class name if I open the `properties` pane 😞 
Neither for `<axa-container>`:

```sh
axa-container.o-container
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
HTMLElement
Element
Node
EventTarget
Object
```

nor for `<table is="axa-table">`:

```sh
table.o-table
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLTableElement
HTMLElement
Element
Node
EventTarget
Object
```

## Steps to Reproduce the Problem

1. got to https://axa-ch.github.io/patterns-library
2. and inspect any `<custom-element>` or `<div is="built-in">`

![massive-prototype-chain](https://user-images.githubusercontent.com/914443/51322014-9461cd00-1a64-11e9-85a6-9627583cc468.gif)

## Specifications

 - Browser: Chrome
 - Browser Version: Newest

It's definetly **not a polyfill** issue (because Chrome doesn't use them).

If I would guess it's Babel 🤔

**Comment by AndyOGo** [comment]
Alright, I got very curious so I tried our babel setup including https://www.npmjs.com/package/babel-plugin-transform-builtin-classes online at [Babel's REPL](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAcwKYwJIBM4DMoRHAcgDoiB6AVxmABsBnU5GAWmHQIG4AoTgYwgDta8AO7AYACwBCAQ1pI4AXjgAJACoBZADIBRakhBJ-8BQD5OcOKQBUV8xatwZcuD2qzacAN5OkAYTyQ_IYwAL5EdnAOquLAHq7ucOLS_Oh6HmC4YEhQLgIwSAAe8ORgCFDS6MD8CNjQcFViABQAlAA0EQ5icBXoHtJw5PzAAI7k8gAGAPqs490pcBkQAG6sSH1wQtJUPHAAqruoACKIhtlb0OEWkR2RVqjqAAoA8gBKqgCCAHKqAFw2cKoIHAQNIANbyQr5FJITAAI3INGYVTgSD0BiMfXmkGoAE8sDQ9HDcMI5DlhNBQVUaosslBce0rg5hPIeMkCPAoKicXABLlBDAoOQeDBoC1WnB0GM4CK-fkivVaLQxrRLvYbgABahVUGJGAwMC0H6kBhicTkWFEPggUgAdSQsJeSCwemFwAEpHQEB45HRzE5CFi-SgTFR-mCAGIlgBGJispZILYarX8UE_XX6w3GgMSc2WvAUarSMCkb1CPAhtHBWhMeGIqrhvj8wXC6Cx6TxxOM0h2eKKuA200-FFFQy9FQaHSVoxeCL1IYwFozq5XCSxIjTTBKRgYRqrlX8CDoJCfaQGZpcZcWPfrhpUaRauSb6WCpAXq4hbjL40bErZergaAYGSeA3AAL25W9gHvYBQPkARcR5fgeHkWQ4CCGEGSub8kFNP8Sl5RsgldARZ0IpBhRhXx72oWFpB4UFF08WcLGALA4EaABCa9pnnKCHxhZol0vK8YhVW8WjfZcPykz8sNIHk2Pw_huj1KBgHhfIXCSap5EaVllKSMAsmU2EnWgFkBCIqheVYtCIBA4B42aWctgFdTKD8bTkHQKjqBouiGMEpjhNszjuMg6DHyC5iV1EohxPPGLpPfOwQi4ThrEQagIFoug4AANW0F4AGVUCeT5Im7XgBCEOBRAkfLsloN1lKUIdTDsaxbEZOB3nQMcJBZcgoE5adxnjKBmoEWYcDwOBxjAALpGQIgACtaGm6UgQTHhxFyACgiMVVrh69VClPMA9BuRtaveAANd5JEoEVWpccgyxAXQwwxIhGEaAhpAKaQa2egQCESnqbogPQiGyhBGnux7Qf4IgJqm_gIbVHrvzqWFuUWEBYiQa73pFT6pxgFVhHEQxDidKoYX-wHgY0l7wZuCwiEG_hGkXUwhMiS8bvgRGnr1XklFLMmvt9FU_oBoGQfF_hwckhxlyhmG4YRh6xZe1GmpaiH1ffTHKp7Nw-wHBrDd5SFRw8IdgquTZtjgNGWsUAqitK8q3zS7h1BxGXgi9-rxEayaWsacOfD0y2PCDkPp2dsiKJ86jaPoxjZ2vOUYH8IxQ6UAgab8iAOFSzgQmaZy4F4Um8GTymiCPfEgn-kAcQrb6YAIcUk4p88gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=true&targets=&version=6.26.0&envVersion=).

It seems to come from Babel's inherit, which creates an Object of `superClass`, but overrides it's constructor to `subClass` (which will always be `HTMLElement`).
<img width="1190" alt="screenshot 2019-01-17 at 14 46 51" src="https://user-images.githubusercontent.com/914443/51322842-dd1a8580-1a66-11e9-8dcd-2d5c9bf48906.png">

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
