### ISSUE TITLE
Nicer appearing of "error" in form-group (AXAFormGroup)

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#791]
When the error in form-group suddenly appears, then the form gets expanded, which doesn't look very nice.

Ideally the error would be absolutely positioned, or appear smoothly (animated).

Mentioned by @Hettlingen 

![image](https://user-images.githubusercontent.com/43809369/51540041-c05ec300-1e55-11e9-8685-d9bc5a055590.png)

![image](https://user-images.githubusercontent.com/43809369/51540062-c94f9480-1e55-11e9-9d3e-4feaf665dbbd.png)

**Comment by raphaellueckl** [comment]
There is a PR open that fixes the issue in a controversial way. As soon as we have a UX concept, we can start to look at this issue again.

Link: https://github.com/axa-ch/patterns-library/pull/819

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
