### ISSUE TITLE
NotFoundError on table data update in React - probably DOM manipulation outside of React

### ISSUE THREAD

**Issue by marek99999** [axa-ch/patterns-library#795]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

React should not crash, when updated props are passed to table in React (creating udpdated <td> element content)

## Actual Behavior
On table data update (especially when sets with more/less data are passed to table consecutively) React crashes with "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

Forums suggest that possible cause of this error is DOM manipulation outside of React.

## Steps to Reproduce the Problem
...
import '@axa-ch/patterns-library/lib/components/o-table';
....
<table is="axa-table" action>
        <tbody is="axa-tbody">
          {this.props.data.map((dataObject, rowIndex) =>  (
            <tr
              is="axa-tr"
              key={rowIndex}
              className="wr-table-body-row wr-table-row"
              <td is="axa-td" >
                {dataObject.claimDate}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
...
....
pass updated {data} props and at some step React application crashes.

If import of table from patterns-library is removed (or is="axa-table", is=... attributes of patterns library in table are removed), the react application renders correctly and data updates produce no crashes.

 - Browser: Chrome
 - Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
 - Node Version:
 - NPM Version:
 - Platform: Windows

**Comment by AndyOGo** [comment]
Thanks for your issue.

> Forums suggest that possible cause of this error is DOM manipulation outside of React.
Agree 100%. But that the point of custom elements, actually DOM manipulation outside of any framework/library.

My assumption is that this issue is related to loosing React `refs` #778 
And `children` get out of sync.

**Comment by AndyOGo** [comment]
@marek99999 
@markus-walther 
@LucaMele 
I just created a public test case with the [newest V1 release `2.0.1-beta.264`](https://github.com/axa-ch/patterns-library/releases/tag/v2.0.1-beta.264) with #913 merged and this works now as expected :)
https://codesandbox.io/s/lrxj3vk0nz

If all of you agree I close this ticket?

**Comment by LucaMele** [comment]
yes close it, thank you @AndyOGo
