### ISSUE TITLE
with-react: axa-dropdown value of item isn't in value-attribute when selected

### ISSUE THREAD

**Issue by MarcSchneider1** [axa-ch/patterns-library#799]
## Are you reporting a bug or a feature?
 - [x] Bug

## Expected Behavior
When an item is selected, the value-attribute should be equal to the item-value.

## Actual Behavior
The value-attribute is always "undefined".

## Steps to Reproduce the Problem

import '@axa-ch/patterns-library/lib/components/m-dropdown';

create a dropdown:
<axa-dropdown value={this.state.absender} data-seleniumid="absender" size="sm" items='[{"name": "Audanet", "value": "Audanet"}, {"name": "EC2", "value": "EC2"}]' native></axa-dropdown>

this.state.absender is empty at any time.

## Specifications

Please provide any relevant information about your setup - os, browser, node, npm, etc. -->

 - Browser: chrome
 - Browser Version: 71
 - Node Version:
 - NPM Version:
 - Platform: windows

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
