### ISSUE TITLE
Datepicker hover/selected broken

### ISSUE THREAD

**Issue by lina-salih** [axa-ch/patterns-library#802]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Actual Behavior
Die hover und selected Animationen funktionieren nicht immer korrekt. 
Siehe Screenshot:
![image](https://user-images.githubusercontent.com/23553747/52343908-bde59700-2a19-11e9-8b2a-bc3150ebbc9d.png)

## Steps to Reproduce the Problem

1. Datepicker öffnen
2. Diverse Daten selektieren

## Specifications

 - Browser: Chrome
 - Browser Version: Version 71.0.3578.98
 - Node Version:
 - NPM Version:
 - Platform:

**Comment by jackblackCH** [comment]
We optimized the hover, selected and focus states within the bugfix #809
