### ISSUE TITLE
Datepicker v2 Sammelbug

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#803]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The Datepicker should follow UX Best Practices and should behave naturally.
As described in the origional feature ticket #244 

## Actual Behavior

- [ ] Clicking disabled days focuses random disabled days
   ![datepicker-v2-random-select](https://user-images.githubusercontent.com/914443/52344938-52e98f80-2a1c-11e9-87e7-9bde7ef32d00.gif)
- [ ] Dropdowns for month and year do not close if clicked outside
- [x] Dropdowns stay open after the datepicker is closed
   ![datepicker-v2-dropdowns-stay-open](https://user-images.githubusercontent.com/914443/52345131-becbf800-2a1c-11e9-9bb1-6d6e2f503553.gif)
- [ ] changing the input's value manually with the keyboard does not validate the allowed range
   ![datepicker-v2-dropdowns-manual-input](https://user-images.githubusercontent.com/914443/52345330-3ac64000-2a1d-11e9-98d9-273a9a1547a1.gif)
- [x] focus and hover states are different
- [x] clicking the datepicker active day shows a filled day with an ugly dotted border
   ![datepicker-v2-dropdowns-hover-focus](https://user-images.githubusercontent.com/914443/52345439-8547bc80-2a1d-11e9-8025-e457463a9294.gif)
- [x] disabled days should not be interactive in any way - at the moment they can be clicked and tabbed/focused
   ![datepicker-v2-dropdowns-disabled-days](https://user-images.githubusercontent.com/914443/52345541-cb048500-2a1d-11e9-807c-cf49bee3dff3.gif)

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/components/o-datepicker/index.html
2. and click around as shown in the screen videos above

## Specifications

 - Browser: Chrome (on Mac)
 - Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by jackblackCH** [comment]
Thanks for reporting. I am fixing the criticals

**Comment by LucaMele** [comment]
@AndyOGo thank you for the detailed description. All UI & Click on disaled days feature are based on axa design. Dotted border is approved from design and am sorry if you think is ugly, but is not an issue

**Comment by lina-salih** [comment]
@kenaxa Ist das wirklich eine Design-Vorgabe vom AXA group styleguide? 🤕

**Comment by LucaMele** [comment]
To be fixed IMHO:

* Clicking disabled days selects random dates
* Dropdowns for month and year do not close if clicked outside
* Dropdowns stay open after the datepicker is closed
* disabled days should not be interactive in any way - at the moment they can be clicked and tabbed/focused -> HERE TO BE FIXED ONLY THAT THEY SHOULD NOT BE TABBABLE. clickung and chaing month is a feature

**Comment by LucaMele** [comment]
@lina-salih soweit ich weiss ist es eine design vorgabe von axa CH nicht von axa group und @jackblackCH hat es meines wissen nach mit @kenaxa oder @jojackpot reviewed. Gerne könnt ihr aber dies challangen in seinem separaten task oder mit ihnen. Ist aber kein Bug

**Comment by AndyOGo** [comment]
Thanks @LucaMele and @jackblackCH for your instant feedback.

Just to make one point clear **disabled** fields are per definition non-interactive. And making them interactive introduces an UX-Antipattern. Please consider my appeal and rethink this approach.
IMHO therefore It is a bug and definitely not a feature.

**Comment by LucaMele** [comment]
@AndyOGo open you calendar on the mac, click on "ligher grey" colored dates (ergo disabled) and see. This was a feature from day 1 of the datepicker and is actually part of axa group design. So no anti pattern here

**Comment by LucaMele** [comment]
@AndyOGo even W3C native datepicker hast this feature: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date

**Comment by AndyOGo** [comment]
Thanks @LucaMele for this tip.
I quily tried it, but seems not to working like this everywhere. Can you please provide a screen video which highlight mouse movement and clicks?

Here is my result:
![mac-calender-disabled-click](https://user-images.githubusercontent.com/914443/52347709-e756f080-2a22-11e9-9fad-8cc48c0d0d8f.gif)

**Comment by LucaMele** [comment]
on the little calendar bottom left and here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date

**Comment by LucaMele** [comment]
every datepicker behaves like that

**Comment by AndyOGo** [comment]
Thanks @LucaMele . I just did this too.
Please observe for yourself, the little datepicker at the left does never change, just the big one 🤔 
So this is different behavior from the axa datepicker.

![mac-calender-disabled-click-2](https://user-images.githubusercontent.com/914443/52347926-66e4bf80-2a23-11e9-8e4f-c68fa0483466.gif)

**Comment by LucaMele** [comment]
<img width="632" alt="bildschirmfoto 2019-02-06 um 15 25 19" src="https://user-images.githubusercontent.com/275235/52347971-7fed7080-2a23-11e9-8fe0-cb281db96b42.png">

**Comment by LucaMele** [comment]
@AndyOGo click on that. the one on the mac goes back and forward only per 1 month but it triggers on disabled looking clicks.

**Comment by AndyOGo** [comment]
@LucaMele Nope, I can't observe that. What I see is:
actually **all days** control the month of the bigger view, but not the little view itself.

**Comment by kenaxa** [comment]
@lina-salih Ja, das ist die neuste Version des Datepickers. Der wird aktuell so fertig gestellt. Das heisst Du kannst in schon bald so verwenden.

**Comment by kenaxa** [comment]
@LucaMele @AndyOGo Danke für euren Input. Ich habe mir den Datepicker angeschaut und im Team besprochen. 

Offene Punkte die gerade angepasst werden sind:

- [ ] Bei den Daten die in den neuen Monat reingehen, switcht man automatisch auf den entsprechenden Monat.
- [ ] Die gestrichelte Linie wird "nur" zum Einsatz kommen wenn die Tastatur verwendet wird. (Bei klicks nicht ersichtlich)
- [ ] Bei den Dropdowns wird jeweils 1 DD ersichtlich sein
- [ ] Beim Jahreswechsel: Tage von nicht vorhandenem Jahr werden nicht angezeigt.

Lg

**Comment by AndyOGo** [comment]
@jackblackCH @LucaMele @kenaxa @jojackpot 
To clarify the **dotted border** style. If I'm right it is meant for `:focus`/`tabbed` selection.
But it styles become mixed upon `:hover`, please see my screen video.
Is this really desired, shouldn't one take precedence?

![datepicker-dotted-border-](https://user-images.githubusercontent.com/914443/52380363-bfd94580-2a6d-11e9-89f6-62c169f5200f.gif)

**Comment by jackblackCH** [comment]
> * Bei den Daten die in den neuen Monat reingehen, switcht man automatisch auf den entsprechenden Monat.
> * Die gestrichelte Linie wird "nur" zum Einsatz kommen wenn die Tastatur verwendet wird. (Bei klicks nicht ersichtlich)
> * Bei den Dropdowns wird jeweils 1 DD ersichtlich sein
> * Beim Jahreswechsel: Tage von nicht vorhandenem Jahr werden nicht angezeigt.

Open Bugfix in #809

**Comment by jackblackCH** [comment]
> To be fixed IMHO:
> 
> * Clicking disabled days selects random dates
> * Dropdowns for month and year do not close if clicked outside
> * Dropdowns stay open after the datepicker is closed
> * disabled days should not be interactive in any way - at the moment they can be clicked and tabbed/focused -> HERE TO BE FIXED ONLY THAT THEY SHOULD NOT BE TABBABLE. clickung and chaing month is a feature

All of these are solved, too (rel to comments of @kenaxa) with #809

**Comment by jackblackCH** [comment]
>  * changing the input's value manually with the keyboard does not validate the allowed range

Validation can be done better, it's not changing because the chose dates where not in the allowed years.

**Comment by jackblackCH** [comment]
Open feature: > * Dropdowns for month and year do not close if clicked outside
They close now on datepicker close

**Comment by AndyOGo** [comment]
@jackblackCH 
> Open feature: > * Dropdowns for month and year do not close if clicked outside
They close now on datepicker close

This is not what was originally carefully worked out with Anja Wagner regarding UX.
Dropdows close before upon ESC-key press and click outside.

This is regression and I created another clear bug for it:
https://github.com/axa-ch/patterns-library/issues/810

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
