### ISSUE TITLE
Datepicker placeholder cut off

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#804]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Placeholders should be visible and readable.

## Actual Behavior

Placeholder is cut off (at least iOS)

## Steps to Reproduce the Problem

1. pick an iPhone
2. go to https://axa-ch.github.io/patterns-library/components/o-datepicker/index.html

![image from ios](https://user-images.githubusercontent.com/914443/52346133-3864e580-2a1f-11e9-8592-754021e224f2.png)

**Comment by jackblackCH** [comment]
Fixed with #809

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
