### ISSUE TITLE
Datepicker not all days visible

### ISSUE THREAD

**Issue by mjenny** [axa-ch/patterns-library#805]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All days visible (December 1st to 31st).

## Actual Behavior

Only days starting December 2nd 2019 are visible.
![image](https://user-images.githubusercontent.com/4191545/52349815-9990b700-2a27-11e9-9884-0db5e63e7f1f.png)

## Steps to Reproduce the Problem

1. Select December 2019

## Specifications

 - Browser: Firefox Mobile Overlay (not limited to, seems all browsers are affected)
 - Browser Version: 65

**Comment by jackblackCH** [comment]
Ouch. Nice catch. Will check

**Comment by jackblackCH** [comment]
Fixed with #809
