### ISSUE TITLE
Datepicker: some touch presses are recognized as text selection

### ISSUE THREAD

**Issue by mjenny** [axa-ch/patterns-library#806]
## Are you reporting a bug or a feature?

 - [X] Bug
 - [ ] Feature

## Expected Behavior

Touch presses should be interpreted as date selection not for marking text inside the datepicker

## Actual Behavior

Text selection on android pops up:
![image](https://user-images.githubusercontent.com/4191545/52350299-88947580-2a28-11e9-9ac8-c23cca56892e.png)

## Steps to Reproduce the Problem

1. Randomly choose different dates

## Specifications

 - Browser: Firefox Mobile Overlay
 - Browser Version: 65
 - Platform: Androuid

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
