### ISSUE TITLE
Dropdown regression, does not close anymore on ESC and click outside

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#810]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The Dropdown should close if:

- [x] ESC key is pressed
- [x] Clicking outside the dropdown

**Note**: This feature was already working and implemented through UI-Events.
This was clearly defined and worked out with Anja Wagner and an essential core feature of the redesign and user experience.

## Actual Behavior

Some refactoring caused a regression witch broke that feature.
At the moment it seems to be that troubles started with the datepicker v2 refactoring #767 

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/components/m-dropdown/index.html
2. open the JS-enhanced datepicker
3. press ESC or click outside, nothing happens 

![dropdown-close-regression](https://user-images.githubusercontent.com/914443/52396254-832f3d80-2ab1-11e9-88a7-4b19802509ec.gif)

## Specifications

 - Browser: All

**Comment by jackblackCH** [comment]
Fixed
