### ISSUE TITLE
Open Datepicker Icon focused/outlined

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#811]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

If I open the datepicker, the datepicker itself should have `focus` or it's input field.

## Actual Behavior

The Icon next to the Datepicker's input field has `focus` and shows and an unbeautiful CSS outline.

## Steps to Reproduce the Problem

1. got to https://axa-ch.github.io/patterns-library/components/o-datepicker/index.html
2. open the datepicker (by clicking the icon)

![datepicker-icon-outline](https://user-images.githubusercontent.com/914443/52463285-a07a0f80-2b76-11e9-89d6-2a470cfbed34.gif)

## Specifications

 - Browser: Chrome
 - Browser Version: Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
