### ISSUE TITLE
Webfonts are not loaded in production release, nowhere.

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#812]
<img width="1437" alt="screen shot 2019-02-11 at 13 47 36" src="https://user-images.githubusercontent.com/2416200/52564183-c5cf7d80-2e03-11e9-9212-e51400fe451e.png">

**Comment by jackblackCH** [comment]
It's on all pages: i.e https://axa-ch.github.io/patterns-library/

**Comment by jackblackCH** [comment]
Font's are are not in the assets folder -> i.e  https://axa-ch.github.io/assets/fonts/source-sans-pro-v10-latin-700.woff2

**Comment by jackblackCH** [comment]
<img width="1403" alt="screen shot 2019-02-11 at 13 59 02" src="https://user-images.githubusercontent.com/2416200/52565274-ac7c0080-2e06-11e9-88ac-1d9f6c13a0ab.png">

There is a different implementation and definition of the font-names

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
