### ISSUE TITLE
m-link arrow lost dimensions

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#818]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Link component icon classes should properly style dimension, without adjoining classes:
https://github.com/axa-ch/patterns-library/blame/abf3d7529120e6c299b4e671e89eaccc35afd231/src/components/m-link/index.scss#L39-L43

## Actual Behavior

Needs to be adjoined with `.a-icon__svg` to make the selector work.

## Steps to Reproduce the Problem

1. import the CSS from `@import "@axa-ch/patterns-library/src/components/m-link/mixins/link";`
2. and build your own  link component using `.m-link__arrow` for the `<svg>` tag

<img width="734" alt="screenshot 2019-02-12 at 12 27 22" src="https://user-images.githubusercontent.com/914443/52637863-d4379b00-2ed0-11e9-9bcd-1b18e9b58cdd.png">

## Quick Workaround

Add `.a-icon__svg` class to your `<svg>` tag, and selectors match again 🎉

**Comment by AndyOGo** [comment]
introduced with this  change:
https://github.com/axa-ch/patterns-library/blob/e07e99e12c1810592aff803d3fbc5e4bd3884222/src/components/m-link/index.scss#L40-L45

in relating commit https://github.com/axa-ch/patterns-library/commit/c39c298515fdef9e0eccb71e5e6617738c33bb6b

**Comment by jackblackCH** [comment]
I try to reproduce, please send the exact snippet to reproduce it (like in the screenshot)

**Comment by AndyOGo** [comment]
@jackblackCH
I dont' now if you have access rights for aletheia.

Meanwhile I quickfixed it myself by adding `.a-icon__svg` class at this commit
https://github.com/axa-ch/aletheia/pull/377/commits/879433e8b688c35cd8e336eac1b7f0c0cf0b9037

Within this PR:
https://github.com/axa-ch/aletheia/pull/377

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
This is still an issue for all plib v1 users

**Comment by LucaMele** [comment]
Migrate to v2, we cannot fix this in v1
