### ISSUE TITLE
Setup CI/CD Infrastructure

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#823]
- Build with Travis
- Deployment to gh-pages with Travis
- Deployment to npmjs with Travis
- Request domains for PROD/ACC/DEV spaces

Concept:
![image](https://user-images.githubusercontent.com/8248662/52864450-79a17780-313a-11e9-981d-fd04b5f10922.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
