### ISSUE TITLE
Input loses value when attribute is changed

### ISSUE THREAD

**Issue by nakovskijosif** [axa-ch/patterns-library#832]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior
1. When error="error" is added to the axa-input component the text in the input field should stay as is.
2. Error should be boolean instead of string.
## Actual Behavior

When I add error attribute to axa-input the text previously typed in the input is lost.

## Steps to Reproduce the Problem

1. type some text in any axa-input component.
2. add error="error" to axa-input.
3. typed text is lost.

Note: error is taken as example. This happens with other attributes too.

**Comment by nakovskijosif** [comment]
@AndyOGo, @LucaMele 
I have no idea of proper way to fix this issue, I managed to find a workaround in the current AEM implementation. Any hints will be appreciated.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
