### ISSUE TITLE
Possibility to provide icon path to icon components

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#835]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

 - [ ] Bug
 - [x] Feature

## Expected Behavior

I would love to have the possibility if I'm using any component with icon, that I can supply the path of my .svg file and it takes the icon from there.

`<AXAButtonReact color="red" icon="print.svg"> `

## Actual Behavior

Currently I have to run the compile script to include the svg into the icons.svg file and afterwards I can refer by it by name. 

`<AXAButtonReact color="red" icon="download">`

While this is ok and great for a production build, in case of development there are two problem.
- In case we don't have a final icon yet or it changes often, we need to recompile each time the file.
- The other major drawback is, I have no idea what other icons are included. In case we are working with multiple branches and other people are including their own icons, it makes it harder to not accidentally remove one icon from a different branch.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
