### ISSUE TITLE
Broken default m-button divider line and icon

### ISSUE THREAD

**Issue by MatthiasDyballa** [axa-ch/patterns-library#836]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Actual Behavior

Currently the default button with icon is broken. 
- The divider line stop 4/5 down
- The icon is smaller than it should be and placed towards the top.

## Steps to Reproduce the Problem

Can be seen even in the showcase of components [m-button](https://axa-ch.github.io/patterns-library/components/m-button/index.html)

<img width="1048" alt="screenshot 2019-02-26 at 10 23 38" src="https://user-images.githubusercontent.com/914443/53401815-dc073d00-39b0-11e9-9e20-471fcd3bc9f0.png">

## Specifications

 - Browser: Chrome, IE

**Comment by AndyOGo** [comment]
@MatthiasDyballa Thanks for the heads up.

Some of the latest releases broke that button 😞 

<img width="1048" alt="screenshot 2019-02-26 at 10 23 38" src="https://user-images.githubusercontent.com/914443/53401758-b4b07000-39b0-11e9-9a07-f69249256476.png">

**Comment by jackblackCH** [comment]
I am fixing it.

**Comment by jackblackCH** [comment]
Please check again. I fixed, was the same reason as we had in #814
