### ISSUE TITLE
Footer links mobile dropdown icon too big

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#842]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Icon size of the footer links mobile dropdown should be as defined within the design spec.

## Actual Behavior

Icon size is to big.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/components/o-footer/index.html

<img width="1260" alt="screenshot 2019-03-01 at 15 07 58" src="https://user-images.githubusercontent.com/914443/53643359-21876c80-3c34-11e9-9fa3-3751aadc852f.png">

## Specifications

 - Browser: Chrome
 - Browser Version: Version 72.0.3626.119 (Official Build) (64-bit)
 - Platform: Mac OS X Mojave
 
## Related

Seems to be again related to a workaround causing more bugs, instead of solving the correct problem of missing dependencies between components - tracked here #723 and a PR here #724

Related bugs reported so far: #841, #836, #818 and #814

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
