### ISSUE TITLE
Language dropdown does not work within Header

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#843]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The dropdown should open if clicked or <kbd>tabbed</kbd> and <kbd>enter</kbd> and close if select, <kbd>esc</kbd> or click outside.

## Actual Behavior

Does not open at all...

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/components/o-header/index.html

![header-lang-dropdown-broken](https://user-images.githubusercontent.com/914443/53644397-c99e3500-3c36-11e9-8c40-9702365ff80d.gif)

Please provide any relevant information about your setup - os, browser, node, npm, etc. -->

 - Browser: Chrome

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
