### ISSUE TITLE
Footer Links mobile dropdown not working

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#844]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The Footer Links dropdowns on mobile only should open if clicked or <kbd>tabbed</kbd> and <kbd>enter</kbd> and close if select, <kbd>esc</kbd> or click outside.

## Actual Behavior

They do nothing.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/components/o-footer/index.html

![footer-links-mobile-broken](https://user-images.githubusercontent.com/914443/53644664-695bc300-3c37-11e9-9ef3-2964c19ccf18.gif)

## Specifications

 - Browser: Chrome

**Comment by MarekLacoAXA** [comment]
Yes, clicking on expand arrow does nothing. The Links keep being collapsed (on small screen).
(I don't mind the keyboard navigation for now, at least the mouse click would be great to have working)
Thanks!

**Comment by jackblackCH** [comment]
on it

**Comment by jackblackCH** [comment]
Fixed by #862
