### ISSUE TITLE
Modal Jittering after load

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#848]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Modal should never be visible until it is opened.

## Actual Behavior

Modal is visible at the beginning and jitters, then invisible.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/components/o-modal/index.html

![modal-jittering](https://user-images.githubusercontent.com/914443/53737334-8806c780-3e8c-11e9-9c71-ba02185fe8f8.gif)

## Specifications

 - Browser: Latest Chrome

**Comment by AndyOGo** [comment]
Guess is also related to FOUC #365 🤔

**Comment by raphaellueckl** [comment]
Yes, this is related and we were aware of it. This won't be a problem for V2 anymore, but I will provide a fix for this, as soon as I am done with the current work. Thanks for the feedback! This should definitely be fixed, no matter of versions.

**Comment by raphaellueckl** [comment]
#854

**Comment by AndyOGo** [comment]
@raphaellueckl 
Thanks for the update.

FYI: You can close issues via pull requests, by `fixes #848` (you can close as many as you wish).
More info: https://github.blog/2013-05-14-closing-issues-via-pull-requests/
