### ISSUE TITLE
Modal has no bottom padding

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#849]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The modal should cleary separate itself  from the underlying content and should include a bottom `padding`.

## Actual Behavior

The modal currently has not bottom `padding`.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/components/o-modal/index.html
2. click open button

<img width="940" alt="screenshot 2019-03-04 at 14 45 33" src="https://user-images.githubusercontent.com/914443/53737474-ea5fc800-3e8c-11e9-84ce-1b814b567b8d.png">

## Specifications

 - Browser: Latest Chrome
 - Platform:Mac OS Mojave

**Comment by AndyOGo** [comment]
Hmh seems the same for top padding 🤔

**Comment by raphaellueckl** [comment]
Thanks for the hint! But this is up to the designers to decide if it needs some padding, because the current situation could lead the user to the conclusion, that there must be coming more further down (on macos, the scrollbar is not visible if it is not used for example, same counts for other operating systems).

**Comment by raphaellueckl** [comment]
@jojackpot Please make a decision and close this issue, depending on how you decided. Please let me know.

**Comment by AndyOGo** [comment]
@raphaellueckl Thanks for your quick answer.
Correct designer should decide, that why assigned them too 😉 

@jojackpot 
@kenaxa 
Here is some nice motivation about modals and how others are doing them:
https://ant.design/components/modal/
https://material-ui.com/utils/modal/#modal
https://material-ui.com/demos/dialogs/
https://developer.microsoft.com/en-us/fabric/#/components/modal
https://getbootstrap.com/docs/4.1/components/modal/
https://en.wikipedia.org/wiki/Modal_window

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
