### ISSUE TITLE
Modal content not optimised for mobile viewports

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#853]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Content of the modal should be displayed nicely, like centered, buttons not glued together, etc. please see the pictures.

## Actual Behavior

Buttons glued together, some content may looks nicer if centered, etc.

## Steps to Reproduce the Problem

1. Take your iPhone
2. https://axa-ch.github.io/patterns-library/components/o-modal/index.html
3. click open button

![image from ios 1](https://user-images.githubusercontent.com/914443/53790667-cb624400-3f27-11e9-9c2c-87a03b67ccce.png)

## Specifications

 - Browser: iOS Webkit at iPhone

**Comment by raphaellueckl** [comment]
Thanks for the feedback, but the content is up to the guy who implements it. That was a team internal decision. We only make the modal responsive, but the content is not our responsibility.

**Comment by AndyOGo** [comment]
@raphaellueckl 
I understand.

But shouldn't the example show how to do it nicely?
@LucaMele Please reopen, IMHO the style-guide should not give examples that show unwanted practices.

**Comment by LucaMele** [comment]
@raphaellueckl its up to you if you want to fix the example or not. As its true a nice example is better. Its up to you

**Comment by raphaellueckl** [comment]
#854

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
