### ISSUE TITLE
state classes are constantly repeating

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#9]
I periodically utilize generic state classes like `is-open`, `is-active`, etc.

So I'm concerned what if 2 separate components utilize the same state class and are being nested within each other. This could lead to wrong states triggering false CSS properties.

Hence I propose to namespace even state classes by the components name in the format of `is-component-state`, like: `is-dropdown-open`.

**Comment by LucaMele** [comment]
well utopic answer would be shadow dom. But till we really have it, it make sense to namespace it.

I was also thinking to introduce a generic automatism for namespace for the components, but is too complex for this state.

So yes i guess namespaced classes here would be ok
