### ISSUE TITLE
Trigger axa-change on datepicker input change

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#903]
IS: no axa-change is triggered on datepicker input change
SHOULD: same as dropdown and datepicker, input change should trigger axa-change

Hint: stop propagation on lower triggered axa-changes in case they bubble all the way up

**Comment by markus-walther** [comment]
@LucaMele Is this still relevant if we have a onChange callback instead? What's the differential use case requiring a custom event that cannot be replaced by a callback here?

**Comment by LucaMele** [comment]
solved
