### ISSUE TITLE
Nested Grid containers add up outer gutter widths

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#924]
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

It should be possible to disable the outer gutter for nested grid containers, so that children line up nicely with their parents.

**Note:**

According to Bootstrap `4` Grid docs, containers are only use at the first level (which makes sense)
https://getbootstrap.com/docs/4.0/layout/grid/#nesting

## Actual Behavior

Grid gutters always add up for nested containers.

## Steps to Reproduce the Problem

```html
<axa-container>
  <axa-row>
    <axa-col>
      <h1>1. Level</h1>
      
      <!-- This issue can be avoided just by omitting the nested <axa-container> -->
      <axa-container>
        <axa-row>
          <axa-col>
            <h2>2. Level</h2>
          </axa-col>
        </axa-row>
      </axa-container>

    </axa-col>
  </axa-row>
</axa-container>
```

![nested-grid-container-gutters-add-up](https://user-images.githubusercontent.com/914443/56584684-90ea5e80-65dc-11e9-8d07-e34e91d4ee2b.png)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
This is a rather general feature question, which I would like to have discussed and sorted out.
Current use case is the ui-renderer

**Comment by LucaMele** [comment]
yepp lets discuss it

**Comment by raphaellueckl** [comment]
This issue is open since more than a month and no discussion happened. I would like to keep "disucussions" to slack, because they seem to pollute our issue section here with nobody knowing what to do with it or nobody knowing when the disussion is at a state where an issue can be closed.

@AndyOGo Feel free to reopen if you see it otherwise! :)

**Comment by AndyOGo** [comment]
Indeed, you are right @raphaellueckl . Not much has happended here 😞 
Actually I asked for feedback some time ago, especially I would like to the viewpoint of designers @kenaxa @jojackpot ?

From my point of view, there should always be only one `<axa-container>` at the root level and nesting containers within containers should be regarded as bad-practice.
Though it happens that content get's created which is doing this and it is unfortunately out of our control.

So I would like to have a decision, if the patterns-library should deal with such "quirks"?
