### ISSUE TITLE
Fix storybook dev experience

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#947]
Since we started with module imports with an alias of @ axa-ch
i.e
`import '@ axa-ch/dropdown';` instead of `import ../dropdown/index`
`import '@ axa-ch/button';`

Now “live” developing/updates in storybook do not work anymore, since the imported modules are pointing to the installed lib versions (node_modules) and not to the raw files which are watched by webpack/storybook.

Ideas: Create a storybook webpack alias that resolves all @axa-ch to the local files instead the installed in the lib/node_modules folder
- checkout: https://github.com/lerna/lerna/tree/master/commands/link#readme
- checkout: lerna bootstrap again

**Comment by LucaMele** [comment]
Very good idea

**Comment by jackblackCH** [comment]
This was fixed, by removing `npm install in the packages via post install` and replacing it with `npx lerna bootstrap`
