### ISSUE TITLE
Dropdown: Uncaught TypeError: this.onDropdownClick is not a function

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#953]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Clicking a Button should not throw a **TypeError** nor trigger a Dropdown's click event.

## Actual Behavior

```sh
Uncaught TypeError: this.onDropdownClick is not a function
    at HTMLElement.value (all-demos.js:1)
    at wl (all-demos.js:1)
    at Hl (all-demos.js:1)
    at Ql (all-demos.js:1)
    at all-demos.js:1
    at Object.i.unstable_runWithPriority (all-demos.js:1)
    at Lu (all-demos.js:1)
    at Ru (all-demos.js:1)
    at ju (all-demos.js:1)
    at Ou (all-demos.js:1)
```

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/react.html
2. delete a todo item (by clicking the remove button)
3. open console

![react-dropdown-click-triggered-at-button](https://user-images.githubusercontent.com/914443/57308482-b734f180-70e6-11e9-9214-58f183c53a1b.gif)

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
