### ISSUE TITLE
Fix npm security Issue

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#999]
![Bildschirmfoto 2019-05-13 um 16 12 31](https://user-images.githubusercontent.com/275235/57628315-fc9b6800-7599-11e9-9260-c8a58c2d6928.png)

**Comment by MKaHead** [comment]
fixed

![Bildschirmfoto 2019-06-07 um 17 03 31](https://user-images.githubusercontent.com/11683864/59113884-3e73c000-8946-11e9-9889-ebc8f00998a7.png)
